# Generated By: Claude Code (Claude Opus 4.6)
#
# OpenShell sandbox image with Claude Code, tools, and project layout.
# Build: make build
# Usage: openshell sandbox create --from <image> ...

# Fully qualified: an unqualified name resolves through podman's
# unqualified-search-registries list, so which registry serves the base image
# becomes a matter of local configuration rather than something stated here.
ARG BASE_IMAGE=docker.io/library/python:3.13-slim
FROM ${BASE_IMAGE}

# shellcheck and rsync are here for `make check`, which runs INSIDE the
# sandbox: test-lint is shellcheck, and tests/test-upload-skip.sh silently
# skips its --download half without rsync. shellcheck is a 34MB static Haskell
# binary, the largest single thing in this line; the alternative is a
# completion gate that cannot run where the work happens.
#
# No openssh-client, deliberately. Nothing commits in a sandbox, so git never
# needs ssh-keygen — and adding it would make the uploaded gitconfig's
# commit.gpgsign=true reachable. See upload_config() in scripts/sandbox.sh.
RUN apt-get update && apt-get install -y --no-install-recommends \
        curl git gawk iproute2 nftables make jq vim-nox python3-tk dtach \
        shellcheck rsync \
    && rm -rf /var/lib/apt/lists/*

# Node.js (Claude Code, MCP servers)
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y --no-install-recommends nodejs \
    && rm -rf /var/lib/apt/lists/*

# Claude Code + gws (Google Workspace CLI) + Codex CLI
#
# Codex is baked, not installed on demand: the OpenShell L7 proxy resets any
# request whose path contains %2f, and that is exactly how npm asks for a
# scoped package (registry.npmjs.org/@openai%2fcodex). Verified from inside a
# sandbox — the unencoded path returns 200, the encoded one returns nothing.
# So `npm install -g @scope/pkg` cannot work in a sandbox at all, and every
# scoped tool has to arrive in the image.
#
# It is also the largest single thing here: ~126MB compressed, ~309MB
# unpacked, because the platform package vendors a musl codex binary plus
# bwrap, rg and zsh.
RUN npm install -g @anthropic-ai/claude-code @googleworkspace/cli @openai/codex

# uv (Python package manager)
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# Python tools
# yq (kislyuk) wraps the jq installed above and takes jq filter syntax — not
# the Go mikefarah/yq, whose expression language differs.
RUN pip install --no-cache-dir pytest jsonschema yq

# Sandbox user (HOME=/sandbox so all exec calls see correct home)
RUN groupadd -g 1000 sandbox && \
    useradd -m -u 1000 -g sandbox -s /bin/bash -d /sandbox sandbox

COPY --chown=sandbox:sandbox bin/ /sandbox/bin/
COPY --chown=sandbox:sandbox config/bashrc /sandbox/.bashrc

USER sandbox

RUN mkdir -p /sandbox/bin /sandbox/source /sandbox/.config


WORKDIR /sandbox
