# Generated By: Claude Code (Claude Opus 4.6)
#
# OpenShell sandbox image with Claude Code, tools, and project layout.
# Build: make build
# Usage: openshell sandbox create --from <image> ...

ARG BASE_IMAGE=python:3.13-slim
FROM ${BASE_IMAGE}

RUN apt-get update && apt-get install -y --no-install-recommends \
        curl git iproute2 nftables make jq vim \
    && rm -rf /var/lib/apt/lists/*

# Node.js (Claude Code, MCP servers)
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
    && apt-get install -y --no-install-recommends nodejs \
    && rm -rf /var/lib/apt/lists/*

# Claude Code
RUN npm install -g @anthropic-ai/claude-code

# uv (Python package manager)
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# Sandbox user (OpenShell requirement: high UID to avoid host conflicts)
RUN groupadd -g 1000660000 sandbox && \
    useradd -m -u 1000660000 -g sandbox -s /bin/bash sandbox

# Project layout
RUN install -d -o sandbox -g sandbox /sandbox/bin /sandbox/source

COPY --chown=sandbox:sandbox bin/ /sandbox/bin/
COPY --chown=sandbox:sandbox config/bashrc /sandbox/.bashrc
COPY --chown=sandbox:sandbox config/repo-update.json /sandbox/.config/repo-update.json

USER sandbox

# Bake in reference repos
RUN git clone https://github.com/jewzaam/knowledgebase.git /sandbox/source/knowledgebase \
    && git clone https://github.com/jewzaam/standards.git /sandbox/source/standards

WORKDIR /sandbox
