#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# One rule under test: ~/sandboxes/<name>/openshell-policy.yaml is written ONLY
# by install_policy(), and install_policy() runs only after the enforcer has
# accepted the policy. render_policy() renders to a temp file and never touches
# the sandbox dir. Everything else follows — a path that does not apply a
# policy cannot change the artifact, so upload_static is always safe.
#
# Runs sandbox.sh against a scratch HOME with --dryrun, so no openshell calls
# are made. The hot-swap paths need a live enforcer and are not covered.
#
# Run: tests/test-policy-artifact.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "$WORK/"
# site.env is gitignored and absent on a fresh clone (and in CI); sandbox.sh
# refuses to run without one. Values are never dialled — every run is --dryrun.
if [[ ! -f "${WORK}/config/site.env" ]]; then
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
fi
SANDBOX_SH="${WORK}/scripts/sandbox.sh"

FAKE_HOME="${TMP}/home"
D="${FAKE_HOME}/sandboxes/probe"
mkdir -p "$D"

blocks() { yq -r '.network_policies[].name' "$1" 2>/dev/null | sort | tr '\n' ' '; }
subst() { sed -e 's|${OTEL_HOST}|x|g' -e 's|${OTEL_PORT}|4318|g' \
              -e 's|${PROMETHEUS_HOST}|x|g' -e 's|${PROMETHEUS_PORT}|9090|g' \
              -e 's|${LOKI_HOST}|x|g' -e 's|${LOKI_PORT}|3100|g' "$1"; }

# Stand in for a sandbox running a --policy-applied fetch-service policy.
seed_applied() {
    printf '{"name":"probe","profile":"personal","repos":{}}' > "${D}/manifest.json"
    subst "${WORK}/policies/fetch-service.yaml" > "${D}/openshell-policy.yaml"
}

run_sandbox() { HOME="$FAKE_HOME" bash "$SANDBOX_SH" "$@" >/dev/null 2>&1 || true; }

APPLIED="$(subst "${WORK}/policies/fetch-service.yaml" | yq -r '.network_policies[].name' | sort | tr '\n' ' ')"
PERSONAL="$(subst "${WORK}/policies/personal.yaml" | yq -r '.network_policies[].name' | sort | tr '\n' ' ')"

fail=0
check() {
    local what="$1" want="$2" got
    got="$(blocks "${D}/openshell-policy.yaml")"
    if [[ "$got" != "$want" ]]; then
        echo "FAIL: ${what}" >&2
        echo "  want: ${want}" >&2
        echo "  got:  ${got}" >&2
        fail=1
    fi
}

# --refresh applies no policy, so it must not change the artifact. It still
# renders the profile default into a temp; if that render ever lands in the
# sandbox dir again, fetch-service and search-engines vanish here.
seed_applied
run_sandbox --refresh probe --dryrun
check "--refresh leaves the applied policy alone" "$APPLIED"

# Same for --upload, which exits before the render entirely.
seed_applied
run_sandbox --upload probe --dryrun
check "--upload leaves the applied policy alone" "$APPLIED"

# --refresh --policy would ship an artifact for a policy never applied.
seed_applied
out="$(HOME="$FAKE_HOME" bash "$SANDBOX_SH" --refresh probe --policy personal --dryrun 2>&1 || true)"
grep -q "not valid with --refresh" <<<"$out" \
    || { echo "FAIL: --refresh --policy should be refused" >&2; fail=1; }
check "--refresh --policy leaves the artifact alone" "$APPLIED"

# A host-side template edit is not an applied policy. It must not reach the
# artifact through any path that does not call `openshell policy set`.
seed_applied
cat >> "${WORK}/policies/fetch-service.yaml" <<'YAML'
  unapplied-edit:
    endpoints:
      - host: example.invalid
        port: 443
        protocol: rest
        enforcement: enforce
YAML
run_sandbox --refresh probe --dryrun
run_sandbox --upload probe --dryrun
if [[ "$(blocks "${D}/openshell-policy.yaml")" == *unapplied-edit* ]]; then
    echo "FAIL: an unapplied template edit reached the artifact" >&2
    fail=1
fi
cp "${REPO_ROOT}/policies/fetch-service.yaml" "${WORK}/policies/fetch-service.yaml"

# No artifact means no policy was ever applied through this script, so what
# the enforcer holds is unknown. Nothing may invent one: --upload must not
# manufacture a profile-default artifact, it must warn and stage nothing.
seed_applied
rm -f "${D}/openshell-policy.yaml"
out="$(HOME="$FAKE_HOME" bash "$SANDBOX_SH" --upload probe --dryrun 2>&1 || true)"
if [[ -f "${D}/openshell-policy.yaml" ]]; then
    echo "FAIL: --upload invented an artifact for an unknown policy" >&2
    fail=1
fi
grep -q "no policy artifact in" <<<"$out" \
    || { echo "FAIL: --upload should warn when there is no artifact" >&2; fail=1; }

# --create does apply a policy, so it installs one.
rm -rf "$D" && mkdir -p "$D"
printf '{"name":"probe","profile":"personal","repos":{}}' > "${D}/manifest.json"
run_sandbox --create probe --no-clone --no-connect --dryrun
check "--create installs the policy it handed the enforcer" "$PERSONAL"

[[ $fail -eq 0 ]] && echo "all policy-artifact checks passed"
exit $fail
