#!/bin/bash
# Generated By: Claude Code (claude-opus-5)
#
# One rule under test: a repo upload must not carry .venv into a sandbox.
# `openshell sandbox upload` accepts no exclude, and upload_repo() passes
# --no-git-ignore, so nothing filtered the tree and a host virtualenv rode in.
# The host builds it with Python 3.14 and the sandbox interpreter is 3.13, so
# the arriving site-packages cannot be imported: `python -m pip` in that venv
# fails with "No module named pip" and it has to be deleted and rebuilt.
#
# Drives stage_repo_for_upload() against a fake repo. The upload itself needs a
# live sandbox; the filtering does not.
#
# Run: tests/test-upload-venv.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SANDBOX_SH="${REPO_ROOT}/scripts/sandbox.sh"

if ! command -v rsync >/dev/null 2>&1; then
    echo "warning: rsync not installed, skipping the upload staging checks" >&2
    echo "all upload-venv checks passed"
    exit 0
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

fail=0

# Lift the function out of sandbox.sh — sourcing the script would run it.
HELPERS="${TMP}/helpers.sh"
sed -n '/^stage_repo_for_upload()/,/^}/p' "$SANDBOX_SH" > "$HELPERS"
grep -q 'stage_repo_for_upload' "$HELPERS" \
    || { echo "FAIL: could not lift stage_repo_for_upload out of sandbox.sh" >&2; exit 1; }
# shellcheck source=/dev/null
source "$HELPERS"

# A repo shaped like a real one: tracked files, a gitignored build artifact
# that must still travel, a .git dir, a symlink, and the venv that must not.
SRC="${TMP}/src/myrepo"
mkdir -p "${SRC}/.git" "${SRC}/src" "${SRC}/.venv/lib/python3.14/site-packages"
echo "code" > "${SRC}/src/main.py"
echo "ignored-but-wanted" > "${SRC}/build.log"
echo "objects" > "${SRC}/.git/config"
echo "pip" > "${SRC}/.venv/lib/python3.14/site-packages/pip.py"
echo "bin" > "${SRC}/.venv/pyvenv.cfg"
ln -s src "${SRC}/link-to-src"

DEST="${TMP}/stage"
stage_repo_for_upload "$SRC" "$DEST"

[[ -d "${DEST}/myrepo" ]] \
    || { echo "FAIL: staged tree is not under its repo name" >&2; fail=1; }
[[ ! -e "${DEST}/myrepo/.venv" ]] \
    || { echo "FAIL: .venv was staged for upload" >&2; fail=1; }

# Everything else has to survive. --no-git-ignore is deliberate: untracked and
# gitignored work the host wants must still reach the sandbox.
[[ -f "${DEST}/myrepo/src/main.py" ]] \
    || { echo "FAIL: tracked file was dropped" >&2; fail=1; }
[[ -f "${DEST}/myrepo/build.log" ]] \
    || { echo "FAIL: gitignored file was dropped; only .venv should be" >&2; fail=1; }
[[ -f "${DEST}/myrepo/.git/config" ]] \
    || { echo "FAIL: .git was dropped; the sandbox needs real git history" >&2; fail=1; }
[[ -L "${DEST}/myrepo/link-to-src" ]] \
    || { echo "FAIL: symlink was resolved or dropped; -a must not become -rL" >&2; fail=1; }

# A nested .venv deeper in the tree is the same hazard.
SRC2="${TMP}/src2/multi"
mkdir -p "${SRC2}/sub/.venv" "${SRC2}/sub/pkg"
echo x > "${SRC2}/sub/.venv/pyvenv.cfg"
echo y > "${SRC2}/sub/pkg/mod.py"
stage_repo_for_upload "$SRC2" "${TMP}/stage2"
[[ ! -e "${TMP}/stage2/multi/sub/.venv" ]] \
    || { echo "FAIL: a nested .venv was staged" >&2; fail=1; }
[[ -f "${TMP}/stage2/multi/sub/pkg/mod.py" ]] \
    || { echo "FAIL: nested content was dropped" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all upload-venv checks passed"
exit $fail
