#!/bin/bash
# Generated By: Claude Code (claude-opus-5-5[1m])
#
# Self-check for deferred work on stopped sandboxes: --refresh (NAME or --all)
# and --recreate --all mark the manifest instead of starting a stopped
# sandbox, and the next --connect runs what is pending — recreate over refresh,
# never both. Drives sandbox.sh end to end with openshell and podman stubbed.
#
# Run: tests/test-pending-work.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

fail() { echo "FAIL: $1" >&2; exit 1; }

# --- stubs: phase from $TMP/phase; any start makes it Ready ---
mkdir -p "${TMP}/bin"
cat > "${TMP}/bin/openshell" << 'STUB'
#!/bin/bash
if [[ "$2" == "start" ]]; then echo "${*: -1}" >> "${TMP}/os_started"; echo Ready > "${TMP}/phase"; exit 0; fi
printf '{"sandboxes":[{"name":"sb-test","phase":"%s"}]}\n' "$(cat "${TMP}/phase")"
STUB
cat > "${TMP}/bin/podman" << 'STUB'
#!/bin/bash
[[ "$1" == "start" ]] && { echo Ready > "${TMP}/phase"; exit 0; }
echo '[{"Id":"deadbeef","Labels":{"openshell.ai/sandbox-name":"sb-test"}}]'
STUB
chmod +x "${TMP}/bin/openshell" "${TMP}/bin/podman"
export PATH="${TMP}/bin:${PATH}" TMP

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "$WORK/"
if [[ ! -f "${WORK}/config/site.env" ]]; then
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
fi
SANDBOX_SH="${WORK}/scripts/sandbox.sh"

FAKE_HOME="${TMP}/home"
PROBE="${FAKE_HOME}/sandboxes/probe"
mkdir -p "$PROBE"
MANIFEST="${PROBE}/manifest.json"
reset_manifest() {
    printf '{"name":"probe","openshell_name":"sb-test","profile":"personal","repos":{}}' > "$MANIFEST"
}
flag() { jq -r --arg k "$1" '.[$k] // false' "$MANIFEST"; }
sb() { HOME="$FAKE_HOME" bash "$SANDBOX_SH" "$@" 2>&1; }

# --- lib helpers: set, read, clear several at once ---
(
    # shellcheck source=/dev/null
    source "${REPO_ROOT}/scripts/lib.sh"
    reset_manifest
    manifest_pending "$PROBE" refresh_pending && fail "unset flag read as pending"
    set_manifest_pending "$PROBE" refresh_pending
    set_manifest_pending "$PROBE" recreate_pending
    manifest_pending "$PROBE" refresh_pending || fail "set flag not read back"
    clear_manifest_pending "$PROBE" recreate_pending refresh_pending
    manifest_pending "$PROBE" refresh_pending && fail "refresh flag not cleared"
    manifest_pending "$PROBE" recreate_pending && fail "recreate flag not cleared"
    [[ "$(jq -r .profile "$MANIFEST")" == personal ]] || fail "clearing flags lost other keys"
)

# --- --refresh on a stopped sandbox: marked, not started ---
reset_manifest
echo Stopped > "${TMP}/phase"
rm -f "${TMP}/os_started"
out="$(sb --refresh probe)" || fail "--refresh on a stopped sandbox exited non-zero: ${out}"
[[ "$(flag refresh_pending)" == true ]] || fail "--refresh did not mark a stopped sandbox pending"
[[ -f "${TMP}/os_started" ]] && fail "--refresh started a stopped sandbox"
grep -qF "Refreshing config" <<<"$out" && fail "--refresh refreshed a stopped sandbox"

# Stopping counts as stopped.
reset_manifest
echo Stopping > "${TMP}/phase"
sb --refresh probe >/dev/null || fail "--refresh on a Stopping sandbox exited non-zero"
[[ "$(flag refresh_pending)" == true ]] || fail "--refresh did not defer on a Stopping sandbox"

# --dryrun changes nothing on disk.
reset_manifest
echo Stopped > "${TMP}/phase"
sb --refresh probe --dryrun >/dev/null
[[ "$(flag refresh_pending)" == false ]] || fail "--refresh --dryrun wrote the manifest"

# --- --refresh --all defers the same way (it runs --refresh per sandbox) ---
reset_manifest
sb --refresh --all >/dev/null || fail "--refresh --all failed on a stopped sandbox"
[[ "$(flag refresh_pending)" == true ]] || fail "--refresh --all did not mark a stopped sandbox"

# --- --recreate --all on a stopped sandbox: marked, not recreated ---
reset_manifest
echo Stopped > "${TMP}/phase"
rm -f "${TMP}/os_started"
out="$(sb --recreate --all)" || fail "--recreate --all failed on a stopped sandbox: ${out}"
[[ "$(flag recreate_pending)" == true ]] || fail "--recreate --all did not mark a stopped sandbox"
grep -qF "Recreating sandbox" <<<"$out" && fail "--recreate --all recreated a stopped sandbox"
[[ -f "${TMP}/os_started" ]] && fail "--recreate --all started a stopped sandbox"

# --- --connect runs what is pending, recreate over refresh ---
echo Ready > "${TMP}/phase"

reset_manifest
out="$(sb --connect probe --dryrun || true)"
grep -qF "pending for probe" <<<"$out" && fail "--connect ran pending work with nothing pending"

reset_manifest
jq '.refresh_pending = true' "$MANIFEST" > "${MANIFEST}.tmp" && cat "${MANIFEST}.tmp" > "$MANIFEST"
out="$(sb --connect probe --dryrun || true)"
grep -qF "Refresh pending for probe" <<<"$out" || fail "--connect skipped a pending refresh"

jq '.recreate_pending = true' "$MANIFEST" > "${MANIFEST}.tmp" && cat "${MANIFEST}.tmp" > "$MANIFEST"
out="$(sb --connect probe --dryrun || true)"
grep -qF "Recreate pending for probe" <<<"$out" || fail "--connect skipped a pending recreate"
grep -qF "Refresh pending for probe" <<<"$out" && fail "--connect ran refresh alongside recreate"
grep -qF "Recreating sandbox probe" <<<"$out" || fail "pending recreate did not reach --recreate"

# A pending recreate on a sandbox with no profile stops rather than guessing.
printf '{"name":"probe","openshell_name":"sb-test","repos":{},"recreate_pending":true}' > "$MANIFEST"
if sb --connect probe --dryrun >/dev/null; then
    fail "--connect proceeded with a pending recreate and no profile"
fi

echo "PASS: tests/test-pending-work.sh"
