#!/bin/bash
# Generated By: Claude Code (claude-opus-5-5[1m])
#
# One rule under test: --upload and --download move gitignored files. Repos are
# working copies, not releases: untracked build output, local notes, and
# context files the host gitignores (pr-context.md, open-prs.json) all have to
# survive a round trip. Only .venv is dropped, in both directions.
#
# Each direction can lose them in its own way:
#   - upload: `openshell sandbox upload` filters through
#     `git ls-files --exclude-standard` unless given --no-git-ignore, and
#     stage_repo_for_upload() could grow a gitignore filter of its own;
#   - download: the in-sandbox tar could grow `--exclude-vcs-ignores`, or the
#     host rsync a `.gitignore` filter.
#
# Runs sandbox.sh against a scratch HOME with an `openshell` stub on PATH that
# plays the sandbox with a local directory: /sandbox/... maps to it, exec runs
# the command there, and upload applies openshell's gitignore filter unless
# --no-git-ignore is passed — so dropping that flag fails here exactly as it
# would against a real sandbox.
#
# Run: tests/test-repo-gitignored-transfer.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

for tool in rsync git tar jq; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "warning: ${tool} not installed, skipping the gitignored transfer checks" >&2
        echo "all repo-gitignored-transfer checks passed"
        exit 0
    fi
done

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
export GIT_CONFIG_GLOBAL=/dev/null

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "${REPO_ROOT}/bin" "$WORK/"
if [[ ! -f "${WORK}/config/site.env" ]]; then
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
fi
SANDBOX_SH="${WORK}/scripts/sandbox.sh"

FAKE_HOME="${TMP}/home"
D="${FAKE_HOME}/sandboxes/probe"
# Not a GitHub URL, and no origin remote: generate_repo_context() and the
# private-repo guard both return early, so nothing here reaches gh.
mkdir -p "${D}/myrepo"
printf '{"name":"probe","openshell_name":"sb-probe","profile":"personal","repos":{"myrepo":{"url":"file:///nowhere/myrepo"}}}' \
    > "${D}/manifest.json"

# A real repo, so the stub's gitignore filter has something to apply. Ignored:
# a file by name, a whole directory, and a nested match.
HOST_REPO="${D}/myrepo"
printf 'build.log\nout/\n*.tmp\n.venv/\n' > "${HOST_REPO}/.gitignore"
echo "code" > "${HOST_REPO}/main.py"
git -C "$HOST_REPO" init -q
git -C "$HOST_REPO" add -A
git -C "$HOST_REPO" -c user.name=t -c user.email=t commit -qm init
echo "ignored file" > "${HOST_REPO}/build.log"
mkdir -p "${HOST_REPO}/out" "${HOST_REPO}/src" "${HOST_REPO}/.venv"
echo "ignored dir" > "${HOST_REPO}/out/artifact.bin"
echo "ignored nested" > "${HOST_REPO}/src/scratch.tmp"
echo "venv" > "${HOST_REPO}/.venv/pyvenv.cfg"

SBX="${TMP}/sandbox-root"
mkdir -p "${SBX}/source"

STUB_BIN="${TMP}/stub-bin"
mkdir -p "$STUB_BIN"
cat > "${STUB_BIN}/openshell" <<'EOF'
#!/bin/bash
# Maps /sandbox paths onto $SBX. Only the subcommands sandbox.sh uses on the
# --upload/--download paths do anything; the rest succeed silently.
set -euo pipefail
map() { case "$1" in /sandbox|/sandbox/*) echo "${SBX}${1#/sandbox}" ;; *) echo "$1" ;; esac; }

[[ "${1:-}" == sandbox ]] || exit 0
sub="${2:-}"
shift 2
case "$sub" in
    exec)
        while [[ $# -gt 0 && "$1" != "--" ]]; do shift; done
        shift
        cmd=()
        for a in "$@"; do cmd+=("$(map "$a")"); done
        "${cmd[@]}"
        ;;
    upload)
        no_git_ignore=false
        pos=()
        for a in "$@"; do
            case "$a" in
                --no-git-ignore) no_git_ignore=true ;;
                --*) ;;
                *) pos+=("$a") ;;
            esac
        done
        src="${pos[1]}"
        dest="$(map "${pos[2]}")"
        mkdir -p "$dest"
        if [[ "$no_git_ignore" == false ]] && git -C "$src" rev-parse --git-dir >/dev/null 2>&1; then
            # openshell's default: send only what git does not ignore.
            mkdir -p "${dest}/$(basename "$src")"
            git -C "$src" ls-files -z --cached --others --exclude-standard \
                | rsync -a --from0 --files-from=- "$src/" "${dest}/$(basename "$src")/"
        else
            cp -a "$src" "$dest/"
        fi
        ;;
    download)
        pos=()
        for a in "$@"; do [[ "$a" == --* ]] || pos+=("$a"); done
        cp -a "$(map "${pos[1]}")" "${pos[2]}/"
        ;;
esac
EOF
chmod +x "${STUB_BIN}/openshell"

sbx() {
    SBX="$SBX" HOME="$FAKE_HOME" PATH="${STUB_BIN}:${PATH}" \
        bash "$SANDBOX_SH" "$@" > "${TMP}/last.log" 2>&1 \
        || { echo "FAIL: sandbox.sh $* exited non-zero:" >&2; sed 's/^/    /' "${TMP}/last.log" >&2; return 1; }
}

fail=0
IGNORED=(build.log out/artifact.bin src/scratch.tmp)

# Self-check: the stub really filters without --no-git-ignore, or the upload
# assertions below prove nothing. Runs first, on the untouched host repo.
probe_dest="${TMP}/probe-dest"
SBX="$SBX" "${STUB_BIN}/openshell" sandbox upload sb-probe "$HOST_REPO" "$probe_dest"
[[ -f "${probe_dest}/myrepo/main.py" && ! -e "${probe_dest}/myrepo/build.log" ]] \
    || { echo "FAIL: stub does not apply openshell's gitignore filter; the test is vacuous" >&2; fail=1; }

# --- upload carries gitignored files into the sandbox ---
sbx --upload probe --force || fail=1
SBX_REPO="${SBX}/source/myrepo"
[[ -f "${SBX_REPO}/main.py" ]] \
    || { echo "FAIL: upload dropped a tracked file" >&2; fail=1; }
for f in "${IGNORED[@]}"; do
    [[ -f "${SBX_REPO}/${f}" ]] \
        || { echo "FAIL: upload dropped gitignored ${f}" >&2; fail=1; }
done
[[ ! -e "${SBX_REPO}/.venv" ]] \
    || { echo "FAIL: upload carried .venv" >&2; fail=1; }

# --- download carries gitignored files the sandbox created back to the host ---
echo "made in sandbox" > "${SBX_REPO}/session.tmp"
mkdir -p "${SBX_REPO}/out/new"
echo "made in sandbox" > "${SBX_REPO}/out/new/report.bin"
echo "edited in sandbox" > "${SBX_REPO}/build.log"
sbx --download probe --force || fail=1
for f in session.tmp out/new/report.bin "${IGNORED[@]}"; do
    [[ -f "${HOST_REPO}/${f}" ]] \
        || { echo "FAIL: download dropped gitignored ${f}" >&2; fail=1; }
done
grep -q "edited in sandbox" "${HOST_REPO}/build.log" 2>/dev/null \
    || { echo "FAIL: download did not bring back the sandbox's edit to gitignored build.log" >&2; fail=1; }
[[ -f "${HOST_REPO}/.venv/pyvenv.cfg" ]] \
    || { echo "FAIL: download removed the host's .venv" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all repo-gitignored-transfer checks passed"
exit $fail
