#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# One rule under test: --refresh uploads each per-repo context file INTO the
# repo directory, regardless of whether the host gitignores it.
#
# Both halves matter and both are invisible without a real sandbox:
#   - a dest without a trailing slash is the file's new *name*, so the upload
#     tries to write a regular file over /sandbox/source/<repo> and the remote
#     tar fails;
#   - without --no-git-ignore, `openshell sandbox upload` filters through
#     `git ls-files --exclude-standard`, which honors the user's global ignore
#     file — so gitignoring pr-context.md on the host changes which upload path
#     runs.
#
# Runs sandbox.sh against a scratch HOME with --dryrun, so no openshell calls
# are made and the upload command is only printed.
#
# Run: tests/test-refresh-context-upload.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "$WORK/"
if [[ ! -f "${WORK}/config/site.env" ]]; then
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
fi
SANDBOX_SH="${WORK}/scripts/sandbox.sh"

FAKE_HOME="${TMP}/home"
D="${FAKE_HOME}/sandboxes/probe"
# No .git in the repo dir: generate_repo_context() returns early, so nothing
# here reaches gh and the seeded context files survive the regeneration step.
mkdir -p "${D}/myrepo"
printf '{"name":"probe","openshell_name":"sb-probe","profile":"personal","repos":{"myrepo":{"url":"git@github.com:x/myrepo.git"}}}' \
    > "${D}/manifest.json"
for f in pr-context.md jira-context.md open-prs.json; do
    echo "seeded" > "${D}/myrepo/${f}"
done

out="$(HOME="$FAKE_HOME" bash "$SANDBOX_SH" --refresh probe --dryrun 2>&1 || true)"

fail=0
for f in pr-context.md jira-context.md open-prs.json; do
    line="$(grep -F "myrepo/${f}" <<<"$out" | grep -F 'sandbox upload' || true)"
    if [[ -z "$line" ]]; then
        echo "FAIL: --refresh did not upload ${f}" >&2
        fail=1
        continue
    fi
    grep -q -- '--no-git-ignore' <<<"$line" \
        || { echo "FAIL: ${f} upload is subject to gitignore filtering: ${line}" >&2; fail=1; }
    grep -q -- '/sandbox/source/myrepo/$' <<<"$line" \
        || { echo "FAIL: ${f} dest is not the repo directory: ${line}" >&2; fail=1; }
done

# --quick skips the per-repo block outright: no gh calls, and nothing to
# re-send when nothing was regenerated. Config still uploads.
quick_out="$(HOME="$FAKE_HOME" bash "$SANDBOX_SH" --refresh probe --quick --dryrun 2>&1 || true)"
if grep -F 'sandbox upload' <<<"$quick_out" | grep -qF 'myrepo/'; then
    echo "FAIL: --refresh --quick still uploaded per-repo context" >&2
    fail=1
fi
grep -qF -- '--quick: skipping per-repo context generation' <<<"$quick_out" \
    || { echo "FAIL: --refresh --quick did not say what it skipped" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all refresh-context-upload checks passed"
exit $fail
