#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# Rules under test:
#   1. --upload does not re-upload a repo with nothing modified since
#      .repos[<name>].last_upload. `openshell sandbox upload` is a full tar with
#      no delta, so an unchanged reference repo otherwise re-sends its whole
#      .git every time.
#   2. --upload --force ALWAYS sends, unchanged or not. It rm -rf's the sandbox
#      copy first, so it is how edits a session made inside the sandbox get
#      wiped back to host state. Skipping there would assume host and sandbox
#      already agree — the one thing it cannot assume.
#   3. A real upload stamps last_upload; a download stamps last_download; a
#      --dryrun stamps neither, or the next real run skips a repo it never sent.
#   4. --upload without --force skips context generation entirely (no gh, no
#      Jira).
#   5. --download writes only what actually differs, so an --upload after a
#      download still skips. The download does not preserve mtimes.
#   6. --download pulls only the repos the sandbox changed, asked in one exec,
#      and pulls everything when the answer does not arrive.
#   7. Both move repos and nothing else. --upload does not ship the system
#      prompt, manifest or policy (upload_static's callers each do), and
#      --download does not pull Claude session state (--recreate does).
#
# openshell and gh are stubbed, so the test needs no gateway, auth, or network.
#
# Run: tests/test-upload-skip.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "$WORK/"
# site.env is gitignored and absent on a fresh clone; sandbox.sh refuses to run
# without one. Never dialled — openshell is stubbed.
if [[ ! -f "${WORK}/config/site.env" ]]; then
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
fi

export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null
export GIT_AUTHOR_NAME=test GIT_AUTHOR_EMAIL=test@example.com
export GIT_COMMITTER_NAME=test GIT_COMMITTER_EMAIL=test@example.com

fail=0

# --- stubs: openshell and gh both log and succeed ---
STUB="${TMP}/stub"
mkdir -p "$STUB"
CALL_LOG="${TMP}/calls"
export CALL_LOG
cat > "${STUB}/openshell" << 'STUBEOF'
#!/bin/bash
echo "openshell $*" >> "$CALL_LOG"
# $UPLOAD_BROKEN stands in for a transfer that fails. It prints openshell's own
# completion line first, because the filter upload_repo() pipes this through must
# not be what decides the exit status.
if [[ "$1 $2" == "sandbox upload" && -n "${UPLOAD_BROKEN:-}" ]]; then
    echo "✓ Upload complete" >&2
    exit 1
fi
# `sandbox download <name> [--gateway X] <remote-path> <dest>` serves from
# $SANDBOX_FS when one is set. A .tar source is the repo tarball the exec below
# just wrote, so it is copied as a file — its path is under /sandbox/source and
# has already been rewritten into $SANDBOX_FS. Anything else is a directory
# pull, copied WITHOUT -a: that path does not preserve mtimes, which is the
# whole reason a download used to make every repo look modified.
if [[ "$1 $2" == "sandbox download" && -n "${SANDBOX_FS:-}" ]]; then
    src="${@: -2:1}"
    dest="${@: -1}"
    # The real CLI resolves a download source against the workspace root it
    # discovers with `pwd -P` and refuses anything outside it, which is a
    # separate gate from the Landlock policy — /tmp is writable and still
    # rejected. Staging the tarball there shipped and failed on the first real
    # run; a stub that maps any path into $SANDBOX_FS cannot see that, so it
    # refuses here too.
    if [[ "$src" != /sandbox/* ]]; then
        echo "Error:   × sandbox source path '$src' is outside the sandbox workspace (/sandbox)" >&2
        exit 1
    fi
    if [[ "$src" == *.tar ]]; then
        src="${SANDBOX_FS}/$(basename "$src")"
        [[ -f "$src" && -d "$dest" ]] && cp "$src" "${dest}/"
    else
        src="${SANDBOX_FS}/$(basename "$src")"
        [[ -d "$src" && -d "$dest" ]] && cp -r "${src}/." "${dest}/"
    fi
fi
# `sandbox exec ... -- <command>`: run the command for real with /sandbox/source
# rewritten to $SANDBOX_FS, so both the clean-repos walk and the download tar
# are the ones that ship. Everything after `--` is the command, so `bash -c
# <script>` and `tar cf ...` both work without the stub knowing which is which.
# $EXEC_BROKEN stands in for a dead gateway — the case that must never be read
# as "clean".
if [[ "$1 $2" == "sandbox exec" && -n "${SANDBOX_FS:-}" ]]; then
    [[ -n "${EXEC_BROKEN:-}" ]] && exit 1
    cmd=(); seen=0
    for a in "$@"; do
        [[ $seen == 1 ]] && cmd+=("${a//\/sandbox\/source/$SANDBOX_FS}")
        [[ "$a" == "--" ]] && seen=1
    done
    # Only the two execs the paths under test depend on actually run: the
    # clean-repos walk (bash -c) and the download tar. Everything else stays a
    # no-op, as it was before this stub could run commands at all. upload_repo's
    # `rm -rf /sandbox/source/<repo>` is the one that matters — running it for
    # real would have every `upload` in this file wipe the fixture, and `upload`
    # is used throughout just to move the stamp.
    case "${cmd[0]:-}" in
        bash|tar) "${cmd[@]}"; exit $? ;;
    esac
    exit 0
fi
exit 0
STUBEOF
# gh answers with a stable PR and a stable PR list, so context generation
# produces byte-identical files on every run — which is the case that has to
# leave the repo looking clean.
cat > "${STUB}/gh" << 'STUBEOF'
#!/bin/bash
echo "gh $*" >> "$CALL_LOG"
case "$1 $2" in
    # $GH_NO_PR makes the branch look like it has no PR, so generate_repo_context
    # writes nothing into the repo. Exit 1 with no recognisable message is the
    # "gh could not answer" path, which keeps existing files rather than deleting.
    "pr view") [[ -n "${GH_NO_PR:-}" ]] && exit 1
               echo '{"number":7,"title":"t","body":"b","headRefName":"main","baseRefName":"main","labels":[],"assignees":[]}' ;;
    "pr list") echo '[]' ;;
    *) exit 1 ;;
esac
STUBEOF
chmod +x "${STUB}/openshell" "${STUB}/gh"
export PATH="${STUB}:${PATH}"

# --- fixture: a sandbox dir with one GitHub repo ---
export HOME="${TMP}/home"
SBX="${HOME}/sandboxes/probe"
REPO="${SBX}/myrepo"
mkdir -p "$REPO"
git -C "$REPO" init -q -b main
echo hello > "${REPO}/file.txt"
git -C "$REPO" add file.txt
git -C "$REPO" commit -qm init
jq -n '{name:"probe",openshell_name:"sb-probe",profile:"personal",
        repos:{myrepo:{url:"git@github.com:org/myrepo.git"}}}' > "${SBX}/manifest.json"

MANIFEST="${SBX}/manifest.json"
stamp_of() { jq -r --arg f "$1" '.repos.myrepo[$f] // empty' "$MANIFEST"; }
uploaded() { grep -qE 'openshell sandbox upload .*/myrepo /sandbox/source/' "$CALL_LOG"; }

# last_upload has whole-second resolution, so a file written in the same second
# as the stamp reads as newer than it. That is deliberate — it costs one
# redundant upload rather than dropping a change — but it makes a test whose
# every step lands in the same second meaningless. Settle first.
upload() {
    sleep 1
    : > "$CALL_LOG"
    ( cd "$SBX" && "${WORK}/scripts/sandbox.sh" --upload probe "$@" ) >/dev/null 2>&1
}

# --- first upload: sends the repo and stamps last_upload ---
upload
uploaded || { echo "FAIL: first upload did not send the repo" >&2; fail=1; }
FIRST="$(stamp_of last_upload)"
[[ -n "$FIRST" ]] \
    || { echo "FAIL: no last_upload in manifest after a real upload" >&2; fail=1; }

# --- the default makes no gh call ---
grep -q '^gh ' "$CALL_LOG" && { echo "FAIL: --upload still called gh" >&2; fail=1; }

# --- nothing changed: skipped ---
upload
uploaded && { echo "FAIL: re-uploaded a repo with no changes" >&2; fail=1; }
[[ "$(stamp_of last_upload)" == "$FIRST" ]] \
    || { echo "FAIL: a skipped upload moved last_upload" >&2; fail=1; }

# --- a modified file brings it back ---
echo changed > "${REPO}/file.txt"
upload
uploaded || { echo "FAIL: a modified repo was skipped" >&2; fail=1; }
[[ "$(stamp_of last_upload)" != "$FIRST" ]] \
    || { echo "FAIL: last_upload not refreshed after a real upload" >&2; fail=1; }

# --- a dryrun stamps nothing ---
BEFORE="$(stamp_of last_upload)"
echo again > "${REPO}/file.txt"
upload --dryrun
[[ "$(stamp_of last_upload)" == "$BEFORE" ]] \
    || { echo "FAIL: --dryrun stamped last_upload for an upload it never made" >&2; fail=1; }
upload
uploaded || { echo "FAIL: a repo changed during --dryrun was skipped afterwards" >&2; fail=1; }

# --- a --force run generates context ---
upload --force
uploaded || { echo "FAIL: --force upload did not send the repo" >&2; fail=1; }
grep -q 'gh pr view' "$CALL_LOG" \
    || { echo "FAIL: --force upload generated no context" >&2; fail=1; }
[[ -f "${REPO}/pr-context.md" ]] \
    || { echo "FAIL: pr-context.md not written" >&2; fail=1; }

# --- the default over the same repo writes nothing, so it settles to skipping.
# The first may still re-send: last_upload has whole-second resolution, so
# context files written in the second the stamp names read as newer than it.
# One redundant tar, then quiet. ---
upload
upload
uploaded && { echo "FAIL: --upload re-uploaded a repo it did not modify" >&2; fail=1; }
grep -q '^gh ' "$CALL_LOG" && { echo "FAIL: --upload called gh" >&2; fail=1; }

# --- THE WIPE CASE: --upload --force sends an unchanged repo anyway. A session
# may have edited files inside the sandbox; rm -rf + re-upload is how that gets
# reset, and the host copy looks identical either way.
#
# GH_NO_PR stops pr-context.md being rewritten and open-prs.json is inside its
# TTL, so nothing lands in the repo — without that, context generation dirties
# it and the upload happens for the wrong reason. ---
GH_NO_PR=1 upload --force
[[ -z "$(find "$REPO" -newermt "$(stamp_of last_upload)" -print -quit)" ]] \
    || { echo "FAIL: setup wrong — the repo was modified, so this proves nothing" >&2; fail=1; }
uploaded || { echo "FAIL: --upload --force skipped an unchanged repo, so a session's sandbox-side edits cannot be wiped" >&2; fail=1; }

# --- -f is the same flag as --force. The optional-NAME parsers accepted
# anything not starting with `--` as the sandbox name, so `--upload -f` set the
# name to "-f" and died resolving it. ---
# `|| true` on both: with the bug, sandbox.sh exits non-zero, and under set -e
# that aborts the whole file before any assertion runs — a real failure would
# show up as a silent early exit rather than a FAIL line.
: > "$CALL_LOG"
( cd "$SBX" && "${WORK}/scripts/sandbox.sh" --upload probe -f ) >/dev/null 2>&1 || true
grep -q '^gh ' "$CALL_LOG" \
    || { echo "FAIL: -f did not force context generation" >&2; fail=1; }
: > "$CALL_LOG"
( cd "$SBX" && "${WORK}/scripts/sandbox.sh" --upload -f ) >/dev/null 2>&1 || true
grep -q 'sandbox upload' "$CALL_LOG" \
    || { echo "FAIL: --upload -f did nothing — -f was consumed as the sandbox name" >&2; fail=1; }

# --- --upload moves repos and nothing else. upload_static() stages the system
# prompt, manifest and policy into <tmp>/source and uploads that to /sandbox; a
# repo goes to /sandbox/source/. So a destination of exactly /sandbox is those
# three riding along on a command that cannot change any of them — including
# every run where all repos were skipped. --create and --refresh ship them
# through upload_config(), --add-repo once it has rewritten the repo list,
# --policy once the enforcer has accepted. ---
upload --force
grep -qE 'openshell sandbox upload .* /sandbox$' "$CALL_LOG" \
    && { echo "FAIL: --upload shipped sandbox config, not just repos" >&2; fail=1; }

# --- a failed upload still fails the run. upload_repo() pipes openshell's stderr
# through a filter to drop its `✓ Upload complete` and reprint it with the reason
# attached; a pipeline reports the LAST element's status, so without pipefail
# reaching openshell, a failed tar would exit 0 and go on to stamp last_upload —
# which then skips the repo that never arrived. ---
BEFORE_BROKEN="$(stamp_of last_upload)"
export UPLOAD_BROKEN=1
upload --force && { echo "FAIL: a failed openshell upload exited 0" >&2; fail=1; }
unset UPLOAD_BROKEN
[[ "$(stamp_of last_upload)" == "$BEFORE_BROKEN" ]] \
    || { echo "FAIL: a failed upload stamped last_upload" >&2; fail=1; }

source "${WORK}/scripts/lib.sh"

# --- git state detection. `git status` rewrites .git and .git/index and
# nothing else, so an editor or shell prompt polling it used to make every repo
# look modified on every run. Excluding those must not cost real git signals:
# staging, committing and branch switches all write elsewhere under .git. ---
git_quiet() { git -C "$REPO" -c commit.gpgsign=false "$@" >/dev/null 2>&1; }
settle() { upload; upload; }

settle
uploaded && { echo "FAIL: setup wrong — repo not in the skipped state" >&2; fail=1; }

git_quiet status --porcelain
upload
uploaded && { echo "FAIL: a bare 'git status' made the repo look modified" >&2; fail=1; }

echo staged > "${REPO}/staged.txt"
git_quiet add staged.txt
rm -f "${REPO}/staged.txt"          # worktree back as it was; only the index and objects hold it
upload
uploaded || { echo "FAIL: a staged change was not detected" >&2; fail=1; }

settle
git_quiet checkout -b other-branch
upload
uploaded || { echo "FAIL: a branch switch was not detected" >&2; fail=1; }

settle
echo committed > "${REPO}/committed.txt"
git_quiet add committed.txt
git_quiet commit -m c
upload
uploaded || { echo "FAIL: a commit was not detected" >&2; fail=1; }

# --- a download of unchanged content leaves the host mtimes alone, so an
# upload after it still skips. `openshell sandbox download` does not preserve
# mtimes; under a plain `rsync -a` that rewrote every file and made the repo
# newer than last_upload. Edit in the sandbox, download, upload is the usual
# pattern, so the upload had nothing left to skip. ---
# The real download path, so it needs the real rsync. sandbox.sh cannot do
# anything without it either, so this only fires where nothing would work.
if ! command -v rsync >/dev/null 2>&1; then
    echo "warning: rsync not installed, skipping the --download checks" >&2
fi
export SANDBOX_FS="${TMP}/sandboxfs"
mkdir -p "$SANDBOX_FS"
download() {
    sleep 1
    : > "$CALL_LOG"
    # Output is dropped, so an unexpected non-zero exit would abort the file
    # under set -e with nothing said — which is how the tarball-in-/tmp bug
    # looked here: no FAIL, no pass line, just exit 1. The status is returned
    # unchanged, because the fail-safe check below asserts on it.
    ( cd "$SBX" && "${WORK}/scripts/sandbox.sh" --download probe "$@" ) >/dev/null 2>&1 \
        || { [[ -n "${EXPECT_DOWNLOAD_FAIL:-}" ]] \
                || echo "note: sandbox.sh --download $* exited non-zero" >&2
             return 1; }
}

if command -v rsync >/dev/null 2>&1; then
    settle
    uploaded && { echo "FAIL: setup wrong — repo not in the skipped state" >&2; fail=1; }

    rm -rf "${SANDBOX_FS}/myrepo"
    cp -a "$REPO" "${SANDBOX_FS}/myrepo"
    download --force
    upload
    uploaded && { echo "FAIL: --download of unchanged content made the next upload re-send everything" >&2; fail=1; }

    # ...and a real sandbox-side edit still lands, and still counts as a change
    echo "from the sandbox" > "${SANDBOX_FS}/myrepo/file.txt"
    download --force
    grep -q "from the sandbox" "${REPO}/file.txt" \
        || { echo "FAIL: --download did not bring the sandbox edit to the host" >&2; fail=1; }
    upload
    uploaded || { echo "FAIL: a file changed by --download was not uploaded" >&2; fail=1; }
fi

# --- --download asks the sandbox which repos it changed and pulls only those.
# The upload side reads host mtimes; nothing on the host can see the sandbox,
# and downloading a repo to learn whether it was worth downloading is the cost
# being avoided. One exec covers every repo. ---
if command -v rsync >/dev/null 2>&1; then
    # A pull is now the download of that repo's tarball. The tar and the rm that
    # bracket it are execs, so `execs` counts only the clean-repos walk — the
    # one exec that runs `bash -c`. Counting every exec would make "one exec for
    # all repos" grow with the number of repos actually pulled. Matching on the
    # walk script's own text does not work: the stub logs `openshell $*`, and
    # the script's embedded newlines put its body on lines of its own.
    pulled() { grep -q 'openshell sandbox download .*openshell-dl-myrepo\.tar' "$CALL_LOG"; }
    execs() { grep -c 'openshell sandbox exec .*bash -c' "$CALL_LOG"; }

    # host and sandbox agree, and the sandbox has not touched the repo since
    rm -rf "${SANDBOX_FS}/myrepo"
    cp -a "$REPO" "${SANDBOX_FS}/myrepo"
    upload
    download
    pulled && { echo "FAIL: --download pulled a repo the sandbox never touched" >&2; fail=1; }
    [[ "$(execs)" == "1" ]] \
        || { echo "FAIL: expected exactly one exec for all repos, got $(execs)" >&2; fail=1; }

    # a sandbox-side edit brings it back, and the content actually arrives
    echo "edited in the sandbox" > "${SANDBOX_FS}/myrepo/file.txt"
    download
    pulled || { echo "FAIL: --download skipped a repo the sandbox changed" >&2; fail=1; }
    grep -q "edited in the sandbox" "${REPO}/file.txt" \
        || { echo "FAIL: --download did not bring the edit to the host" >&2; fail=1; }

    # --- a write inside .venv is not a reason to pull. download_sandbox()'s
    # rsync drops .venv on arrival, so it is the one thing the walk can find
    # that cannot change the host copy — and a live virtualenv moves on every
    # pip install and every .pyc rewrite, which made a Python repo dirty on
    # every check and dragged the whole venv across to be discarded. The dir is
    # created BEFORE the stamp on purpose: adding it rewrites the repo root's
    # own mtime, which is a real change and pulls once. It is the writes
    # afterwards, inside it, that must not. ---
    mkdir -p "${SANDBOX_FS}/myrepo/.venv/lib"
    upload
    echo wheel > "${SANDBOX_FS}/myrepo/.venv/lib/pkg.so"
    download
    pulled && { echo "FAIL: a .venv write made --download pull the whole repo" >&2; fail=1; }

    # ...and a real edit beside a .venv still pulls, without the venv. The
    # exclusion is the tar's now, not the rsync's — it has to hold at the source
    # or the bytes cross the wire anyway, which is the whole point of the tar.
    echo "beside the venv" > "${SANDBOX_FS}/myrepo/file.txt"
    download
    pulled || { echo "FAIL: --download skipped a repo edited alongside a .venv" >&2; fail=1; }
    [[ -e "${REPO}/.venv" ]] \
        && { echo "FAIL: .venv reached the host" >&2; fail=1; }
    # ...and specifically at the source. The rsync would drop .venv on arrival
    # either way, so the check above passes even with the tar's exclusion
    # removed — it cannot tell "never sent" from "sent and discarded", which is
    # the entire difference this change exists to make.
    grep -q 'sandbox exec .*tar cf .*--exclude=\.venv' "$CALL_LOG" \
        || { echo "FAIL: the source-side tar did not exclude .venv" >&2; fail=1; }
    grep -q "beside the venv" "${REPO}/file.txt" \
        || { echo "FAIL: the tar did not carry the real edit to the host" >&2; fail=1; }

    # Three repos, ONE exec, and a per-repo answer. A call per repo would
    # multiply the round trip by the repo count, which is the whole cost being
    # avoided — the reference repos are why a download is slow.
    #
    # `ball` and `baseballbat` are the names on purpose: the clean set is a
    # space-delimited string, and the delimiters are the only thing stopping
    # one repo's verdict from being read off another's name. Both directions
    # are checked, because only one of them is obvious.
    pulled_repo() { grep -q "openshell sandbox download .*openshell-dl-${1}\.tar" "$CALL_LOG"; }
    for r in ball baseballbat; do
        mkdir -p "${SBX}/${r}"
        echo "$r" > "${SBX}/${r}/notes.txt"
        jq --arg r "$r" '.repos[$r] = {url:("git@github.com:org/" + $r + ".git")}' \
            "$MANIFEST" > "${MANIFEST}.t" && mv "${MANIFEST}.t" "$MANIFEST"
    done

    # a substring of a clean repo's name must not be read as clean itself
    sandbox_mirror() {
        rm -rf "${SANDBOX_FS}/myrepo" "${SANDBOX_FS}/ball" "${SANDBOX_FS}/baseballbat"
        cp -a "$REPO" "${SANDBOX_FS}/myrepo"
        cp -a "${SBX}/ball" "${SANDBOX_FS}/ball"
        cp -a "${SBX}/baseballbat" "${SANDBOX_FS}/baseballbat"
    }
    changed_only() {
        local target="$1" other="$2"
        upload
        sandbox_mirror
        echo "changed in the sandbox" > "${SANDBOX_FS}/${target}/notes.txt"
        download
        [[ "$(execs)" == "1" ]] \
            || { echo "FAIL: three repos took $(execs) execs, not one" >&2; fail=1; }
        pulled_repo "$target" \
            || { echo "FAIL: did not pull ${target}, which the sandbox changed" >&2; fail=1; }
        pulled_repo "$other" \
            && { echo "FAIL: pulled ${other} — its verdict came off ${target}'s name" >&2; fail=1; }
        pulled && { echo "FAIL: pulled the repo the sandbox left alone" >&2; fail=1; }
        grep -q "changed in the sandbox" "${SBX}/${target}/notes.txt" \
            || { echo "FAIL: ${target}'s content did not reach the host" >&2; fail=1; }
    }
    changed_only baseballbat ball
    changed_only ball baseballbat

    # --download --force pulls regardless, and asks nothing
    upload
    download --force
    pulled || { echo "FAIL: --download --force skipped an unchanged repo" >&2; fail=1; }
    [[ "$(execs)" == "0" ]] \
        || { echo "FAIL: --download --force still asked the sandbox what changed" >&2; fail=1; }

    # THE FAIL-SAFE: a broken exec must never read as "nothing changed". A
    # wrongly skipped upload costs one tar; a wrongly skipped download loses
    # whatever the session did.
    #
    # It used to reach that by pulling every repo when the walk got no answer.
    # Since the pull builds its tarball over the same exec channel, a dead exec
    # now fails the download outright instead. Both honour the rule; only a
    # silent success would break it, so that is what is asserted. The stub's
    # combination — exec dead, download alive — does not occur in practice:
    # `openshell sandbox download` rides the same gateway.
    upload
    EXPECT_DOWNLOAD_FAIL=1 EXEC_BROKEN=1 download \
        && { echo "FAIL: a broken exec let --download exit 0" >&2; fail=1; }
    pulled && { echo "FAIL: --download reported a pull it could not have made" >&2; fail=1; }
fi

# --- --download is the mirror: repos and nothing else. Claude session state
# (the OAuth token, .claude.json, and the whole transcript directory) is
# --recreate's business — it is the only consumer, through
# upload_claude_state() on the create that follows. Pulling it on every
# download meant a routine pull of a repo also copied the token to the host and
# re-fetched every transcript. --dryrun so this runs without rsync. ---
out="$( cd "$SBX" && "${WORK}/scripts/sandbox.sh" --download probe --dryrun 2>&1 || true )"
grep -q 'sandbox download .*\.claude' <<<"$out" \
    && { echo "FAIL: --download pulled Claude session state, not just repos" >&2; fail=1; }

# --- last_download is stamped separately from last_upload ---
record_repo_timestamp "$SBX" myrepo last_download
[[ -n "$(stamp_of last_download)" ]] \
    || { echo "FAIL: last_download not recorded" >&2; fail=1; }

# --- re-registering a repo must not wipe the stamps. write_manifest assigned a
# fresh object to .repos[<name>], so --create/--add-repo dropped them and every
# later --upload re-uploaded everything. Checked with last_download, which
# --add-repo never writes: last_upload is legitimately re-stamped by the upload
# --add-repo performs, so it cannot tell a merge from a replace. ---
BEFORE_CLONE="$(stamp_of last_download)"
( cd "$SBX" && "${WORK}/scripts/sandbox.sh" --add-repo probe \
    --repo git@github.com:org/myrepo.git --source-dir "$REPO" ) >/dev/null 2>&1 || true
[[ "$(stamp_of last_download)" == "$BEFORE_CLONE" ]] \
    || { echo "FAIL: re-registering a repo dropped last_download (got: '$(stamp_of last_download)')" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all upload-skip checks passed"
exit $fail
