#!/bin/bash
# Generated By: Claude Code (claude-opus-5[1m])
#
# One rule under test: --jira writes every key given into one jira-context.md
# in the sandbox directory named by CWD.
#
# curl is stubbed on PATH — the fetch is real code, --dryrun does not cover it.
#
# Run: tests/test-jira-flag.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "$WORK/"
if [[ ! -f "${WORK}/config/site.env" ]]; then
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
fi
SANDBOX_SH="${WORK}/scripts/sandbox.sh"

# Stub Jira: no Acceptance Criteria field, one canned issue for any key. The
# key in the heading comes from the caller, so a heading per key is proof that
# key was fetched.
mkdir -p "${TMP}/bin"
cat > "${TMP}/bin/curl" <<'CURL'
#!/bin/bash
for arg in "$@"; do :; done
case "$arg" in
    */rest/api/3/field) echo '[]' ;;
    */rest/api/3/issue/*) echo '{"fields":{"summary":"Canned","status":{"name":"New"},"issuetype":{"name":"Story"},"description":{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"line one"},{"type":"hardBreak"},{"type":"text","text":"line two"}]}]}}}' ;;
    *) ;;
esac
CURL
chmod +x "${TMP}/bin/curl"
export PATH="${TMP}/bin:${PATH}"

FAKE_HOME="${TMP}/home"
D="${FAKE_HOME}/sandboxes/probe"
mkdir -p "$D"

fail=0
out="$(cd "$D" && HOME="$FAKE_HOME" JIRA_USERNAME=u JIRA_TOKEN=t \
    bash "$SANDBOX_SH" --jira AAA-1 --jira 'https://example.atlassian.net/browse/BBB-2?atlOrigin=x' 2>&1 || true)"

for key in AAA-1 BBB-2; do
    grep -q "^### ${key}:" "${D}/jira-context.md" 2>/dev/null \
        || { echo "FAIL: ${key} missing from jira-context.md: ${out}" >&2; fail=1; }
done

# A hardBreak is a line break inside a paragraph, and carries no text of its
# own — dropping it runs the lines either side together.
grep -q '^line two$' "${D}/jira-context.md" 2>/dev/null \
    || { echo "FAIL: hardBreak did not survive rendering" >&2; fail=1; }

# Outside a sandbox directory there is nowhere to write.
if (cd "$TMP" && HOME="$FAKE_HOME" JIRA_USERNAME=u JIRA_TOKEN=t \
    bash "$SANDBOX_SH" --jira AAA-1 >/dev/null 2>&1); then
    echo "FAIL: --jira outside a sandbox directory was accepted" >&2
    fail=1
fi

[[ $fail -eq 0 ]] && echo "all jira-flag checks passed"
exit $fail
