#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# Rules under test:
#   1. No --since and no SANDBOX_CLONE_SINCE is a full clone. That is the
#      shipped default, so a fresh checkout of this repo behaves as it always
#      did.
#   2. --since prunes history, and the clone keeps its remote-tracking
#      branches. `git clone --shallow-since` implies --single-branch, which
#      would leave a sandbox holding one branch and no network to fetch the
#      rest, so clone_repo_host passes --no-single-branch.
#   3. SANDBOX_CLONE_SINCE from site.env supplies the default, and --since ''
#      overrides it back to full history.
#   4. A --since value git would accept and misread is rejected before any
#      clone runs. git's approxidate answers '30d' with the current time
#      rather than an error, which clones zero history and reports success;
#      `date -d` is what turns that into a failure.
#   5. A window containing no commits falls back to a full clone. git treats it
#      as fatal ("no commits selected for shallow requests"), and a repo idle
#      longer than the window is the ordinary way to reach it.
#
# openshell and gh are stubbed and the upstream is a local file:// repo, so the
# test needs no gateway, auth, or network.
#
# Run: tests/test-clone-since.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "$WORK/"

export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null
export GIT_AUTHOR_NAME=test GIT_AUTHOR_EMAIL=test@example.com
export GIT_COMMITTER_NAME=test GIT_COMMITTER_EMAIL=test@example.com

fail=0

# --- stubs: neither is dialled by this path, both must exist ---
STUB="${TMP}/stub"
mkdir -p "$STUB"
printf '#!/bin/bash\nexit 0\n' > "${STUB}/openshell"
printf '#!/bin/bash\nexit 1\n' > "${STUB}/gh"
chmod +x "${STUB}/openshell" "${STUB}/gh"
export PATH="${STUB}:${PATH}"

# --- fixture: two commits two years old, then one from today, plus a branch ---
# --shallow-since reads the COMMITTER date, so both are pinned.
UPSTREAM="${TMP}/upstream"
mkdir -p "$UPSTREAM"
git -C "$UPSTREAM" init -q -b main
old_commit() {
    echo "$1" > "${UPSTREAM}/f"
    git -C "$UPSTREAM" add f
    GIT_AUTHOR_DATE="$2" GIT_COMMITTER_DATE="$2" git -C "$UPSTREAM" commit -qm "$1"
}
OLD_DATE="$(date -u -d '-2 years' --iso-8601=seconds)"
old_commit ancient "$OLD_DATE"
old_commit ancient2 "$OLD_DATE"
git -C "$UPSTREAM" checkout -q -b feature
echo branched > "${UPSTREAM}/g"
git -C "$UPSTREAM" add g && git -C "$UPSTREAM" commit -qm branched
git -C "$UPSTREAM" checkout -q main
echo recent > "${UPSTREAM}/h"
git -C "$UPSTREAM" add h && git -C "$UPSTREAM" commit -qm recent
URL="file://${UPSTREAM}"

export HOME="${TMP}/home"
SBX="${HOME}/sandboxes/probe"
mkdir -p "$SBX"
# work profile: guard_private_repo returns early, so no gh call on a file:// URL.
jq -n '{name:"probe",openshell_name:"sb-probe",profile:"work",repos:{}}' \
    > "${SBX}/manifest.json"

# site.env is gitignored and absent on a fresh clone; sandbox.sh refuses to run
# without one. Rewritten per case, because SANDBOX_CLONE_SINCE lives in it.
write_site_env() {
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
    [[ $# -eq 0 ]] || printf 'SANDBOX_CLONE_SINCE=%s\n' "$1" >> "${WORK}/config/site.env"
}

# Each case clones fresh: clone_repo_host skips a repo that is already there.
add_repo() {
    rm -rf "${SBX}/upstream"
    ( cd "$SBX" && "${WORK}/scripts/sandbox.sh" --add-repo probe --repo "$URL" "$@" ) 2>&1
}
commits()  { git -C "${SBX}/upstream" rev-list --count HEAD; }
shallow()  { [[ -f "${SBX}/upstream/.git/shallow" ]]; }

# --- 1. no window anywhere: full history ---
write_site_env
add_repo >/dev/null
shallow && { echo "FAIL: default clone is shallow" >&2; fail=1; }
[[ "$(commits)" == 3 ]] \
    || { echo "FAIL: default clone lost history (commits: $(commits))" >&2; fail=1; }

# --- 2. --since prunes, and keeps every remote-tracking branch ---
add_repo --since '-30 days' >/dev/null
shallow || { echo "FAIL: --since did not produce a shallow clone" >&2; fail=1; }
[[ "$(commits)" == 1 ]] \
    || { echo "FAIL: --since kept history older than the window (commits: $(commits))" >&2; fail=1; }
git -C "${SBX}/upstream" rev-parse --verify -q origin/feature >/dev/null \
    || { echo "FAIL: --since dropped origin/feature (--shallow-since implies --single-branch)" >&2; fail=1; }

# --- 3. site.env supplies the default, --since '' takes it back ---
# No space in the value: site.env is sourced, so `=-30 days` would run `days`.
write_site_env '-30days'
add_repo >/dev/null
shallow || { echo "FAIL: SANDBOX_CLONE_SINCE did not prune" >&2; fail=1; }
add_repo --since '' >/dev/null
shallow && { echo "FAIL: --since '' did not override SANDBOX_CLONE_SINCE" >&2; fail=1; }
[[ "$(commits)" == 3 ]] \
    || { echo "FAIL: --since '' did not restore full history (commits: $(commits))" >&2; fail=1; }
write_site_env

# --- 4. a value git would silently misread is refused, and nothing is cloned ---
out="$(add_repo --since '30d' || true)"
grep -q "is not a date" <<<"$out" \
    || { echo "FAIL: --since 30d was not rejected (got: ${out})" >&2; fail=1; }
[[ ! -d "${SBX}/upstream" ]] \
    || { echo "FAIL: --since 30d cloned anyway" >&2; fail=1; }

# --- 5. an empty window is not a failure: warn and clone in full ---
# '+1 year' rather than a stale-repo fixture: the fixture's newest commit is
# from now, and what git rejects is a window with nothing in it either way.
out="$(add_repo --since '+1 year' || true)"
grep -q "cloning full history" <<<"$out" \
    || { echo "FAIL: empty window did not fall back (got: ${out})" >&2; fail=1; }
[[ -d "${SBX}/upstream" ]] && [[ "$(commits)" == 3 ]] \
    || { echo "FAIL: empty-window fallback did not produce a full clone" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all clone-since checks passed"
exit $fail
