#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# One rule under test: `--connect [NAME] [HARNESS]` reaches the wrapper as an
# argument, and a sandbox whose NAME happens to be "claude" or "codex" is still
# addressable. The second half is not theoretical — --recreate re-execs
# `--connect "$SANDBOX_NAME"`, so a name/harness mix-up breaks it.
#
# Runs with --dryrun against a scratch HOME, so no openshell calls.
#
# Run: tests/test-connect-harness.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'cd /; rm -rf "$TMP"' EXIT

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "$WORK/"
if [[ ! -f "${WORK}/config/site.env" ]]; then
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
fi

FAKE_HOME="${TMP}/home"
mkdir -p "${FAKE_HOME}/sandboxes/myapp"

fail=0

# The dryrun trace carries the exec line; the wrapper argument is the last
# thing on it.
wrapper_arg() {
    HOME="$FAKE_HOME" bash "${WORK}/scripts/sandbox.sh" --connect "$@" --dryrun 2>&1 \
        | grep -oE 'harness-wrapper\.sh ?[a-z]*' | tail -1 | sed 's/harness-wrapper\.sh *//'
}

# The remembered value travels as an env assignment, not as argv.
wrapper_default() {
    HOME="$FAKE_HOME" bash "${WORK}/scripts/sandbox.sh" --connect "$@" --dryrun 2>&1 \
        | grep -oE 'HARNESS_DEFAULT=[a-z]*' | tail -1 | cut -d= -f2
}

sandbox_arg() {
    HOME="$FAKE_HOME" bash "${WORK}/scripts/sandbox.sh" --connect "$@" --dryrun 2>&1 \
        | grep -oE 'sandbox exec --name [a-z0-9-]+' | tail -1 | awk '{print $NF}'
}

check() {
    local what="$1" want="$2" got="$3"
    if [[ "$got" != "$want" ]]; then
        echo "FAIL: ${what}: wanted '${want}', got '${got}'" >&2
        fail=1
    fi
}

check "--connect NAME forces nothing on its own" "" "$(wrapper_arg myapp)"
check "--harness codex is forced, as argv" "codex" "$(wrapper_arg myapp --harness codex)"
check "--harness claude is forced, as argv" "claude" "$(wrapper_arg myapp --harness claude)"

# An explicit --harness is what writes the memory; the wrapper's prompt is not.
HOME="$FAKE_HOME" bash "${WORK}/scripts/sandbox.sh" --connect myapp --harness codex --dryrun >/dev/null 2>&1
check "--harness records itself in the manifest" "codex" \
    "$(jq -r '.harness' "${FAKE_HOME}/sandboxes/myapp/manifest.json")"

# ...and a later bare connect offers it as a default rather than forcing it.
check "a remembered harness arrives as HARNESS_DEFAULT" "codex" "$(wrapper_default myapp)"
check "a remembered harness is not forced" "" "$(wrapper_arg myapp)"

# Use case 3: the manifest is on the host, so it is still there after the
# remote sandbox is deleted and rebuilt. Nothing else has to carry it.
check "the manifest survives a rebuilt container" "codex" \
    "$(jq -r '.harness' "${FAKE_HOME}/sandboxes/myapp/manifest.json")"

# A sandbox named "codex" is just a name now — no positional harness to collide
# with. This is the shape --recreate re-execs.
mkdir -p "${FAKE_HOME}/sandboxes/codex"
[[ -n "$(sandbox_arg codex)" ]] || { echo "FAIL: no sandbox resolved for name codex" >&2; fail=1; }
check "a sandbox named codex forces no harness" "" "$(wrapper_arg codex)"

HOME="$FAKE_HOME" bash "${WORK}/scripts/sandbox.sh" --connect myapp --harness bogus --dryrun >/dev/null 2>&1 \
    && { echo "FAIL: --harness bogus was accepted" >&2; fail=1; }

# --- the wrapper's own dispatch ---
W="${REPO_ROOT}/bin/harness-wrapper.sh"
grep -q '/sandbox/\.dtach-\$1' "$W" \
    || { echo "FAIL: wrapper does not derive the dtach socket from the harness" >&2; fail=1; }
grep -q 'codex resume --dangerously-bypass-approvals-and-sandbox' "$W" \
    || { echo "FAIL: wrapper does not launch codex resume with the bypass flag" >&2; fail=1; }
# There is no --yolo in codex 0.152.0; it is not an alias for the long flag.
# Comments are stripped first — the wrapper says so in prose, which is not a use.
grep -v '^[[:space:]]*#' "$W" | grep -q -- '--yolo' \
    && { echo "FAIL: wrapper uses --yolo, which codex does not accept" >&2; fail=1; }
# An empty harness must still mean "what this sandbox did before", or every
# sandbox built before harness selection changes behaviour on a bare --connect.
# The prompt must be bounded, and must fall back explicitly. `read -t` returns
# non-zero and leaves the variable EMPTY on timeout — the `-i` prefill is not
# retained — so a wrapper that trusts `-i` launches nothing at all when the
# prompt times out. Verified: `read -t 1 -e -i codex ans` gives rc=1, ans="".
grep -q 'read -t "\$HARNESS_PROMPT_TIMEOUT"' "$W" \
    || { echo "FAIL: harness prompt is unbounded" >&2; fail=1; }
grep -q 'HARNESS="\${answer:-\$default}"' "$W" \
    || { echo "FAIL: harness prompt does not fall back to the default on timeout" >&2; fail=1; }

# A live dtach socket overrides the profile default — reattaching to the
# session already running is the point of asking at all.
grep -q '\-S "\$(socket_for "\$h")"' "$W" \
    || { echo "FAIL: wrapper does not let a live session pick the harness" >&2; fail=1; }

# Naming the harness is a decision already made; it must not then prompt.
grep -q 'if \[\[ -z "\$HARNESS" \]\]; then' "$W" \
    || { echo "FAIL: wrapper prompts even when the harness was named" >&2; fail=1; }

grep -q -- '--dangerously-bypass-hook-trust' "$W" \
    || { echo "FAIL: codex command is missing --dangerously-bypass-hook-trust" >&2; fail=1; }

# --- default harness precedence ---
#
# The rule the wrapper must implement, in order: one live dtach socket wins,
# then whatever ran here last, then the fallback. Nothing profile-based — the
# work profile carries both agents, so the profile cannot say which one the
# human wants. Exercised for real: the helpers are lifted out of the wrapper
# and driven against actual AF_UNIX sockets in a scratch dir.
HELPERS="${TMP}/helpers.sh"
sed -n '/^default_harness()/,/^}/p' "$W" > "$HELPERS"
grep -q 'default_harness' "$HELPERS" \
    || { echo "FAIL: could not lift default_harness out of the wrapper" >&2; exit 1; }

SOCKDIR="${TMP}/sock"
mkdir -p "$SOCKDIR"
mksock() { python3 -c "
import socket, sys
s = socket.socket(socket.AF_UNIX)
s.bind(sys.argv[1])
" "${SOCKDIR}/.dtach-$1"; }

# shellcheck disable=SC1090
picks() {
    (
        source "$HELPERS"
        socket_for() { echo "${SOCKDIR}/.dtach-$1"; }
        # Read by the sourced default_harness, which shellcheck cannot see into.
        # shellcheck disable=SC2034
        HARNESS_FALLBACK=claude
        default_harness
    )
}

check "nothing remembered falls back" "claude default" "$(HARNESS_DEFAULT='' picks)"
check "the remembered harness wins over the fallback" "codex remembered" \
    "$(HARNESS_DEFAULT=codex picks)"

mksock claude
check "a live socket beats the remembered harness" "claude session running" \
    "$(HARNESS_DEFAULT=codex picks)"

mksock codex
check "two live sockets are not a signal, so the remembered harness decides" \
    "codex remembered" "$(HARNESS_DEFAULT=codex picks)"

rm -f "${SOCKDIR}/.dtach-claude" "${SOCKDIR}/.dtach-codex"

# The profile must not reach the default. A stray $SANDBOX_PROFILE has to
# change nothing.
check "the profile does not decide" "claude default" \
    "$(SANDBOX_PROFILE=codex HARNESS_DEFAULT='' picks)"
grep -q 'SANDBOX_PROFILE' <(sed -n '/^default_harness()/,/^}/p' "$W") \
    && { echo "FAIL: default_harness still reads the profile" >&2; fail=1; }

if [[ $fail -eq 0 ]]; then
    echo "all connect-harness checks passed"
else
    exit 1
fi
