#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# One rule under test: the settings.json a sandbox receives carries none of the
# host's model pinning. ANTHROPIC_DEFAULT_{HAIKU,OPUS,SONNET}_MODEL override
# whatever the wrapper asks for, silently and with no trace in the command
# line, so they are stripped for every profile.
#
# Also pins the strip rules that were already there: host paths rewritten to
# /sandbox, permissions.allow dropped, work-only env gone on personal/home, and
# only the dummy OTEL hooks kept (Claude Code emits no telemetry for a hook type
# with no registered hook, which is the only reason those entries exist).
#
# Run: tests/test-strip-settings.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STRIP="${REPO_ROOT}/scripts/strip-settings.py"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

fail=0
S="${TMP}/settings.json"

seed() {
    cat > "$S" << 'JSON'
{
  "env": {
    "ANTHROPIC_DEFAULT_HAIKU_MODEL": "claude-haiku-4-5-20251001",
    "ANTHROPIC_DEFAULT_OPUS_MODEL": "claude-opus-5",
    "ANTHROPIC_DEFAULT_SONNET_MODEL": "claude-sonnet-5",
    "CLAUDE_CODE_USE_VERTEX": "1",
    "JIRA_URL": "https://example.atlassian.net",
    "OTEL_METRICS_EXPORTER": "otlp",
    "EDITOR": "vi"
  },
  "permissions": {"allow": ["Bash(rm:*)"], "deny": ["Read(/etc/**)"]},
  "hooks": {
    "SessionStart": [
      {"hooks": [{"type": "command", "command": "python3 -c \"\""}]},
      {"hooks": [{"type": "command", "command": "/home/me/bin/notify.sh"}]}
    ],
    "PreToolUse": [
      {"hooks": [{"type": "command", "command": "/home/me/bin/guard.sh"}]}
    ]
  },
  "statusLine": {"command": "/home/me/bin/statusline.sh"}
}
JSON
}

strip() { python3 "$STRIP" "$S" /home/me "$1"; }
get() { jq -r "$1" "$S"; }

# --- model pinning goes, on every profile ---
for profile in personal home work ""; do
    seed
    strip "$profile"
    for key in ANTHROPIC_DEFAULT_HAIKU_MODEL ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_SONNET_MODEL; do
        [[ "$(get ".env.\"${key}\" // \"gone\"")" == "gone" ]] \
            || { echo "FAIL: ${key} survived on profile '${profile:-<none>}'" >&2; fail=1; }
    done
    # ...and the rest of env is untouched by that rule
    [[ "$(get '.env.EDITOR')" == "vi" ]] \
        || { echo "FAIL: unrelated env dropped on profile '${profile:-<none>}'" >&2; fail=1; }
done

# --- personal and home lose work-only env; work keeps it ---
for profile in personal home; do
    seed
    strip "$profile"
    [[ "$(get '.env.CLAUDE_CODE_USE_VERTEX // "gone"')" == "gone" ]] \
        || { echo "FAIL: vertex env survived on ${profile}" >&2; fail=1; }
    [[ "$(get '.env.JIRA_URL // "gone"')" == "gone" ]] \
        || { echo "FAIL: jira env survived on ${profile}" >&2; fail=1; }
done

seed
strip work
[[ "$(get '.env.CLAUDE_CODE_USE_VERTEX')" == "1" ]] \
    || { echo "FAIL: work profile lost its vertex env" >&2; fail=1; }

# --- the pre-existing rules ---
seed
strip work
[[ "$(get '.permissions.allow // "gone"')" == "gone" ]] \
    || { echo "FAIL: permissions.allow survived" >&2; fail=1; }
[[ "$(get '.permissions.deny[0]')" == "Read(/etc/**)" ]] \
    || { echo "FAIL: permissions.deny was dropped" >&2; fail=1; }
[[ "$(get '.statusLine.command')" == "/sandbox/bin/statusline.sh" ]] \
    || { echo "FAIL: host home not rewritten to /sandbox" >&2; fail=1; }
[[ "$(get '.hooks.SessionStart | length')" == "1" ]] \
    || { echo "FAIL: SessionStart should keep only the OTEL dummy hook" >&2; fail=1; }
[[ "$(get '.hooks.SessionStart[0].hooks[0].command')" == 'python3 -c ""' ]] \
    || { echo "FAIL: kept the wrong SessionStart hook" >&2; fail=1; }
[[ "$(get '.hooks.PreToolUse // "gone"')" == "gone" ]] \
    || { echo "FAIL: a hook event with no OTEL dummy should be removed" >&2; fail=1; }

# --- a settings.json with no env at all must not crash ---
echo '{"permissions": {"allow": ["Bash(ls)"]}}' > "$S"
strip personal || { echo "FAIL: strip failed on settings.json with no env" >&2; fail=1; }
[[ "$(get '.permissions.allow // "gone"')" == "gone" ]] \
    || { echo "FAIL: allow survived in the no-env case" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all strip-settings checks passed"
exit $fail
