#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# Two rules under test:
#   1. open-prs.json is always written for a GitHub repo, including when there
#      are no open PRs (`{"prs": []}`). A missing file used to mean "none",
#      "the fetch failed", and "not a GitHub repo" all at once.
#   2. A file younger than $OPEN_PRS_TTL_MINUTES is not refetched. `gh pr list
#      --json files` is the slowest call in an upload and it runs per repo.
#
# gh is stubbed and records its calls, so the test needs no auth and no network.
#
# Run: tests/test-open-prs.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null
export GIT_AUTHOR_NAME=test GIT_AUTHOR_EMAIL=test@example.com
export GIT_COMMITTER_NAME=test GIT_COMMITTER_EMAIL=test@example.com

# The failure cases below go through gh_retry; no reason to sit through it.
export GH_RETRY_DELAY=0
source "${REPO_ROOT}/scripts/lib.sh"

fail=0
GH_LOG="${TMP}/gh-calls"
export GH_LOG

STUB="${TMP}/stub"
mkdir -p "$STUB"
# $GH_LIST_JSON is what `gh pr list` returns; unset means the call fails.
# `pr view` always fails — pr-context.md is a different test's concern.
cat > "${STUB}/gh" << 'STUBEOF'
#!/bin/bash
echo "$*" >> "$GH_LOG"
case "$1 $2" in
    "pr list")
        [[ -n "${GH_LIST_JSON:-}" ]] || exit 1
        cat "$GH_LIST_JSON"
        ;;
    *) exit 1 ;;
esac
STUBEOF
chmod +x "${STUB}/gh"
export PATH="${STUB}:${PATH}"

# --- fixture: a sandbox dir with one GitHub repo ---
SBX="${TMP}/sandbox"
REPO="${SBX}/myrepo"
mkdir -p "$REPO"
git -C "$REPO" init -q -b main
jq -n '{name:"probe",repos:{myrepo:{url:"git@github.com:org/myrepo.git"}}}' > "${SBX}/manifest.json"
OPEN_PRS="${REPO}/open-prs.json"

EMPTY_LIST="${TMP}/empty.json"
echo '[]' > "$EMPTY_LIST"
ONE_PR="${TMP}/one.json"
cat > "$ONE_PR" << 'JSON'
[{"number":5,"headRefName":"feat","baseRefName":"main","title":"t","body":"b",
  "author":{"login":"someone"},"labels":[],"files":[{"path":"a.txt"}],
  "mergeStateStatus":"CLEAN"}]
JSON

run_context() {
    : > "$GH_LOG"
    generate_repo_context "$SBX" myrepo personal >/dev/null 2>&1 || true
}
listed() { grep -qF 'pr list' "$GH_LOG"; }

# --- no open PRs still produces a file ---
rm -f "$OPEN_PRS"
GH_LIST_JSON="$EMPTY_LIST" run_context
[[ -f "$OPEN_PRS" ]] \
    || { echo "FAIL: no file written when the repo has no open PRs" >&2; fail=1; }
[[ "$(jq -c '.prs' "$OPEN_PRS" 2>/dev/null)" == "[]" ]] \
    || { echo "FAIL: empty result is not {\"prs\": []} (got: $(cat "$OPEN_PRS" 2>/dev/null))" >&2; fail=1; }

# --- a fresh file is not refetched ---
GH_LIST_JSON="$ONE_PR" run_context
listed && { echo "FAIL: refetched a file written seconds ago" >&2; fail=1; }
[[ "$(jq -c '.prs' "$OPEN_PRS")" == "[]" ]] \
    || { echo "FAIL: skipped fetch still rewrote the file" >&2; fail=1; }

# --- past the TTL it refetches ---
touch -d '2 hours ago' "$OPEN_PRS"
GH_LIST_JSON="$ONE_PR" run_context
listed || { echo "FAIL: a 2h-old file was not refetched" >&2; fail=1; }
[[ "$(jq -r '.prs[0].number' "$OPEN_PRS")" == "5" ]] \
    || { echo "FAIL: refetch did not update the file" >&2; fail=1; }

# --- TTL 0 forces a fetch ---
GH_LIST_JSON="$EMPTY_LIST" OPEN_PRS_TTL_MINUTES=0 run_context
listed || { echo "FAIL: OPEN_PRS_TTL_MINUTES=0 did not force a fetch" >&2; fail=1; }

# --- a failed fetch keeps the previous PRs and marks the failure ---
echo '{"prs":[{"number":9}]}' > "$OPEN_PRS"
touch -d '2 hours ago' "$OPEN_PRS"
run_context   # no GH_LIST_JSON -> gh pr list exits 1
[[ "$(jq -r '.prs[0].number' "$OPEN_PRS" 2>/dev/null)" == "9" ]] \
    || { echo "FAIL: a failed fetch overwrote the previous open-prs.json" >&2; fail=1; }
[[ "$(jq -r '.fetch_error // empty' "$OPEN_PRS")" == *"org/myrepo"* ]] \
    || { echo "FAIL: a failed fetch left no fetch_error marker" >&2; fail=1; }
[[ ! -f "${OPEN_PRS}.tmp" ]] \
    || { echo "FAIL: a failed fetch left open-prs.json.tmp behind" >&2; fail=1; }

# --- and the failure is debounced: these failures are repo-pinned, so the
# next upload must not pay for the same doomed call ---
run_context
listed && { echo "FAIL: refetched right after a recorded failure" >&2; fail=1; }

# --- with no previous file, the failure itself is the file ---
rm -f "$OPEN_PRS"
run_context
[[ -f "$OPEN_PRS" ]] \
    || { echo "FAIL: a failed fetch recorded nothing, so it will retry forever" >&2; fail=1; }
[[ -n "$(jq -r '.fetch_error // empty' "$OPEN_PRS")" ]] \
    || { echo "FAIL: failure marker missing from a fresh open-prs.json" >&2; fail=1; }
[[ "$(jq -r '.prs // "absent"' "$OPEN_PRS")" == "absent" ]] \
    || { echo "FAIL: a failed fetch claimed a PR list it never got" >&2; fail=1; }

# --- every manifest URL spelling yields the same --repo slug. `.git` and a
# trailing slash are independent: `…/standards/` used to reach gh as
# `jewzaam/standards/`, which it rejects, and the failure was indistinguishable
# from a repo with no PRs. ---
for url in \
    "git@github.com:org/myrepo.git" \
    "git@github.com:org/myrepo" \
    "git@github.com:org/myrepo/" \
    "git@github.com:org/myrepo.git/" \
    "https://github.com/org/myrepo.git" \
    "https://github.com/org/myrepo/"
do
    rm -f "$OPEN_PRS"
    jq -n --arg u "$url" '{name:"probe",repos:{myrepo:{url:$u}}}' > "${SBX}/manifest.json"
    GH_LIST_JSON="$EMPTY_LIST" run_context
    grep -qF -- '--repo org/myrepo --state' "$GH_LOG" \
        || { echo "FAIL: ${url} -> $(grep -F 'pr list' "$GH_LOG" || echo 'no pr list call')" >&2; fail=1; }
done

# --- a non-GitHub repo is left alone ---
rm -f "$OPEN_PRS"   # the failure case above recorded one
jq -n '{name:"probe",repos:{myrepo:{url:"git@gitlab.com:org/myrepo.git"}}}' > "${SBX}/manifest.json"
run_context
[[ ! -f "$OPEN_PRS" ]] \
    || { echo "FAIL: wrote open-prs.json for a non-GitHub repo" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all open-prs checks passed"
exit $fail
