#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# One rule under test: nothing gets built without a profile named on the
# command line. The profile decides which credentials leave the host, so a
# forgotten --profile must stop the command, not pick work and carry on.
#
# Also pins the three names (work, personal, home) to the three policy files,
# and the split system prompt: the Jira section lives in the work-only
# fragment, so a personal or home sandbox cannot inherit it by accident.
#
# Runs against a scratch HOME with --dryrun, so no openshell calls.
#
# Run: tests/test-profile-required.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "$WORK/"
# site.env is gitignored and absent on a fresh clone; sandbox.sh refuses to run
# without one. Values are never dialled — every run below is --dryrun.
if [[ ! -f "${WORK}/config/site.env" ]]; then
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
fi

FAKE_HOME="${TMP}/home"
mkdir -p "${FAKE_HOME}/sandboxes"

# A `code` stub, so a scode that wrongly succeeds opens nothing real.
STUB="${TMP}/stub"
mkdir -p "$STUB"
printf '#!/bin/bash\nexit 0\n' > "${STUB}/code"
chmod +x "${STUB}/code"

fail=0

# Asserts the command fails AND says why. An exit 1 from an unrelated crash
# would otherwise read as the gate working.
refuses() {
    local what="$1" want="$2"; shift 2
    local out status=0
    out="$(HOME="$FAKE_HOME" PATH="${STUB}:${PATH}" "$@" 2>&1)" || status=$?
    if [[ $status -eq 0 ]]; then
        echo "FAIL: ${what} was accepted" >&2
        fail=1
        return
    fi
    if [[ "$out" != *"$want"* ]]; then
        echo "FAIL: ${what} failed without saying '${want}':" >&2
        echo "  ${out}" >&2
        fail=1
    fi
}

SB="${WORK}/scripts/sandbox.sh"
SC="${WORK}/scripts/scode"

# --- sandbox.sh: --create and --recreate demand a profile ---
refuses "--create with no --profile" "--profile is required" \
    bash "$SB" --create probe-a --no-clone --no-connect --dryrun
refuses "--recreate with no --profile" "--profile is required" \
    bash "$SB" --recreate probe-a --dryrun
refuses "--create with an unknown profile" "unknown profile" \
    bash "$SB" --create probe-a --profile bogus --no-clone --no-connect --dryrun
refuses "--create with the retired 'code' profile" "unknown profile" \
    bash "$SB" --create probe-a --profile code --no-clone --no-connect --dryrun

# Refusing early matters: a manifest left behind would name a sandbox that was
# never built, and the host prompt reads .profile out of it.
[[ ! -e "${FAKE_HOME}/sandboxes/probe-a" ]] \
    || { echo "FAIL: a refused --create still created ~/sandboxes/probe-a" >&2; fail=1; }

# --- scode: every invocation, including reopening an existing sandbox ---
refuses "scode with no --profile" "--profile is required" \
    bash "$SC" --name probe-b
refuses "scode with an unknown profile" "unknown profile" \
    bash "$SC" --profile bogus --name probe-b

EXIST="${FAKE_HOME}/sandboxes/probe-exist"
mkdir -p "$EXIST"
printf '{"name":"probe-exist","openshell_name":"sb-x","profile":"work","repos":{}}' \
    > "${EXIST}/manifest.json"
refuses "scode reopening a sandbox with no --profile" "--profile is required" \
    bash "$SC" "$EXIST"

# --- one profile name, one policy file ---
for p in work personal home; do
    [[ -f "${REPO_ROOT}/policies/${p}.yaml" ]] \
        || { echo "FAIL: no policies/${p}.yaml for profile ${p}" >&2; fail=1; }
done

# --- home is personal plus telemetry reads, and nothing else ---
blocks() { yq -r '.network_policies[].name' "${REPO_ROOT}/policies/$1.yaml" 2>/dev/null | sort; }
if command -v yq >/dev/null 2>&1; then
    for want in prometheus-read loki-read; do
        blocks home | grep -qx "$want" \
            || { echo "FAIL: home policy is missing ${want}" >&2; fail=1; }
        blocks personal | grep -qx "$want" \
            && { echo "FAIL: personal policy grants ${want} — it is push-only" >&2; fail=1; }
    done
    # Everything else in home must already be in personal: home is a copy plus
    # two reads, not a place work endpoints quietly accumulate.
    extra="$(comm -23 <(blocks home) <(blocks personal) | grep -vx -e prometheus-read -e loki-read || true)"
    [[ -z "$extra" ]] \
        || { echo "FAIL: home policy has blocks personal does not: ${extra}" >&2; fail=1; }
else
    echo "warning: yq not installed, skipping policy content checks" >&2
fi

# --- the split system prompt ---
grep -q '^## Jira$' "${REPO_ROOT}/config/sandbox-claude.d/work.md" \
    || { echo "FAIL: the Jira section is not in the work-only prompt fragment" >&2; fail=1; }
grep -q '^## Jira$' "${REPO_ROOT}/config/sandbox-claude.md" \
    && { echo "FAIL: the Jira section is back in the base prompt every profile gets" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all profile-required checks passed"
exit $fail
