#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# One rule under test: the settings.json a sandbox receives carries none of the
# host's model pinning. ANTHROPIC_DEFAULT_{HAIKU,OPUS,SONNET}_MODEL override
# whatever the wrapper asks for, silently and with no trace in the command
# line, so they are stripped for every profile.
#
# Also pins the strip rules that were already there: host paths rewritten to
# /sandbox, permissions.allow dropped, work-only env gone on personal/home.
#
# And the hook rule: a hook survives stripping only if its command carries a
# `# KEEP:` shell comment saying why. Nothing is kept by name, so the
# OTEL no-ops and the commit skill's attribution hook are both here as ordinary
# marked hooks, and an unmarked no-op is checked to confirm it is dropped.
#
# The last case runs the script over a Codex hooks.json, which sandbox.sh also
# strips. Same shape, same rule, and my-codex-stuff's PreToolUse guards are
# unmarked on purpose -- a sandbox runs Codex with approvals bypassed.
#
# Run: tests/test-strip-settings.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STRIP="${REPO_ROOT}/scripts/strip-settings.py"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

fail=0
S="${TMP}/settings.json"

seed() {
    cat > "$S" << 'JSON'
{
  "env": {
    "ANTHROPIC_DEFAULT_HAIKU_MODEL": "claude-haiku-4-5-20251001",
    "ANTHROPIC_DEFAULT_OPUS_MODEL": "claude-opus-5",
    "ANTHROPIC_DEFAULT_SONNET_MODEL": "claude-sonnet-5",
    "CLAUDE_CODE_USE_VERTEX": "1",
    "JIRA_URL": "https://example.atlassian.net",
    "OTEL_METRICS_EXPORTER": "otlp",
    "EDITOR": "vi"
  },
  "permissions": {"allow": ["Bash(rm:*)"], "deny": ["Read(/etc/**)"]},
  "hooks": {
    "SessionStart": [
      {"hooks": [{"type": "command", "command": "python3 -c \"\"  # KEEP: OTEL telemetry trigger"}]},
      {"hooks": [{"type": "command", "command": "/home/me/bin/notify.sh"}]}
    ],
    "Notification": [
      {"hooks": [{"type": "command", "command": "python3 -c \"\""}]}
    ],
    "PreToolUse": [
      {"hooks": [{"type": "command", "command": "/home/me/bin/guard.sh"}]}
    ],
    "PostToolUse": [
      {"hooks": [
        {"type": "command", "command": "python3 /home/me/.claude/skills/commit/hooks/record-attribution.py  # KEEP: records the authoring model"},
        {"type": "command", "command": "/home/me/bin/hitchhiker.sh"}
      ]},
      {"hooks": [{"type": "command", "command": "/home/me/bin/other.sh"}]}
    ]
  },
  "statusLine": {"command": "/home/me/bin/statusline.sh"}
}
JSON
}

strip() { python3 "$STRIP" "$S" /home/me "$1"; }
get() { jq -r "$1" "$S"; }

# --- model pinning goes, on every profile ---
for profile in personal home work ""; do
    seed
    strip "$profile"
    for key in ANTHROPIC_DEFAULT_HAIKU_MODEL ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_SONNET_MODEL; do
        [[ "$(get ".env.\"${key}\" // \"gone\"")" == "gone" ]] \
            || { echo "FAIL: ${key} survived on profile '${profile:-<none>}'" >&2; fail=1; }
    done
    # ...and the rest of env is untouched by that rule
    [[ "$(get '.env.EDITOR')" == "vi" ]] \
        || { echo "FAIL: unrelated env dropped on profile '${profile:-<none>}'" >&2; fail=1; }
done

# --- personal and home lose work-only env; work keeps it ---
for profile in personal home; do
    seed
    strip "$profile"
    [[ "$(get '.env.CLAUDE_CODE_USE_VERTEX // "gone"')" == "gone" ]] \
        || { echo "FAIL: vertex env survived on ${profile}" >&2; fail=1; }
    [[ "$(get '.env.JIRA_URL // "gone"')" == "gone" ]] \
        || { echo "FAIL: jira env survived on ${profile}" >&2; fail=1; }
done

seed
strip work
[[ "$(get '.env.CLAUDE_CODE_USE_VERTEX')" == "1" ]] \
    || { echo "FAIL: work profile lost its vertex env" >&2; fail=1; }

# --- the pre-existing rules ---
seed
strip work
[[ "$(get '.permissions.allow // "gone"')" == "gone" ]] \
    || { echo "FAIL: permissions.allow survived" >&2; fail=1; }
[[ "$(get '.permissions.deny[0]')" == "Read(/etc/**)" ]] \
    || { echo "FAIL: permissions.deny was dropped" >&2; fail=1; }
[[ "$(get '.statusLine.command')" == "/sandbox/bin/statusline.sh" ]] \
    || { echo "FAIL: host home not rewritten to /sandbox" >&2; fail=1; }
[[ "$(get '.hooks.SessionStart | length')" == "1" ]] \
    || { echo "FAIL: SessionStart should keep only the marked hook" >&2; fail=1; }
[[ "$(get '.hooks.SessionStart[0].hooks[0].command')" == 'python3 -c ""  # KEEP: OTEL telemetry trigger' ]] \
    || { echo "FAIL: kept the wrong SessionStart hook" >&2; fail=1; }
[[ "$(get '.hooks.PreToolUse // "gone"')" == "gone" ]] \
    || { echo "FAIL: a hook event with nothing marked should be removed" >&2; fail=1; }
# The marker must be a shell comment. A dummy argument would survive the same
# rewrite but would land in a real hook's argv.
[[ "$(get '.hooks.SessionStart[0].hooks[0].command')" == *"# KEEP:"* ]] \
    || { echo "FAIL: marker is not a shell comment" >&2; fail=1; }
# Retention is the marker and nothing else. An OTEL no-op that did not ask to
# survive is dropped like anything else -- if this passes while the fixture is
# unmarked, command matching has crept back in.
[[ "$(get '.hooks.Notification // "gone"')" == "gone" ]] \
    || { echo "FAIL: an unmarked 'python3 -c \"\"' survived; name matching is back" >&2; fail=1; }
[[ "$(get '.hooks.PostToolUse | length')" == "1" ]] \
    || { echo "FAIL: PostToolUse should keep only the rule holding a marked hook" >&2; fail=1; }
[[ "$(get '.hooks.PostToolUse[0].hooks[0].command')" == "python3 /sandbox/.claude/skills/commit/hooks/record-attribution.py  # KEEP: records the authoring model" ]] \
    || { echo "FAIL: a marked hook was stripped, or its path not rewritten" >&2; fail=1; }
# Filtering is per hook, not per rule entry: an unmarked hook sharing an entry
# with a marked one must not ride in on it.
[[ "$(get '.hooks.PostToolUse[0].hooks | length')" == "1" ]] \
    || { echo "FAIL: an unmarked hook survived by sharing a rule entry" >&2; fail=1; }

# --- a settings.json with no env at all must not crash ---
echo '{"permissions": {"allow": ["Bash(ls)"]}}' > "$S"
strip personal || { echo "FAIL: strip failed on settings.json with no env" >&2; fail=1; }
[[ "$(get '.permissions.allow // "gone"')" == "gone" ]] \
    || { echo "FAIL: allow survived in the no-env case" >&2; fail=1; }

# --- Codex hooks.json goes through the same script ---
# Same top-level "hooks" shape, so strip_hooks() covers it. The OTEL hooks ask
# to survive; my-codex-stuff's PreToolUse guards deliberately do not, because a
# sandbox runs Codex with approvals bypassed on purpose.
cat > "$S" << 'JSON'
{
  "description": "Codex hooks",
  "hooks": {
    "SessionStart": [
      {"hooks": [{"type": "command", "command": "python3 /home/me/.codex/observe-hook.py  # KEEP: OTEL telemetry"}]}
    ],
    "PreToolUse": [
      {"hooks": [{"type": "command", "command": "python3 /home/me/.codex/observe-hook.py  # KEEP: OTEL telemetry"}]},
      {"hooks": [{"type": "command", "command": "python3 -m harness_guards.block_commands"}]},
      {"hooks": [{"type": "command", "command": "python3 -m harness_guards.block_paths"}]}
    ]
  }
}
JSON
strip work
[[ "$(get '.hooks.SessionStart | length')" == "1" ]] \
    || { echo "FAIL: codex SessionStart telemetry hook was stripped" >&2; fail=1; }
[[ "$(get '.hooks.PreToolUse | length')" == "1" ]] \
    || { echo "FAIL: codex PreToolUse should keep only the marked telemetry hook" >&2; fail=1; }
[[ "$(get '.hooks.PreToolUse[0].hooks[0].command')" == "python3 /sandbox/.codex/observe-hook.py  # KEEP: OTEL telemetry" ]] \
    || { echo "FAIL: kept the wrong codex PreToolUse hook, or path not rewritten" >&2; fail=1; }
[[ "$(get '[.hooks[][].hooks[].command] | map(select(test("harness_guards"))) | length')" == "0" ]] \
    || { echo "FAIL: a host guard hook reached the sandbox" >&2; fail=1; }
[[ "$(get '.description')" == "Codex hooks" ]] \
    || { echo "FAIL: a top-level key other than hooks was dropped" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all strip-settings checks passed"
exit $fail
