#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# One rule under test: --recreate must not lose Codex conversation history the
# way it used to. `codex resume` needs both halves — the `threads` table in the
# schema-versioned state database, and the rollout jsonl each row points at —
# so the filter has to carry the databases WITH their write-ahead logs and
# leave the rest of ~/.codex behind.
#
# Drives codex_state_filter() against a fake downloaded tree. The download
# itself needs a live sandbox; the filtering does not.
#
# Run: tests/test-codex-state.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SANDBOX_SH="${REPO_ROOT}/scripts/sandbox.sh"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Lift the filter and the keep-list out of sandbox.sh — sourcing the script
# would run it.
HELPERS="${TMP}/helpers.sh"
sed -n '/^CODEX_STATE_KEEP=/p;/^codex_state_filter()/,/^}/p' "$SANDBOX_SH" > "$HELPERS"
grep -q 'codex_state_filter' "$HELPERS" \
    || { echo "FAIL: could not lift codex_state_filter out of sandbox.sh" >&2; exit 1; }
# Directory downloads contain the source directory's contents directly in the
# destination. Keep this assertion next to the filter test because a nested
# destination assumption makes the real recreate path preserve nothing.
grep -q '"/sandbox/.codex" "\${dl_tmp}/codex"' "$SANDBOX_SH" \
    || { echo "FAIL: Codex download does not use an explicit content destination" >&2; exit 1; }
# shellcheck disable=SC1090
source "$HELPERS"

fail=0
present() {
    [[ -e "${DST}/$1" ]] || { echo "FAIL: ${1} was not preserved" >&2; fail=1; }
}
absent() {
    [[ ! -e "${DST}/$1" ]] || { echo "FAIL: ${1} should not be preserved" >&2; fail=1; }
}

# A realistic ~/.codex as downloaded from a sandbox.
SRC="${TMP}/src"
DST="${TMP}/dst"
mkdir -p "${SRC}/sessions/2026/09/01" "${SRC}/thread-writer-locks" \
         "${SRC}/shell_snapshots" "${SRC}/tmp/arg0" "${SRC}/.tmp"
echo '{"type":"session_meta"}' > "${SRC}/sessions/2026/09/01/rollout-x.jsonl"
echo '{"session_id":"x"}'      > "${SRC}/history.jsonl"
echo '{"id":"x"}'              > "${SRC}/session_index.jsonl"
echo 'model = "gpt-5.6-luna"'  > "${SRC}/config.toml"
echo 'KEY'                     > "${SRC}/auth.json"
echo 'id'                      > "${SRC}/installation_id"
: > "${SRC}/thread-writer-locks/x.lock"
: > "${SRC}/shell_snapshots/x.sh"
for db in state_5 logs_2 thread_history_1; do
    echo db  > "${SRC}/${db}.sqlite"
    echo wal > "${SRC}/${db}.sqlite-wal"
    echo shm > "${SRC}/${db}.sqlite-shm"
done

codex_state_filter "$SRC" "$DST" || { echo "FAIL: filter reported nothing kept" >&2; fail=1; }

# What `codex resume` needs.
present "sessions/2026/09/01/rollout-x.jsonl"
present "state_5.sqlite"
present "history.jsonl"
present "session_index.jsonl"
present "config.toml"

# Schema-versioned names mean the filter cannot hardcode one. All the databases
# travel, and each keeps its write-ahead log: a state_5.sqlite moved without
# its -wal is nearly empty — measured live at 4KB of database against 2.1MB of
# log.
for db in state_5 logs_2 thread_history_1; do
    present "${db}.sqlite"
    present "${db}.sqlite-wal"
    # SQLite rebuilds -shm from the -wal and says not to move it between
    # machines; a stale one is worse than none.
    absent  "${db}.sqlite-shm"
done

# auth.json holds OPENAI_API_KEY. It is not preserved on purpose: on work the
# host ships it through upload_config(), and a preserved copy would let a stale
# key beat a rotated one. See gotcha 19.
absent "auth.json"

# Host-side or per-container junk.
absent "thread-writer-locks"
absent "shell_snapshots"
absent "tmp"
absent "installation_id"

# Nothing to keep must not look like success — an empty ~/.codex would
# otherwise stage an empty upload over the real one.
EMPTY_SRC="${TMP}/empty-src"
mkdir -p "$EMPTY_SRC"
if codex_state_filter "$EMPTY_SRC" "${TMP}/empty-dst"; then
    echo "FAIL: filter reported success on an empty source" >&2
    fail=1
fi

# Re-running must not accumulate stale rollouts: the second pass replaces the
# directory rather than merging into it.
rm -rf "${SRC:?}/sessions"
mkdir -p "${SRC}/sessions/2026/09/02"
echo '{}' > "${SRC}/sessions/2026/09/02/rollout-y.jsonl"
codex_state_filter "$SRC" "$DST" || true
present "sessions/2026/09/02/rollout-y.jsonl"
absent  "sessions/2026/09/01/rollout-x.jsonl"

if [[ $fail -eq 0 ]]; then
    echo "all codex-state checks passed"
else
    exit 1
fi
