#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# Self-check for start_error_sandbox(): --ensure against a sandbox in Error
# phase must podman start the container and wait for Ready before connecting.
# Stopped (and Stopping, once it settles) goes through `openshell sandbox start`.
# Stubs openshell and podman on $PATH and lifts the real functions out of
# sandbox.sh, so the test cannot drift from the code it covers.
#
# Run: tests/test-error-sandbox-start.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# --- stubs: phase comes from $TMP/phase, `podman start` flips it to Ready ---
mkdir -p "${TMP}/bin"
# `openshell sandbox start` flips Stopped to Ready, or fails when
# $TMP/start_fails exists. A Stopping phase turns into $TMP/stop_result
# after $TMP/stopping_polls list calls, standing in for a
# slow stop. List call number $TMP/blank_call (counted in $TMP/calls) omits
# the sandbox, as a gateway that did not answer reads to sandbox_phase().
cat > "${TMP}/bin/openshell" << 'STUB'
#!/bin/bash
if [[ "$2" == "start" ]]; then
    [[ -f "${TMP}/start_fails" ]] && exit 1
    echo "${*: -1}" >> "${TMP}/os_started"
    echo Ready > "${TMP}/phase"
    exit 0
fi
calls=$(( $(cat "${TMP}/calls" 2>/dev/null || echo 0) + 1 ))
echo "$calls" > "${TMP}/calls"
if [[ "$calls" == "$(cat "${TMP}/blank_call" 2>/dev/null)" ]]; then
    echo '{"sandboxes":[]}'
    exit 0
fi
if [[ "$(cat "${TMP}/phase")" == "Stopping" ]]; then
    n=$(( $(cat "${TMP}/stopping_polls") - 1 ))
    echo "$n" > "${TMP}/stopping_polls"
    [[ $n -le 0 ]] && cat "${TMP}/stop_result" > "${TMP}/phase"
fi
printf '{"sandboxes":[{"name":"sb-test","phase":"%s"}]}\n' "$(cat "${TMP}/phase")"
STUB
cat > "${TMP}/bin/podman" << 'STUB'
#!/bin/bash
if [[ "$1" == "start" ]]; then
    echo "$2" >> "${TMP}/started"
    echo Ready > "${TMP}/phase"
    exit 0
fi
cat "${TMP}/containers"
STUB
chmod +x "${TMP}/bin/openshell" "${TMP}/bin/podman"
export PATH="${TMP}/bin:${PATH}" TMP

# --- the functions under test, lifted from sandbox.sh ---
eval "$(sed -n '/^sandbox_phase()/,/^}/p; /^start_error_sandbox()/,/^}/p' \
    "${REPO_ROOT}/scripts/sandbox.sh")"
declare -F start_error_sandbox >/dev/null || {
    echo "FAIL: start_error_sandbox not found in sandbox.sh" >&2; exit 1; }

# Read by the eval'd functions, not by anything shellcheck can see here.
# shellcheck disable=SC2034
DRYRUN=false
# shellcheck disable=SC2034
GW_FLAG=()
run() { "$@"; }

fail() { echo "FAIL: $1" >&2; exit 1; }

with_container() { echo '[{"Id":"deadbeef","Labels":{"openshell.ai/sandbox-name":"sb-test"}}]' > "${TMP}/containers"; }
no_container() { echo '[]' > "${TMP}/containers"; }

# --- Ready sandbox: nothing to start ---
echo Ready > "${TMP}/phase"
with_container
rm -f "${TMP}/started"
start_error_sandbox sb-test
if [[ -f "${TMP}/started" ]]; then fail "podman start ran on a Ready sandbox"; fi

# --- Error sandbox with a container: started, then waited to Ready ---
echo Error > "${TMP}/phase"
start_error_sandbox sb-test
[[ -f "${TMP}/started" ]] || fail "podman start did not run on an Error sandbox"
[[ "$(cat "${TMP}/started")" == "deadbeef" ]] || fail "started the wrong container"
[[ "$(cat "${TMP}/phase")" == "Ready" ]] || fail "returned before phase was Ready"

# --- Error sandbox with no container: exit 1, do not connect ---
echo Error > "${TMP}/phase"
no_container
rm -f "${TMP}/started"
if (start_error_sandbox sb-test 2>/dev/null); then
    fail "no container should be fatal"
fi
if [[ -f "${TMP}/started" ]]; then fail "podman start ran without a container"; fi

# --- Stopped sandbox: openshell start, never podman start ---
echo Stopped > "${TMP}/phase"
with_container
rm -f "${TMP}/started" "${TMP}/os_started"
start_error_sandbox sb-test 2>/dev/null
[[ "$(cat "${TMP}/os_started" 2>/dev/null)" == "sb-test" ]] \
    || fail "openshell sandbox start did not run on a Stopped sandbox"
if [[ -f "${TMP}/started" ]]; then fail "podman start ran on a Stopped sandbox"; fi
[[ "$(cat "${TMP}/phase")" == "Ready" ]] || fail "Stopped sandbox not Ready after start"

# --- Stopping sandbox: wait for Stopped, then openshell start ---
echo Stopping > "${TMP}/phase"
echo Stopped > "${TMP}/stop_result"
echo 2 > "${TMP}/stopping_polls"
rm -f "${TMP}/started" "${TMP}/os_started"
start_error_sandbox sb-test 2>/dev/null
[[ "$(cat "${TMP}/os_started" 2>/dev/null)" == "sb-test" ]] \
    || fail "Stopping sandbox was not started once it reached Stopped"
if [[ -f "${TMP}/started" ]]; then fail "podman start ran on a Stopping sandbox"; fi

# --- Gateway silent mid-wait: an empty phase keeps waiting, not "done" ---
# Call 1 is the initial read (Stopping), call 2 comes back blank, call 3 is
# where the stop settles.
echo Stopping > "${TMP}/phase"
echo 2 > "${TMP}/stopping_polls"
echo 0 > "${TMP}/calls"
echo 2 > "${TMP}/blank_call"
rm -f "${TMP}/os_started"
start_error_sandbox sb-test 2>/dev/null
[[ "$(cat "${TMP}/os_started" 2>/dev/null)" == "sb-test" ]] \
    || fail "an empty phase during the Stopping wait ended the wait without starting"
rm -f "${TMP}/blank_call"

# --- Stop that settles in Error: falls through to the podman path ---
echo Stopping > "${TMP}/phase"
echo Error > "${TMP}/stop_result"
echo 1 > "${TMP}/stopping_polls"
rm -f "${TMP}/started" "${TMP}/os_started"
start_error_sandbox sb-test 2>/dev/null
[[ "$(cat "${TMP}/started" 2>/dev/null)" == "deadbeef" ]] \
    || fail "a stop that ended in Error did not podman start the container"
if [[ -f "${TMP}/os_started" ]]; then fail "openshell start ran on an Error sandbox"; fi

# --- openshell start fails: non-zero, so every caller stops ---
echo Stopped > "${TMP}/phase"
touch "${TMP}/start_fails"
if (start_error_sandbox sb-test 2>/dev/null); then
    fail "a failed openshell sandbox start should be fatal"
fi
rm -f "${TMP}/start_fails"

# ---------------------------------------------------------------------------
# Call sites: every mode that talks to the container must start a stopped one
# ---------------------------------------------------------------------------
#
# End-to-end through sandbox.sh with the same stubs, --dryrun so the openshell
# calls are only printed. Lifting the function proves it works; this proves it
# is reached.

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "$WORK/"
if [[ ! -f "${WORK}/config/site.env" ]]; then
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
fi
SANDBOX_SH="${WORK}/scripts/sandbox.sh"

FAKE_HOME="${TMP}/home"
mkdir -p "${FAKE_HOME}/sandboxes/probe"
printf '{"name":"probe","openshell_name":"sb-test","profile":"personal","repos":{}}' \
    > "${FAKE_HOME}/sandboxes/probe/manifest.json"

echo Error > "${TMP}/phase"
with_container

for mode in "--connect probe" "--refresh probe" "--recreate probe --profile personal --no-connect"; do
    # shellcheck disable=SC2086  # deliberate word split: mode carries flags
    out="$(HOME="$FAKE_HOME" bash "$SANDBOX_SH" $mode --dryrun 2>&1 || true)"
    grep -qF "Sandbox in Error phase, starting container..." <<<"$out" \
        || fail "${mode%% *} did not start the stopped container"
done

echo Stopped > "${TMP}/phase"
for mode in "--connect probe" "--refresh probe" "--recreate probe --profile personal --no-connect"; do
    # shellcheck disable=SC2086  # deliberate word split: mode carries flags
    out="$(HOME="$FAKE_HOME" bash "$SANDBOX_SH" $mode --dryrun 2>&1 || true)"
    grep -qF "[dryrun]: openshell sandbox start" <<<"$out" \
        || fail "${mode%% *} did not openshell-start a Stopped sandbox"
done
echo Error > "${TMP}/phase"

# A container that will not start is fatal everywhere. --recreate most of all:
# its next step deletes the container the download was supposed to drain, so
# proceeding would rebuild from stale local state and lose the session's work.
no_container
for mode in "--connect probe" "--refresh probe" "--recreate probe --profile personal --no-connect"; do
    # shellcheck disable=SC2086  # deliberate word split: mode carries flags
    if HOME="$FAKE_HOME" bash "$SANDBOX_SH" $mode --dryrun >/dev/null 2>&1; then
        fail "${mode%% *} proceeded against an unstartable sandbox"
    fi
done
# shellcheck disable=SC2086
rc_out="$(HOME="$FAKE_HOME" bash "$SANDBOX_SH" --recreate probe --profile personal --no-connect --dryrun 2>&1 || true)"
grep -qF "sandbox delete" <<<"$rc_out" \
    && fail "--recreate deleted the container after failing to download from it"

echo "PASS: tests/test-error-sandbox-start.sh"
