#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# One rule under test: a PR checkout is a real branch with an upstream.
# checkout_pr() goes through `gh pr checkout` so the branch is the PR's head
# ref with branch.<name>.{remote,merge} set; the refs/pull fetch that produced
# an untracked pr-<num> branch survives only as a fallback. Both spellings, and
# a fork PR's refs/pull upstream, must still resolve to the PR number in
# generate_repo_context().
#
# gh is stubbed — it records its arguments and emulates only what these paths
# need, so the test needs no auth and no network.
#
# Run: tests/test-pr-checkout.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Commit signing and per-user config would follow the host in here.
export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null
export GIT_AUTHOR_NAME=test GIT_AUTHOR_EMAIL=test@example.com
export GIT_COMMITTER_NAME=test GIT_COMMITTER_EMAIL=test@example.com

source "${REPO_ROOT}/scripts/lib.sh"

fail=0
GH_LOG="${TMP}/gh-calls"
STUB="${TMP}/stub"
mkdir -p "$STUB"
export PATH="${STUB}:${PATH}"

# --- fixture: an "upstream" repo with a PR head branch and refs/pull/7/head ---
UPSTREAM="${TMP}/upstream"
mkdir -p "$UPSTREAM"
git -C "$UPSTREAM" init -q -b main
echo base > "${UPSTREAM}/f"
git -C "$UPSTREAM" add f && git -C "$UPSTREAM" commit -qm base
git -C "$UPSTREAM" checkout -q -b feature-x
echo change > "${UPSTREAM}/f"
git -C "$UPSTREAM" commit -qam change
PR_SHA="$(git -C "$UPSTREAM" rev-parse HEAD)"
git -C "$UPSTREAM" update-ref refs/pull/7/head "$PR_SHA"
git -C "$UPSTREAM" update-ref refs/pull/8/head "$PR_SHA"
git -C "$UPSTREAM" checkout -q main

fresh_clone() {
    local dest="$1"
    rm -rf "$dest"
    git clone -q "$UPSTREAM" "$dest"
}

# gh stub: $GH_MODE picks the behaviour under test.
#   ok    — emulate `gh pr checkout` for a same-repo PR (branch + tracking)
#   fail  — every call fails, as it would with no auth or no network
write_gh_stub() {
    cat > "${STUB}/gh" << 'STUBEOF'
#!/bin/bash
echo "$*" >> "$GH_LOG"
[[ "${GH_MODE}" == "fail" ]] && exit 1
case "$1 $2" in
    "pr checkout")
        # What gh does for a PR whose head branch lives in the base repo.
        git fetch -q origin "+refs/heads/feature-x:refs/remotes/origin/feature-x"
        git checkout -q -b feature-x --track origin/feature-x
        ;;
    "pr list")  echo '[]' ;;
    "pr view")  cat "${GH_PR_VIEW_JSON}" ;;
    *)          exit 1 ;;
esac
STUBEOF
    chmod +x "${STUB}/gh"
}
write_gh_stub
export GH_LOG

# --- gh pr checkout is what runs, and the branch it leaves has an upstream ---
C1="${TMP}/clone-ok"
fresh_clone "$C1"
GH_MODE=ok checkout_pr "$C1" 7 >/dev/null 2>&1

grep -qx "pr checkout 7" "$GH_LOG" 2>/dev/null \
    || { echo "FAIL: checkout_pr did not run 'gh pr checkout 7'" >&2; fail=1; }
[[ "$(git -C "$C1" rev-parse --abbrev-ref HEAD)" == "feature-x" ]] \
    || { echo "FAIL: not on the PR head branch (got: $(git -C "$C1" rev-parse --abbrev-ref HEAD))" >&2; fail=1; }
[[ "$(git -C "$C1" rev-parse --abbrev-ref '@{upstream}' 2>/dev/null)" == "origin/feature-x" ]] \
    || { echo "FAIL: PR branch has no upstream" >&2; fail=1; }

# --- dryrun touches nothing ---
C2="${TMP}/clone-dry"
fresh_clone "$C2"
: > "$GH_LOG"
DRYRUN=true GH_MODE=ok checkout_pr "$C2" 7 >/dev/null 2>&1
[[ ! -s "$GH_LOG" ]] \
    || { echo "FAIL: --dryrun still called gh" >&2; fail=1; }
[[ "$(git -C "$C2" rev-parse --abbrev-ref HEAD)" == "main" ]] \
    || { echo "FAIL: --dryrun changed the checkout" >&2; fail=1; }

# --- gh unavailable: fall back to refs/pull rather than staying on main ---
C3="${TMP}/clone-fallback"
fresh_clone "$C3"
out="$(GH_MODE=fail checkout_pr "$C3" 7 2>&1)"
[[ "$(git -C "$C3" rev-parse --abbrev-ref HEAD)" == "pr-7" ]] \
    || { echo "FAIL: fallback did not check out pr-7 (got: $(git -C "$C3" rev-parse --abbrev-ref HEAD))" >&2; fail=1; }
grep -q "without an upstream" <<<"$out" \
    || { echo "FAIL: fallback did not warn that the branch is untracked" >&2; fail=1; }

# --- generate_repo_context resolves the PR number from every branch shape ---
# It asks gh for `pr view <arg>`; <arg> is what has to be right.
GH_PR_VIEW_JSON="${TMP}/pr.json"
export GH_PR_VIEW_JSON
cat > "$GH_PR_VIEW_JSON" << 'JSON'
{"number":7,"title":"t","body":"b","headRefName":"feature-x","baseRefName":"main","labels":[],"assignees":[]}
JSON

pr_view_arg() {
    # $1: a clone already on the branch shape under test
    local sandbox_dir="${TMP}/sbx" repo_name
    repo_name="$(basename "$1")"
    rm -rf "$sandbox_dir" && mkdir -p "$sandbox_dir"
    cp -r "$1" "${sandbox_dir}/${repo_name}"
    jq -n --arg r "$repo_name" '{name:"probe",repos:{($r):{url:"https://github.com/org/repo.git"}}}' \
        > "${sandbox_dir}/manifest.json"
    : > "$GH_LOG"
    GH_MODE=ok generate_repo_context "$sandbox_dir" "$repo_name" personal >/dev/null 2>&1
    grep -m1 '^pr view ' "$GH_LOG" | awk '{print $3}'
}

# real branch from gh pr checkout -> the branch name resolves the PR
[[ "$(pr_view_arg "$C1")" == "feature-x" ]] \
    || { echo "FAIL: a real PR branch should be looked up by name (got: $(pr_view_arg "$C1"))" >&2; fail=1; }

# fallback branch pr-7 -> the number, there is no such branch on the remote
[[ "$(pr_view_arg "$C3")" == "7" ]] \
    || { echo "FAIL: pr-<num> branch should be looked up by number (got: $(pr_view_arg "$C3"))" >&2; fail=1; }

# fork PR: gh points the upstream at refs/pull/<num>/head, and the branch name
# belongs to the fork — only the number identifies it in the base repo
C4="${TMP}/clone-fork"
fresh_clone "$C4"
git -C "$C4" fetch -q origin "refs/pull/8/head"
git -C "$C4" checkout -q -b patch-1 FETCH_HEAD
git -C "$C4" config branch.patch-1.remote origin
git -C "$C4" config branch.patch-1.merge refs/pull/8/head
[[ "$(pr_view_arg "$C4")" == "8" ]] \
    || { echo "FAIL: fork PR should be looked up by number (got: $(pr_view_arg "$C4"))" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all pr-checkout checks passed"
exit $fail
