#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# Two rules under test:
#   1. A GitHub API failure is not evidence about the PR. `gh pr view` exits 1
#      both for "this branch has no PR" and for a 502, and only the first may
#      delete pr-context.md / jira-context.md. Getting this wrong means a flaky
#      API silently destroys correct context during an upload.
#   2. Context generation costs at most one gh call per kind, per repo, even
#      when every call fails. It runs on every upload for every repo; a retry
#      backoff here turns a multi-repo upload into minutes of sleeping for data
#      that is optional or already on disk. Only `gh pr checkout` retries.
#
# Run: tests/test-gh-retry.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null
export GIT_AUTHOR_NAME=test GIT_AUTHOR_EMAIL=test@example.com
export GIT_COMMITTER_NAME=test GIT_COMMITTER_EMAIL=test@example.com

# No real waiting; the backoff itself is not what is under test.
export GH_RETRY_DELAY=0
source "${REPO_ROOT}/scripts/lib.sh"

fail=0
GH_LOG="${TMP}/gh-calls"
export GH_LOG

# gh stub. $GH_MODE:
#   ok        — pr view returns a PR, pr list returns []
#   transient — every call fails the way a bad gateway does
#   nopr      — pr view answers "no pull requests found", pr list returns []
#   flaky     — fails once, succeeds after (proves a retry recovers)
STUB="${TMP}/stub"
mkdir -p "$STUB"
cat > "${STUB}/gh" << 'STUBEOF'
#!/bin/bash
echo "$*" >> "$GH_LOG"
PR_JSON='{"number":5,"title":"t","body":"b","headRefName":"feat","baseRefName":"main","labels":[],"assignees":[]}'
case "${GH_MODE}" in
    transient)
        echo "error connecting to api.github.com: HTTP 502" >&2
        exit 1
        ;;
    flaky)
        if [[ ! -f "${TMP_FLAG}" ]]; then
            touch "${TMP_FLAG}"
            echo "error connecting to api.github.com: HTTP 502" >&2
            exit 1
        fi
        ;;
    nopr)
        if [[ "$1 $2" == "pr view" ]]; then
            echo 'no pull requests found for branch "feat"' >&2
            exit 1
        fi
        ;;
esac
case "$1 $2" in
    "pr view")     echo "$PR_JSON" ;;
    "pr list")     echo '[]' ;;
    "pr checkout") ;;
    *) exit 1 ;;
esac
STUBEOF
chmod +x "${STUB}/gh"
export PATH="${STUB}:${PATH}"
export TMP_FLAG="${TMP}/flaky-flag"

# --- fixture ---
SBX="${TMP}/sandbox"
REPO="${SBX}/myrepo"
mkdir -p "$REPO"
git -C "$REPO" init -q -b feat
echo x > "${REPO}/f"
git -C "$REPO" add f
git -C "$REPO" commit -qm init   # rev-parse HEAD must resolve, or context generation returns early
jq -n '{name:"probe",repos:{myrepo:{url:"git@github.com:org/myrepo.git"}}}' > "${SBX}/manifest.json"

seed_context() {
    echo "# PR #5: existing" > "${REPO}/pr-context.md"
    echo "# Jira Context" > "${REPO}/jira-context.md"
    echo '{"prs":[{"number":9}]}' > "${REPO}/open-prs.json"
    touch -d '2 hours ago' "${REPO}/open-prs.json"
    rm -f "$TMP_FLAG"
    : > "$GH_LOG"
}
calls() { grep -c "$1" "$GH_LOG" 2>/dev/null || true; }

# --- a 502 keeps existing context and does not claim the PR is gone ---
seed_context
GH_MODE=transient generate_repo_context "$SBX" myrepo personal >/dev/null 2>&1 || true
[[ -f "${REPO}/pr-context.md" && -f "${REPO}/jira-context.md" ]] \
    || { echo "FAIL: a transient gh failure deleted the PR context" >&2; fail=1; }
[[ "$(jq -r '.prs[0].number' "${REPO}/open-prs.json" 2>/dev/null)" == "9" ]] \
    || { echo "FAIL: a transient gh failure clobbered open-prs.json" >&2; fail=1; }
# The cost ceiling: one call each, even with GitHub down. Retrying here is what
# made a multi-repo upload 3x slower during an outage.
[[ "$(calls 'pr view')" == "1" ]] \
    || { echo "FAIL: pr view made $(calls 'pr view') calls during an outage, want 1" >&2; fail=1; }
[[ "$(calls 'pr list')" == "1" ]] \
    || { echo "FAIL: pr list made $(calls 'pr list') calls during an outage, want 1" >&2; fail=1; }

# --- "no such PR" is a real answer: delete stale context, and do not retry ---
seed_context
GH_MODE=nopr generate_repo_context "$SBX" myrepo personal >/dev/null 2>&1 || true
[[ ! -f "${REPO}/pr-context.md" && ! -f "${REPO}/jira-context.md" ]] \
    || { echo "FAIL: stale context survived a definitive 'no pull requests found'" >&2; fail=1; }
[[ "$(calls 'pr view')" == "1" ]] \
    || { echo "FAIL: retried a definitive answer $(calls 'pr view')x — that cost is paid per non-PR repo" >&2; fail=1; }

# --- gh pr checkout is the one call that retries ---
# It decides what code lands in the sandbox and runs once per repo at create
# time, so waiting on it is worth it where waiting on context is not.
seed_context
GH_MODE=flaky checkout_pr "$REPO" 5 >/dev/null 2>&1 || true
[[ "$(calls 'pr checkout')" == "2" ]] \
    || { echo "FAIL: checkout did not retry past one failure ($(calls 'pr checkout') calls)" >&2; fail=1; }

seed_context
GH_MODE=transient checkout_pr "$REPO" 5 >/dev/null 2>&1 || true
[[ "$(calls 'pr checkout')" == "$GH_RETRY_ATTEMPTS" ]] \
    || { echo "FAIL: checkout made $(calls 'pr checkout') attempts, want ${GH_RETRY_ATTEMPTS}" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all gh-retry checks passed"
exit $fail
