#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# One rule under test: a work-profile Codex sandbox must come up with the
# host's own choices — model, context window, auto-compact threshold, reasoning
# effort, status line, [tui], [features] — and the portable [otel] keys, and a
# working native OTEL exporter, without ever mirroring the host's own
# config.toml (host-only MCP/sandbox_permissions entries, a model pinned under
# some other profile's table, and an [otel] exporter pointed at the host's own,
# unreachable collector — see gotcha 21).
#
# Drives render_codex_config() directly. The endpoint/protocol schema this
# checks against was confirmed empirically against a live `codex logout`:
# an [otel.exporter.otlp-http] table needs `endpoint` (no environment
# fallback) and accepts only "binary" or "json" for `protocol`.
#
# Run: tests/test-render-codex-config.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SANDBOX_SH="${REPO_ROOT}/scripts/sandbox.sh"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Lift the renderer out of sandbox.sh — sourcing the script would run it.
HELPERS="${TMP}/helpers.sh"
sed -n '/^render_codex_config()/,/^}/p' "$SANDBOX_SH" > "$HELPERS"
grep -q 'render_codex_config' "$HELPERS" \
    || { echo "FAIL: could not lift render_codex_config out of sandbox.sh" >&2; exit 1; }
# shellcheck disable=SC1090
source "$HELPERS"

fail=0
OTEL_URL="http://host.containers.internal:4318"

# --- host has a pinned model: line carries over verbatim ---
HOST_CONFIG="${TMP}/config.toml"
cat > "$HOST_CONFIG" << 'EOF'
model = "gpt-5.6-luna"
model_context_window = 872000
model_auto_compact_token_limit = 860000
model_auto_compact_token_limit_scope = "total"
model_reasoning_effort = "high"
status_line = ["model-with-reasoning", "context-used"]
status_line_use_colors = true

[sandbox_permissions]
disk-full-read-access = true

[otel]
environment = "staging"
log_user_prompt = false
exporter = "host-only"

[mcp_servers.my_server]
command = "/home/me/bin/my-mcp-server"

[profiles.other]
model = "not-this-one"

[tui]
status_line = ["context-used"]
notifications = true

[features]
web_search_request = true
EOF

OUT="$(render_codex_config "$HOST_CONFIG" "$OTEL_URL")"

echo "$OUT" | grep -qx 'model = "gpt-5.6-luna"' \
    || { echo "FAIL: model line missing or altered" >&2; fail=1; }
echo "$OUT" | grep -qx 'model_context_window = 872000' \
    || { echo "FAIL: model_context_window missing or altered" >&2; fail=1; }
echo "$OUT" | grep -qx 'model_auto_compact_token_limit = 860000' \
    || { echo "FAIL: model_auto_compact_token_limit missing or altered" >&2; fail=1; }
echo "$OUT" | grep -qx 'model_auto_compact_token_limit_scope = "total"' \
    || { echo "FAIL: model_auto_compact_token_limit_scope missing or altered" >&2; fail=1; }
echo "$OUT" | grep -qx 'model_reasoning_effort = "high"' \
    || { echo "FAIL: model_reasoning_effort missing or altered" >&2; fail=1; }
echo "$OUT" | grep -qx 'status_line = \["model-with-reasoning", "context-used"\]' \
    || { echo "FAIL: top-level status_line missing or altered" >&2; fail=1; }
echo "$OUT" | grep -qx 'status_line_use_colors = true' \
    || { echo "FAIL: status_line_use_colors missing or altered" >&2; fail=1; }
[[ "$(echo "$OUT" | grep -c '^model = ')" -eq 1 ]] \
    || { echo "FAIL: a model line below a table header was hoisted" >&2; fail=1; }

# --- kept tables travel whole, dropped tables not at all ---
echo "$OUT" | grep -q '^\[tui\]$' \
    || { echo "FAIL: [tui] table missing" >&2; fail=1; }
echo "$OUT" | grep -qx 'notifications = true' \
    || { echo "FAIL: [tui] table did not travel whole" >&2; fail=1; }
echo "$OUT" | grep -q '^\[features\]$' \
    || { echo "FAIL: [features] table missing" >&2; fail=1; }
echo "$OUT" | grep -qx 'web_search_request = true' \
    || { echo "FAIL: [features] table did not travel whole" >&2; fail=1; }
echo "$OUT" | grep -q 'host-only' \
    && { echo "FAIL: host [otel] table was copied whole" >&2; fail=1; }
echo "$OUT" | grep -q 'not-this-one' \
    && { echo "FAIL: host [profiles.other] table leaked into rendered config" >&2; fail=1; }
echo "$OUT" | grep -q '^\[otel.exporter.otlp-http\]$' \
    || { echo "FAIL: otel exporter table missing" >&2; fail=1; }
echo "$OUT" | grep -qx 'environment = "staging"' \
    || { echo "FAIL: OTEL environment was not preserved" >&2; fail=1; }
echo "$OUT" | grep -qx 'log_user_prompt = false' \
    || { echo "FAIL: log_user_prompt was not preserved" >&2; fail=1; }
echo "$OUT" | grep -q '^\[projects\."/sandbox/source"\]$' \
    || { echo "FAIL: sandbox project entry missing" >&2; fail=1; }
echo "$OUT" | grep -qx 'trust_level = "trusted"' \
    || { echo "FAIL: sandbox project is not trusted" >&2; fail=1; }
echo "$OUT" | grep -qx "endpoint = \"${OTEL_URL}/v1/logs\"" \
    || { echo "FAIL: log endpoint not set to the sandbox's own OTEL_URL" >&2; fail=1; }
echo "$OUT" | grep -qx "endpoint = \"${OTEL_URL}/v1/metrics\"" \
    || { echo "FAIL: metrics endpoint not set to the sandbox's own OTEL_URL" >&2; fail=1; }
echo "$OUT" | grep -qx 'protocol = "binary"' \
    || { echo "FAIL: protocol not set to binary (otlp-http/protobuf)" >&2; fail=1; }
echo "$OUT" | grep -q '^\[otel.metrics_exporter.otlp-http\]$' \
    || { echo "FAIL: metrics exporter table missing" >&2; fail=1; }
[[ "$(echo "$OUT" | grep -cF "endpoint = \"${OTEL_URL}/v1/")" -eq 2 ]] \
    || { echo "FAIL: both exporters do not use the sandbox's own OTEL_URL" >&2; fail=1; }
[[ "$(echo "$OUT" | grep -cF 'protocol = "binary"')" -eq 2 ]] \
    || { echo "FAIL: both exporters do not set protocol to binary" >&2; fail=1; }

# --- the feature flag that makes request_user_input usable ---
# Without it the tool is Plan-mode-only, and Plan mode cannot run anything, so
# a skill can ask a question or do the work but never both. Set here rather
# than copied from the host so a machine that never enabled it still gets
# sandboxes that behave the same.
echo "$OUT" | grep -q '^\[features\]$' \
    || { echo "FAIL: [features] table missing" >&2; fail=1; }
echo "$OUT" | grep -qx 'default_mode_request_user_input = true' \
    || { echo "FAIL: default_mode_request_user_input not enabled" >&2; fail=1; }

# A bare key after a table header belongs to that table, so `model` has to come
# before every `[...]` line or Codex loads a config with no model pinned and a
# junk key inside [features].
model_line=$(echo "$OUT" | grep -n '^model' | head -1 | cut -d: -f1)
first_table=$(echo "$OUT" | grep -n '^\[' | head -1 | cut -d: -f1)
[[ -n "$model_line" && -n "$first_table" && "$model_line" -lt "$first_table" ]] \
    || { echo "FAIL: model line is not above the first table header" >&2; fail=1; }

# Never a mirror: host-only MCP server commands and sandbox_permissions must
# not appear in the rendered output.
echo "$OUT" | grep -q "my-mcp-server" \
    && { echo "FAIL: host MCP server entry leaked into rendered config" >&2; fail=1; }
echo "$OUT" | grep -q "sandbox_permissions" \
    && { echo "FAIL: host sandbox_permissions leaked into rendered config" >&2; fail=1; }

# --- host has no config.toml at all: otel still renders, no model line ---
OUT_NO_HOST="$(render_codex_config "${TMP}/does-not-exist.toml" "$OTEL_URL")"
echo "$OUT_NO_HOST" | grep -q '^model' \
    && { echo "FAIL: model line appeared with no host config.toml" >&2; fail=1; }
echo "$OUT_NO_HOST" | grep -qx "endpoint = \"${OTEL_URL}/v1/logs\"" \
    || { echo "FAIL: otel endpoint missing with no host config.toml" >&2; fail=1; }
echo "$OUT_NO_HOST" | grep -qx 'default_mode_request_user_input = true' \
    || { echo "FAIL: feature flag missing with no host config.toml" >&2; fail=1; }

# --- host config.toml has no model line: same, no model line rendered ---
NO_MODEL_CONFIG="${TMP}/no-model-config.toml"
cat > "$NO_MODEL_CONFIG" << 'EOF'
[otel]
exporter = "none"
EOF
OUT_NO_MODEL="$(render_codex_config "$NO_MODEL_CONFIG" "$OTEL_URL")"
echo "$OUT_NO_MODEL" | grep -q '^model' \
    && { echo "FAIL: model line appeared when host config.toml had none" >&2; fail=1; }
echo "$OUT_NO_MODEL" | grep -qx "endpoint = \"${OTEL_URL}/v1/logs\"" \
    || { echo "FAIL: carrying nothing over from the host killed the render" >&2; fail=1; }

if [[ $fail -eq 0 ]]; then
    echo "all render-codex-config checks passed"
else
    exit 1
fi
