#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# --all fans --refresh/--recreate out over every sandbox in ~/sandboxes/.
#
# Three things it has to get right, none visible without running it:
#   - the list comes from ~/sandboxes/*/manifest.json, so a stray directory
#     with no manifest is not a sandbox and must not be touched;
#   - --all is pre-scanned, because --refresh/--recreate resolve their NAME as
#     they are parsed and would infer-or-die before a trailing --all is seen;
#   - --recreate needs --profile on the CLI (the manifest fallback runs after
#     it) and ends by exec'ing --connect, so the fan-out has to supply the
#     profile per sandbox and suppress the connect.
#
# Runs sandbox.sh against a scratch HOME with --dryrun, so no openshell calls
# are made.
#
# Run: tests/test-all-fanout.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "$WORK/"
if [[ ! -f "${WORK}/config/site.env" ]]; then
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
fi
SANDBOX_SH="${WORK}/scripts/sandbox.sh"

FAKE_HOME="${TMP}/home"
for n in alpha beta; do
    mkdir -p "${FAKE_HOME}/sandboxes/${n}"
    printf '{"name":"%s","openshell_name":"sb-%s","profile":"personal","repos":{}}' "$n" "$n" \
        > "${FAKE_HOME}/sandboxes/${n}/manifest.json"
done
# No manifest: not a sandbox.
mkdir -p "${FAKE_HOME}/sandboxes/notasandbox"

fail=0

# --- --refresh --all reaches both sandboxes and only those two ---
out="$(HOME="$FAKE_HOME" bash "$SANDBOX_SH" --refresh --all --dryrun 2>&1 || true)"
for n in alpha beta; do
    grep -qF "=== refresh ${n} ===" <<<"$out" \
        || { echo "FAIL: --refresh --all skipped ${n}" >&2; fail=1; }
done
grep -qF "notasandbox" <<<"$out" \
    && { echo "FAIL: --refresh --all picked up a directory with no manifest" >&2; fail=1; }

# --- flag order: --all before the mode parses the same ---
pre_out="$(HOME="$FAKE_HOME" bash "$SANDBOX_SH" --all --refresh --dryrun 2>&1 || true)"
grep -qF "=== refresh alpha ===" <<<"$pre_out" \
    || { echo "FAIL: --all before --refresh did not fan out" >&2; fail=1; }

# --- --recreate --all: profile comes from each manifest, connect suppressed ---
rc_out="$(HOME="$FAKE_HOME" bash "$SANDBOX_SH" --recreate --all --dryrun 2>&1 || true)"
for n in alpha beta; do
    # Reaching this line at all proves --profile was passed: --recreate exits
    # on a missing profile before it prints anything.
    grep -qF "Recreating sandbox ${n}" <<<"$rc_out" \
        || { echo "FAIL: --recreate --all did not recreate ${n}" >&2; fail=1; }
    grep -qF "Recreated ${n}." <<<"$rc_out" \
        || { echo "FAIL: --recreate --all connected (or died) on ${n} instead of moving on" >&2; fail=1; }
done
grep -qF "Starting Claude" <<<"$rc_out" \
    && { echo "FAIL: --recreate --all launched a session" >&2; fail=1; }

# --- a sandbox with no profile in its manifest is skipped, not guessed ---
mkdir -p "${FAKE_HOME}/sandboxes/oldie"
printf '{"name":"oldie","openshell_name":"sb-oldie","repos":{}}' \
    > "${FAKE_HOME}/sandboxes/oldie/manifest.json"
old_out="$(HOME="$FAKE_HOME" bash "$SANDBOX_SH" --recreate --all --dryrun 2>&1 || true)"
grep -qF "Skipped oldie" <<<"$old_out" \
    || { echo "FAIL: --recreate --all did not skip the profile-less sandbox" >&2; fail=1; }
rm -rf "${FAKE_HOME:?}/sandboxes/oldie"

# --- rejections ---
if HOME="$FAKE_HOME" bash "$SANDBOX_SH" --all --dryrun >/dev/null 2>&1; then
    echo "FAIL: --all without --refresh/--recreate was accepted" >&2
    fail=1
fi
if HOME="$FAKE_HOME" bash "$SANDBOX_SH" --refresh alpha --all --dryrun >/dev/null 2>&1; then
    echo "FAIL: --all with an explicit NAME was accepted" >&2
    fail=1
fi

[[ $fail -eq 0 ]] && echo "all --all fan-out checks passed"
exit $fail
