#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# Self-check for start_error_sandbox(): --ensure against a sandbox in Error
# phase must podman start the container and wait for Ready before connecting.
# Stubs openshell and podman on $PATH and lifts the real functions out of
# sandbox.sh, so the test cannot drift from the code it covers.
#
# Run: tests/test-error-sandbox-start.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# --- stubs: phase comes from $TMP/phase, `podman start` flips it to Ready ---
mkdir -p "${TMP}/bin"
cat > "${TMP}/bin/openshell" << 'STUB'
#!/bin/bash
printf '[{"name":"sb-test","phase":"%s"}]\n' "$(cat "${TMP}/phase")"
STUB
cat > "${TMP}/bin/podman" << 'STUB'
#!/bin/bash
if [[ "$1" == "start" ]]; then
    echo "$2" >> "${TMP}/started"
    echo Ready > "${TMP}/phase"
    exit 0
fi
cat "${TMP}/containers"
STUB
chmod +x "${TMP}/bin/openshell" "${TMP}/bin/podman"
export PATH="${TMP}/bin:${PATH}" TMP

# --- the functions under test, lifted from sandbox.sh ---
eval "$(sed -n '/^sandbox_phase()/,/^}/p; /^start_error_sandbox()/,/^}/p' \
    "${REPO_ROOT}/scripts/sandbox.sh")"
declare -F start_error_sandbox >/dev/null || {
    echo "FAIL: start_error_sandbox not found in sandbox.sh" >&2; exit 1; }

# Read by the eval'd functions, not by anything shellcheck can see here.
# shellcheck disable=SC2034
DRYRUN=false
# shellcheck disable=SC2034
GW_FLAG=()
run() { "$@"; }

fail() { echo "FAIL: $1" >&2; exit 1; }

with_container() { echo '[{"Id":"deadbeef","Labels":{"openshell.ai/sandbox-name":"sb-test"}}]' > "${TMP}/containers"; }
no_container() { echo '[]' > "${TMP}/containers"; }

# --- Ready sandbox: nothing to start ---
echo Ready > "${TMP}/phase"
with_container
rm -f "${TMP}/started"
start_error_sandbox sb-test
if [[ -f "${TMP}/started" ]]; then fail "podman start ran on a Ready sandbox"; fi

# --- Error sandbox with a container: started, then waited to Ready ---
echo Error > "${TMP}/phase"
start_error_sandbox sb-test
[[ -f "${TMP}/started" ]] || fail "podman start did not run on an Error sandbox"
[[ "$(cat "${TMP}/started")" == "deadbeef" ]] || fail "started the wrong container"
[[ "$(cat "${TMP}/phase")" == "Ready" ]] || fail "returned before phase was Ready"

# --- Error sandbox with no container: exit 1, do not connect ---
echo Error > "${TMP}/phase"
no_container
rm -f "${TMP}/started"
if (start_error_sandbox sb-test 2>/dev/null); then
    fail "no container should be fatal"
fi
if [[ -f "${TMP}/started" ]]; then fail "podman start ran without a container"; fi

echo "PASS: tests/test-error-sandbox-start.sh"
