#!/bin/bash
# Generated By: Claude Code (claude-opus-5)
#
# One rule under test: the advisor model is derived from the model the session
# is actually launching with, one class up, and nothing is written when there
# is no model to derive from.
#
# Drives the two wrapper functions directly — lifted out of the script the way
# tests/test-connect-harness.sh lifts default_harness — so no container, no
# openshell, and no interactive prompt is needed.
#
# Run: tests/test-advisor-model.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
W="${REPO_ROOT}/bin/harness-wrapper.sh"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

HELPERS="${TMP}/helpers.sh"
sed -n '/^advisor_for()/,/^}/p;/^apply_advisor()/,/^}/p' "$W" > "$HELPERS"
grep -q 'advisor_for' "$HELPERS" \
    || { echo "FAIL: could not lift advisor_for out of the wrapper" >&2; exit 1; }
grep -q 'apply_advisor' "$HELPERS" \
    || { echo "FAIL: could not lift apply_advisor out of the wrapper" >&2; exit 1; }
# shellcheck disable=SC1090
source "$HELPERS"

fail=0

check() {
    local what="$1" want="$2" got="$3"
    if [[ "$got" != "$want" ]]; then
        echo "FAIL: ${what}: wanted '${want}', got '${got}'" >&2
        fail=1
    fi
}

# --- the mapping: one class up, fable is the ceiling ---
#
# Matched on substring so a full id and a bare alias take the same row. The
# wrapper's own pin is a full id with a bracketed suffix
# (claude-opus-5[1m]); `/model haiku` at the prompt is not.
check "haiku maps to sonnet" "sonnet" "$(advisor_for 'claude --model haiku')"
check "a haiku id maps to sonnet" "sonnet" \
    "$(advisor_for 'claude --model claude-haiku-4-5-20251001')"
check "sonnet maps to opus" "opus" "$(advisor_for 'claude --model sonnet')"
check "a sonnet id maps to opus" "opus" "$(advisor_for 'claude --model claude-sonnet-5')"
check "opus maps to fable" "fable" "$(advisor_for 'claude --model opus')"
check "fable is its own advisor, nothing is above it" "fable" \
    "$(advisor_for 'claude --model claude-fable-5-1')"

# What the wrapper actually builds on personal/home, verbatim including the
# bracketed context suffix — the one row that fires without a hand edit.
check "the profile pin maps to fable" "fable" \
    "$(advisor_for 'dtach -c /sandbox/.dtach-claude claude --model claude-opus-5[1m] --dangerously-skip-permissions -c')"

check "--model=X is the same as --model X" "fable" "$(advisor_for 'claude --model=opus')"

# --- nothing to derive from: emit nothing rather than guess ---
check "no --model derives nothing" "" \
    "$(advisor_for 'dtach -c /sandbox/.dtach-claude claude --dangerously-skip-permissions -c')"
check "a reattach derives nothing" "" "$(advisor_for 'dtach -a /sandbox/.dtach-claude')"
check "codex derives nothing" "" \
    "$(advisor_for 'dtach -c /sandbox/.dtach-codex codex resume --dangerously-bypass-approvals-and-sandbox')"
check "an unknown model derives nothing" "" "$(advisor_for 'claude --model gpt-5')"
# --model is a flag, not a prefix: a longer flag starting with it is not a match.
check "--model-foo is not --model" "" "$(advisor_for 'claude --model-foo opus')"

# --- the write ---
S="${TMP}/settings.json"
export ADVISOR_SETTINGS="$S"

printf '{"hooks": {"Stop": []}, "advisorModel": "sonnet"}\n' > "$S"
apply_advisor 'claude --model claude-opus-5[1m]'
check "the advisor is written" "fable" "$(jq -r '.advisorModel' "$S")"
check "the rest of settings.json survives" "true" "$(jq -r 'has("hooks")' "$S")"
[[ -e "${S}.tmp" ]] && { echo "FAIL: the temp file was left behind" >&2; fail=1; }

# A host value chosen for the host's own model must not stand. This is the
# whole reason the wrapper writes rather than inherits: a sandbox pinned to
# opus with a host advisor of sonnet gets a reviewer weaker than itself.
printf '{"advisorModel": "sonnet"}\n' > "$S"
apply_advisor 'claude --model opus'
check "a stale host value is overwritten" "fable" "$(jq -r '.advisorModel' "$S")"

# Nothing derived means the file is not touched at all — not emptied, not
# reset. The work profile and every reattach land here.
printf '{"advisorModel": "sonnet"}\n' > "$S"
before="$(cat "$S")"
apply_advisor 'dtach -a /sandbox/.dtach-claude'
check "no model leaves settings.json alone" "$before" "$(cat "$S")"

# A settings.json that is not there is not an error: the wrapper runs before
# anything guarantees one exists.
rm -f "$S"
apply_advisor 'claude --model opus'
[[ -e "$S" ]] && { echo "FAIL: a missing settings.json was created" >&2; fail=1; }

# Malformed JSON must fail closed. jq exits non-zero, the mv never runs, and
# the original is still whatever it was — a truncated settings.json is a
# sandbox with no hooks and no permissions.
printf 'not json\n' > "$S"
# jq's own parse error on stderr is the mechanism working; keep it out of the
# test's output so a real failure is the only thing that shows up there.
apply_advisor 'claude --model opus' 2>/dev/null
check "a malformed settings.json is left intact" "not json" "$(cat "$S")"
[[ -e "${S}.tmp" ]] && { echo "FAIL: the temp file was left behind on failure" >&2; fail=1; }

# --- placement in the wrapper ---
#
# Derived AFTER the prompt, so a --model the user typed over the default is
# what decides. Before the read it would only ever see the profile's pin.
grep -q 'apply_advisor "\$user_cmd"' "$W" \
    || { echo "FAIL: wrapper does not apply the advisor to the final command" >&2; fail=1; }
read_line=$(grep -n 'read -erp "> "' "$W" | cut -d: -f1)
apply_line=$(grep -n 'apply_advisor "\$user_cmd"' "$W" | cut -d: -f1)
[[ -n "$read_line" && -n "$apply_line" && "$apply_line" -gt "$read_line" ]] \
    || { echo "FAIL: the advisor is derived before the command prompt" >&2; fail=1; }

if [[ $fail -eq 0 ]]; then
    echo "all advisor-model checks passed"
else
    exit 1
fi
