#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# Rules under test:
#   1. --quick does not re-upload a repo with nothing modified since
#      .repos[<name>].last_upload. `openshell sandbox upload` is a full tar with
#      no delta, so an unchanged reference repo otherwise re-sends its whole
#      .git every time.
#   2. A plain --upload ALWAYS sends, unchanged or not. It rm -rf's the sandbox
#      copy first, so it is how edits a session made inside the sandbox get
#      wiped back to host state. Skipping there would assume host and sandbox
#      already agree — the one thing it cannot assume.
#   3. A real upload stamps last_upload; a download stamps last_download; a
#      --dryrun stamps neither, or the next real run skips a repo it never sent.
#   4. --quick skips context generation entirely (no gh, no Jira).
#
# openshell and gh are stubbed, so the test needs no gateway, auth, or network.
#
# Run: tests/test-upload-skip.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "$WORK/"
# site.env is gitignored and absent on a fresh clone; sandbox.sh refuses to run
# without one. Never dialled — openshell is stubbed.
if [[ ! -f "${WORK}/config/site.env" ]]; then
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
fi

export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null
export GIT_AUTHOR_NAME=test GIT_AUTHOR_EMAIL=test@example.com
export GIT_COMMITTER_NAME=test GIT_COMMITTER_EMAIL=test@example.com

fail=0

# --- stubs: openshell and gh both log and succeed ---
STUB="${TMP}/stub"
mkdir -p "$STUB"
CALL_LOG="${TMP}/calls"
export CALL_LOG
cat > "${STUB}/openshell" << 'STUBEOF'
#!/bin/bash
echo "openshell $*" >> "$CALL_LOG"
exit 0
STUBEOF
# gh answers with a stable PR and a stable PR list, so context generation
# produces byte-identical files on every run — which is the case that has to
# leave the repo looking clean.
cat > "${STUB}/gh" << 'STUBEOF'
#!/bin/bash
echo "gh $*" >> "$CALL_LOG"
case "$1 $2" in
    # $GH_NO_PR makes the branch look like it has no PR, so generate_repo_context
    # writes nothing into the repo. Exit 1 with no recognisable message is the
    # "gh could not answer" path, which keeps existing files rather than deleting.
    "pr view") [[ -n "${GH_NO_PR:-}" ]] && exit 1
               echo '{"number":7,"title":"t","body":"b","headRefName":"main","baseRefName":"main","labels":[],"assignees":[]}' ;;
    "pr list") echo '[]' ;;
    *) exit 1 ;;
esac
STUBEOF
chmod +x "${STUB}/openshell" "${STUB}/gh"
export PATH="${STUB}:${PATH}"

# --- fixture: a sandbox dir with one GitHub repo ---
export HOME="${TMP}/home"
SBX="${HOME}/sandboxes/probe"
REPO="${SBX}/myrepo"
mkdir -p "$REPO"
git -C "$REPO" init -q -b main
echo hello > "${REPO}/file.txt"
git -C "$REPO" add file.txt
git -C "$REPO" commit -qm init
jq -n '{name:"probe",openshell_name:"sb-probe",profile:"personal",
        repos:{myrepo:{url:"git@github.com:org/myrepo.git"}}}' > "${SBX}/manifest.json"

MANIFEST="${SBX}/manifest.json"
stamp_of() { jq -r --arg f "$1" '.repos.myrepo[$f] // empty' "$MANIFEST"; }
uploaded() { grep -qE 'openshell sandbox upload .*/myrepo /sandbox/source/' "$CALL_LOG"; }

# last_upload has whole-second resolution, so a file written in the same second
# as the stamp reads as newer than it. That is deliberate — it costs one
# redundant upload rather than dropping a change — but it makes a test whose
# every step lands in the same second meaningless. Settle first.
upload() {
    sleep 1
    : > "$CALL_LOG"
    ( cd "$SBX" && "${WORK}/scripts/sandbox.sh" --upload probe "$@" ) >/dev/null 2>&1
}

# --- first upload: sends the repo and stamps last_upload ---
upload --quick
uploaded || { echo "FAIL: first upload did not send the repo" >&2; fail=1; }
FIRST="$(stamp_of last_upload)"
[[ -n "$FIRST" ]] \
    || { echo "FAIL: no last_upload in manifest after a real upload" >&2; fail=1; }

# --- --quick makes no gh call ---
grep -q '^gh ' "$CALL_LOG" && { echo "FAIL: --quick still called gh" >&2; fail=1; }

# --- nothing changed: skipped ---
upload --quick
uploaded && { echo "FAIL: re-uploaded a repo with no changes" >&2; fail=1; }
[[ "$(stamp_of last_upload)" == "$FIRST" ]] \
    || { echo "FAIL: a skipped upload moved last_upload" >&2; fail=1; }

# --- a modified file brings it back ---
echo changed > "${REPO}/file.txt"
upload --quick
uploaded || { echo "FAIL: a modified repo was skipped" >&2; fail=1; }
[[ "$(stamp_of last_upload)" != "$FIRST" ]] \
    || { echo "FAIL: last_upload not refreshed after a real upload" >&2; fail=1; }

# --- a dryrun stamps nothing ---
BEFORE="$(stamp_of last_upload)"
echo again > "${REPO}/file.txt"
upload --quick --dryrun
[[ "$(stamp_of last_upload)" == "$BEFORE" ]] \
    || { echo "FAIL: --dryrun stamped last_upload for an upload it never made" >&2; fail=1; }
upload --quick
uploaded || { echo "FAIL: a repo changed during --dryrun was skipped afterwards" >&2; fail=1; }

# --- a non-quick run generates context ---
upload
uploaded || { echo "FAIL: non-quick upload did not send the repo" >&2; fail=1; }
grep -q 'gh pr view' "$CALL_LOG" \
    || { echo "FAIL: non-quick upload generated no context" >&2; fail=1; }
[[ -f "${REPO}/pr-context.md" ]] \
    || { echo "FAIL: pr-context.md not written" >&2; fail=1; }

# --- --quick over the same repo writes nothing, so it settles to skipping.
# The first may still re-send: last_upload has whole-second resolution, so
# context files written in the second the stamp names read as newer than it.
# One redundant tar, then quiet. ---
upload --quick
upload --quick
uploaded && { echo "FAIL: --quick re-uploaded a repo it did not modify" >&2; fail=1; }
grep -q '^gh ' "$CALL_LOG" && { echo "FAIL: --quick called gh" >&2; fail=1; }

# --- THE WIPE CASE: a plain --upload sends an unchanged repo anyway. A session
# may have edited files inside the sandbox; rm -rf + re-upload is how that gets
# reset, and the host copy looks identical either way.
#
# GH_NO_PR stops pr-context.md being rewritten and open-prs.json is inside its
# TTL, so nothing lands in the repo — without that, context generation dirties
# it and the upload happens for the wrong reason. ---
GH_NO_PR=1 upload
[[ -z "$(find "$REPO" -newermt "$(stamp_of last_upload)" -print -quit)" ]] \
    || { echo "FAIL: setup wrong — the repo was modified, so this proves nothing" >&2; fail=1; }
uploaded || { echo "FAIL: plain --upload skipped an unchanged repo, so a session's sandbox-side edits cannot be wiped" >&2; fail=1; }

# --- -q is the same flag as --quick. The optional-NAME parsers accepted
# anything not starting with `--` as the sandbox name, so `--upload -q` set the
# name to "-q" and died resolving it. ---
# `|| true` on both: with the bug, sandbox.sh exits non-zero, and under set -e
# that aborts the whole file before any assertion runs — a real failure would
# show up as a silent early exit rather than a FAIL line.
: > "$CALL_LOG"
( cd "$SBX" && "${WORK}/scripts/sandbox.sh" --upload probe -q ) >/dev/null 2>&1 || true
grep -q '^gh ' "$CALL_LOG" && { echo "FAIL: -q did not suppress context generation" >&2; fail=1; }
: > "$CALL_LOG"
( cd "$SBX" && "${WORK}/scripts/sandbox.sh" --upload -q ) >/dev/null 2>&1 || true
grep -q 'sandbox upload' "$CALL_LOG" \
    || { echo "FAIL: --upload -q did nothing — -q was consumed as the sandbox name" >&2; fail=1; }

source "${WORK}/scripts/lib.sh"

# --- git state detection. `git status` rewrites .git and .git/index and
# nothing else, so an editor or shell prompt polling it used to make every repo
# look modified on every run. Excluding those must not cost real git signals:
# staging, committing and branch switches all write elsewhere under .git. ---
git_quiet() { git -C "$REPO" -c commit.gpgsign=false "$@" >/dev/null 2>&1; }
settle_quick() { upload --quick; upload --quick; }

settle_quick
uploaded && { echo "FAIL: setup wrong — repo not in the skipped state" >&2; fail=1; }

git_quiet status --porcelain
upload --quick
uploaded && { echo "FAIL: a bare 'git status' made the repo look modified" >&2; fail=1; }

echo staged > "${REPO}/staged.txt"
git_quiet add staged.txt
rm -f "${REPO}/staged.txt"          # worktree back as it was; only the index and objects hold it
upload --quick
uploaded || { echo "FAIL: a staged change was not detected" >&2; fail=1; }

settle_quick
git_quiet checkout -b other-branch
upload --quick
uploaded || { echo "FAIL: a branch switch was not detected" >&2; fail=1; }

settle_quick
echo committed > "${REPO}/committed.txt"
git_quiet add committed.txt
git_quiet commit -m c
upload --quick
uploaded || { echo "FAIL: a commit was not detected" >&2; fail=1; }

# --- last_download is stamped separately from last_upload ---
record_repo_timestamp "$SBX" myrepo last_download
[[ -n "$(stamp_of last_download)" ]] \
    || { echo "FAIL: last_download not recorded" >&2; fail=1; }

# --- re-registering a repo must not wipe the stamps. write_manifest assigned a
# fresh object to .repos[<name>], so --create/--add-repo dropped them and every
# later --quick re-uploaded everything. Checked with last_download, which
# --add-repo never writes: last_upload is legitimately re-stamped by the upload
# --add-repo performs, so it cannot tell a merge from a replace. ---
BEFORE_CLONE="$(stamp_of last_download)"
( cd "$SBX" && "${WORK}/scripts/sandbox.sh" --add-repo probe \
    --repo git@github.com:org/myrepo.git --source-dir "$REPO" ) >/dev/null 2>&1 || true
[[ "$(stamp_of last_download)" == "$BEFORE_CLONE" ]] \
    || { echo "FAIL: re-registering a repo dropped last_download (got: '$(stamp_of last_download)')" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all upload-skip checks passed"
exit $fail
