#!/bin/bash
# Generated By: Claude Code (claude-opus-5-5[1m])
#
# Two rules under test, both about the ~/.claude staging copy --refresh builds:
#   - what git ignores is not staged. `rsync -rL` follows a skill symlinked to
#     its own checkout, and that checkout's gitignored worktree dir was copied
#     into every sandbox in full. The fixture also carries the two cases a
#     naive .gitignore filter broke: a skills/.gitignore listing the symlink
#     itself, and a plugin clone using `!negation` on committed files;
#   - the staging dir is removed when the upload fails. The inline `rm -rf`
#     only ran on success, so a failure under `set -e` left it in /tmp.
#
# Runs sandbox.sh against a scratch HOME with an `openshell` stub on PATH that
# records what each `sandbox upload` was handed, or fails it on request.
#
# Run: tests/test-refresh-staging.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

if ! command -v rsync >/dev/null 2>&1; then
    echo "warning: rsync not installed, skipping the refresh staging checks" >&2
    echo "all refresh-staging checks passed"
    exit 0
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "${REPO_ROOT}/bin" "$WORK/"
if [[ ! -f "${WORK}/config/site.env" ]]; then
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
fi
SANDBOX_SH="${WORK}/scripts/sandbox.sh"

FAKE_HOME="${TMP}/home"
mkdir -p "${FAKE_HOME}/sandboxes/probe" "${FAKE_HOME}/.claude/skills"
printf '{"name":"probe","openshell_name":"sb-probe","profile":"personal","repos":{}}' \
    > "${FAKE_HOME}/sandboxes/probe/manifest.json"
echo '{}' > "${FAKE_HOME}/.claude/settings.json"

export GIT_CONFIG_GLOBAL=/dev/null
git_repo() {
    git -C "$1" init -q
    git -C "$1" add -A
    git -C "$1" -c user.name=t -c user.email=t commit -qm init
}

# The skill lives in its own checkout, outside ~/.claude, like the real one,
# with the real checkout's anchored glob over its scratch dirs.
CHECKOUT="${TMP}/skill-checkout"
mkdir -p "$CHECKOUT"
echo "skill" > "${CHECKOUT}/SKILL.md"
echo "/.tmp-*" > "${CHECKOUT}/.gitignore"
git_repo "$CHECKOUT"
mkdir -p "${CHECKOUT}/.tmp-worktrees/wt1"
echo "scratch" > "${CHECKOUT}/.tmp-worktrees/wt1/file"
ln -s "$CHECKOUT" "${FAKE_HOME}/.claude/skills/my-skill"

# skills/ is itself a repo that gitignores the linked skill, as link-skills.sh
# does on the host. A symlink is content to ship, ignored or not.
echo "/my-skill" > "${FAKE_HOME}/.claude/skills/.gitignore"
git_repo "${FAKE_HOME}/.claude/skills"

# A plugin clone that ignores a dir and re-includes a committed part of it.
PLUGIN="${FAKE_HOME}/.claude/plugins/marketplaces/docs"
mkdir -p "${PLUGIN}/.claude/agents"
echo "agent" > "${PLUGIN}/.claude/agents/writer.md"
printf '.claude/*\n!.claude/agents/\n' > "${PLUGIN}/.gitignore"
git_repo "$PLUGIN"
echo "state" > "${PLUGIN}/.claude/runtime.json"

# Stub: copy the path handed to `sandbox upload` (second-to-last arg) into
# CAPTURE, or fail it when FAIL_UPLOAD is set. Everything else succeeds silently.
STUB_BIN="${TMP}/stub-bin"
mkdir -p "$STUB_BIN"
cat > "${STUB_BIN}/openshell" <<'EOF'
#!/bin/bash
if [[ "$1 $2" == "sandbox upload" ]]; then
    [[ -n "${FAIL_UPLOAD:-}" ]] && exit 1
    args=("$@")
    cp -r "${args[${#args[@]}-2]}" "$CAPTURE/"
fi
exit 0
EOF
chmod +x "${STUB_BIN}/openshell"

fail=0

# --- gitignored files are not staged ---
CAPTURE="${TMP}/capture"
mkdir -p "$CAPTURE"
CAPTURE="$CAPTURE" HOME="$FAKE_HOME" PATH="${STUB_BIN}:${PATH}" \
    bash "$SANDBOX_SH" --refresh probe >/dev/null 2>&1 \
    || { echo "FAIL: --refresh against the stub exited non-zero" >&2; fail=1; }
STAGED="${CAPTURE}/.claude/skills/my-skill"
[[ -f "${STAGED}/SKILL.md" ]] \
    || { echo "FAIL: gitignored symlinked skill was not staged" >&2; fail=1; }
[[ ! -e "${STAGED}/.tmp-worktrees" ]] \
    || { echo "FAIL: gitignored .tmp-worktrees was staged" >&2; fail=1; }
STAGED_PLUGIN="${CAPTURE}/.claude/plugins/marketplaces/docs/.claude"
[[ -f "${STAGED_PLUGIN}/agents/writer.md" ]] \
    || { echo "FAIL: tracked file under a negated ignore was not staged" >&2; fail=1; }
[[ ! -e "${STAGED_PLUGIN}/runtime.json" ]] \
    || { echo "FAIL: gitignored plugin runtime state was staged" >&2; fail=1; }

# --- a failed upload leaves nothing in TMPDIR ---
RUN_TMP="${TMP}/run-tmp"
mkdir -p "$RUN_TMP"
if FAIL_UPLOAD=1 CAPTURE="$CAPTURE" HOME="$FAKE_HOME" PATH="${STUB_BIN}:${PATH}" \
    TMPDIR="$RUN_TMP" bash "$SANDBOX_SH" --refresh probe >/dev/null 2>&1; then
    echo "FAIL: --refresh succeeded although every upload failed" >&2
    fail=1
fi
leftover="$(find "$RUN_TMP" -mindepth 1 -print -quit)"
[[ -z "$leftover" ]] \
    || { echo "FAIL: failed --refresh left temp files behind: ${leftover}" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all refresh-staging checks passed"
exit $fail
