#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# One rule under test: a work-profile Codex sandbox must come up with the
# host's chosen model and a working native OTEL exporter, without ever
# mirroring the host's own config.toml (host-only MCP/sandbox_permissions
# entries, and an [otel] table pointed at the host's own, unreachable
# collector — see gotcha 21).
#
# Drives render_codex_config() directly. The endpoint/protocol schema this
# checks against was confirmed empirically against a live `codex logout`:
# an [otel.exporter.otlp-http] table needs `endpoint` (no environment
# fallback) and accepts only "binary" or "json" for `protocol`.
#
# Run: tests/test-render-codex-config.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SANDBOX_SH="${REPO_ROOT}/scripts/sandbox.sh"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Lift the renderer out of sandbox.sh — sourcing the script would run it.
HELPERS="${TMP}/helpers.sh"
sed -n '/^render_codex_config()/,/^}/p' "$SANDBOX_SH" > "$HELPERS"
grep -q 'render_codex_config' "$HELPERS" \
    || { echo "FAIL: could not lift render_codex_config out of sandbox.sh" >&2; exit 1; }
# shellcheck disable=SC1090
source "$HELPERS"

fail=0
OTEL_URL="http://host.containers.internal:4318"

# --- host has a pinned model: line carries over verbatim ---
HOST_CONFIG="${TMP}/config.toml"
cat > "$HOST_CONFIG" << 'EOF'
model = "gpt-5.6-luna"

[sandbox_permissions]
disk-full-read-access = true

[mcp_servers.my_server]
command = "/home/me/bin/my-mcp-server"
EOF

OUT="$(render_codex_config "$HOST_CONFIG" "$OTEL_URL")"

echo "$OUT" | grep -qx 'model = "gpt-5.6-luna"' \
    || { echo "FAIL: model line missing or altered" >&2; fail=1; }
echo "$OUT" | grep -q '^\[otel.exporter.otlp-http\]$' \
    || { echo "FAIL: otel exporter table missing" >&2; fail=1; }
echo "$OUT" | grep -qx "endpoint = \"${OTEL_URL}\"" \
    || { echo "FAIL: endpoint not set to the sandbox's own OTEL_URL" >&2; fail=1; }
echo "$OUT" | grep -qx 'protocol = "binary"' \
    || { echo "FAIL: protocol not set to binary (otlp-http/protobuf)" >&2; fail=1; }
echo "$OUT" | grep -q '^\[otel.metrics_exporter.otlp-http\]$' \
    || { echo "FAIL: metrics exporter table missing" >&2; fail=1; }
[[ "$(echo "$OUT" | grep -cF "endpoint = \"${OTEL_URL}\"")" -eq 2 ]] \
    || { echo "FAIL: both exporters do not use the sandbox's own OTEL_URL" >&2; fail=1; }
[[ "$(echo "$OUT" | grep -cF 'protocol = "binary"')" -eq 2 ]] \
    || { echo "FAIL: both exporters do not set protocol to binary" >&2; fail=1; }

# Never a mirror: host-only MCP server commands and sandbox_permissions must
# not appear in the rendered output.
echo "$OUT" | grep -q "my-mcp-server" \
    && { echo "FAIL: host MCP server entry leaked into rendered config" >&2; fail=1; }
echo "$OUT" | grep -q "sandbox_permissions" \
    && { echo "FAIL: host sandbox_permissions leaked into rendered config" >&2; fail=1; }

# --- host has no config.toml at all: otel still renders, no model line ---
OUT_NO_HOST="$(render_codex_config "${TMP}/does-not-exist.toml" "$OTEL_URL")"
echo "$OUT_NO_HOST" | grep -q '^model' \
    && { echo "FAIL: model line appeared with no host config.toml" >&2; fail=1; }
echo "$OUT_NO_HOST" | grep -qx "endpoint = \"${OTEL_URL}\"" \
    || { echo "FAIL: otel endpoint missing with no host config.toml" >&2; fail=1; }

# --- host config.toml has no model line: same, no model line rendered ---
NO_MODEL_CONFIG="${TMP}/no-model-config.toml"
cat > "$NO_MODEL_CONFIG" << 'EOF'
[otel]
exporter = "none"
EOF
OUT_NO_MODEL="$(render_codex_config "$NO_MODEL_CONFIG" "$OTEL_URL")"
echo "$OUT_NO_MODEL" | grep -q '^model' \
    && { echo "FAIL: model line appeared when host config.toml had none" >&2; fail=1; }

if [[ $fail -eq 0 ]]; then
    echo "all render-codex-config checks passed"
else
    exit 1
fi
