#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 5)
#
# Outbound fetch service for research sandboxes.
#
# A sandbox cannot perform HTTPS itself: its only egress is OpenShell's HTTP
# CONNECT proxy, which permits only hosts named in policy and refuses a nested
# CONNECT outright. So the sandbox asks this service, over plain HTTP, to make
# the request on its behalf:
#
#     GET /fetch?url=https%3A%2F%2Fexample.com%2Fpage
#
# The sandbox's policy names one host:port — this service — and nothing else.
#
# This process runs on the host with unrestricted network access, so the URL it
# is handed is attacker-controlled input from the sandbox's point of view.
# Everything below exists to keep that from becoming an SSRF pivot into the LAN.

import argparse
import ipaddress
import socket
import sys
import urllib.error
import urllib.parse
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

ALLOWED_SCHEMES = {"http", "https"}
MAX_BYTES = 8 * 1024 * 1024
MAX_REDIRECTS = 5
TIMEOUT_SECONDS = 30
USER_AGENT = "openshell-sandbox-fetchsvc/1.0"


class Refused(Exception):
    """Request rejected before any outbound connection was made."""


def _public_addresses(host):
    """Resolve host and fail unless every address is publicly routable.

    Checked after resolution, not on the hostname: a name that looks external
    can resolve to 127.0.0.1 or 192.168.x.x. Every address is checked because a
    name may resolve to several and the client does not choose which is used.
    """
    try:
        infos = socket.getaddrinfo(host, None, proto=socket.IPPROTO_TCP)
    except socket.gaierror as exc:
        raise Refused(f"cannot resolve {host}: {exc}") from exc

    addresses = {info[4][0] for info in infos}
    for address in addresses:
        ip = ipaddress.ip_address(address)
        if (ip.is_private or ip.is_loopback or ip.is_link_local
                or ip.is_multicast or ip.is_reserved or ip.is_unspecified):
            raise Refused(f"{host} resolves to non-public address {address}")
    return addresses


def validate(raw_url):
    """Return the parsed URL, or raise Refused with a reason."""
    parts = urllib.parse.urlsplit(raw_url)
    if parts.scheme not in ALLOWED_SCHEMES:
        raise Refused(f"scheme {parts.scheme!r} not allowed")
    if not parts.hostname:
        raise Refused("no host in url")
    _public_addresses(parts.hostname)
    return parts


def fetch(raw_url):
    """Follow redirects manually so each hop is validated before it is taken.

    urllib's default redirect handling would follow a 302 into 169.254.169.254
    without the destination ever passing validate().
    """
    url = raw_url
    for _ in range(MAX_REDIRECTS + 1):
        validate(url)
        request = urllib.request.Request(
            url, method="GET", headers={"User-Agent": USER_AGENT})
        opener = urllib.request.build_opener(_NoRedirect)
        try:
            with opener.open(request, timeout=TIMEOUT_SECONDS) as response:
                return url, response.status, response.headers, response.read(MAX_BYTES)
        except urllib.error.HTTPError as exc:
            location = exc.headers.get("Location") if exc.headers else None
            if exc.code in (301, 302, 303, 307, 308) and location:
                url = urllib.parse.urljoin(url, location)
                continue
            return url, exc.code, exc.headers, exc.read(MAX_BYTES)
    raise Refused(f"more than {MAX_REDIRECTS} redirects")


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, *_args, **_kwargs):
        return None


class Handler(BaseHTTPRequestHandler):
    server_version = USER_AGENT
    protocol_version = "HTTP/1.1"

    def log_message(self, fmt, *args):
        # One line per request, with the full URL. The audit trail an HTTP
        # proxy cannot produce, because it only ever sees the hostname.
        sys.stdout.write("%s - %s\n" % (self.address_string(), fmt % args))
        sys.stdout.flush()

    def _respond(self, status, body, content_type="text/plain; charset=utf-8"):
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        parts = urllib.parse.urlsplit(self.path)
        if parts.path == "/healthz":
            self._respond(200, b"ok\n")
            return
        if parts.path != "/fetch":
            self._respond(404, b"use /fetch?url=<encoded-url>\n")
            return

        target = urllib.parse.parse_qs(parts.query).get("url", [None])[0]
        if not target:
            self._respond(400, b"missing url parameter\n")
            return

        try:
            final_url, status, headers, body = fetch(target)
        except Refused as exc:
            self.log_message('REFUSED "%s" %s', target, exc)
            self._respond(403, f"refused: {exc}\n".encode())
            return
        except Exception as exc:  # upstream failure, not a policy decision
            self.log_message('ERROR "%s" %s', target, exc)
            self._respond(502, f"upstream error: {exc}\n".encode())
            return

        self.log_message('FETCH "%s" -> %s %s %d bytes',
                         target, final_url, status, len(body))
        self._respond(status, body,
                      headers.get("Content-Type", "application/octet-stream"))

    def _reject_method(self):
        self._respond(405, b"GET only\n")

    do_POST = do_PUT = do_DELETE = do_PATCH = _reject_method


def selfcheck():
    """Validation-only checks. No network required, so this runs anywhere."""
    for bad, why in [
        ("file:///etc/passwd", "scheme"),
        ("ftp://example.com/x", "scheme"),
        ("https://localhost/", "loopback"),
        ("https://127.0.0.1/", "loopback"),
        ("https://192.168.1.123/", "private"),
        ("https://169.254.169.254/latest/meta-data/", "link-local"),
        ("https://[::1]/", "loopback"),
        ("https:///nohost", "no host"),
    ]:
        try:
            validate(bad)
        except Refused:
            continue
        raise AssertionError(f"should have refused ({why}): {bad}")

    # A name that resolves publicly must pass. Skipped without DNS.
    try:
        validate("https://example.com/")
    except Refused as exc:
        if "cannot resolve" not in str(exc):
            raise AssertionError(f"public URL wrongly refused: {exc}") from exc
        print("selfcheck: no DNS, skipped the positive case")

    print("selfcheck: ok")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8090)
    parser.add_argument("--selfcheck", action="store_true")
    args = parser.parse_args()

    if args.selfcheck:
        selfcheck()
        return

    server = ThreadingHTTPServer((args.host, args.port), Handler)
    print(f"fetchsvc listening on {args.host}:{args.port}", flush=True)
    server.serve_forever()


if __name__ == "__main__":
    main()
