#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# Boot and tear down the sandbox fetch service. Deliberately not a service:
# it lets a sandbox read arbitrary public URLs, so it should run only while a
# research task needs it.
#
#   ./fetchsvc.sh build      build the image
#   ./fetchsvc.sh up         start it
#   ./fetchsvc.sh down       stop and remove it
#   ./fetchsvc.sh status     running? on what address?
#   ./fetchsvc.sh running    exit 0 if running (for scripts)
#   ./fetchsvc.sh logs       follow the per-request audit log
#   ./fetchsvc.sh check      exercise it from the host
#
# Override with env vars:
#   FETCHSVC_NETWORK   podman network      (default: sandbox-net)
#   FETCHSVC_SUBNET    subnet if created   (default: 172.30.0.0/24)
#   FETCHSVC_IP        fixed address       (default: 172.30.0.21)
#   FETCHSVC_PORT      listen port         (default: 8090)
#
# A sandbox has one interface (10.200.0.2/24) and one route (default via
# 10.200.0.1), so it cannot reach FETCHSVC_IP directly — only through
# OpenShell's proxy, which requires the address to be named in its policy.
# Under rootless podman the host cannot reach that address either, hence the
# published loopback port used by `check`.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

NAME="sandbox-fetchsvc"
IMAGE="sandbox-fetchsvc:latest"
NETWORK="${FETCHSVC_NETWORK:-sandbox-net}"
SUBNET="${FETCHSVC_SUBNET:-172.30.0.0/24}"
IP="${FETCHSVC_IP:-172.30.0.21}"
PORT="${FETCHSVC_PORT:-8090}"
LOGDIR="${FETCHSVC_LOGDIR:-${SCRIPT_DIR}/.tmp-fetchsvc}"

case "${1:-}" in
    build)
        podman build -t "$IMAGE" "$SCRIPT_DIR"
        ;;
    up)
        if ! podman network exists "$NETWORK"; then
            echo "creating podman network ${NETWORK} (${SUBNET})" >&2
            podman network create --subnet "$SUBNET" "$NETWORK" >/dev/null
        fi
        if podman container exists "$NAME"; then
            echo "already exists — run '$0 down' first" >&2
            exit 1
        fi
        mkdir -p "$LOGDIR"
        podman run -d --name "$NAME" \
            --network "${NETWORK}:ip=${IP}" \
            -p "127.0.0.1:${PORT}:${PORT}" \
            --restart no \
            "$IMAGE" >/dev/null

        # A container that exits immediately still leaves `podman run`
        # successful, so "up" would otherwise report a dead service as started.
        sleep 1
        if ! podman container inspect "$NAME" --format '{{.State.Running}}' | grep -q true; then
            echo "error: service exited on startup:" >&2
            podman logs "$NAME" 2>&1 | tail -10 >&2
            exit 1
        fi

        echo "up at ${IP}:${PORT}"
        echo
        echo "Verify from the host:  $0 check"
        echo "Policy must name ${IP}:${PORT} with protocol: rest — without it,"
        echo "the sandbox gets 403 on anything but a plain absolute-URI GET."
        ;;
    down)
        podman rm -f "$NAME" >/dev/null 2>&1 || true
        echo "down"
        ;;
    running)
        # Exit status only, for scripts. `status` is for humans.
        podman container inspect "$NAME" --format '{{.State.Running}}' 2>/dev/null \
            | grep -q true
        ;;
    status)
        if podman container exists "$NAME"; then
            podman ps --filter "name=${NAME}" \
                --format '{{.Names}}\t{{.Status}}\t{{.Networks}}'
            echo "address: ${IP}:${PORT}  (host-testable at 127.0.0.1:${PORT})"
        else
            echo "not running"
        fi
        ;;
    logs)
        podman logs -f "$NAME"
        ;;
    check)
        base="http://127.0.0.1:${PORT}"
        printf '%-34s ' "healthz"
        curl -s -o /dev/null -w '%{http_code}\n' --max-time 10 "${base}/healthz"
        printf '%-34s ' "fetch https://example.com/"
        curl -s -o /dev/null -w '%{http_code}\n' --max-time 20 \
            "${base}/fetch?url=https%3A%2F%2Fexample.com%2F"
        printf '%-34s ' "refuse private address"
        curl -s -o /dev/null -w '%{http_code}\n' --max-time 10 \
            "${base}/fetch?url=http%3A%2F%2F192.168.1.123%2F"
        echo "(expect 200, 200, 403)"
        ;;
    *)
        sed -n '2,26p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
        exit 1
        ;;
esac
