#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 4.6)
#
# Fetch open PRs for a GitHub repo and output compact JSON.
# Bot PRs get title only. Human PRs get cleaned summary text.
# Cross-references extracted automatically.
#
# Usage: format-open-prs.py <org/repo> [limit]

import json
import re
import subprocess
import sys

BOT_BRANCH_RE = re.compile(
    r"^(renovate/|dependabot/|konflux/|mintmaker/|snyk-|release-please/)",
    re.IGNORECASE,
)
BOT_AUTHOR_RE = re.compile(r"\[bot\]$", re.IGNORECASE)

PR_REF_RE = re.compile(r"#(\d+)")
JIRA_RE = re.compile(r"([a-zA-Z]+-\d+)")


def is_bot(pr):
    branch = pr.get("headRefName", "")
    author = pr.get("author", {}).get("login", "")
    return bool(BOT_BRANCH_RE.match(branch) or BOT_AUTHOR_RE.search(author))


def extract_refs(pr, all_numbers):
    text = pr.get("title", "") + "\n" + (pr.get("body", "") or "")
    pr_refs = {int(m) for m in PR_REF_RE.findall(text)} & all_numbers
    pr_refs.discard(pr["number"])
    jira_refs = {r.upper() for r in JIRA_RE.findall(text)}
    return sorted(pr_refs), sorted(jira_refs)


def main():
    if len(sys.argv) < 2:
        print("Usage: format-open-prs.py <org/repo>", file=sys.stderr)
        sys.exit(1)

    repo = sys.argv[1]
    limit = sys.argv[2] if len(sys.argv) > 2 else "100"
    fields = "number,headRefName,baseRefName,title,body,author,labels,files,mergeStateStatus"

    print(f"  fetching open PRs for {repo} (limit {limit})...", file=sys.stderr)
    result = subprocess.run(
        ["gh", "pr", "list", "--repo", repo, "--state", "open", "--limit", limit,
         "--json", fields],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        # Exit non-zero so the caller can tell "the fetch failed" from "this
        # repo has no open PRs" — the second is a fact worth writing down.
        print(f"  warning: gh pr list failed for {repo}: {result.stderr.strip()}",
              file=sys.stderr)
        sys.exit(1)

    prs = json.loads(result.stdout)
    if not prs:
        print("  0 open PRs", file=sys.stderr)
        json.dump({"prs": []}, sys.stdout, indent=2)
        print()
        return
    print(f"  {len(prs)} open PRs", file=sys.stderr)

    all_numbers = {p["number"] for p in prs}
    human_prs = [p for p in prs if not is_bot(p)]
    bot_prs = [p for p in prs if is_bot(p)]

    output = {"prs": [], "bot_prs": [], "cross_refs": []}

    for p in sorted(human_prs, key=lambda x: x["number"]):
        pr_refs, jira_refs = extract_refs(p, all_numbers)
        files = [f["path"] for f in p.get("files", []) if "path" in f]
        labels = [l["name"] for l in p.get("labels", [])]
        entry = {
            "number": p["number"],
            "branch": p["headRefName"],
            "base": p.get("baseRefName", ""),
            "title": p["title"],
            "body": p.get("body", ""),
            "merge_state": p.get("mergeStateStatus", ""),
            "files": files,
        }
        if labels:
            entry["labels"] = labels
        if pr_refs:
            entry["related_prs"] = pr_refs
        if jira_refs:
            entry["jira_keys"] = jira_refs
        output["prs"].append(entry)

        if pr_refs or jira_refs:
            output["cross_refs"].append({
                "number": p["number"],
                "related_prs": pr_refs or None,
                "jira_keys": jira_refs or None,
            })

    for p in sorted(bot_prs, key=lambda x: x["number"]):
        output["bot_prs"].append({
            "number": p["number"],
            "title": p["title"],
            "author": p.get("author", {}).get("login", "bot"),
        })

    if not output["cross_refs"]:
        del output["cross_refs"]
    if not output["bot_prs"]:
        del output["bot_prs"]

    print(f"  {len(human_prs)} PRs, {len(bot_prs)} bot PRs", file=sys.stderr)
    json.dump(output, sys.stdout, indent=2)
    print()


if __name__ == "__main__":
    main()
