#!/bin/bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Generate pr-context.md and jira-context.md for each PR-based repo.
# Thin wrapper — delegates to generate_repo_context() in lib.sh.
#
# Usage: generate-pr-context.sh <sandbox-dir> [profile]
#
# Requires: gh CLI, jq, curl
# Env vars: JIRA_USERNAME, JIRA_TOKEN (for Jira lookups)

set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <sandbox-dir> [profile]" >&2
    exit 1
fi

SANDBOX_DIR="$1"
PROFILE="${2:-}"
MANIFEST="${SANDBOX_DIR}/manifest.json"

if [[ ! -f "$MANIFEST" ]]; then
    echo "no manifest at ${MANIFEST}, skipping pr-context" >&2
    exit 0
fi

source "$(dirname "$0")/lib.sh"

for repo_name in $(jq -r '.repos | keys[]' "$MANIFEST"); do
    generate_repo_context "$SANDBOX_DIR" "$repo_name" "$PROFILE"
done
