#!/bin/bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Generate pr-context.md for each PR-based repo in a sandbox manifest.
# Fetches GitHub PR metadata and linked Jira issue context.
#
# Usage: generate-pr-context.sh <sandbox-dir>
#
# Requires: gh CLI, jq, curl
# Env vars: JIRA_USERNAME, JIRA_TOKEN (for Jira lookups)

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <sandbox-dir>" >&2
    exit 1
fi

SANDBOX_DIR="$1"
MANIFEST="${SANDBOX_DIR}/manifest.json"

if [[ ! -f "$MANIFEST" ]]; then
    echo "no manifest at ${MANIFEST}, skipping pr-context" >&2
    exit 0
fi

JIRA_BASE="https://redhat.atlassian.net"
JIRA_AC_FIELD=""

jira_auth() {
    local email="${JIRA_USERNAME:-${JIRA_EMAIL:-}}"
    local token="${JIRA_TOKEN:-${JIRA_API_TOKEN:-}}"
    if [[ -z "$email" || -z "$token" ]]; then
        return 1
    fi
    printf '%s' "$email:$token" | base64 -w0
}

jira_get() {
    local path="$1" auth="$2"
    curl -s -H "Authorization: Basic ${auth}" -H "Accept: application/json" \
        "${JIRA_BASE}${path}"
}

discover_ac_field() {
    local auth="$1"
    if [[ -n "$JIRA_AC_FIELD" ]]; then
        echo "$JIRA_AC_FIELD"
        return
    fi
    JIRA_AC_FIELD=$(jira_get "/rest/api/3/field" "$auth" | \
        jq -r '.[] | select(.name == "Acceptance Criteria") | .id' | head -1)
    echo "$JIRA_AC_FIELD"
}

render_adf_to_text() {
    # Minimal ADF (Atlassian Document Format) to plain text
    python3 -c "
import json, sys

def walk(node):
    if isinstance(node, str):
        return node
    if isinstance(node, dict):
        t = node.get('type', '')
        text = node.get('text', '')
        if text:
            return text
        parts = [walk(c) for c in node.get('content', [])]
        joined = ''.join(parts)
        if t == 'paragraph':
            return joined + '\n\n'
        if t == 'bulletList':
            return joined
        if t == 'orderedList':
            return joined
        if t == 'listItem':
            return '- ' + joined.strip() + '\n'
        if t == 'heading':
            level = node.get('attrs', {}).get('level', 1)
            return '#' * level + ' ' + joined.strip() + '\n\n'
        if t == 'codeBlock':
            return '\`\`\`\n' + joined + '\`\`\`\n\n'
        return joined
    if isinstance(node, list):
        return ''.join(walk(c) for c in node)
    return ''

data = json.load(sys.stdin)
if isinstance(data, dict) and 'content' in data:
    print(walk(data).strip())
elif isinstance(data, str):
    print(data)
else:
    print(json.dumps(data, indent=2))
" 2>/dev/null
}

fetch_jira_context() {
    local key="$1" auth="$2"
    local ac_field
    ac_field=$(discover_ac_field "$auth")

    local fields="summary,description,status,issuetype"
    if [[ -n "$ac_field" ]]; then
        fields="${fields},${ac_field}"
    fi

    local issue
    issue=$(jira_get "/rest/api/3/issue/${key}?fields=${fields}" "$auth")
    if [[ -z "$issue" ]] || echo "$issue" | jq -e '.errorMessages' &>/dev/null; then
        echo "  warning: could not fetch Jira ${key}" >&2
        return
    fi

    local summary status issue_type
    summary=$(echo "$issue" | jq -r '.fields.summary // ""')
    status=$(echo "$issue" | jq -r '.fields.status.name // ""')
    issue_type=$(echo "$issue" | jq -r '.fields.issuetype.name // ""')

    echo "### ${key}: ${summary}"
    echo ""
    echo "**Type:** ${issue_type} | **Status:** ${status}"
    echo ""

    # Description
    local desc
    desc=$(echo "$issue" | jq '.fields.description')
    if [[ "$desc" != "null" ]]; then
        echo "#### Description"
        echo ""
        echo "$desc" | render_adf_to_text
        echo ""
    fi

    # Acceptance Criteria
    if [[ -n "$ac_field" ]]; then
        local ac
        ac=$(echo "$issue" | jq ".fields.${ac_field}")
        if [[ "$ac" != "null" && "$ac" != '""' ]]; then
            echo "#### Acceptance Criteria"
            echo ""
            echo "$ac" | render_adf_to_text
            echo ""
        fi
    fi
}

# Process each repo in manifest
jq -r '.repos | to_entries[] | [.key, .value.url, .value.ref] | @tsv' "$MANIFEST" | \
while IFS=$'\t' read -r repo_name repo_url repo_ref; do
    # Only PR refs on GitHub repos
    if [[ ! "$repo_ref" =~ ^pr/([0-9]+)$ ]]; then
        continue
    fi
    pr_num="${BASH_REMATCH[1]}"
    if [[ ! "$repo_url" =~ github\.com ]]; then
        continue
    fi

    # Extract org/repo from URL
    gh_repo=$(echo "$repo_url" | sed -E 's|.*github\.com[:/]||; s|\.git/?$||')

    echo "  generating pr-context for ${repo_name} PR #${pr_num}..." >&2

    # Fetch PR metadata
    pr_json=$(gh pr view "$pr_num" --repo "$gh_repo" \
        --json number,title,body,headRefName,baseRefName,labels,assignees 2>/dev/null) || {
        echo "  warning: gh pr view failed for ${gh_repo}#${pr_num}" >&2
        continue
    }

    pr_title=$(echo "$pr_json" | jq -r '.title // ""')
    pr_branch=$(echo "$pr_json" | jq -r '.headRefName // ""')
    pr_base=$(echo "$pr_json" | jq -r '.baseRefName // ""')
    pr_body=$(echo "$pr_json" | jq -r '.body // ""')
    pr_labels=$(echo "$pr_json" | jq -r '[.labels[].name] | join(", ") // ""')
    pr_assignees=$(echo "$pr_json" | jq -r '[.assignees[].login] | join(", ") // ""')

    # Build pr-context.md
    pr_context="${SANDBOX_DIR}/${repo_name}/pr-context.md"
    {
        echo "# PR #${pr_num}: ${pr_title}"
        echo ""
        echo "**Branch:** ${pr_branch}"
        echo "**Base:** ${pr_base}"
        echo "**Labels:** ${pr_labels}"
        echo "**Assignees:** ${pr_assignees}"
        echo ""
        echo "Diff against base: \`git diff origin/${pr_base}...HEAD\`"
        echo ""
        echo "# PR Description"
        echo ""
        echo "$pr_body"
        echo ""
    } > "$pr_context"

    # Extract Jira keys from title, branch, and body
    jira_keys=$(printf '%s\n%s\n%s' "$pr_title" "$pr_branch" "$pr_body" | \
        grep -ioE '(ANSTRAT|AAP)-[0-9]+' | tr '[:lower:]' '[:upper:]' | sort -u || true)

    echo "# Jira Context" >> "$pr_context"
    echo "" >> "$pr_context"

    if [[ -n "$jira_keys" ]]; then
        auth=$(jira_auth) || {
            echo "  warning: JIRA_USERNAME/JIRA_TOKEN not set, skipping Jira context" >&2
            echo "No Jira context available (credentials not set)." >> "$pr_context"
            continue
        }

        for key in $jira_keys; do
            echo "  fetching Jira ${key}..." >&2
            fetch_jira_context "$key" "$auth" >> "$pr_context"
        done
    else
        echo "No Jira keys found in PR title, branch, or description." >> "$pr_context"
    fi

    echo "  wrote ${pr_context}" >&2
done
