#!/bin/bash
# Generated By: Claude Code (Claude Opus 4.6)
# Shared functions for sandbox scripts.

# ---------------------------------------------------------------------------
# Jira helpers (shared by scode and generate-pr-context.sh)
# ---------------------------------------------------------------------------

JIRA_BASE="${JIRA_BASE:-https://redhat.atlassian.net}"
_JIRA_AC_FIELD=""

jira_auth() {
    local email="${JIRA_USERNAME:-${JIRA_EMAIL:-}}"
    local token="${JIRA_TOKEN:-${JIRA_API_TOKEN:-}}"
    if [[ -z "$email" || -z "$token" ]]; then
        return 1
    fi
    printf '%s' "$email:$token" | base64 -w0
}

jira_get() {
    local path="$1" auth="$2"
    curl -s -H "Authorization: Basic ${auth}" -H "Accept: application/json" \
        "${JIRA_BASE}${path}"
}

discover_ac_field() {
    local auth="$1"
    if [[ -n "$_JIRA_AC_FIELD" ]]; then
        echo "$_JIRA_AC_FIELD"
        return
    fi
    _JIRA_AC_FIELD=$(jira_get "/rest/api/3/field" "$auth" | \
        jq -r '.[] | select(.name == "Acceptance Criteria") | .id' | head -1)
    echo "$_JIRA_AC_FIELD"
}

render_adf_to_text() {
    python3 -c "
import json, sys

def walk(node):
    if isinstance(node, str):
        return node
    if isinstance(node, dict):
        t = node.get('type', '')
        text = node.get('text', '')
        if text:
            return text
        parts = [walk(c) for c in node.get('content', [])]
        joined = ''.join(parts)
        if t == 'paragraph':
            return joined + '\n\n'
        if t == 'bulletList':
            return joined
        if t == 'orderedList':
            return joined
        if t == 'listItem':
            return '- ' + joined.strip() + '\n'
        if t == 'heading':
            level = node.get('attrs', {}).get('level', 1)
            return '#' * level + ' ' + joined.strip() + '\n\n'
        if t == 'codeBlock':
            return '\`\`\`\n' + joined + '\`\`\`\n\n'
        return joined
    if isinstance(node, list):
        return ''.join(walk(c) for c in node)
    return ''

data = json.load(sys.stdin)
if isinstance(data, dict) and 'content' in data:
    print(walk(data).strip())
elif isinstance(data, str):
    print(data)
else:
    print(json.dumps(data, indent=2))
" 2>/dev/null
}

fetch_jira_context() {
    local key="$1" auth="$2"
    local ac_field
    ac_field=$(discover_ac_field "$auth")

    local fields="summary,description,status,issuetype"
    if [[ -n "$ac_field" ]]; then
        fields="${fields},${ac_field}"
    fi

    local issue
    issue=$(jira_get "/rest/api/3/issue/${key}?fields=${fields}" "$auth")
    if [[ -z "$issue" ]] || echo "$issue" | jq -e '.errorMessages' &>/dev/null; then
        echo "  warning: could not fetch Jira ${key}" >&2
        return
    fi

    local summary status issue_type
    summary=$(echo "$issue" | jq -r '.fields.summary // ""')
    status=$(echo "$issue" | jq -r '.fields.status.name // ""')
    issue_type=$(echo "$issue" | jq -r '.fields.issuetype.name // ""')

    echo "### ${key}: ${summary}"
    echo ""
    echo "**Type:** ${issue_type} | **Status:** ${status}"
    echo ""

    local desc
    desc=$(echo "$issue" | jq '.fields.description')
    if [[ "$desc" != "null" ]]; then
        echo "#### Description"
        echo ""
        echo "$desc" | render_adf_to_text
        echo ""
    fi

    if [[ -n "$ac_field" ]]; then
        local ac
        ac=$(echo "$issue" | jq ".fields.${ac_field}")
        if [[ "$ac" != "null" && "$ac" != '""' ]]; then
            echo "#### Acceptance Criteria"
            echo ""
            echo "$ac" | render_adf_to_text
            echo ""
        fi
    fi
}

# ---------------------------------------------------------------------------
# Per-repo context generation (pr-context.md + jira-context.md)
# ---------------------------------------------------------------------------

generate_repo_context() {
    local sandbox_dir="$1" repo_name="$2" profile="${3:-}"
    local repo_dir="${sandbox_dir}/${repo_name}"
    local manifest="${sandbox_dir}/manifest.json"

    [[ -d "${repo_dir}/.git" ]] || return 0
    [[ -f "$manifest" ]] || return 0

    local repo_url
    repo_url=$(jq -r --arg r "$repo_name" '.repos[$r].url // ""' "$manifest")
    [[ "$repo_url" =~ github\.com ]] || return 0

    local gh_repo
    gh_repo=$(echo "$repo_url" | sed -E 's|.*github\.com[:/]||; s|\.git/?$||')

    # Detect PR from current branch (git state is source of truth, not manifest ref)
    local branch
    branch=$(git -C "$repo_dir" rev-parse --abbrev-ref HEAD 2>/dev/null) || return 0

    local pr_json
    pr_json=$(gh pr view "$branch" --repo "$gh_repo" \
        --json number,title,body,headRefName,baseRefName,labels,assignees 2>/dev/null) || {
        # Not a PR branch — clean up stale context files
        rm -f "${repo_dir}/pr-context.md" "${repo_dir}/jira-context.md"
        return 0
    }

    local pr_num
    pr_num=$(echo "$pr_json" | jq -r '.number')

    # Update manifest ref to match actual checkout
    jq --arg r "$repo_name" --arg ref "pr/${pr_num}" \
        '.repos[$r].ref = $ref' "$manifest" > "${manifest}.tmp" && mv "${manifest}.tmp" "$manifest"

    echo "  generating context for ${repo_name} PR #${pr_num}..." >&2

    local pr_title pr_branch pr_base pr_body pr_labels pr_assignees
    pr_title=$(echo "$pr_json" | jq -r '.title // ""')
    pr_branch=$(echo "$pr_json" | jq -r '.headRefName // ""')
    pr_base=$(echo "$pr_json" | jq -r '.baseRefName // ""')
    pr_body=$(echo "$pr_json" | jq -r '.body // ""')
    pr_labels=$(echo "$pr_json" | jq -r '[.labels[].name] | join(", ") // ""')
    pr_assignees=$(echo "$pr_json" | jq -r '[.assignees[].login] | join(", ") // ""')

    # pr-context.md — PR metadata only
    {
        echo "# PR #${pr_num}: ${pr_title}"
        echo ""
        echo "**Branch:** ${pr_branch}"
        echo "**Base:** ${pr_base}"
        echo "**Labels:** ${pr_labels}"
        echo "**Assignees:** ${pr_assignees}"
        echo ""
        echo "Diff against base: \`git diff origin/${pr_base}...HEAD\`"
        echo ""
        echo "# PR Description"
        echo ""
        echo "$pr_body"
    } > "${sandbox_dir}/${repo_name}/pr-context.md"
    echo "  wrote pr-context.md" >&2

    # jira-context.md — Jira issue context (skip for personal profile)
    [[ "$profile" == "personal" ]] && return 0

    local jira_keys
    jira_keys=$(printf '%s\n%s\n%s' "$pr_title" "$pr_branch" "$pr_body" | \
        grep -ioE '(ANSTRAT|AAP)-[0-9]+' | tr '[:lower:]' '[:upper:]' | sort -u || true)

    [[ -n "$jira_keys" ]] || return 0

    local auth
    auth=$(jira_auth) || {
        echo "  warning: JIRA_USERNAME/JIRA_TOKEN not set, skipping Jira context" >&2
        return 0
    }

    {
        echo "# Jira Context"
        echo ""
        for key in $jira_keys; do
            echo "  fetching Jira ${key}..." >&2
            fetch_jira_context "$key" "$auth"
        done
    } > "${sandbox_dir}/${repo_name}/jira-context.md"
    echo "  wrote jira-context.md" >&2
}

# ---------------------------------------------------------------------------
# Repo visibility helpers
# ---------------------------------------------------------------------------

# Check if repo is private via gh CLI. Returns 0 if private, 1 if public.
is_private_repo() {
    local url="${1%/}"
    local private
    private=$(gh repo view "$url" --json isPrivate -q '.isPrivate' 2>/dev/null) || return 1
    [[ "$private" == "true" ]]
}

# Warn and confirm if personal profile is adding a private repo
guard_private_repo() {
    local url="$1"
    if [[ "${SANDBOX_PROFILE:-}" != "personal" ]]; then
        return 0
    fi
    if is_private_repo "$url"; then
        local repo_name
        repo_name=$(basename "$url" .git)
        echo "" >&2
        echo "WARNING: '${repo_name}' is a private repo." >&2
        echo "Personal sandboxes should only use public repos." >&2
        echo "" >&2
        read -rp "Continue anyway? [y/N]: " confirm
        if [[ "${confirm:-N}" != [yY] ]]; then
            echo "aborted." >&2
            exit 1
        fi
    fi
}
