#!/bin/bash
# Generated By: Claude Code (Claude Opus 4.6)
# Shared functions for sandbox scripts.

# Check if repo is private via gh CLI. Returns 0 if private, 1 if public.
is_private_repo() {
    local url="${1%/}"
    local private
    private=$(gh repo view "$url" --json isPrivate -q '.isPrivate' 2>/dev/null) || return 1
    [[ "$private" == "true" ]]
}

# Warn and confirm if personal profile is adding a private repo
guard_private_repo() {
    local url="$1"
    if [[ "${SANDBOX_PROFILE:-}" != "personal" ]]; then
        return 0
    fi
    if is_private_repo "$url"; then
        local repo_name
        repo_name=$(basename "$url" .git)
        echo "" >&2
        echo "WARNING: '${repo_name}' is a private repo." >&2
        echo "Personal sandboxes should only use public repos." >&2
        echo "" >&2
        read -rp "Continue anyway? [y/N]: " confirm
        if [[ "${confirm:-N}" != [yY] ]]; then
            echo "aborted." >&2
            exit 1
        fi
    fi
}
