#!/bin/bash
# Generated By: Claude Code (Claude Opus 4.6)
# Shared functions for sandbox scripts.

# ---------------------------------------------------------------------------
# Jira helpers (shared by scode and generate-pr-context.sh)
# ---------------------------------------------------------------------------

JIRA_BASE="${JIRA_BASE:-https://redhat.atlassian.net}"
_JIRA_AC_FIELD=""

jira_auth() {
    local email="${JIRA_USERNAME:-${JIRA_EMAIL:-}}"
    local token="${JIRA_TOKEN:-${JIRA_API_TOKEN:-}}"
    if [[ -z "$email" || -z "$token" ]]; then
        return 1
    fi
    printf '%s' "$email:$token" | base64 -w0
}

jira_get() {
    local path="$1" auth="$2"
    curl -s -H "Authorization: Basic ${auth}" -H "Accept: application/json" \
        "${JIRA_BASE}${path}"
}

discover_ac_field() {
    local auth="$1"
    if [[ -n "$_JIRA_AC_FIELD" ]]; then
        echo "$_JIRA_AC_FIELD"
        return
    fi
    _JIRA_AC_FIELD=$(jira_get "/rest/api/3/field" "$auth" | \
        jq -r '.[] | select(.name == "Acceptance Criteria") | .id' | head -1)
    echo "$_JIRA_AC_FIELD"
}

render_adf_to_text() {
    python3 -c "
import json, sys

def walk(node):
    if isinstance(node, str):
        return node
    if isinstance(node, dict):
        t = node.get('type', '')
        text = node.get('text', '')
        if text:
            return text
        parts = [walk(c) for c in node.get('content', [])]
        joined = ''.join(parts)
        if t == 'paragraph':
            return joined + '\n\n'
        if t == 'bulletList':
            return joined
        if t == 'orderedList':
            return joined
        if t == 'listItem':
            return '- ' + joined.strip() + '\n'
        if t == 'heading':
            level = node.get('attrs', {}).get('level', 1)
            return '#' * level + ' ' + joined.strip() + '\n\n'
        if t == 'codeBlock':
            return '\`\`\`\n' + joined + '\`\`\`\n\n'
        return joined
    if isinstance(node, list):
        return ''.join(walk(c) for c in node)
    return ''

data = json.load(sys.stdin)
if isinstance(data, dict) and 'content' in data:
    print(walk(data).strip())
elif isinstance(data, str):
    print(data)
else:
    print(json.dumps(data, indent=2))
" 2>/dev/null
}

fetch_jira_context() {
    local key="$1" auth="$2"
    local ac_field
    ac_field=$(discover_ac_field "$auth")

    local fields="summary,description,status,issuetype"
    if [[ -n "$ac_field" ]]; then
        fields="${fields},${ac_field}"
    fi

    local issue
    issue=$(jira_get "/rest/api/3/issue/${key}?fields=${fields}" "$auth")
    if [[ -z "$issue" ]] || echo "$issue" | jq -e '.errorMessages' &>/dev/null; then
        echo "  warning: could not fetch Jira ${key}" >&2
        return
    fi

    local summary status issue_type
    summary=$(echo "$issue" | jq -r '.fields.summary // ""')
    status=$(echo "$issue" | jq -r '.fields.status.name // ""')
    issue_type=$(echo "$issue" | jq -r '.fields.issuetype.name // ""')

    echo "### ${key}: ${summary}"
    echo ""
    echo "**Type:** ${issue_type} | **Status:** ${status}"
    echo ""

    local desc
    desc=$(echo "$issue" | jq '.fields.description')
    if [[ "$desc" != "null" ]]; then
        echo "#### Description"
        echo ""
        echo "$desc" | render_adf_to_text
        echo ""
    fi

    if [[ -n "$ac_field" ]]; then
        local ac
        ac=$(echo "$issue" | jq ".fields.${ac_field}")
        if [[ "$ac" != "null" && "$ac" != '""' ]]; then
            echo "#### Acceptance Criteria"
            echo ""
            echo "$ac" | render_adf_to_text
            echo ""
        fi
    fi
}

_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

format_open_prs() {
    python3 "${_LIB_DIR}/format-open-prs.py" "$@"
}

# Fetch into a file rather than redirecting the whole retry loop: `>` truncates
# per attempt, so a partial write from a failed attempt cannot end up prepended
# to a good one.
fetch_open_prs() {
    local gh_repo="$1" dest="$2"
    format_open_prs "$gh_repo" > "$dest"
}

# ---------------------------------------------------------------------------
# PR checkout + per-repo context generation (pr-context.md + jira-context.md)
# ---------------------------------------------------------------------------

# GitHub's API fails often enough that a single attempt is not a signal. Two
# short retries turn most 502s and connection resets into a normal run.
GH_RETRY_ATTEMPTS="${GH_RETRY_ATTEMPTS:-3}"
GH_RETRY_DELAY="${GH_RETRY_DELAY:-2}"

# Run a command, retrying transient failures with a doubling delay.
# Only for calls whose failure is always an error — never for one where
# "not found" is an expected answer, or every miss costs the full backoff.
gh_retry() {
    local attempt=1 delay="$GH_RETRY_DELAY"
    while :; do
        "$@" && return 0
        (( attempt++ >= GH_RETRY_ATTEMPTS )) && return 1
        echo "  gh call failed, retrying in ${delay}s (attempt ${attempt}/${GH_RETRY_ATTEMPTS})..." >&2
        sleep "$delay"
        delay=$(( delay * 2 ))
    done
}

# Fetch a PR as JSON on stdout.
#   0 — JSON on stdout
#   2 — gh answered, and there is no such PR (final; do not retry, do not
#       treat as an outage)
#   1 — gh could not answer after retries; the caller knows nothing new
#
# The split matters because `gh pr view` exits 1 for both, and the caller
# deletes stale context files on "no PR". Conflating them means a 502 during
# an upload destroys correct pr-context.md and jira-context.md — and
# jira-context.md costs Jira calls to rebuild.
gh_pr_view_json() {
    local pr_arg="$1" gh_repo="$2"
    local attempt=1 delay="$GH_RETRY_DELAY" out err
    err="$(mktemp)"
    while :; do
        if out=$(gh pr view "$pr_arg" --repo "$gh_repo" \
            --json number,title,body,headRefName,baseRefName,labels,assignees 2>"$err"); then
            rm -f "$err"
            printf '%s' "$out"
            return 0
        fi
        case "$(cat "$err")" in
            *"no pull requests found"*|*"no open pull requests"*|*"Could not resolve"*)
                rm -f "$err"
                return 2
                ;;
        esac
        if (( attempt++ >= GH_RETRY_ATTEMPTS )); then
            echo "  warning: gh pr view failed: $(head -1 "$err")" >&2
            rm -f "$err"
            return 1
        fi
        echo "  gh pr view failed, retrying in ${delay}s (attempt ${attempt}/${GH_RETRY_ATTEMPTS})..." >&2
        sleep "$delay"
        delay=$(( delay * 2 ))
    done
}

# Check out a PR as a real branch. `git fetch origin pull/N/head:pr-N` produced
# a branch named pr-N with no upstream at all — fine to work in, but anything
# reading @{upstream} (monitoring, prompt, status tooling) sees a local-only
# branch. `gh pr checkout` names the branch after the PR head ref and writes
# branch.<name>.{remote,merge}, so the checkout looks like any other branch.
#
# The fallback keeps the old refs/pull fetch: gh needs auth and network, and a
# create that silently stays on the default branch is worse than a branch
# without tracking. generate_repo_context() reads both spellings.
checkout_pr() {
    local target="$1" pr_num="$2"

    if [[ "${DRYRUN:-false}" == true ]]; then
        echo "[dryrun]: (cd ${target} && gh pr checkout ${pr_num})" >&2
        return 0
    fi

    # cd, not -C: gh has no repo-directory flag, and --repo names the GitHub
    # repo, not the clone to check out into.
    if ( cd "$target" && gh_retry gh pr checkout "$pr_num" ); then
        return 0
    fi

    echo "  warning: gh pr checkout ${pr_num} failed — falling back to a" >&2
    echo "    refs/pull fetch, which leaves the branch without an upstream" >&2
    git -C "$target" fetch origin "pull/${pr_num}/head:pr-${pr_num}"
    git -C "$target" checkout "pr-${pr_num}"
}

# How long an open-prs.json is trusted before the PR list is fetched again.
# `gh pr list --json files` is the slowest call in an upload and it runs once
# per repo, so a multi-repo `--upload` paid for a full refetch every time even
# when nothing could plausibly have changed. An hour is short enough that a PR
# opened this morning shows up, long enough that repeated uploads are free.
# Set OPEN_PRS_TTL_MINUTES=0 to force a fetch.
OPEN_PRS_TTL_MINUTES="${OPEN_PRS_TTL_MINUTES:-60}"

generate_repo_context() {
    local sandbox_dir="$1" repo_name="$2" profile="${3:-}"
    local repo_dir="${sandbox_dir}/${repo_name}"
    local manifest="${sandbox_dir}/manifest.json"

    [[ -d "${repo_dir}/.git" ]] || return 0
    [[ -f "$manifest" ]] || return 0

    local repo_url
    repo_url=$(jq -r --arg r "$repo_name" '.repos[$r].url // ""' "$manifest")
    [[ "$repo_url" =~ github\.com ]] || return 0

    local gh_repo
    gh_repo=$(echo "$repo_url" | sed -E 's|.*github\.com[:/]||; s|\.git/?$||')

    # open-prs.json — all open PRs, compact structured data
    local open_prs="${repo_dir}/open-prs.json"
    # Age in minutes, or "old enough" when the file is missing or unreadable.
    # Not `find -newermt "-N minutes"`: the sandbox image's find is bfs, which
    # takes only absolute ISO timestamps and errors on the relative form — the
    # check would have silently meant "always stale".
    local open_prs_age=999999
    if [[ -f "$open_prs" ]]; then
        open_prs_age=$(( ( $(date +%s) - $(stat -c %Y "$open_prs" 2>/dev/null || echo 0) ) / 60 ))
    fi
    if (( open_prs_age < OPEN_PRS_TTL_MINUTES )); then
        echo "  open-prs.json is ${open_prs_age}m old (< ${OPEN_PRS_TTL_MINUTES}m), skipping PR list fetch" >&2
    elif gh_retry fetch_open_prs "$gh_repo" "${open_prs}.tmp"; then
        # A repo with no open PRs gets `{"prs": []}`, not a missing file: the
        # absence of the file used to mean "none", "gh failed", and "not a
        # GitHub repo" all at once, and a session cannot tell those apart.
        mv "${open_prs}.tmp" "$open_prs"
    else
        # Failed fetch: leave the previous file, mtime and all, so the next
        # upload retries instead of debouncing on a file this run never wrote.
        rm -f "${open_prs}.tmp"
    fi

    # Detect PR from current branch (git state is source of truth, not manifest ref)
    local branch pr_arg
    branch=$(git -C "$repo_dir" rev-parse --abbrev-ref HEAD 2>/dev/null) || return 0
    # A PR checkout is normally a real branch (gh pr checkout), so the name is
    # the head ref and `gh pr view <branch>` resolves it.
    pr_arg="$branch"
    # Legacy and fallback checkouts are named pr-<num>; no such branch exists
    # on the remote, so gh pr view needs the number.
    if [[ "$branch" =~ ^pr-([0-9]+)$ ]]; then
        pr_arg="${BASH_REMATCH[1]}"
    fi
    # A fork PR's head ref lives in the fork, so the branch name does not
    # identify it in the base repo. gh writes refs/pull/<num>/head as the
    # upstream in that case — the number is right there, no guessing.
    local merge_ref
    merge_ref=$(git -C "$repo_dir" config "branch.${branch}.merge" 2>/dev/null || true)
    if [[ "$merge_ref" =~ ^refs/pull/([0-9]+)/head$ ]]; then
        pr_arg="${BASH_REMATCH[1]}"
    fi

    echo "  checking branch '${branch}' for PR..." >&2
    local pr_json rc
    pr_json=$(gh_pr_view_json "$pr_arg" "$gh_repo") || rc=$?
    if [[ -n "${rc:-}" ]]; then
        if (( rc == 2 )); then
            # gh answered: no such PR. Whatever context is here is stale.
            rm -f "${repo_dir}/pr-context.md" "${repo_dir}/jira-context.md"
        else
            # gh could not answer. Deleting here would throw away correct
            # context on a transient API failure, so keep what is on disk.
            echo "  keeping existing PR context for ${repo_name} (gh unreachable)" >&2
        fi
        return 0
    fi

    local pr_num
    pr_num=$(echo "$pr_json" | jq -r '.number')

    # Update manifest ref to match actual checkout
    jq --arg r "$repo_name" --arg ref "pr/${pr_num}" \
        '.repos[$r].ref = $ref' "$manifest" > "${manifest}.tmp" && mv "${manifest}.tmp" "$manifest"

    echo "  generating context for ${repo_name} PR #${pr_num}..." >&2

    local pr_title pr_branch pr_base pr_body pr_labels pr_assignees
    pr_title=$(echo "$pr_json" | jq -r '.title // ""')
    pr_branch=$(echo "$pr_json" | jq -r '.headRefName // ""')
    pr_base=$(echo "$pr_json" | jq -r '.baseRefName // ""')
    pr_body=$(echo "$pr_json" | jq -r '.body // ""')
    pr_labels=$(echo "$pr_json" | jq -r '[.labels[].name] | join(", ") // ""')
    pr_assignees=$(echo "$pr_json" | jq -r '[.assignees[].login] | join(", ") // ""')

    # pr-context.md — PR metadata only
    {
        echo "# PR #${pr_num}: ${pr_title}"
        echo ""
        echo "**Branch:** ${pr_branch}"
        echo "**Base:** ${pr_base}"
        echo "**Labels:** ${pr_labels}"
        echo "**Assignees:** ${pr_assignees}"
        echo ""
        echo "Diff against base: \`git diff origin/${pr_base}...HEAD\`"
        echo ""
        echo "# PR Description"
        echo ""
        echo "$pr_body"
    } > "${sandbox_dir}/${repo_name}/pr-context.md"
    echo "  wrote pr-context.md" >&2

    # jira-context.md — Jira issue context (skip for personal profile)
    [[ "$profile" == "personal" ]] && return 0

    local jira_keys
    jira_keys=$(printf '%s\n%s\n%s' "$pr_title" "$pr_branch" "$pr_body" | \
        grep -oE '[a-zA-Z]+-[0-9]+' | sort -u || true)

    [[ -n "$jira_keys" ]] || return 0

    local auth
    auth=$(jira_auth) || {
        echo "  warning: JIRA_USERNAME/JIRA_TOKEN not set, skipping Jira context" >&2
        return 0
    }

    {
        echo "# Jira Context"
        echo ""
        for key in $jira_keys; do
            echo "  fetching Jira ${key}..." >&2
            fetch_jira_context "$key" "$auth"
        done
    } > "${sandbox_dir}/${repo_name}/jira-context.md"
    echo "  wrote jira-context.md" >&2
}

# ---------------------------------------------------------------------------
# Machine default profile
# ---------------------------------------------------------------------------

# DEFAULT_PROFILE from config/site.env, or empty. sandbox.sh sources site.env
# wholesale and reads the variable directly; scode does not, but needs the
# effective profile for guard_private_repo — a personal-by-default machine
# must still be warned before a private repo goes into a personal sandbox.
# Subshell so the rest of site.env does not leak into the caller.
site_default_profile() {
    local site_env
    site_env="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/config/site.env"
    [[ -f "$site_env" ]] || return 0
    # shellcheck source=/dev/null  # gitignored, per-machine — nothing to follow
    ( set -a; . "$site_env"; echo "${DEFAULT_PROFILE:-}" )
}

# ---------------------------------------------------------------------------
# Repo visibility helpers
# ---------------------------------------------------------------------------

# Check if repo is private via gh CLI. Returns 0 if private, 1 if public.
is_private_repo() {
    local url="${1%/}"
    local private
    private=$(gh repo view "$url" --json isPrivate -q '.isPrivate' 2>/dev/null) || return 1
    [[ "$private" == "true" ]]
}

# ---------------------------------------------------------------------------
# Sandbox manifest (shared by scode and sandbox.sh)
# ---------------------------------------------------------------------------

# Short name for OpenShell (19-char limit from DNS label constraint)
short_name() {
    local hash
    hash=$(printf '%s' "$1" | md5sum | cut -c1-12)
    echo "sb-${hash}"
}

# Write the manifest skeleton — name, openshell name, profile — creating the
# sandbox dir if needed. Idempotent: an existing manifest keeps its repos and
# only has .profile refreshed.
#
# scode calls this before opening VS Code, and sandbox.sh before `openshell
# sandbox create`, because the host prompt reads .profile out of this file.
# Written only by the repo loop, it appears minutes late — after create, the
# credential uploads, and the host clone — and until then every shell in that
# directory shows no profile at all.
init_manifest() {
    local sandbox_dir="$1" sandbox_name="$2" profile="${3:-}"
    local manifest="${sandbox_dir}/manifest.json"

    mkdir -p "$sandbox_dir"

    if [[ ! -f "$manifest" ]]; then
        jq -n \
            --arg name "$sandbox_name" \
            --arg os_name "$(short_name "$sandbox_name")" \
            --arg created "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
            '{name: $name, openshell_name: $os_name, created: $created, repos: {}}' \
            > "${manifest}.tmp"
        mv "${manifest}.tmp" "$manifest"
    fi

    if [[ -n "$profile" ]]; then
        jq --arg profile "$profile" '.profile = $profile' \
            "$manifest" > "${manifest}.tmp"
        mv "${manifest}.tmp" "$manifest"
    fi
}

# Warn and confirm if personal profile is adding a private repo
guard_private_repo() {
    local url="$1"
    if [[ "${SANDBOX_PROFILE:-}" != "personal" ]]; then
        return 0
    fi
    if is_private_repo "$url"; then
        local repo_name
        repo_name=$(basename "$url" .git)
        echo "" >&2
        echo "WARNING: '${repo_name}' is a private repo." >&2
        echo "Personal sandboxes should only use public repos." >&2
        echo "" >&2
        read -rp "Continue anyway? [y/N]: " confirm
        if [[ "${confirm:-N}" != [yY] ]]; then
            echo "aborted." >&2
            exit 1
        fi
    fi
}
