#!/bin/bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Wait for the gateway, then re-mint JWTs and restart all errored sandboxes.
# Used after reboot / gateway restart when sandbox tokens have expired.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

wait_for_gateway() {
    local port="${1:-18080}"
    local timeout="${2:-60}"
    local elapsed=0
    echo "Waiting for gateway on port ${port}..."
    while [[ "${elapsed}" -lt "${timeout}" ]]; do
        if curl -s -m 1 "http://127.0.0.1:${port}/" >/dev/null 2>&1; then
            echo "Gateway ready after ${elapsed}s"
            return 0
        fi
        sleep 2
        elapsed=$((elapsed + 2))
    done
    echo "ERROR: gateway not ready after ${timeout}s"
    return 1
}

wait_for_gateway 18080 60

for name in $(openshell sandbox list 2>/dev/null | awk '/Error/ {print $1}'); do
    echo "Re-minting token for ${name}..."
    python3 "${SCRIPT_DIR}/mint-sandbox-token.py" "$name" &&
        podman stop "openshell-sandbox-${name}" &&
        podman start "openshell-sandbox-${name}"
done
