#!/bin/bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Create and manage OpenShell sandboxes with Claude Code.
# Captures env vars, uploads credentials and ~/.claude/ config,
# clones repos, and starts Claude in auto mode.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Defaults
SANDBOX_NAME=""
CONNECT_NAME=""
DELETE_NAME=""
LIST_MODE=false
GATEWAY=""
POLICY_FILE=""
REPOS=()
EXTRA_ARGS=()

# ---------------------------------------------------------------------------
# Env var groups — add new groups as needed
# ---------------------------------------------------------------------------

ANTHROPIC_VARS=(
    ANTHROPIC_API_KEY
)

VERTEX_VARS=(
    CLAUDE_CODE_USE_VERTEX
    CLOUD_ML_REGION
    ANTHROPIC_VERTEX_PROJECT_ID
    GOOGLE_APPLICATION_CREDENTIALS
    GOOGLE_CLOUD_PROJECT
    CLOUDSDK_CONFIG
)

JIRA_VARS=(
    JIRA_USERNAME
    JIRA_API_TOKEN
    JIRA_TOKEN
    JIRA_URL
    JIRA_CLOUD_ID
)

GITHUB_VARS=(
    GITHUB_TOKEN
    GH_TOKEN
    GITHUB_USER
)

CLAUDE_VARS=(
    CLAUDE_CODE_MAX_TURNS
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC
    CLAUDE_CODE_USE_BEDROCK
)

OTEL_VARS=(
    CLAUDE_CODE_ENABLE_TELEMETRY
    CLAUDE_CODE_ENHANCED_TELEMETRY_BETA
    OTEL_METRICS_EXPORTER
    OTEL_METRIC_EXPORT_INTERVAL
    OTEL_LOGS_EXPORTER
    OTEL_LOGS_EXPORT_INTERVAL
    OTEL_TRACES_EXPORTER
    OTEL_EXPORTER_OTLP_PROTOCOL
    OTEL_EXPORTER_OTLP_ENDPOINT
    OTEL_LOG_TOOL_DETAILS
    OTEL_LOG_USER_PROMPTS
    OTEL_RESOURCE_ATTRIBUTES
)

ALL_VARS=(
    "${ANTHROPIC_VARS[@]}"
    "${VERTEX_VARS[@]}"
    "${JIRA_VARS[@]}"
    "${GITHUB_VARS[@]}"
    "${CLAUDE_VARS[@]}"
    "${OTEL_VARS[@]}"
)

# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------

usage() {
    cat >&2 <<EOF
Usage: $(basename "$0") [OPTIONS] [-- CLAUDE_ARGS...]

Create an OpenShell sandbox running Claude Code in auto mode.

OPTIONS:
    --name NAME       Sandbox name (auto-generated if omitted)
    --policy FILE     Override policy file (default: auto-detect home/work)
    --repo URL        Git repo to clone (repeatable, auto-detects cwd origin)
    --gateway NAME    OpenShell gateway (default: \$OPENSHELL_GATEWAY)
    --connect NAME    Reconnect to an existing sandbox
    --delete NAME     Delete a sandbox
    --list            List sandboxes
    --help            Show this help

EXAMPLES:
    $(basename "$0")                                          # auto-detect policy and repo
    $(basename "$0") --name nexus                             # named sandbox
    $(basename "$0") --repo git@github.com:org/a.git --repo git@github.com:org/b.git
    $(basename "$0") --connect nexus                          # reconnect
    $(basename "$0") --list                                   # list sandboxes
    $(basename "$0") --delete nexus                           # cleanup
EOF
    exit "${1:-0}"
}

# ---------------------------------------------------------------------------
# Parse args
# ---------------------------------------------------------------------------

while [[ $# -gt 0 ]]; do
    case "$1" in
        --help|-h)
            usage 0
            ;;
        --name)
            SANDBOX_NAME="$2"
            shift 2
            ;;
        --policy)
            POLICY_FILE="$2"
            shift 2
            ;;
        --repo)
            REPOS+=("$2")
            shift 2
            ;;
        --connect)
            CONNECT_NAME="$2"
            shift 2
            ;;
        --delete)
            DELETE_NAME="$2"
            shift 2
            ;;
        --list)
            LIST_MODE=true
            shift
            ;;
        --gateway|-g)
            GATEWAY="$2"
            shift 2
            ;;
        *)
            EXTRA_ARGS+=("$1")
            shift
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------

GW_FLAG=()
if [[ -n "$GATEWAY" ]]; then
    GW_FLAG=(--gateway "$GATEWAY")
fi

if [[ "$LIST_MODE" == true ]]; then
    exec openshell sandbox list "${GW_FLAG[@]}"
    exit $?
elif [[ -n "$DELETE_NAME" ]]; then
    exec openshell sandbox delete "$DELETE_NAME" "${GW_FLAG[@]}"
    exit $?
elif [[ -n "$CONNECT_NAME" ]]; then
    exec openshell sandbox connect "$CONNECT_NAME" "${GW_FLAG[@]}"
    exit $?
fi

# ---------------------------------------------------------------------------
# Resolve policy
# ---------------------------------------------------------------------------

if [[ -z "$POLICY_FILE" ]]; then
    local profile="home"
    if [[ -n "${CLAUDE_CODE_USE_VERTEX+x}" ]]; then
        profile="work"
    fi

    POLICY_FILE="${REPO_ROOT}/policies/${profile}.yaml"
    if [[ ! -f "$POLICY_FILE" ]]; then
        echo "error: policy file not found: ${POLICY_FILE}" >&2
        exit 1
    fi
fi

# ---------------------------------------------------------------------------
# Generate /sandbox/.env content (runtime env vars)
# ---------------------------------------------------------------------------

ENV_CONTENT=""
captured=0
for var in "${ALL_VARS[@]}"; do
    if [[ -n "${!var+x}" ]]; then
        ENV_CONTENT+="$(printf '%s=%q\n' "$var" "${!var}")"
        captured=$((captured + 1))
    fi
done

# Remap credential file paths for sandbox
if [[ -n "${GOOGLE_APPLICATION_CREDENTIALS+x}" ]]; then
    ENV_CONTENT+=$'\n'"GOOGLE_APPLICATION_CREDENTIALS=/sandbox/.config/gcloud/application_default_credentials.json"
fi

if [[ $captured -eq 0 ]]; then
    echo "warning: no env vars captured, sandbox will have no credentials" >&2
else
    echo "captured $captured env vars" >&2
fi

# ---------------------------------------------------------------------------
# Create sandbox
# ---------------------------------------------------------------------------

CREATE_CMD=(openshell sandbox create "${GW_FLAG[@]}" --no-auto-providers)

if [[ -n "$SANDBOX_NAME" ]]; then
    CREATE_CMD+=(--name "$SANDBOX_NAME")
fi

CREATE_CMD+=(--policy "$POLICY_FILE")

SANDBOX_TARGET="${SANDBOX_NAME:-}"

echo "creating sandbox..." >&2
echo "  policy:  ${POLICY_FILE}" >&2
echo "" >&2

# sandbox create hangs on SSH connect (podman driver issue).
# Run in background, poll for sandbox, then use sandbox exec.
"${CREATE_CMD[@]}" &>/dev/null &
CREATE_PID=$!

elapsed=0
while ! openshell sandbox list "${GW_FLAG[@]}" 2>/dev/null | grep -q "${SANDBOX_TARGET}"; do
    sleep 1
    elapsed=$((elapsed + 1))
    if [[ $elapsed -ge 60 ]]; then
        kill "$CREATE_PID" 2>/dev/null || true
        echo "error: sandbox did not appear within 60s" >&2
        exit 1
    fi
done

sleep 2
kill "$CREATE_PID" 2>/dev/null || true
wait "$CREATE_PID" 2>/dev/null || true

# ---------------------------------------------------------------------------
# Upload credentials
# ---------------------------------------------------------------------------

echo "uploading credentials..." >&2

if [[ -d "${HOME}/.config/gcloud" ]]; then
    openshell sandbox upload "${SANDBOX_TARGET}" "${GW_FLAG[@]}" \
        "${HOME}/.config/gcloud" /sandbox/.config
fi

# ---------------------------------------------------------------------------
# Upload ~/.claude/ (resolve symlinks, strip for sandbox)
# ---------------------------------------------------------------------------

echo "uploading claude config..." >&2
if [[ -d "${HOME}/.claude" ]]; then
    CLAUDE_TMP="$(mktemp -d)"
    rsync -rL \
        --exclude=projects \
        --exclude=agentpulse \
        --exclude=venvs \
        --exclude=file-history \
        --exclude=backups \
        --exclude=paste-cache \
        --exclude=debug \
        --exclude=my-claude-stuff-data \
        --exclude=claude-dashboard \
        --exclude=.git \
        "${HOME}/.claude/" "${CLAUDE_TMP}/.claude/"

    # Strip settings.json: remove allow permissions and hooks
    # (sandbox policy is the security boundary)
    if [[ -f "${CLAUDE_TMP}/.claude/settings.json" ]]; then
        python3 -c "
import json, sys
with open(sys.argv[1], 'r') as f:
    s = json.load(f)
for key in list(s.keys()):
    if key.startswith('permissions') and 'allow' in key.lower():
        del s[key]
s.pop('hooks', None)
with open(sys.argv[1], 'w') as f:
    json.dump(s, f, indent=2)
" "${CLAUDE_TMP}/.claude/settings.json"
    fi

    openshell sandbox upload "${SANDBOX_TARGET}" "${GW_FLAG[@]}" \
        "${CLAUDE_TMP}/.claude" /sandbox
    rm -rf "$CLAUDE_TMP"
fi

# ---------------------------------------------------------------------------
# Write runtime env vars to /sandbox/.env
# ---------------------------------------------------------------------------

echo "$ENV_CONTENT" | openshell sandbox exec --name "${SANDBOX_TARGET}" "${GW_FLAG[@]}" \
    --no-tty -- bash -c 'cat > /sandbox/.env'

# ---------------------------------------------------------------------------
# Clone repos
# ---------------------------------------------------------------------------

if [[ ${#REPOS[@]} -eq 0 ]]; then
    current_remote=$(git remote get-url origin 2>/dev/null || true)
    if [[ -n "$current_remote" ]]; then
        REPOS+=("$current_remote")
    fi
fi

WORKDIR="/sandbox"
if [[ ${#REPOS[@]} -gt 0 ]]; then
    echo "cloning repos..." >&2
    for repo in "${REPOS[@]}"; do
        repo_name=$(basename "$repo" .git)
        echo "  ${repo_name}" >&2
        openshell sandbox exec --name "${SANDBOX_TARGET}" "${GW_FLAG[@]}" \
            --no-tty -- git clone "$repo" "/sandbox/source/$repo_name" 2>&1 || true
    done

    first_repo=$(basename "${REPOS[0]}" .git)
    WORKDIR="/sandbox/source/$first_repo"
fi

# ---------------------------------------------------------------------------
# Start Claude Code
# ---------------------------------------------------------------------------

echo "starting claude in ${WORKDIR}..." >&2
exec openshell sandbox exec --name "${SANDBOX_TARGET}" "${GW_FLAG[@]}" \
    --tty -- bash -c "source /sandbox/.bashrc && cd $WORKDIR && exec claude --dangerously-skip-permissions"
exit $?
