#!/bin/bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Create and manage OpenShell sandboxes with Claude Code.
# Captures env vars, uploads credentials and ~/.claude/ config,
# clones repos on host, uploads to sandbox, and starts Claude in auto mode.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SANDBOXES_DIR="${HOME}/sandboxes"

# ---------------------------------------------------------------------------
# Site config — where this host sends telemetry. See config/site.env.example.
# Loaded before anything resolves a policy, because policies reference it.
# ---------------------------------------------------------------------------

SITE_ENV="${REPO_ROOT}/config/site.env"
if [[ ! -f "$SITE_ENV" ]]; then
    cat >&2 <<EOF
error: ${SITE_ENV} does not exist.

    cp ${REPO_ROOT}/config/site.env.example ${SITE_ENV}
    \$EDITOR ${SITE_ENV}

It describes where THIS HOST sends and reads Claude Code telemetry. It is not
created automatically: the template's values are one site's, and silently
adopting them would point a sandbox at a collector that may not exist here.
EOF
    exit 1
fi
set -a
# shellcheck disable=SC1090
source "$SITE_ENV"
set +a

# All three are required. A missing URL would make validate-profile.sh skip
# that check, and a skipped check is indistinguishable from a passing one.
for site_var in OTEL_URL PROMETHEUS_URL LOKI_URL; do
    if [[ -z "${!site_var:-}" ]]; then
        echo "error: ${site_var} not set in ${SITE_ENV} (all values are required)" >&2
        exit 1
    fi
done

# Policy blocks need a host and a port. site.env stores URLs — the richer
# form, carrying scheme and path — and the pair is derived from it. Storing
# both would be the same value twice, free to drift, with nothing checking it.
eval "$(python3 - "$OTEL_URL" "$PROMETHEUS_URL" "$LOKI_URL" <<'PY'
import sys, urllib.parse
for name, url in (("OTEL", sys.argv[1]), ("PROMETHEUS", sys.argv[2]), ("LOKI", sys.argv[3])):
    parts = urllib.parse.urlsplit(url)
    port = parts.port or (443 if parts.scheme == "https" else 80)
    print(f"{name}_HOST={parts.hostname}")
    print(f"{name}_PORT={port}")
PY
)"
GWS_SANDBOX_SCOPES="https://www.googleapis.com/auth/calendar.readonly,https://www.googleapis.com/auth/directory.readonly,https://www.googleapis.com/auth/documents.readonly,https://www.googleapis.com/auth/drive.readonly,https://www.googleapis.com/auth/gmail.readonly,https://www.googleapis.com/auth/meetings.space.readonly,https://www.googleapis.com/auth/presentations.readonly,https://www.googleapis.com/auth/spreadsheets.readonly,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile"

# Defaults
DRYRUN=false
DEBUG=false
SANDBOX_NAME=""
CONNECT_NAME=""
DELETE_NAME=""
LIST_MODE=false
FETCH_SERVICE_MODE=false
NO_CLONE=false
NO_CONNECT=false
DOWNLOAD_MODE=false
UPLOAD_MODE=false
ADD_REPO_MODE=false
CREATE_MODE=false
ENSURE_MODE=false
REFRESH_MODE=false
RECREATE_MODE=false
GATEWAY=""
POLICY_FILE=""
SANDBOX_PROFILE=""
PROFILE_FROM_CLI=false
SOURCE_DIR=""
REPOS=()
REFS=()

# ---------------------------------------------------------------------------
# Env var groups — add new groups as needed
# ---------------------------------------------------------------------------

ANTHROPIC_VARS=(
    ANTHROPIC_API_KEY
)

VERTEX_VARS=(
    CLAUDE_CODE_USE_VERTEX
    CLOUD_ML_REGION
    ANTHROPIC_VERTEX_PROJECT_ID
    GOOGLE_APPLICATION_CREDENTIALS
    GOOGLE_CLOUD_PROJECT
    CLOUDSDK_CONFIG
)

JIRA_VARS=(
    JIRA_USERNAME
    JIRA_EMAIL
    JIRA_API_TOKEN
    JIRA_TOKEN
    JIRA_URL
    JIRA_CLOUD_ID
)


CLAUDE_VARS=(
    CLAUDE_CODE_MAX_TURNS
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC
    CLAUDE_CODE_USE_BEDROCK
)

OTEL_VARS=(
    CLAUDE_CODE_ENABLE_TELEMETRY
    CLAUDE_CODE_ENHANCED_TELEMETRY_BETA
    OTEL_METRICS_EXPORTER
    OTEL_METRIC_EXPORT_INTERVAL
    OTEL_LOGS_EXPORTER
    OTEL_LOGS_EXPORT_INTERVAL
    OTEL_TRACES_EXPORTER
    OTEL_EXPORTER_OTLP_PROTOCOL
    OTEL_EXPORTER_OTLP_ENDPOINT
    OTEL_LOG_TOOL_DETAILS
    OTEL_LOG_USER_PROMPTS
    OTEL_RESOURCE_ATTRIBUTES
)

ALL_VARS=(
    "${ANTHROPIC_VARS[@]}"
    "${VERTEX_VARS[@]}"
    "${JIRA_VARS[@]}"
    "${CLAUDE_VARS[@]}"
    "${OTEL_VARS[@]}"
)

# ---------------------------------------------------------------------------
# Infer sandbox name from CWD if under ~/sandboxes/<name>/
# ---------------------------------------------------------------------------

infer_sandbox_name() {
    local cwd
    cwd="$(pwd)"
    if [[ "$cwd" == "${SANDBOXES_DIR}/"* ]]; then
        local relative="${cwd#${SANDBOXES_DIR}/}"
        echo "${relative%%/*}"
        return 0
    fi
    return 1
}

# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------

usage() {
    cat >&2 <<EOF
Usage: $(basename "$0") [OPTIONS] [-- CLAUDE_ARGS...]

Create an OpenShell sandbox running Claude Code in auto mode.

OPTIONS:
    --create NAME     Create sandbox with this name
    --ensure [NAME]   Create sandbox if missing, reconnect if exists (use with --repo/--ref)
    --repo URL        Git repo to clone on host and upload (repeatable)
    --ref REF         Ref for preceding --repo: branch, pr/<num>, tag/<name>, or SHA
    --source-dir DIR  Derive origin URL from local repo checkout
    --add-repo [NAME] Add repo(s) to existing sandbox (use --repo for URL)
    --download [NAME] Download repos from sandbox to ~/sandboxes/<name>/
    --upload [NAME]   Upload local repo changes back into sandbox
    --policy NAME     Policy name or path (e.g. research, work). Standalone: hot-swap on running sandbox
    --profile NAME    Credential profile (e.g. personal). Controls env vars, uploads, and default policy.
                      Only valid with --create, --recreate, or --ensure — applied at build, not after
    --gateway NAME    OpenShell gateway (default: \$OPENSHELL_GATEWAY)
    --refresh [NAME]  Re-upload ~/.claude/, bin/, .bashrc, .env, system prompt
    --recreate [NAME] Download, delete sandbox container, recreate with new image, re-upload repos
    --connect [NAME]  Reconnect to an existing sandbox
    --delete [NAME]   Delete a sandbox and local state

    NAME is optional for commands marked [NAME] when CWD is under ~/sandboxes/<name>/.
    --no-clone        Skip repo cloning (create sandbox with env + config only)
    --list            List sandboxes
    --fetch-service   Start the outbound fetch service, follow its log, stop it on exit
    --dryrun          Print commands instead of running them
    --debug           Show all commands as they run (set -x)
    --help            Show this help

EXAMPLES:
    $(basename "$0") --create nexus --repo git@github.com:org/nexus.git --ref pr/42
    $(basename "$0") --ensure nexus-pr-42 --repo git@github.com:org/nexus.git --ref pr/42
    $(basename "$0") --add-repo nexus --repo git@github.com:org/lib.git --ref v2.0
    $(basename "$0") --add-repo nexus --repo git@github.com:org/ui.git --source-dir ~/source/ui
    $(basename "$0") --download nexus
    $(basename "$0") --upload nexus --repo nexus
    $(basename "$0") --connect nexus
    $(basename "$0") --delete nexus
EOF
    exit "${1:-0}"
}

# ---------------------------------------------------------------------------
# Ensure gws sandbox credentials are valid (interactive — may open browser)
# ---------------------------------------------------------------------------

ensure_gws_creds() {
    command -v gws &>/dev/null || return 0
    local gws_dir="${HOME}/.config/gws-sandbox"
    if [[ -f "${gws_dir}/credentials.enc" ]]; then
        local valid
        valid=$(GOOGLE_WORKSPACE_CLI_CONFIG_DIR="$gws_dir" gws auth status 2>/dev/null | jq -r '.token_valid // false')
        if [[ "$valid" == "true" ]]; then
            echo "gws sandbox credentials valid" >&2
        else
            echo "gws sandbox credentials expired, re-authenticating..." >&2
            GOOGLE_WORKSPACE_CLI_CONFIG_DIR="$gws_dir" gws auth login --scopes "$GWS_SANDBOX_SCOPES"
        fi
    else
        echo "gws sandbox credentials not found, authenticating (readonly)..." >&2
        mkdir -p "$gws_dir"
        if [[ -f "${HOME}/.config/gws/client_secret.json" ]]; then
            cp "${HOME}/.config/gws/client_secret.json" "${gws_dir}/"
        fi
        GOOGLE_WORKSPACE_CLI_CONFIG_DIR="$gws_dir" gws auth login --scopes "$GWS_SANDBOX_SCOPES"
    fi
}

# ---------------------------------------------------------------------------
# Generate PR + Jira context for sandbox repos
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Connect to sandbox via exec
# ---------------------------------------------------------------------------

connect_sandbox() {
    local os_name="$1" workdir="$2"
    run exec openshell sandbox exec --name "${os_name}" "${GW_FLAG[@]}" \
        --tty --timeout 0 -- bash -c "(while sleep 30; do printf '\\005' 2>/dev/null; done) & source /sandbox/.bashrc && cd ${workdir} && /sandbox/bin/claude-wrapper.sh"
}

# ---------------------------------------------------------------------------
# Short name for OpenShell (19-char limit from DNS label constraint)
# ---------------------------------------------------------------------------

short_name() {
    local hash
    hash=$(printf '%s' "$1" | md5sum | cut -c1-12)
    echo "sb-${hash}"
}

# Resolve full name → openshell name from manifest
resolve_openshell_name() {
    local name="$1"
    local manifest="${SANDBOXES_DIR}/${name}/manifest.json"
    if [[ -f "$manifest" ]]; then
        local os_name
        os_name=$(jq -r '.openshell_name // empty' "$manifest")
        if [[ -n "$os_name" ]]; then
            echo "$os_name"
            return
        fi
    fi
    # No manifest — fall back to short_name for pre-existing sandboxes
    short_name "$name"
}

# Resolve openshell name → full name by scanning manifests
resolve_full_name() {
    local os_name="$1"
    local manifest
    for manifest in "${SANDBOXES_DIR}"/*/manifest.json; do
        [[ -f "$manifest" ]] || continue
        local stored
        stored=$(jq -r '.openshell_name // empty' "$manifest")
        if [[ "$stored" == "$os_name" ]]; then
            jq -r '.name' "$manifest"
            return
        fi
    done
    echo "$os_name"
}

# ---------------------------------------------------------------------------
# Dry-run wrapper — prints command instead of running it
# ---------------------------------------------------------------------------

run() {
    if [[ "$DRYRUN" == true ]]; then
        echo "[dryrun]: $*" >&2
        # exec would replace process — exit cleanly in dryrun
        if [[ "$1" == "exec" ]]; then
            exit 0
        fi
        return 0
    fi
    "$@"
}

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

source "${SCRIPT_DIR}/lib.sh"

clone_repo_host() {
    local url="$1" ref="$2" sandbox_dir="$3"
    local repo_name
    repo_name=$(basename "$url" .git)
    local target="${sandbox_dir}/${repo_name}"

    if [[ -d "$target" ]]; then
        echo "  ${repo_name} already cloned, skipping" >&2
        return 0
    fi

    # Strip trailing slash — gh CLI fails to resolve repo name with it
    local clean_url="${url%/}"
    guard_private_repo "$clean_url"
    run git clone "$clean_url" "$target"

    if [[ -n "$ref" ]]; then
        if [[ "$ref" =~ ^pr/([0-9]+)$ ]]; then
            local pr_num="${BASH_REMATCH[1]}"
            run git -C "$target" fetch origin "pull/${pr_num}/head:pr-${pr_num}"
            run git -C "$target" checkout "pr-${pr_num}"
        elif [[ "$ref" =~ ^tag/ ]]; then
            run git -C "$target" checkout "tags/${ref#tag/}"
        else
            if ! run git -C "$target" checkout "$ref" 2>/dev/null; then
                echo "  warning: ref '${ref}' not found, using default branch" >&2
            fi
        fi
    fi
}

upload_repo() {
    local sandbox_name="$1" sandbox_dir="$2" repo_name="$3"
    # Pre-delete to avoid tar type conflicts (symlink vs dir) on re-upload
    if [[ -z "$repo_name" ]]; then
        echo "error: upload_repo called with empty repo_name" >&2
        return 1
    fi
    # Resolve profile from manifest if not set (covers --upload sub-invocations)
    local effective_profile="$SANDBOX_PROFILE"
    if [[ -z "$effective_profile" && -f "${sandbox_dir}/manifest.json" ]]; then
        effective_profile=$(jq -r '.profile // empty' "${sandbox_dir}/manifest.json" 2>/dev/null || true)
    fi
    # Personal profile: block private repos
    if [[ "$effective_profile" == "personal" && -d "${sandbox_dir}/${repo_name}/.git" ]]; then
        local origin_url
        origin_url=$(git -C "${sandbox_dir}/${repo_name}" remote get-url origin 2>/dev/null || true)
        if [[ -n "$origin_url" ]]; then
            guard_private_repo "$origin_url"
        fi
    fi
    # Auto-generate pr-context.md + jira-context.md if repo is a PR checkout
    generate_repo_context "$sandbox_dir" "$repo_name" "${effective_profile:-${SANDBOX_PROFILE:-}}"

    run openshell sandbox exec --name "$sandbox_name" "${GW_FLAG[@]}" \
        -- rm -rf "/sandbox/source/${repo_name}" 2>/dev/null || true
    run openshell sandbox upload "$sandbox_name" "${GW_FLAG[@]}" \
        --no-git-ignore \
        "${sandbox_dir}/${repo_name}" /sandbox/source/
}

write_manifest() {
    local sandbox_dir="$1" sandbox_name="$2" repo_name="$3"
    local url="$4" ref="$5" sha="$6"
    local manifest="${sandbox_dir}/manifest.json"
    local now
    now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    if [[ ! -f "$manifest" ]]; then
        local os_name
        os_name=$(short_name "$sandbox_name")
        local manifest_args=(
            --arg name "$sandbox_name"
            --arg os_name "$os_name"
            --arg created "$now"
        )
        local manifest_expr='{name: $name, openshell_name: $os_name, created: $created, repos: {}}'
        if [[ -n "$SANDBOX_PROFILE" ]]; then
            manifest_args+=(--arg profile "$SANDBOX_PROFILE")
            manifest_expr='{name: $name, openshell_name: $os_name, profile: $profile, created: $created, repos: {}}'
        fi
        jq -n "${manifest_args[@]}" "$manifest_expr" > "${manifest}.tmp"
        mv "${manifest}.tmp" "$manifest"
    fi

    # Update profile if specified (handles recreate with different profile)
    if [[ -n "$SANDBOX_PROFILE" ]]; then
        jq --arg profile "$SANDBOX_PROFILE" '.profile = $profile' \
            "$manifest" > "${manifest}.tmp"
        mv "${manifest}.tmp" "$manifest"
    fi

    jq \
        --arg repo "$repo_name" \
        --arg url "$url" \
        --arg ref "$ref" \
        --arg sha "$sha" \
        --arg ts "$now" \
        '.repos[$repo] = {url: $url, ref: $ref, sha: $sha, cloned_at: $ts}' \
        "$manifest" > "${manifest}.tmp"
    mv "${manifest}.tmp" "$manifest"
}

download_sandbox() {
    local sandbox_name="$1" sandbox_dir="$2"
    local manifest="${sandbox_dir}/manifest.json"

    if [[ ! -f "$manifest" ]]; then
        echo "error: no manifest at ${manifest}" >&2
        exit 1
    fi

    local repos
    repos=$(jq -r '.repos | keys[]' "$manifest")

    local dl_tmp
    dl_tmp="$(mktemp -d)"
    for repo_name in $repos; do
        echo "  downloading ${repo_name}..." >&2
        mkdir -p "${dl_tmp}/${repo_name}"
        run openshell sandbox download "$sandbox_name" "${GW_FLAG[@]}" \
            "/sandbox/source/${repo_name}" "${dl_tmp}/${repo_name}"
        mkdir -p "${sandbox_dir}/${repo_name}"
        run rsync -a --delete --exclude=.venv "${dl_tmp}/${repo_name}/" "${sandbox_dir}/${repo_name}/"
    done
    rm -rf "$dl_tmp"
}

upload_sandbox() {
    local sandbox_name="$1" sandbox_dir="$2" target_repo="${3:-}"
    local manifest="${sandbox_dir}/manifest.json"

    if [[ ! -f "$manifest" ]]; then
        echo "error: no manifest at ${manifest}" >&2
        exit 1
    fi

    if [[ -n "$target_repo" ]]; then
        if [[ ! -d "${sandbox_dir}/${target_repo}" ]]; then
            echo "error: repo not found at ${sandbox_dir}/${target_repo}" >&2
            exit 1
        fi
        echo "  uploading ${target_repo}..." >&2
        upload_repo "$sandbox_name" "$sandbox_dir" "$target_repo"
    else
        local repos
        repos=$(jq -r '.repos | keys[]' "$manifest")
        for repo_name in $repos; do
            if [[ -d "${sandbox_dir}/${repo_name}" ]]; then
                echo "  uploading ${repo_name}..." >&2
                upload_repo "$sandbox_name" "$sandbox_dir" "$repo_name"
            fi
        done
    fi

    # Re-upload manifest so sandbox has current repo list
    local manifest_tmp
    manifest_tmp="$(mktemp -d)"
    mkdir -p "${manifest_tmp}/source"
    cp "$manifest" "${manifest_tmp}/source/manifest.json"
    run openshell sandbox upload "$sandbox_name" "${GW_FLAG[@]}" \
        "${manifest_tmp}/source" /sandbox
    rm -rf "$manifest_tmp"
}

download_claude_state() {
    local sandbox_name="$1" sandbox_dir="$2"
    local claude_dir="${sandbox_dir}/claude"
    echo "  downloading claude session state..." >&2
    local dl_tmp
    dl_tmp="$(mktemp -d)"
    mkdir -p "${dl_tmp}/projects"
    run openshell sandbox download "$sandbox_name" "${GW_FLAG[@]}" \
        "/sandbox/.claude/projects" "${dl_tmp}/projects" || true
    if [[ "$(ls -A "${dl_tmp}/projects" 2>/dev/null)" ]]; then
        mkdir -p "${claude_dir}"
        rsync -a "${dl_tmp}/projects/" "${claude_dir}/projects/"
    fi
    # Preserve OAuth credentials from sandbox
    run openshell sandbox download "$sandbox_name" "${GW_FLAG[@]}" \
        "/sandbox/.claude/.credentials.json" "${dl_tmp}/" || true
    if [[ -f "${dl_tmp}/.credentials.json" ]]; then
        mkdir -p "${claude_dir}"
        cp "${dl_tmp}/.credentials.json" "${claude_dir}/.credentials.json"
        echo "  preserved OAuth credentials" >&2
    fi
    # Preserve .claude.json (auth state)
    run openshell sandbox download "$sandbox_name" "${GW_FLAG[@]}" \
        "/sandbox/.claude.json" "${dl_tmp}/" || true
    if [[ -f "${dl_tmp}/.claude.json" ]]; then
        mkdir -p "${claude_dir}"
        cp "${dl_tmp}/.claude.json" "${claude_dir}/.claude.json"
        echo "  preserved .claude.json" >&2
    fi
    rm -rf "$dl_tmp"
}

upload_claude_state() {
    local sandbox_name="$1" sandbox_dir="$2"
    local claude_dir="${sandbox_dir}/claude"
    local has_state=false
    local stage
    stage="$(mktemp -d)"
    mkdir -p "${stage}/.claude"
    if [[ -d "${claude_dir}/projects" ]]; then
        cp -r "${claude_dir}/projects" "${stage}/.claude/projects"
        has_state=true
    fi
    if [[ -f "${claude_dir}/.credentials.json" ]]; then
        cp "${claude_dir}/.credentials.json" "${stage}/.claude/.credentials.json"
        has_state=true
        echo "  restoring OAuth credentials..." >&2
    fi
    # Stage .claude.json inside .claude/ dir, move after upload
    local restore_claude_json=false
    if [[ -f "${claude_dir}/.claude.json" ]]; then
        cp "${claude_dir}/.claude.json" "${stage}/.claude/.claude.json"
        has_state=true
        restore_claude_json=true
        echo "  restoring .claude.json..." >&2
    fi
    if [[ "$has_state" == true ]]; then
        echo "  restoring claude session state..." >&2
        run openshell sandbox upload "$sandbox_name" "${GW_FLAG[@]}" \
            "${stage}/.claude" /sandbox
        if [[ "$restore_claude_json" == true ]]; then
            run openshell sandbox exec --name "$sandbox_name" "${GW_FLAG[@]}" \
                -- mv /sandbox/.claude/.claude.json /sandbox/.claude.json
        fi
    fi
    rm -rf "$stage"
}

upload_config() {
    local sandbox_target="$1"
    local sandbox_dir="$2"

    echo "uploading claude config..." >&2
    if [[ -d "${HOME}/.claude" ]]; then
        CLAUDE_TMP="$(mktemp -d)"
        rsync -rL \
            --exclude=projects \
            --exclude=agentpulse \
            --exclude=venvs \
            --exclude=file-history \
            --exclude=backups \
            --exclude=paste-cache \
            --exclude=debug \
            --exclude=my-claude-stuff-data \
            --exclude=claude-dashboard \
            --exclude=.git \
            --exclude=.venv \
            --exclude=.credentials.json \
            "${HOME}/.claude/" "${CLAUDE_TMP}/.claude/"

        # Strip settings.json: remove allow permissions, keep only OTEL dummy hooks
        if [[ -f "${CLAUDE_TMP}/.claude/settings.json" ]]; then
            python3 -c "
import json, sys
with open(sys.argv[1], 'r') as f:
    raw = f.read()
raw = raw.replace(sys.argv[2], '/sandbox')
s = json.loads(raw)
if isinstance(s.get('permissions'), dict):
    s['permissions'].pop('allow', None)
profile = sys.argv[3] if len(sys.argv) > 3 else ''
if profile == 'personal':
    import re
    strip_re = re.compile(r'^(CLAUDE_CODE_USE_VERTEX|ANTHROPIC_VERTEX|GOOGLE|CLOUDSDK|CLOUD_ML|JIRA|ATLASSIAN)', re.I)
    if isinstance(s.get('env'), dict):
        s['env'] = {k: v for k, v in s['env'].items() if not strip_re.match(k)}
hooks = s.get('hooks')
if isinstance(hooks, dict):
    for event in list(hooks.keys()):
        rules = hooks[event]
        if isinstance(rules, list):
            kept = [r for r in rules if isinstance(r, dict) and any(
                isinstance(h, dict) and h.get('command', '').strip() in ('python3 -c \"\"', 'python -c \"\"')
                for h in r.get('hooks', [])
            )]
            if kept:
                hooks[event] = kept
            else:
                del hooks[event]
    if not hooks:
        del s['hooks']
else:
    s.pop('hooks', None)
with open(sys.argv[1], 'w') as f:
    json.dump(s, f, indent=2)
" "${CLAUDE_TMP}/.claude/settings.json" "${HOME}" "${SANDBOX_PROFILE}"
        fi

        # Rewrite host HOME paths to /sandbox in all plugin config files
        if [[ -d "${CLAUDE_TMP}/.claude/plugins" ]]; then
            find "${CLAUDE_TMP}/.claude/plugins" -name "*.json" -exec \
                sed -i "s|${HOME}|/sandbox|g" {} +
        fi

        # Stage .bashrc and .env into temp dir
        cp "${REPO_ROOT}/config/bashrc" "${CLAUDE_TMP}/.bashrc"
        echo "$ENV_CONTENT" > "${CLAUDE_TMP}/.env"

        # Upload config to /sandbox
        run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
            "${CLAUDE_TMP}/.claude" /sandbox
        run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
            "${CLAUDE_TMP}/.bashrc" /sandbox
        run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
            "${CLAUDE_TMP}/.env" /sandbox
        rm -rf "$CLAUDE_TMP"
    fi

    # Upload gitconfig and commit signing key
    SIGNING_KEY="$(git config --global user.signingkey 2>/dev/null || true)"
    if [[ -n "$SIGNING_KEY" && -f "$SIGNING_KEY" ]]; then
        GIT_TMP="$(mktemp -d)"
        mkdir -p "${GIT_TMP}/.ssh"
        cp "$SIGNING_KEY" "${GIT_TMP}/.ssh/"
        chmod 600 "${GIT_TMP}/.ssh/$(basename "$SIGNING_KEY")"
        # Upload gitconfig with paths rewritten for sandbox
        if [[ -f "${HOME}/.gitconfig" ]]; then
            sed "s|${HOME}|/sandbox|g" "${HOME}/.gitconfig" > "${GIT_TMP}/.gitconfig"
        fi
        run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
            "${GIT_TMP}/.ssh" /sandbox
        run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
            "${GIT_TMP}/.gitconfig" /sandbox
        rm -rf "$GIT_TMP"
    fi

    # Upload gws (Google Workspace CLI) readonly credentials (skip for personal profile)
    if [[ "$SANDBOX_PROFILE" != "personal" ]]; then
        GWS_SANDBOX_DIR="${HOME}/.config/gws-sandbox"
        if [[ -d "$GWS_SANDBOX_DIR" ]]; then
            GWS_TMP="$(mktemp -d)"
            mkdir -p "${GWS_TMP}/.config"
            cp -r "$GWS_SANDBOX_DIR" "${GWS_TMP}/.config/gws"
            rm -rf "${GWS_TMP}/.config/gws/cache"
            run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
                "${GWS_TMP}/.config" /sandbox
            rm -rf "$GWS_TMP"
        fi
    fi

    # Re-upload bin/
    run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
        "${REPO_ROOT}/bin" /sandbox

    upload_static "$sandbox_target" "$sandbox_dir"
}

# ---------------------------------------------------------------------------
# Resolve policy file from bare name or path
# ---------------------------------------------------------------------------

fetch_service_teardown() {
    # Stop the service first, then decide the policy: with the service down the
    # grant points at nothing, so there is no rush and no unsafe interval.
    "${REPO_ROOT}/fetchsvc/fetchsvc.sh" down

    local revert="personal"
    if [[ -t 0 ]]; then
        echo "" >&2
        echo "Revert policy (empty = leave fetch-service applied):" >&2
        read -erp "> " -i "$revert" revert
    else
        echo "not a terminal — reverting policy to ${revert}" >&2
    fi

    if [[ -z "$revert" ]]; then
        echo "policy left as fetch-service — the sandbox keeps a grant to a" >&2
        echo "service that is no longer running" >&2
        return 0
    fi
    "$0" --policy "$revert" ${GATEWAY:+--gateway "$GATEWAY"}
}

render_policy() {
    # Substitute site.env values into a policy template, writing the effective
    # policy next to manifest.json in the sandbox dir. That file is what
    # `openshell` receives and what gets uploaded into the sandbox.
    # ponytail: sed over a fixed placeholder list; switch to a real templating
    # pass if this outgrows simple name substitution.
    local src="$1" sandbox_dir="$2"
    local dest="${sandbox_dir}/openshell-policy.yaml"
    mkdir -p "$sandbox_dir"
    local expr=() v
    for v in OTEL_HOST OTEL_PORT PROMETHEUS_HOST PROMETHEUS_PORT LOKI_HOST LOKI_PORT; do
        expr+=(-e "s|\${${v}}|${!v}|g")
    done
    sed "${expr[@]}" "$src" > "$dest"
    if grep -q '\${' "$dest"; then
        echo "error: unresolved placeholder in ${src} after rendering:" >&2
        grep -n '\${' "$dest" >&2
        rm -f "$dest"
        return 1
    fi
    echo "$dest"
}

upload_static() {
    # Everything in /sandbox/source that is host-owned and not a repo: the
    # system prompt, manifest.json (sandbox name, repo list), and
    # openshell-policy.yaml (what this sandbox may reach). All three go in one
    # staged-directory upload (#12) — they are inert once written, so
    # re-sending an unchanged one costs nothing and there is no reason to
    # decide per file. The only path that uploads any of them; called on
    # create, refresh, and policy hot-swap.
    #
    # None is ever downloaded: download_sandbox() pulls only the repo
    # directories named in the manifest, so the host copies stay authoritative.
    local sandbox_target="$1" sandbox_dir="$2"
    local tmp profile="$SANDBOX_PROFILE"
    tmp="$(mktemp -d)"
    mkdir -p "${tmp}/source"

    ensure_policy "$sandbox_dir"

    # Profile from the manifest when the caller has not resolved it — the
    # policy hot-swap path runs before --profile is read.
    if [[ -z "$profile" && -f "${sandbox_dir}/manifest.json" ]]; then
        profile=$(jq -r '.profile // empty' "${sandbox_dir}/manifest.json" 2>/dev/null || true)
    fi

    # copy: system prompt
    cp "${REPO_ROOT}/config/sandbox-claude.md" "${tmp}/source/CLAUDE.md"
    if [[ "$profile" == "personal" ]]; then
        # Strip the Jira section. Observability needs no stripping — the prompt
        # names no endpoints, it points at openshell-policy.yaml, which already
        # omits whatever this profile cannot reach.
        sed -i '/^## Jira$/,/^## /{ /^## Jira$/d; /^## /!d; }' "${tmp}/source/CLAUDE.md"
    fi

    # copy: manifest — absent on the first create, written by the repo loop
    if [[ -f "${sandbox_dir}/manifest.json" ]]; then
        cp "${sandbox_dir}/manifest.json" "${tmp}/source/manifest.json"
    fi

    # copy: openshell policy — ensure_policy above guarantees it exists
    cp "${sandbox_dir}/openshell-policy.yaml" "${tmp}/source/openshell-policy.yaml"

    # do: upload
    run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
        "${tmp}/source" /sandbox
    rm -rf "$tmp"
}

policy_for_profile() {
    case "$1" in
        personal) resolve_policy "personal" ;;
        *)        resolve_policy "code" ;;
    esac
}

ensure_policy() {
    # Render the effective policy if it is not already on disk, so paths that
    # do not resolve a policy themselves (--upload, --add-repo) still have one
    # to upload. Sandboxes created before openshell-policy.yaml existed have
    # none; without this they would silently upload nothing.
    local sandbox_dir="$1" profile="" template
    [[ -f "${sandbox_dir}/openshell-policy.yaml" ]] && return 0
    if [[ -f "${sandbox_dir}/manifest.json" ]]; then
        profile=$(jq -r '.profile // empty' "${sandbox_dir}/manifest.json" 2>/dev/null || true)
    fi
    template="$(policy_for_profile "$profile")" || return 1
    render_policy "$template" "$sandbox_dir" >/dev/null
}

resolve_policy() {
    local input="$1"
    if [[ -f "$input" ]]; then
        echo "$input"
    elif [[ -f "${REPO_ROOT}/policies/${input}.yaml" ]]; then
        echo "${REPO_ROOT}/policies/${input}.yaml"
    elif [[ -f "${REPO_ROOT}/policies/${input}" ]]; then
        echo "${REPO_ROOT}/policies/${input}"
    else
        echo "error: policy not found: ${input} (tried ${REPO_ROOT}/policies/${input}.yaml)" >&2
        return 1
    fi
}

# ---------------------------------------------------------------------------
# Parse args
# ---------------------------------------------------------------------------

while [[ $# -gt 0 ]]; do
    case "$1" in
        --help|-h)
            usage 0
            ;;
        --create)
            [[ $# -ge 2 ]] || { echo "error: --create requires NAME" >&2; exit 1; }
            CREATE_MODE=true
            SANDBOX_NAME="$2"
            shift 2
            ;;
        --policy)
            [[ $# -ge 2 ]] || { echo "error: --policy requires NAME" >&2; exit 1; }
            POLICY_FILE="$(resolve_policy "$2")" || exit 1
            shift 2
            ;;
        --refresh)
            REFRESH_MODE=true
            if [[ $# -ge 2 && "$2" != --* ]]; then
                SANDBOX_NAME="$2"; shift 2
            else
                SANDBOX_NAME="$(infer_sandbox_name)" || { echo "error: --refresh requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --recreate)
            RECREATE_MODE=true
            if [[ $# -ge 2 && "$2" != --* ]]; then
                SANDBOX_NAME="$2"; shift 2
            else
                SANDBOX_NAME="$(infer_sandbox_name)" || { echo "error: --recreate requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --source-dir)
            [[ $# -ge 2 ]] || { echo "error: --source-dir requires PATH" >&2; exit 1; }
            SOURCE_DIR="$2"
            shift 2
            ;;
        --repo)
            [[ $# -ge 2 ]] || { echo "error: --repo requires URL" >&2; exit 1; }
            REPOS+=("$2")
            REFS+=("")
            shift 2
            ;;
        --ref)
            [[ $# -ge 2 ]] || { echo "error: --ref requires REF" >&2; exit 1; }
            if [[ ${#REFS[@]} -gt 0 ]]; then
                REFS[${#REFS[@]}-1]="$2"
            else
                echo "error: --ref must follow --repo or --add-repo" >&2
                exit 1
            fi
            shift 2
            ;;
        --ensure)
            ENSURE_MODE=true
            if [[ $# -ge 2 && "$2" != --* ]]; then
                SANDBOX_NAME="$2"; shift 2
            else
                SANDBOX_NAME="$(infer_sandbox_name)" || { echo "error: --ensure requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --add-repo)
            ADD_REPO_MODE=true
            if [[ $# -ge 2 && "$2" != --* ]]; then
                SANDBOX_NAME="$2"; shift 2
            else
                SANDBOX_NAME="$(infer_sandbox_name)" || { echo "error: --add-repo requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --download)
            DOWNLOAD_MODE=true
            if [[ $# -ge 2 && "$2" != --* ]]; then
                SANDBOX_NAME="$2"; shift 2
            else
                SANDBOX_NAME="$(infer_sandbox_name)" || { echo "error: --download requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --upload)
            UPLOAD_MODE=true
            if [[ $# -ge 2 && "$2" != --* ]]; then
                SANDBOX_NAME="$2"; shift 2
            else
                SANDBOX_NAME="$(infer_sandbox_name)" || { echo "error: --upload requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --connect)
            if [[ $# -ge 2 && "$2" != --* ]]; then
                CONNECT_NAME="$2"; shift 2
            else
                CONNECT_NAME="$(infer_sandbox_name)" || { echo "error: --connect requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --delete)
            if [[ $# -ge 2 && "$2" != --* ]]; then
                DELETE_NAME="$2"; shift 2
            else
                DELETE_NAME="$(infer_sandbox_name)" || { echo "error: --delete requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --dryrun|--dry-run)
            DRYRUN=true
            shift
            ;;
        --debug)
            DEBUG=true
            shift
            ;;
        --list)
            LIST_MODE=true
            shift
            ;;
        --fetch-service)
            FETCH_SERVICE_MODE=true
            shift
            ;;
        --profile)
            [[ $# -ge 2 ]] || { echo "error: --profile requires NAME" >&2; exit 1; }
            SANDBOX_PROFILE="$2"
            PROFILE_FROM_CLI=true
            shift 2
            ;;
        --no-clone)
            NO_CLONE=true
            shift
            ;;
        --no-connect)
            NO_CONNECT=true
            shift
            ;;
        --gateway|-g)
            [[ $# -ge 2 ]] || { echo "error: --gateway requires NAME" >&2; exit 1; }
            GATEWAY="$2"
            shift 2
            ;;
        --*)
            echo "error: unknown option: $1" >&2
            usage 1
            ;;
        *)
            echo "error: unexpected argument: $1" >&2
            usage 1
            ;;
    esac
done

# ---------------------------------------------------------------------------
# --profile is only applied on a path that creates a sandbox
# ---------------------------------------------------------------------------

# Profile decides four things at once: which env vars land in /sandbox/.env,
# which credentials upload, which policy renders, and whether the system prompt
# keeps its Jira section. Only the create path writes all four. Every other mode
# either ignores --profile outright or — worse, --refresh — applies the new
# .env and leaves the policy, system prompt, and manifest on the old profile.
# Half-applied reads as applied, so refuse instead.
if [[ "$PROFILE_FROM_CLI" == true \
      && "$CREATE_MODE" != true \
      && "$RECREATE_MODE" != true \
      && "$ENSURE_MODE" != true ]]; then
    echo "error: --profile is only valid with --create, --recreate, or --ensure." >&2
    echo "  Profile is applied when a sandbox is built, not afterwards." >&2
    echo "  To switch an existing sandbox: $(basename "$0") --recreate NAME --profile ${SANDBOX_PROFILE}" >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------

if [[ "$DEBUG" == true ]]; then
    set -x
fi

GW_FLAG=()
if [[ -n "$GATEWAY" ]]; then
    GW_FLAG=(--gateway "$GATEWAY")
fi

# --- Fetch service: run in the foreground, tear down on exit ---
if [[ "$FETCH_SERVICE_MODE" == true ]]; then
    FETCHSVC="${REPO_ROOT}/fetchsvc/fetchsvc.sh"
    [[ -x "$FETCHSVC" ]] || { echo "error: ${FETCHSVC} not executable" >&2; exit 1; }

    if "$FETCHSVC" running; then
        echo "fetch service already running — will stop it on exit" >&2
    else
        "$FETCHSVC" up || exit 1
    fi

    # Foreground on purpose: the service widens what a sandbox can read, so it
    # lives exactly as long as this terminal does. The policy grant is applied
    # and reverted alongside it, so the sandbox cannot reach a service that is
    # not running and cannot keep the grant after it stops.
    trap 'trap - INT TERM EXIT; fetch_service_teardown' INT TERM EXIT
    "$0" --policy fetch-service ${GATEWAY:+--gateway "$GATEWAY"} || exit 1

    echo "following log — Ctrl-C stops the service" >&2
    "$FETCHSVC" logs
    exit 0
fi

if [[ "$LIST_MODE" == true ]]; then
    openshell sandbox list "${GW_FLAG[@]}" | while IFS= read -r line; do
        os_name=$(echo "$line" | awk '{print $1}')
        full=$(resolve_full_name "$os_name")
        if [[ "$full" != "$os_name" ]]; then
            echo "$line  ($full)"
        else
            echo "$line"
        fi
    done
    exit $?
elif [[ -n "$DELETE_NAME" ]]; then
    OS_NAME=$(resolve_openshell_name "$DELETE_NAME")
    run openshell sandbox delete "$OS_NAME" "${GW_FLAG[@]}" || true
    if [[ -d "${SANDBOXES_DIR}/${DELETE_NAME}" ]]; then
        rm -rf "${SANDBOXES_DIR}/${DELETE_NAME}"
        echo "removed local state: ${SANDBOXES_DIR}/${DELETE_NAME}" >&2
    fi
    exit 0
elif [[ -n "$CONNECT_NAME" ]]; then
    OS_NAME=$(resolve_openshell_name "$CONNECT_NAME")
    SANDBOX_DIR="${SANDBOXES_DIR}/${CONNECT_NAME}"
    WORKDIR="/sandbox"
    if [[ -f "${SANDBOX_DIR}/manifest.json" ]]; then
        WORKDIR="/sandbox/source/"
    fi
    connect_sandbox "$OS_NAME" "$WORKDIR"
    exit $?
fi

# --- Add repo to existing sandbox ---
if [[ "$ADD_REPO_MODE" == true ]]; then
    if [[ ${#REPOS[@]} -eq 0 && -n "$SOURCE_DIR" && -d "$SOURCE_DIR/.git" ]]; then
        REPOS+=("$(git -C "$SOURCE_DIR" remote get-url origin)")
        REFS+=("")
    fi
    if [[ ${#REPOS[@]} -eq 0 ]]; then
        echo "error: --add-repo requires --repo URL or --source-dir PATH" >&2
        exit 1
    fi
    OS_NAME=$(resolve_openshell_name "$SANDBOX_NAME")
    SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
    mkdir -p "$SANDBOX_DIR"

    # Read profile from manifest for repo visibility check
    if [[ -z "$SANDBOX_PROFILE" && -f "${SANDBOX_DIR}/manifest.json" ]]; then
        SANDBOX_PROFILE=$(jq -r '.profile // empty' "${SANDBOX_DIR}/manifest.json" 2>/dev/null || true)
    fi

    for i in "${!REPOS[@]}"; do
        repo="${REPOS[$i]}"
        ref="${REFS[$i]:-}"
        repo_name=$(basename "$repo" .git)

        echo "adding ${repo_name} to sandbox ${SANDBOX_NAME}..." >&2
        clone_repo_host "$repo" "$ref" "$SANDBOX_DIR"

        sha=$(git -C "${SANDBOX_DIR}/${repo_name}" rev-parse HEAD)
        write_manifest "$SANDBOX_DIR" "$SANDBOX_NAME" "$repo_name" "$repo" "$ref" "$sha"

        echo "uploading ${repo_name}..." >&2
        upload_repo "$OS_NAME" "$SANDBOX_DIR" "$repo_name"
    done

    # Re-upload so the sandbox has the updated repo list
    upload_static "$OS_NAME" "$SANDBOX_DIR"

    echo "done." >&2
    exit 0
fi

# --- Download from sandbox ---
if [[ "$DOWNLOAD_MODE" == true ]]; then
    OS_NAME=$(resolve_openshell_name "$SANDBOX_NAME")
    SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"

    echo "downloading from sandbox ${SANDBOX_NAME}..." >&2
    download_sandbox "$OS_NAME" "$SANDBOX_DIR"
    download_claude_state "$OS_NAME" "$SANDBOX_DIR"
    echo "done. files in ${SANDBOX_DIR}/" >&2
    exit 0
fi

# --- Upload to sandbox ---
if [[ "$UPLOAD_MODE" == true ]]; then
    OS_NAME=$(resolve_openshell_name "$SANDBOX_NAME")
    SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
    target_repo=""
    if [[ ${#REPOS[@]} -gt 0 ]]; then
        target_repo=$(basename "${REPOS[0]}" .git)
    fi

    echo "uploading to sandbox ${SANDBOX_NAME}..." >&2
    upload_sandbox "$OS_NAME" "$SANDBOX_DIR" "$target_repo"
    upload_static "$OS_NAME" "$SANDBOX_DIR"
    echo "done." >&2
    exit 0
fi

# --- Recreate: download, delete remote, ensure (creates + uploads + connects) ---
if [[ "$RECREATE_MODE" == true ]]; then
    COMMON_ARGS=()
    [[ -n "$GATEWAY" ]] && COMMON_ARGS+=(--gateway "$GATEWAY")
    [[ "$DRYRUN" == true ]] && COMMON_ARGS+=(--dryrun)

    echo "recreating sandbox ${SANDBOX_NAME}..." >&2

    # Pre-flight: check all repos before touching anything
    SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
    if [[ -f "${SANDBOX_DIR}/manifest.json" ]]; then
        for repo_name in $(jq -r '.repos | keys[]' "${SANDBOX_DIR}/manifest.json"); do
            if [[ -d "${SANDBOX_DIR}/${repo_name}/.git" ]]; then
                origin_url=$(git -C "${SANDBOX_DIR}/${repo_name}" remote get-url origin 2>/dev/null || true)
                if [[ -n "$origin_url" ]]; then
                    guard_private_repo "$origin_url"
                fi
            fi
        done
    fi

    # 1. Download repos + claude state
    "$0" --download "$SANDBOX_NAME" "${COMMON_ARGS[@]}"

    # 2. Delete remote sandbox only (preserve local dir)
    OS_NAME=$(resolve_openshell_name "$SANDBOX_NAME")
    run openshell sandbox delete "$OS_NAME" "${GW_FLAG[@]}" || true

    # 3. Create fresh sandbox without connecting
    "$0" --create "$SANDBOX_NAME" --no-clone --no-connect ${POLICY_FILE:+--policy "$POLICY_FILE"} ${SANDBOX_PROFILE:+--profile "$SANDBOX_PROFILE"} "${COMMON_ARGS[@]}"

    # 4. Upload local repos
    "$0" --upload "$SANDBOX_NAME" "${COMMON_ARGS[@]}"

    # 5. Connect
    exec "$0" --connect "$SANDBOX_NAME" "${COMMON_ARGS[@]}"
fi

# --- Ensure (create-or-connect) ---
if [[ "$ENSURE_MODE" == true ]]; then
    OS_NAME=$(resolve_openshell_name "$SANDBOX_NAME")
    if openshell sandbox list "${GW_FLAG[@]}" 2>/dev/null | grep -q "^${OS_NAME}[[:space:]]"; then
        SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
        WORKDIR="/sandbox"
        if [[ -f "${SANDBOX_DIR}/manifest.json" ]]; then
            WORKDIR="/sandbox/source/"
        fi
        # This branch connects, it does not build — so --profile is dropped.
        # Dropping it silently when it disagrees with what the sandbox was
        # built as hands the caller a sandbox on the other profile's
        # credentials and policy while the command line says otherwise.
        # scode passes --profile on every --ensure (scode:137,165,189,207,243),
        # so a match must stay silent; only a mismatch is an error.
        if [[ "$PROFILE_FROM_CLI" == true ]]; then
            manifest_profile=$(jq -r '.profile // empty' "${SANDBOX_DIR}/manifest.json" 2>/dev/null || true)
            if [[ "$SANDBOX_PROFILE" != "$manifest_profile" ]]; then
                echo "error: sandbox '${SANDBOX_NAME}' exists with profile '${manifest_profile:-<none>}', cannot connect as '${SANDBOX_PROFILE}'." >&2
                echo "  --ensure connects an existing sandbox; profile is only applied at create." >&2
                echo "  To switch it: $(basename "$0") --recreate ${SANDBOX_NAME} --profile ${SANDBOX_PROFILE}" >&2
                exit 1
            fi
        fi
        echo "sandbox '${SANDBOX_NAME}' exists, connecting..." >&2
        connect_sandbox "$OS_NAME" "$WORKDIR"
    else
        ENSURE_ARGS=(--create "$SANDBOX_NAME")
        for i in "${!REPOS[@]}"; do
            ENSURE_ARGS+=(--repo "${REPOS[$i]}")
            if [[ -n "${REFS[$i]:-}" ]]; then
                ENSURE_ARGS+=(--ref "${REFS[$i]}")
            fi
        done
        [[ -n "$GATEWAY" ]] && ENSURE_ARGS+=(--gateway "$GATEWAY")
        [[ -n "$POLICY_FILE" ]] && ENSURE_ARGS+=(--policy "$POLICY_FILE")
        [[ -n "$SANDBOX_PROFILE" ]] && ENSURE_ARGS+=(--profile "$SANDBOX_PROFILE")
        [[ -n "$SOURCE_DIR" ]] && ENSURE_ARGS+=(--source-dir "$SOURCE_DIR")
        [[ "$DRYRUN" == true ]] && ENSURE_ARGS+=(--dryrun)
        exec "$0" "${ENSURE_ARGS[@]}"
    fi
fi

# --- Policy hot-swap on existing sandbox ---
if [[ -n "$POLICY_FILE" && -z "$SANDBOX_NAME" && -z "$CONNECT_NAME" && "$ENSURE_MODE" != true ]]; then
    POLICY_TARGET="$(infer_sandbox_name)" || { echo "error: --policy requires sandbox NAME or CWD under ~/sandboxes/<name>/" >&2; exit 1; }
    OS_NAME=$(resolve_openshell_name "$POLICY_TARGET")
    POLICY_FILE="$(render_policy "$POLICY_FILE" "${SANDBOXES_DIR}/${POLICY_TARGET}")" || exit 1
    echo "setting policy on ${POLICY_TARGET}..." >&2
    if [[ "$DRYRUN" == true ]]; then
        run openshell policy set "${GW_FLAG[@]}" --policy "$POLICY_FILE" "$OS_NAME"
        exit 0
    fi
    set_output=$(openshell policy set "${GW_FLAG[@]}" --policy "$POLICY_FILE" "$OS_NAME" 2>&1)
    echo "$set_output" >&2
    if ! echo "$set_output" | grep -qi "unchanged"; then
        elapsed=0
    while true; do
        # Highest VERSION wins, not the last row. `openshell policy list` prints
        # newest-first under a header, so `tail -1` read the OLDEST row — always
        # Superseded — and the poll timed out on every real change. The failure
        # is worse than it looks: the timeout exits before the artifact upload,
        # so the enforcer gets the new policy while /sandbox/source keeps
        # advertising the old one.
        latest_status=$(openshell policy list "${GW_FLAG[@]}" "$OS_NAME" 2>/dev/null \
            | awk 'NR>1 && $1 ~ /^[0-9]+$/ {print $1, $3}' | sort -rn | head -1 | awk '{print $2}')
        if [[ "$latest_status" == "Failed" ]]; then
            echo "error: policy validation failed" >&2
            openshell policy list "${GW_FLAG[@]}" "$OS_NAME" >&2
            exit 1
        fi
        if [[ "$latest_status" == "Loaded" || "$latest_status" == "Effective" ]]; then
            break
        fi
        sleep 1
        elapsed=$((elapsed + 1))
        if [[ $elapsed -ge 30 ]]; then
            echo "error: policy update not applied within 30s" >&2
            openshell policy list "${GW_FLAG[@]}" "$OS_NAME" >&2
            exit 1
        fi
    done
    fi
    # Refresh the sandbox's copy so it does not describe the previous policy.
    upload_static "$OS_NAME" "${SANDBOXES_DIR}/${POLICY_TARGET}"
    echo "done." >&2
    exit 0
fi

# ---------------------------------------------------------------------------
# Validate --create required when --repo specified
# ---------------------------------------------------------------------------

if [[ -z "$SANDBOX_NAME" && "$NO_CLONE" != true && ${#REPOS[@]} -gt 0 ]]; then
    echo "error: --create required when --repo is specified" >&2
    exit 1
fi

# Everything past this point creates a sandbox. Reaching it without a name
# means no mode flag matched. Without this guard the create path runs with an
# empty name: short_name "" hashes to sb-d41d8cd98f00, render_policy is skipped
# (it is guarded on SANDBOX_NAME), and the unrendered template goes to
# openshell, which rejects "${OTEL_PORT}" as a port.
if [[ -z "$SANDBOX_NAME" ]]; then
    echo "error: no sandbox name — nothing to do. See --help for modes." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Resolve profile from manifest (for --refresh when --profile not on CLI)
# ---------------------------------------------------------------------------

if [[ -z "$SANDBOX_PROFILE" && -n "$SANDBOX_NAME" && -f "${SANDBOXES_DIR}/${SANDBOX_NAME}/manifest.json" ]]; then
    SANDBOX_PROFILE=$(jq -r '.profile // empty' "${SANDBOXES_DIR}/${SANDBOX_NAME}/manifest.json" 2>/dev/null || true)
    if [[ -n "$SANDBOX_PROFILE" ]]; then
        echo "using profile '${SANDBOX_PROFILE}' from manifest" >&2
    fi
fi

# ---------------------------------------------------------------------------
# Resolve policy
# ---------------------------------------------------------------------------

if [[ -z "$POLICY_FILE" ]]; then
    POLICY_FILE="$(policy_for_profile "$SANDBOX_PROFILE")" || exit 1
fi

# Render the template into ~/sandboxes/<name>/openshell-policy.yaml. From here
# on POLICY_FILE is the effective policy, not the template.
if [[ -n "$SANDBOX_NAME" ]]; then
    POLICY_FILE="$(render_policy "$POLICY_FILE" "${SANDBOXES_DIR}/${SANDBOX_NAME}")" || exit 1
fi

# ---------------------------------------------------------------------------
# Generate /sandbox/.env content (runtime env vars)
# ---------------------------------------------------------------------------

# Build active var list based on profile
ACTIVE_VARS=()
case "$SANDBOX_PROFILE" in
    personal)
        ACTIVE_VARS+=("${ANTHROPIC_VARS[@]}" "${CLAUDE_VARS[@]}" "${OTEL_VARS[@]}")
        ;;
    *)
        ACTIVE_VARS+=("${ALL_VARS[@]}")
        ;;
esac

ENV_CONTENT=""
captured=0
for var in "${ACTIVE_VARS[@]}"; do
    if [[ -n "${!var+x}" ]]; then
        ENV_CONTENT+="$(printf '%s=%q' "$var" "${!var}")"$'\n'
        captured=$((captured + 1))
    fi
done

if [[ "$SANDBOX_PROFILE" != "personal" ]]; then
    # JIRA env var aliases — tools use inconsistent names
    if [[ -n "${JIRA_USERNAME+x}" && -z "${JIRA_EMAIL+x}" ]]; then
        ENV_CONTENT+="$(printf 'JIRA_EMAIL=%q' "${JIRA_USERNAME}")"$'\n'
    fi
    if [[ -n "${JIRA_EMAIL+x}" && -z "${JIRA_USERNAME+x}" ]]; then
        ENV_CONTENT+="$(printf 'JIRA_USERNAME=%q' "${JIRA_EMAIL}")"$'\n'
    fi
    if [[ -n "${JIRA_TOKEN+x}" && -z "${JIRA_API_TOKEN+x}" ]]; then
        ENV_CONTENT+="$(printf 'JIRA_API_TOKEN=%q' "${JIRA_TOKEN}")"$'\n'
    fi
    if [[ -n "${JIRA_API_TOKEN+x}" && -z "${JIRA_TOKEN+x}" ]]; then
        ENV_CONTENT+="$(printf 'JIRA_TOKEN=%q' "${JIRA_API_TOKEN}")"$'\n'
    fi

    # Sandbox-scoped JIRA credentials override (read-only scoped token via gateway)
    if [[ -n "${SANDBOX_JIRA_TOKEN+x}" ]]; then
        ENV_CONTENT+="$(printf 'JIRA_TOKEN=%q' "${SANDBOX_JIRA_TOKEN}")"$'\n'
        ENV_CONTENT+="$(printf 'JIRA_API_TOKEN=%q' "${SANDBOX_JIRA_TOKEN}")"$'\n'
        if [[ -n "${SANDBOX_JIRA_EMAIL+x}" ]]; then
            ENV_CONTENT+="$(printf 'JIRA_EMAIL=%q' "${SANDBOX_JIRA_EMAIL}")"$'\n'
            ENV_CONTENT+="$(printf 'JIRA_USERNAME=%q' "${SANDBOX_JIRA_EMAIL}")"$'\n'
        fi
        if [[ -n "${SANDBOX_JIRA_URL+x}" ]]; then
            ENV_CONTENT+="$(printf 'JIRA_URL=%q' "${SANDBOX_JIRA_URL}")"$'\n'
        fi
        if [[ -n "${SANDBOX_JIRA_CLOUD_ID+x}" ]]; then
            ENV_CONTENT+="$(printf 'JIRA_CLOUD_ID=%q' "${SANDBOX_JIRA_CLOUD_ID}")"$'\n'
        fi
    fi

    # Remap credential file paths for sandbox
    if [[ -n "${GOOGLE_APPLICATION_CREDENTIALS+x}" ]]; then
        ENV_CONTENT+=$'\n'"GOOGLE_APPLICATION_CREDENTIALS=/sandbox/.config/gcloud/application_default_credentials.json"
    fi
fi

# Dashboard hooks: relay to host dashboard via container gateway
ENV_CONTENT+="CLAUDE_DASHBOARD_HOST=host.containers.internal"$'\n'

# Telemetry egress. Always written from site.env, overriding anything captured
# from the host env: the host reaches its collector on a host-local address
# and over gRPC, neither of which works from inside a sandbox (gotcha 13).
ENV_CONTENT+="$(printf 'OTEL_EXPORTER_OTLP_ENDPOINT=%q' "$OTEL_URL")"$'\n'
ENV_CONTENT+="OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf"$'\n'

# Telemetry query endpoints — consumed only by validate-profile.sh.
ENV_CONTENT+="$(printf 'SANDBOX_PROMETHEUS_URL=%q' "$PROMETHEUS_URL")"$'\n'
ENV_CONTENT+="$(printf 'SANDBOX_LOKI_URL=%q' "$LOKI_URL")"$'\n'

# Sandbox source directory name for OTEL enrichment
ENV_CONTENT+="$(printf 'SANDBOX_SOURCE_NAME=%q' "${SANDBOX_NAME}")"$'\n'

# Profile-specific OTEL resource attribute tagging
if [[ "$SANDBOX_PROFILE" == "personal" ]]; then
    ENV_CONTENT+="SANDBOX_PROFILE=personal"$'\n'
fi

if [[ $captured -eq 0 ]]; then
    echo "warning: no env vars captured, sandbox will have no credentials" >&2
else
    echo "captured $captured env vars" >&2
fi

if [[ "$DRYRUN" == true ]]; then
    echo "" >&2
    echo "--- .env content (redacted tokens) ---" >&2
    echo "$ENV_CONTENT" | sed 's/\(TOKEN\|KEY\|SECRET\|CREDENTIALS\)=.*/\1=REDACTED/' >&2
    echo "--------------------------------------" >&2
fi

# --- Refresh config on existing sandbox ---
if [[ "$REFRESH_MODE" == true ]]; then
    if [[ "$SANDBOX_PROFILE" != "personal" ]]; then
        ensure_gws_creds
    fi
    OS_NAME=$(resolve_openshell_name "$SANDBOX_NAME")
    echo "refreshing config on ${SANDBOX_NAME}..." >&2
    SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
    upload_config "$OS_NAME" "$SANDBOX_DIR"
    # Regenerate and upload context files for PR repos
    if [[ -f "${SANDBOX_DIR}/manifest.json" ]]; then
        for repo_name in $(jq -r '.repos | keys[]' "${SANDBOX_DIR}/manifest.json"); do
            generate_repo_context "$SANDBOX_DIR" "$repo_name" "${SANDBOX_PROFILE:-}"
            for ctx_file in pr-context.md jira-context.md; do
                if [[ -f "${SANDBOX_DIR}/${repo_name}/${ctx_file}" ]]; then
                    echo "  uploading ${ctx_file} for ${repo_name}..." >&2
                    run openshell sandbox upload "$OS_NAME" "${GW_FLAG[@]}" \
                        "${SANDBOX_DIR}/${repo_name}/${ctx_file}" "/sandbox/source/${repo_name}"
                fi
            done
        done
    fi
    # Upload top-level jira-context.md (Jira-seeded sandboxes, no repos)
    if [[ -f "${SANDBOX_DIR}/jira-context.md" ]]; then
        echo "  uploading jira-context.md..." >&2
        JIRA_TMP="$(mktemp -d)"
        mkdir -p "${JIRA_TMP}/source"
        cp "${SANDBOX_DIR}/jira-context.md" "${JIRA_TMP}/source/jira-context.md"
        run openshell sandbox upload "$OS_NAME" "${GW_FLAG[@]}" \
            "${JIRA_TMP}/source" /sandbox
        rm -rf "$JIRA_TMP"
    fi
    echo "done. reconnect to apply (sandbox.sh --connect)" >&2
    exit 0
fi

# ---------------------------------------------------------------------------
# Create sandbox
# ---------------------------------------------------------------------------

if [[ "$SANDBOX_PROFILE" != "personal" ]]; then
    ensure_gws_creds
fi

OPENSHELL_NAME=$(short_name "$SANDBOX_NAME")

CREATE_CMD=(openshell sandbox create "${GW_FLAG[@]}" --no-auto-providers --keep)

if [[ -n "$OPENSHELL_NAME" ]]; then
    CREATE_CMD+=(--name "$OPENSHELL_NAME")
fi

CREATE_CMD+=(--policy "$POLICY_FILE")
CREATE_CMD+=(--from "openshell-sandbox:latest")
CREATE_CMD+=(--label "source.directory=${SANDBOX_NAME}")

SANDBOX_TARGET="${OPENSHELL_NAME:-}"

echo "creating sandbox '${SANDBOX_NAME}' (openshell: ${OPENSHELL_NAME})..." >&2
echo "  policy:  ${POLICY_FILE}" >&2
echo "" >&2

# sandbox create hangs on SSH connect (podman driver issue).
# Run in background, poll for sandbox, then use sandbox exec.
if [[ "$DRYRUN" == true ]]; then
    run "${CREATE_CMD[@]}"
    run echo "(poll openshell sandbox list until Ready)"
else
    CREATE_LOG="$(mktemp)"
    "${CREATE_CMD[@]}" &>"$CREATE_LOG" &
    CREATE_PID=$!

    elapsed=0
    while true; do
        if ! kill -0 "$CREATE_PID" 2>/dev/null; then
            if ! wait "$CREATE_PID" 2>/dev/null; then
                echo "error: sandbox create failed:" >&2
                cat "$CREATE_LOG" >&2
                rm -f "$CREATE_LOG"
                exit 1
            fi
        fi
        if openshell sandbox list "${GW_FLAG[@]}" 2>/dev/null | grep -q "^${SANDBOX_TARGET}[[:space:]].*Ready"; then
            break
        fi
        sleep 1
        elapsed=$((elapsed + 1))
        if [[ $elapsed -ge 120 ]]; then
            kill "$CREATE_PID" 2>/dev/null || true
            echo "error: sandbox did not reach Ready within 120s" >&2
            cat "$CREATE_LOG" >&2
            rm -f "$CREATE_LOG"
            exit 1
        fi
    done

    kill "$CREATE_PID" 2>/dev/null || true
    wait "$CREATE_PID" 2>/dev/null || true
    rm -f "$CREATE_LOG"
fi

# Create host-side state directory (full name, not short)
if [[ -n "$SANDBOX_NAME" ]]; then
    mkdir -p "${SANDBOXES_DIR}/${SANDBOX_NAME}"
fi

# Update profile in manifest (handles --recreate with --no-clone where write_manifest is never called)
if [[ -n "$SANDBOX_PROFILE" && -f "${SANDBOXES_DIR}/${SANDBOX_NAME}/manifest.json" ]]; then
    jq --arg profile "$SANDBOX_PROFILE" '.profile = $profile' \
        "${SANDBOXES_DIR}/${SANDBOX_NAME}/manifest.json" > "${SANDBOXES_DIR}/${SANDBOX_NAME}/manifest.json.tmp"
    mv "${SANDBOXES_DIR}/${SANDBOX_NAME}/manifest.json.tmp" "${SANDBOXES_DIR}/${SANDBOX_NAME}/manifest.json"
fi

# ---------------------------------------------------------------------------
# Upload credentials
# ---------------------------------------------------------------------------

echo "uploading credentials..." >&2

if [[ "$SANDBOX_PROFILE" != "personal" && -d "${HOME}/.config/gcloud" ]]; then
    run openshell sandbox upload "${SANDBOX_TARGET}" "${GW_FLAG[@]}" \
        "${HOME}/.config/gcloud" /sandbox/.config
fi

upload_config "${SANDBOX_TARGET}" "${SANDBOXES_DIR}/${SANDBOX_NAME}"

# Restore prior claude session state if available
upload_claude_state "$SANDBOX_TARGET" "${SANDBOXES_DIR}/${SANDBOX_NAME}"

# ---------------------------------------------------------------------------
# Clone repos on host and upload to sandbox
# ---------------------------------------------------------------------------

if [[ "$NO_CLONE" != true && ${#REPOS[@]} -eq 0 ]]; then
    current_remote=$(git remote get-url origin 2>/dev/null || true)
    if [[ -n "$current_remote" ]]; then
        REPOS+=("$current_remote")
        REFS+=("")
    fi
fi

WORKDIR="/sandbox"
if [[ "$NO_CLONE" != true && ${#REPOS[@]} -gt 0 ]]; then
    SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
    mkdir -p "$SANDBOX_DIR"

    echo "cloning repos on host..." >&2
    for i in "${!REPOS[@]}"; do
        repo="${REPOS[$i]}"
        ref="${REFS[$i]:-}"
        repo_name=$(basename "$repo" .git)

        echo "  ${repo_name}${ref:+ (${ref})}" >&2
        clone_repo_host "$repo" "$ref" "$SANDBOX_DIR"

        sha=$(git -C "${SANDBOX_DIR}/${repo_name}" rev-parse HEAD)
        write_manifest "$SANDBOX_DIR" "$SANDBOX_NAME" "$repo_name" "$repo" "$ref" "$sha"
    done

    echo "uploading repos to sandbox..." >&2
    for i in "${!REPOS[@]}"; do
        repo="${REPOS[$i]}"
        repo_name=$(basename "$repo" .git)
        echo "  uploading ${repo_name}..." >&2
        upload_repo "$SANDBOX_TARGET" "$SANDBOX_DIR" "$repo_name"
    done

    WORKDIR="/sandbox/source/"
fi

# Upload jira-context.md if present (generated by scode for Jira-seeded sandboxes)
SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
if [[ -f "${SANDBOX_DIR}/jira-context.md" ]]; then
    echo "uploading jira-context.md..." >&2
    JIRA_TMP="$(mktemp -d)"
    mkdir -p "${JIRA_TMP}/source"
    cp "${SANDBOX_DIR}/jira-context.md" "${JIRA_TMP}/source/jira-context.md"
    run openshell sandbox upload "$SANDBOX_TARGET" "${GW_FLAG[@]}" \
        "${JIRA_TMP}/source" /sandbox
    rm -rf "$JIRA_TMP"
    WORKDIR="/sandbox/source/"
fi

# ---------------------------------------------------------------------------
# Start Claude Code
# ---------------------------------------------------------------------------

if [[ "$NO_CONNECT" == true ]]; then
    echo "sandbox ready. connect with: sandbox.sh --connect ${SANDBOX_NAME}" >&2
    exit 0
fi

echo "starting claude in ${WORKDIR}..." >&2
connect_sandbox "$SANDBOX_TARGET" "$WORKDIR"
exit $?
