#!/bin/bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Create and manage OpenShell sandboxes with Claude Code.
# Captures env vars, uploads credentials and ~/.claude/ config,
# clones repos on host, uploads to sandbox, and starts Claude in auto mode.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SANDBOXES_DIR="${HOME}/sandboxes"

# ---------------------------------------------------------------------------
# Site config — where this host sends telemetry. See config/site.env.example.
# Loaded before anything resolves a policy, because policies reference it.
# ---------------------------------------------------------------------------

SITE_ENV="${REPO_ROOT}/config/site.env"
if [[ ! -f "$SITE_ENV" ]]; then
    cat >&2 <<EOF
error: ${SITE_ENV} does not exist.

    cp ${REPO_ROOT}/config/site.env.example ${SITE_ENV}
    \$EDITOR ${SITE_ENV}

It describes where THIS HOST sends and reads Claude Code telemetry. It is not
created automatically: the template's values are one site's, and silently
adopting them would point a sandbox at a collector that may not exist here.
EOF
    exit 1
fi
set -a
# shellcheck disable=SC1090
source "$SITE_ENV"
set +a

# All three are required. A missing URL would make validate-profile.sh skip
# that check, and a skipped check is indistinguishable from a passing one.
for site_var in OTEL_URL PROMETHEUS_URL LOKI_URL; do
    if [[ -z "${!site_var:-}" ]]; then
        echo "Error: ${site_var} not set in ${SITE_ENV} (all values are required)" >&2
        exit 1
    fi
done

# Policy blocks need a host and a port. site.env stores URLs — the richer
# form, carrying scheme and path — and the pair is derived from it. Storing
# both would be the same value twice, free to drift, with nothing checking it.
eval "$(python3 - "$OTEL_URL" "$PROMETHEUS_URL" "$LOKI_URL" <<'PY'
import sys, urllib.parse
for name, url in (("OTEL", sys.argv[1]), ("PROMETHEUS", sys.argv[2]), ("LOKI", sys.argv[3])):
    parts = urllib.parse.urlsplit(url)
    port = parts.port or (443 if parts.scheme == "https" else 80)
    print(f"{name}_HOST={parts.hostname}")
    print(f"{name}_PORT={port}")
PY
)"
GWS_SANDBOX_SCOPES="https://www.googleapis.com/auth/calendar.readonly,https://www.googleapis.com/auth/directory.readonly,https://www.googleapis.com/auth/documents.readonly,https://www.googleapis.com/auth/drive.readonly,https://www.googleapis.com/auth/gmail.readonly,https://www.googleapis.com/auth/meetings.space.readonly,https://www.googleapis.com/auth/presentations.readonly,https://www.googleapis.com/auth/spreadsheets.readonly,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile"

# Defaults
DRYRUN=false
DEBUG=false
SANDBOX_NAME=""
CONNECT_NAME=""
HARNESS=""
DELETE_NAME=""
LIST_MODE=false
FETCH_SERVICE_MODE=false
NO_CLONE=false
NO_CONNECT=false
DOWNLOAD_MODE=false
UPLOAD_MODE=false
FORCE_MODE=false
ADD_REPO_MODE=false
CREATE_MODE=false
ENSURE_MODE=false
REFRESH_MODE=false
RECREATE_MODE=false
ALL_MODE=false
GATEWAY=""
POLICY_FILE=""
SANDBOX_PROFILE=""
PROFILE_FROM_CLI=false
SOURCE_DIR=""
REPOS=()
REFS=()

# ---------------------------------------------------------------------------
# Env var groups — add new groups as needed
# ---------------------------------------------------------------------------

ANTHROPIC_VARS=(
    ANTHROPIC_API_KEY
)

VERTEX_VARS=(
    CLAUDE_CODE_USE_VERTEX
    CLOUD_ML_REGION
    ANTHROPIC_VERTEX_PROJECT_ID
    GOOGLE_APPLICATION_CREDENTIALS
    GOOGLE_CLOUD_PROJECT
    CLOUDSDK_CONFIG
)

JIRA_VARS=(
    JIRA_USERNAME
    JIRA_EMAIL
    JIRA_API_TOKEN
    JIRA_TOKEN
    JIRA_URL
    JIRA_CLOUD_ID
)


CLAUDE_VARS=(
    CLAUDE_CODE_MAX_TURNS
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC
    CLAUDE_CODE_USE_BEDROCK
)

# No OTEL_VARS list: nothing telemetry-related is captured from the host env.
#
# Two kinds of value used to be in here and neither belongs. The exporter
# selections, intervals, toggles and log-detail flags are a decision about how
# the agent behaves inside the container — container policy, which config/bashrc
# owns, and which a host's local preference must not silently change. The
# endpoint, protocol and resource attributes are host knowledge, but they are
# written unconditionally further down from site.env and the sandbox's own
# identity, which always overrode whatever capture produced anyway.
#
# OTEL_RESOURCE_ATTRIBUTES specifically must never be captured: the host's value
# names the host's project and session, so every attribute in it is wrong here.

ALL_VARS=(
    "${ANTHROPIC_VARS[@]}"
    "${VERTEX_VARS[@]}"
    "${JIRA_VARS[@]}"
    "${CLAUDE_VARS[@]}"
)

# ---------------------------------------------------------------------------
# Infer sandbox name from CWD if under ~/sandboxes/<name>/
# ---------------------------------------------------------------------------

infer_sandbox_name() {
    local cwd
    cwd="$(pwd)"
    if [[ "$cwd" == "${SANDBOXES_DIR}/"* ]]; then
        local relative="${cwd#${SANDBOXES_DIR}/}"
        echo "${relative%%/*}"
        return 0
    fi
    return 1
}

# ---------------------------------------------------------------------------
# Usage
# ---------------------------------------------------------------------------

usage() {
    cat >&2 <<EOF
Usage: $(basename "$0") [OPTIONS] [-- CLAUDE_ARGS...]

Create an OpenShell sandbox running Claude Code in auto mode.

OPTIONS:
    --create NAME     Create sandbox with this name
    --ensure [NAME]   Create sandbox if missing, reconnect if exists (use with --repo/--ref)
    --repo URL        Git repo to clone on host and upload (repeatable)
    --ref REF         Ref for preceding --repo: branch, pr/<num>, tag/<name>, or SHA
    --source-dir DIR  Derive origin URL from local repo checkout
    --add-repo [NAME] Add repo(s) to existing sandbox (use --repo for URL)
    --download [NAME] Download repos from sandbox to ~/sandboxes/<name>/
    --upload [NAME]   Upload local repo changes back into sandbox
    -f, --force       With --upload/--download: transfer every repo and
                      regenerate context, not only what changed
    --policy NAME     Policy name or path (e.g. research). Standalone: hot-swap on running sandbox
    --profile NAME    Credential profile: work, personal, home, or codex. Controls env vars, uploads,
                      and the policy of the same name. REQUIRED with --create and --recreate.
                      Only valid with --create, --recreate, or --ensure — applied at build, not after
    --gateway NAME    OpenShell gateway (default: \$OPENSHELL_GATEWAY)
    --refresh [NAME]  Re-upload ~/.claude/, bin/, .bashrc, .env, system prompt
    --recreate [NAME] Download, delete sandbox container, recreate with new image, re-upload repos
    --all             With --refresh/--recreate: apply to every sandbox in ~/sandboxes/
                      instead of one NAME. --recreate --all never connects.
    --connect [NAME]  Reconnect to an existing sandbox
    --harness NAME    Agent to launch: claude or codex. Recorded in
                      manifest.json and reused by later --connect/--recreate.
                      Valid with --create, --connect and --recreate. Omitted,
                      the wrapper prompts with the remembered value; each
                      harness has its own dtach socket, so both can be live in
                      one sandbox.
    --delete [NAME]   Delete a sandbox and local state

    NAME is optional for commands marked [NAME] when CWD is under ~/sandboxes/<name>/.
    --no-clone        Skip repo cloning (create sandbox with env + config only)
    --list            List sandboxes
    --fetch-service   Start the outbound fetch service, follow its log, stop it on exit
    --dryrun          Print commands instead of running them
    --debug           Show all commands as they run (set -x)
    --help            Show this help

EXAMPLES:
    $(basename "$0") --create myapp --profile work --repo git@github.com:org/myapp.git --ref pr/42
    $(basename "$0") --ensure myapp-pr-42 --profile work --repo git@github.com:org/myapp.git --ref pr/42
    $(basename "$0") --add-repo myapp --repo git@github.com:org/lib.git --ref v2.0
    $(basename "$0") --add-repo myapp --repo git@github.com:org/ui.git --source-dir ~/source/ui
    $(basename "$0") --download myapp
    $(basename "$0") --download myapp --force
    $(basename "$0") --upload myapp --repo myapp
    $(basename "$0") --upload myapp --force
    $(basename "$0") --connect myapp
    $(basename "$0") --connect myapp --harness codex
    $(basename "$0") --recreate myapp --profile work --harness codex
    $(basename "$0") --delete myapp
    $(basename "$0") --refresh --all
    $(basename "$0") --recreate --all
EOF
    exit "${1:-0}"
}

# ---------------------------------------------------------------------------
# Ensure gws sandbox credentials are valid (interactive — may open browser)
# ---------------------------------------------------------------------------

ensure_gws_creds() {
    command -v gws &>/dev/null || return 0
    local gws_dir="${HOME}/.config/gws-sandbox"
    if [[ -f "${gws_dir}/credentials.enc" ]]; then
        local valid
        valid=$(GOOGLE_WORKSPACE_CLI_CONFIG_DIR="$gws_dir" gws auth status 2>/dev/null | jq -r '.token_valid // false')
        if [[ "$valid" == "true" ]]; then
            echo "gws sandbox credentials valid" >&2
        else
            echo "gws sandbox credentials expired, re-authenticating..." >&2
            GOOGLE_WORKSPACE_CLI_CONFIG_DIR="$gws_dir" gws auth login --scopes "$GWS_SANDBOX_SCOPES"
        fi
    else
        echo "gws sandbox credentials not found, authenticating (readonly)..." >&2
        mkdir -p "$gws_dir"
        if [[ -f "${HOME}/.config/gws/client_secret.json" ]]; then
            cp "${HOME}/.config/gws/client_secret.json" "${gws_dir}/"
        fi
        GOOGLE_WORKSPACE_CLI_CONFIG_DIR="$gws_dir" gws auth login --scopes "$GWS_SANDBOX_SCOPES"
    fi
}

# ---------------------------------------------------------------------------
# Generate PR + Jira context for sandbox repos
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Connect to sandbox via exec
# ---------------------------------------------------------------------------

connect_sandbox() {
    local os_name="$1" workdir="$2" harness="${3:-}" sandbox_dir="${4:-}"
    # bin/ ships on every connect, unconditionally. This function execs the
    # wrapper by absolute path, so a sandbox whose copy is older than this
    # script fails here with a bare "No such file or directory", or ignores an
    # argument it does not know and silently starts the wrong agent. Two small
    # files; do not make it conditional.
    run openshell sandbox upload "$os_name" "${GW_FLAG[@]}" \
        "${REPO_ROOT}/bin" /sandbox
    # Two channels, because they mean different things. An explicit --harness is
    # a decision already made, so it goes as argv and the wrapper skips its
    # prompt. The manifest's remembered value is only a suggestion, so it goes
    # as $HARNESS_DEFAULT and the wrapper prompts with it preselected.
    local forced="" default=""
    if [[ -n "$harness" ]]; then
        forced="$harness"
    else
        default="$(manifest_harness "$sandbox_dir")"
        valid_harness "$default" || default=""
    fi
    run exec openshell sandbox exec --name "${os_name}" "${GW_FLAG[@]}" \
        --tty --timeout 0 -- bash -c "(while sleep 30; do printf '\\005' 2>/dev/null; done) & source /sandbox/.bashrc && cd ${workdir} && HARNESS_DEFAULT=${default} /sandbox/bin/harness-wrapper.sh ${forced}"
}

sandbox_phase() {
    openshell sandbox list "${GW_FLAG[@]}" --output json 2>/dev/null \
        | jq -r --arg n "$1" '.[] | select(.name == $n) | .phase'
}

# An Error-phase sandbox is a stopped container, and `sandbox exec` fails
# against one — so does `sandbox upload`/`download`. Start it the way
# claude-dashboard does on click of an error row: podman start, by openshell's
# own label (same lookup as mint-sandbox-tokens.sh).
#
# Returns non-zero rather than exiting so the caller's `|| exit 1` is visible
# at the call site. Every caller stops — --recreate included, because its next
# step deletes the container the download was supposed to drain.
start_error_sandbox() {
    local os_name="$1" cid elapsed=0
    [[ "$(sandbox_phase "$os_name")" == "Error" ]] || return 0

    cid=$(podman ps -a --format json 2>/dev/null \
        | jq -r --arg n "$os_name" '.[] | select(.Labels["openshell.ai/sandbox-name"] == $n) | .Id' | head -1)
    if [[ -z "$cid" ]]; then
        echo "Error: sandbox '${os_name}' is in Error phase with no container — recreate it" >&2
        return 1
    fi

    echo "Sandbox in Error phase, starting container..." >&2
    run podman start "$cid" >/dev/null
    [[ "$DRYRUN" == true ]] && return 0

    # Wait on openshell's phase, not podman's: exec goes through openshell.
    while [[ "$(sandbox_phase "$os_name")" != "Ready" ]]; do
        elapsed=$((elapsed + 1))
        if [[ $elapsed -ge 30 ]]; then
            echo "Error: sandbox '${os_name}' not Ready 30s after start" >&2
            return 1
        fi
        sleep 1
    done
}

# ---------------------------------------------------------------------------
# Name resolution (short_name lives in lib.sh — scode needs it too)
# ---------------------------------------------------------------------------

# Resolve full name → openshell name from manifest
resolve_openshell_name() {
    local name="$1"
    local manifest="${SANDBOXES_DIR}/${name}/manifest.json"
    if [[ -f "$manifest" ]]; then
        local os_name
        os_name=$(jq -r '.openshell_name // empty' "$manifest")
        if [[ -n "$os_name" ]]; then
            echo "$os_name"
            return
        fi
    fi
    # No manifest — fall back to short_name for pre-existing sandboxes
    short_name "$name"
}

# Resolve openshell name → full name by scanning manifests
resolve_full_name() {
    local os_name="$1"
    local manifest
    for manifest in "${SANDBOXES_DIR}"/*/manifest.json; do
        [[ -f "$manifest" ]] || continue
        local stored
        stored=$(jq -r '.openshell_name // empty' "$manifest")
        if [[ "$stored" == "$os_name" ]]; then
            jq -r '.name' "$manifest"
            return
        fi
    done
    echo "$os_name"
}

# ---------------------------------------------------------------------------
# Dry-run wrapper — prints command instead of running it
# ---------------------------------------------------------------------------

run() {
    if [[ "$DRYRUN" == true ]]; then
        echo "[dryrun]: $*" >&2
        # exec would replace process — exit cleanly in dryrun
        if [[ "$1" == "exec" ]]; then
            exit 0
        fi
        return 0
    fi
    "$@"
}

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

source "${SCRIPT_DIR}/lib.sh"

# Run an openshell transfer and report it in one line.
#
# openshell narrates every transfer twice: `Uploading <host path> -> sandbox:...`
# (or `Downloading sandbox:... -> <local>`) and then its own `✓ Upload complete`.
# Both are noise here. The paths are this script's own arguments, and on the
# download side the destination is a mktemp staging dir nobody asked about; the
# completion line names nothing at all, so consecutive ones read as
# "complete — what?". Both are dropped and replaced by $label, which names the
# thing. openshell's indented `  Uploading [n/m] files ...` progress lines do not
# match the filter, so a big repo still shows movement while it transfers.
#
# An empty $label prints nothing, for a caller reporting a group of transfers
# once rather than each in turn.
#
# A pipeline, not `2> >(...)`: bash waits for every element of a pipeline, so a
# filtered line cannot land after the next transfer's. The `|| true` is scoped to
# the grep alone — a no-match grep exits 1 and must not read as failure, while
# openshell's own status still reaches `set -o pipefail`, which is what keeps a
# failed upload from going on to stamp last_upload.
transfer_quiet() {
    local label="$1"
    shift
    { { "$@"; } 2>&1 1>&3 \
        | { grep --line-buffered -Ev \
                '^(Uploading|Downloading) .*sandbox:|(Upload|Download) complete$' >&2 \
            || true; } } 3>&1
    [[ -z "$label" || "$DRYRUN" == true ]] || echo "${MARK_OK} ${label}" >&2
}

clone_repo_host() {
    local url="$1" ref="$2" sandbox_dir="$3"
    local repo_name
    repo_name=$(basename "$url" .git)
    local target="${sandbox_dir}/${repo_name}"

    if [[ -d "$target" ]]; then
        echo "${MARK_SKIP} Clone skipped — ${repo_name} already cloned" >&2
        return 0
    fi

    # Strip trailing slash — gh CLI fails to resolve repo name with it
    local clean_url="${url%/}"
    guard_private_repo "$clean_url"
    run git clone "$clean_url" "$target"

    if [[ -n "$ref" ]]; then
        if [[ "$ref" =~ ^pr/([0-9]+)$ ]]; then
            checkout_pr "$target" "${BASH_REMATCH[1]}"
        elif [[ "$ref" =~ ^tag/ ]]; then
            run git -C "$target" checkout "tags/${ref#tag/}"
        else
            if ! run git -C "$target" checkout "$ref" 2>/dev/null; then
                echo "Warning: ref '${ref}' not found, using default branch" >&2
            fi
        fi
    fi
}

upload_repo() {
    local sandbox_name="$1" sandbox_dir="$2" repo_name="$3"
    # Pre-delete to avoid tar type conflicts (symlink vs dir) on re-upload
    if [[ -z "$repo_name" ]]; then
        echo "Error: upload_repo called with empty repo_name" >&2
        return 1
    fi
    # Resolve profile from manifest if not set (covers --upload sub-invocations)
    local effective_profile="$SANDBOX_PROFILE"
    if [[ -z "$effective_profile" && -f "${sandbox_dir}/manifest.json" ]]; then
        effective_profile=$(jq -r '.profile // empty' "${sandbox_dir}/manifest.json" 2>/dev/null || true)
    fi
    # Personal/home profiles: block private repos
    if personal_profile "$effective_profile" && [[ -d "${sandbox_dir}/${repo_name}/.git" ]]; then
        local origin_url
        origin_url=$(git -C "${sandbox_dir}/${repo_name}" remote get-url origin 2>/dev/null || true)
        if [[ -n "$origin_url" ]]; then
            guard_private_repo "$origin_url"
        fi
    fi
    # Default: skip the per-repo gh and Jira calls, and skip any repo the host
    # has not touched since its last upload. Fast, and trusts the sandbox copy.
    #
    # --force is the opposite bargain: send even when the host copy has not
    # changed. upload_repo() rm -rf's the sandbox copy first, so --force is how
    # a session's edits inside the sandbox get wiped back to host state — the
    # default path assumes host and sandbox agree, which is the one thing
    # --force cannot assume.
    #
    # No caller announces the repo. They used to, before the decision was made,
    # so every skipped repo printed "uploading X..." directly above the line
    # saying it was not uploading X — and the four call sites had drifted to two
    # different indents. openshell announces a repo that really uploads; one that
    # does not is a single ⊘ line here.
    local why=""
    if [[ "$FORCE_MODE" == true ]]; then
        generate_repo_context "$sandbox_dir" "$repo_name" "${effective_profile:-${SANDBOX_PROFILE:-}}"
    elif why=$(repo_changed_since_upload "$sandbox_dir" "$repo_name" 2>&1); then
        : # held until the upload finishes, then hung off the ✓ line below
    else
        echo "${MARK_SKIP} Upload skipped — ${repo_name} unchanged locally (--force to send)" >&2
        return 0
    fi

    run openshell sandbox exec --name "$sandbox_name" "${GW_FLAG[@]}" \
        -- rm -rf "/sandbox/source/${repo_name}" 2>/dev/null || true
    transfer_quiet "Upload complete — ${repo_name}${why:+ ${why}}" \
        run openshell sandbox upload "$sandbox_name" "${GW_FLAG[@]}" \
            --no-git-ignore \
            "${sandbox_dir}/${repo_name}" /sandbox/source/

    # Only a real upload earns a stamp; a dryrun that stamped would make the
    # next real run skip a repo it never sent.
    [[ "$DRYRUN" == true ]] || record_repo_timestamp "$sandbox_dir" "$repo_name" last_upload
}

write_manifest() {
    local sandbox_dir="$1" sandbox_name="$2" repo_name="$3"
    local url="$4" ref="$5" sha="$6"
    local manifest="${sandbox_dir}/manifest.json"
    local now
    now=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

    # Skeleton + profile (profile update handles recreate on another profile)
    init_manifest "$sandbox_dir" "$sandbox_name" "$SANDBOX_PROFILE" "$HARNESS"

    jq \
        --arg repo "$repo_name" \
        --arg url "$url" \
        --arg ref "$ref" \
        --arg sha "$sha" \
        --arg ts "$now" \
        '.repos[$repo] = (.repos[$repo] // {}) + {url: $url, ref: $ref, sha: $sha, cloned_at: $ts}' \
        "$manifest" > "${manifest}.tmp"
    mv "${manifest}.tmp" "$manifest"
}

# Names the repos the sandbox has NOT touched since host and sandbox were last
# known equal — the mirror of repo_changed_since_upload(), run on the side that
# actually knows. The upload side reads host mtimes; there is no host-side
# equivalent for the sandbox, and downloading a repo to find out whether it was
# worth downloading is the cost being avoided.
#
# One exec for every repo, not one per repo: the walk is cheap and the round
# trip is not.
#
# Fail-safe runs the other way from the upload side. A wrongly skipped upload
# costs one redundant tar; a wrongly skipped download loses whatever the
# session did. So a repo is clean only on a positive empty walk — the `WALKED`
# sentinel separates "found nothing" from "the exec never ran", which both
# otherwise print nothing. No sentinel, no skip.
sandbox_clean_repos() {
    local os_name="$1" sandbox_dir="$2"
    local script="" repo since out

    # The reference is the LATEST of the two stamps: both mark a moment the two
    # copies agreed. A skipped upload deliberately does not stamp, so this
    # cannot advance past a divergence it never resolved.
    while IFS=$'\t' read -r repo since; do
        [[ -n "$since" ]] || continue
        script+="check $(printf '%q' "$repo") $(printf '%q' "$since")"$'\n'
    done < <(jq -r '.repos | to_entries[] |
        [.key, ([.value.last_upload, .value.last_download]
                | map(select(. != null)) | max // "")] | @tsv' \
        "${sandbox_dir}/manifest.json")
    [[ -n "$script" ]] || return 0

    # Same three exclusions as the upload walk: `git status` rewrites exactly
    # `.git`, `.git/index` and `.git/index.lock` and nothing else, so a session
    # with a status-polling prompt would otherwise report every repo dirty.
    #
    # `.venv` is pruned, not merely skipped, and the reason is downstream: the
    # rsync in download_sandbox() drops it on arrival, so it is the one thing a
    # walk can find that cannot possibly change the host copy. Letting it decide
    # meant a repo with a live virtualenv was dirty on every check — one pip
    # install or one `python` run rewriting a `.pyc` — and each verdict dragged
    # the whole venv over the wire to be discarded. Skipping such a repo loses
    # nothing, because there was nothing in it the host was ever going to keep.
    # -prune also stops the walk descending it at all, which is most of the
    # inodes in a Python repo.
    out=$(openshell sandbox exec --name "$os_name" "${GW_FLAG[@]}" -- bash -c '
check() {
    d="/sandbox/source/$1"
    [ -d "$d" ] || return 0
    n=$(find "$d" -name .venv -prune -o -newermt "$2" \
        ! -path "$d/.git" ! -path "$d/.git/index" ! -path "$d/.git/index.lock" \
        -print -quit 2>/dev/null)
    [ -n "$n" ] || echo "CLEAN $1"
}
'"$script"'
echo WALKED' 2>/dev/null) || return 0

    [[ "$out" == *WALKED* ]] || return 0
    awk '/^CLEAN /{print $2}' <<<"$out"
}

download_sandbox() {
    local sandbox_name="$1" sandbox_dir="$2"
    local manifest="${sandbox_dir}/manifest.json"

    if [[ ! -f "$manifest" ]]; then
        echo "Error: no manifest at ${manifest}" >&2
        exit 1
    fi

    local repos
    repos=$(jq -r '.repos | keys[]' "$manifest")

    # --force always pulls, the same bargain --upload --force takes: it is the
    # path that assumes nothing about what the other side holds.
    local clean=""
    if [[ "$FORCE_MODE" != true && "$DRYRUN" != true ]]; then
        clean=" $(sandbox_clean_repos "$sandbox_name" "$sandbox_dir" | tr '\n' ' ')"
    fi

    local dl_tmp
    dl_tmp="$(mktemp -d)"
    for repo_name in $repos; do
        if [[ "$clean" == *" ${repo_name} "* ]]; then
            echo "${MARK_SKIP} Download skipped — ${repo_name} unchanged in the sandbox (--force to pull)" >&2
            continue
        fi
        # tar at the source, pull one file, unpack here. `openshell sandbox
        # download` takes a path and a destination and nothing else — no
        # exclude, no filter (openshell-cli/src/main.rs, the Download
        # subcommand) — so pulling the directory sent every regenerable tree in
        # it across the wire for the rsync below to discard on arrival. On a
        # real repo that was a 1.1G .venv inside a 2.4G transfer. tar applies
        # the same exclusion at the source, so what gets thrown away is never
        # sent.
        #
        # One exclusion, matching the rsync's, and deliberately no list: git's
        # ignore rules would drop untracked work the host wants, and a
        # hardcoded set is both incomplete and wrong the moment a virtualenv is
        # not called .venv. This costs nothing to be wrong about — an
        # unexcluded tree is transferred, which is exactly today's behavior.
        #
        # Uncompressed on purpose. The link is a loopback gRPC channel to a
        # local container, .git/objects is already compressed, and gzip is one
        # core against a transfer that may not be bandwidth-bound at all. There
        # is 186G free, so the tarball costs only disk. `cf`/`xf` -> `czf`/`xzf`
        # in the two places below if measurement says otherwise.
        #
        # It is staged in /sandbox/source, NOT /tmp. `sandbox download` resolves
        # its source against the workspace root it discovers with `pwd -P` and
        # refuses anything outside it (openshell-cli/src/ssh.rs,
        # validate_sandbox_source_path) — a Landlock read_write entry for /tmp
        # does not enter into it, they are different gates. The repo pulls that
        # already work prove /sandbox/source/<repo> is inside that root, so a
        # sibling of the repos is too, whether the root turns out to be
        # /sandbox or /sandbox/source. It is a sibling and not inside the repo
        # so that tar is not writing into the tree it is reading.
        #
        # A failed transfer leaves the tarball in the sandbox, where a session
        # will see it. The name is derived from the repo, so the next attempt
        # truncates it rather than accumulating.
        local tarball="/sandbox/source/openshell-dl-${repo_name}.tar"
        run openshell sandbox exec --name "$sandbox_name" "${GW_FLAG[@]}" \
            -- tar cf "$tarball" -C /sandbox/source --exclude=.venv "$repo_name"
        transfer_quiet "Download complete — ${repo_name}" \
            run openshell sandbox download "$sandbox_name" "${GW_FLAG[@]}" \
                "$tarball" "$dl_tmp"
        run openshell sandbox exec --name "$sandbox_name" "${GW_FLAG[@]}" \
            -- rm -f "$tarball"
        # Members are ${repo_name}/..., so this lands where the rsync expects.
        run tar xf "${dl_tmp}/openshell-dl-${repo_name}.tar" -C "$dl_tmp"
        mkdir -p "${sandbox_dir}/${repo_name}"
        # Content decides what gets written, not timestamps. tar does preserve
        # mtimes, so the original hazard here is gone — but the flags stay,
        # because what they actually protect is the host copy of a file the
        # sandbox never touched, and that is unchanged. Before the tar,
        # `openshell sandbox download` did not preserve mtimes, so under a
        # plain `rsync -a` every downloaded file looked newer, rsync rewrote
        # all of them, and the whole
        # repo came out newer than .repos[<name>].last_upload — which made the
        # next `--upload` re-send everything. Edit in the sandbox, download,
        # upload is the usual pattern, so the upload skip had nothing left to
        # skip. `--checksum` alone does not fix it: for a file whose content
        # matches it still does an attribute-only mtime update. `--no-times`
        # is what leaves the untransferred file alone; a file that really
        # changed gets the current time, which is what the walk wants to see.
        # Costs a full read of both trees, against a download that just moved
        # the same bytes over the network.
        run rsync -a --no-times --checksum --delete --exclude=.venv \
            "${dl_tmp}/${repo_name}/" "${sandbox_dir}/${repo_name}/"
        [[ "$DRYRUN" == true ]] || record_repo_timestamp "$sandbox_dir" "$repo_name" last_download
    done
    rm -rf "$dl_tmp"
}

upload_sandbox() {
    local sandbox_name="$1" sandbox_dir="$2" target_repo="${3:-}"
    local manifest="${sandbox_dir}/manifest.json"

    if [[ ! -f "$manifest" ]]; then
        echo "Error: no manifest at ${manifest}" >&2
        exit 1
    fi

    if [[ -n "$target_repo" ]]; then
        if [[ ! -d "${sandbox_dir}/${target_repo}" ]]; then
            echo "Error: repo not found at ${sandbox_dir}/${target_repo}" >&2
            exit 1
        fi
        upload_repo "$sandbox_name" "$sandbox_dir" "$target_repo"
    else
        local repos
        repos=$(jq -r '.repos | keys[]' "$manifest")
        for repo_name in $repos; do
            if [[ -d "${sandbox_dir}/${repo_name}" ]]; then
                upload_repo "$sandbox_name" "$sandbox_dir" "$repo_name"
            fi
        done
    fi

    # The manifest is NOT re-uploaded here, and neither is anything else that
    # is not a repo. What --upload changes about manifest.json is the
    # last_upload stamps upload_repo() writes above, which are host bookkeeping
    # for the skip checks — nothing in the sandbox reads them. The fields the
    # sandbox does read (name, profile, repo list) can only change on the paths
    # that call upload_static() themselves.
}

download_claude_state() {
    local sandbox_name="$1" sandbox_dir="$2"
    local claude_dir="${sandbox_dir}/claude"
    local dl_tmp
    dl_tmp="$(mktemp -d)"

    # Three transfers, one line. Each is reported with an empty label so only the
    # group speaks, and what each one preserved is collected and printed under
    # that line rather than as it happens — a detail line has to follow the line
    # it explains, and the ✓ cannot be printed until all three are done.
    local notes=""
    mkdir -p "${dl_tmp}/projects"
    transfer_quiet "" run openshell sandbox download "$sandbox_name" "${GW_FLAG[@]}" \
        "/sandbox/.claude/projects" "${dl_tmp}/projects" || true
    if [[ "$(ls -A "${dl_tmp}/projects" 2>/dev/null)" ]]; then
        mkdir -p "${claude_dir}"
        rsync -a "${dl_tmp}/projects/" "${claude_dir}/projects/"
    fi
    # Preserve OAuth credentials from sandbox
    transfer_quiet "" run openshell sandbox download "$sandbox_name" "${GW_FLAG[@]}" \
        "/sandbox/.claude/.credentials.json" "${dl_tmp}/" || true
    if [[ -f "${dl_tmp}/.credentials.json" ]]; then
        mkdir -p "${claude_dir}"
        cp "${dl_tmp}/.credentials.json" "${claude_dir}/.credentials.json"
        notes+="    preserved OAuth credentials"$'\n'
    fi
    # Preserve .claude.json (auth state)
    transfer_quiet "" run openshell sandbox download "$sandbox_name" "${GW_FLAG[@]}" \
        "/sandbox/.claude.json" "${dl_tmp}/" || true
    if [[ -f "${dl_tmp}/.claude.json" ]]; then
        mkdir -p "${claude_dir}"
        cp "${dl_tmp}/.claude.json" "${claude_dir}/.claude.json"
        notes+="    preserved .claude.json"$'\n'
    fi
    [[ "$DRYRUN" == true ]] || echo "${MARK_OK} Download complete — Claude session state" >&2
    [[ -z "$notes" ]] || printf '%s' "$notes" >&2
    rm -rf "$dl_tmp"
}

# Codex conversation history, preserved across --recreate the way
# download_claude_state() preserves Claude's.
#
# ONE download of the whole directory rather than a call per file: the state
# databases are schema-versioned (`state_5.sqlite`, and a machine can carry
# several), so there is no static name to ask for, and each one has `-wal` and
# `-shm` siblings that must travel with it. A `state_5.sqlite` moved without
# its `-wal` is nearly empty — measured in a live sandbox: 4KB of database
# against 2.1MB of write-ahead log. Filtering happens on the host, where a
# glob works.
#
# `codex resume` needs both halves: the `threads` table in the state DB to list
# sessions, and the rollout jsonl each row points at. `rollout_path` is stored
# absolute (`/sandbox/.codex/sessions/...`) and that path is identical in the
# rebuilt container, so nothing has to be rewritten.
#
# auth.json is deliberately NOT preserved — see gotcha 19. On work the host
# ships it through upload_config(), and preserving a copy here would let a
# stale key win over a rotated one; on the codex profile signing in inside the
# sandbox remains the documented behaviour.
CODEX_STATE_KEEP=(sessions history.jsonl session_index.jsonl config.toml)

# Copy the parts of a downloaded ~/.codex worth keeping from $1 into $2.
# Returns non-zero when there was nothing to keep. Split out from
# download_codex_state() so it can be driven against a fake tree in a test —
# the download itself needs a live sandbox, the filtering does not.
#
# `-wal` travels with its database; `-shm` deliberately does NOT. SQLite treats
# the shared-memory file as a rebuildable index derived from the WAL and says
# not to move it between machines — a stale one alongside a newer `-wal` is
# worse than none, because SQLite regenerates it correctly when absent.
codex_state_filter() {
    local src="$1" dst="$2" kept=1 item
    mkdir -p "$dst"
    for item in "${CODEX_STATE_KEEP[@]}"; do
        if [[ -e "${src}/${item}" ]]; then
            rm -rf "${dst:?}/${item}"
            cp -r "${src}/${item}" "${dst}/${item}"
            kept=0
        fi
    done
    for item in "${src}"/*.sqlite "${src}"/*.sqlite-wal; do
        [[ -f "$item" ]] || continue
        cp "$item" "${dst}/"
        kept=0
    done
    return $kept
}

# Render the config.toml a work-profile Codex sandbox should get: the host's
# `model =` line, if it pinned one, plus a freshly-generated `[otel]` table
# pointed at *this* sandbox's own collector. Never the host's own file — see
# gotcha 21 for why (host-only MCP/sandbox_permissions entries, and an
# `[otel]` table pointed at the host's own, unreachable collector).
#
# `protocol = "binary"` is the OTLP-over-HTTP-protobuf equivalent of this
# sandbox's OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf; confirmed against a
# live `codex logout` that `"binary"` and `"json"` are the only two values
# accepted here. `endpoint` is required — Codex's own OTLP client does not
# fall back to OTEL_EXPORTER_OTLP_ENDPOINT from the environment the way the
# hooks.json/observe-hook.py pipeline does; confirmed against the same
# `codex logout` that an `[otel.exporter.otlp-http]` table with no `endpoint`
# key fails config load with `missing field "endpoint"` rather than reading
# the env var.
# The metrics exporter uses the same OTLP HTTP endpoint so native Codex metrics
# reach the collector alongside native Codex logs.
#
# Split out so tests/test-render-codex-config.sh can drive it without a live
# sandbox — same reason codex_state_filter() above is split out.
render_codex_config() {
    local host_config="$1" otel_url="$2"
    if [[ -f "$host_config" ]]; then
        grep -E '^model[[:space:]]*=' "$host_config" | head -1
    fi
    printf '[otel.exporter.otlp-http]\n'
    printf 'endpoint = "%s"\n' "$otel_url"
    printf 'protocol = "binary"\n'
    printf '[otel.metrics_exporter.otlp-http]\n'
    printf 'endpoint = "%s"\n' "$otel_url"
    printf 'protocol = "binary"\n'
}

download_codex_state() {
    local sandbox_name="$1" sandbox_dir="$2"
    local codex_dir="${sandbox_dir}/codex"
    local dl_tmp
    dl_tmp="$(mktemp -d)"

    transfer_quiet "" run openshell sandbox download "$sandbox_name" "${GW_FLAG[@]}" \
        "/sandbox/.codex" "${dl_tmp}/" || true

    local src="${dl_tmp}/.codex"
    [[ -d "$src" ]] || src="${dl_tmp}/codex"
    if [[ ! -d "$src" ]]; then
        rm -rf "$dl_tmp"
        return 0
    fi

    local kept=false
    codex_state_filter "$src" "$codex_dir" && kept=true

    rm -rf "$dl_tmp"
    [[ "$kept" == true && "$DRYRUN" != true ]] \
        && echo "    preserved Codex session state" >&2
    return 0
}

upload_codex_state() {
    local sandbox_name="$1" sandbox_dir="$2"
    local codex_dir="${sandbox_dir}/codex"
    [[ -d "$codex_dir" ]] || return 0

    local stage
    stage="$(mktemp -d)"
    mkdir -p "${stage}/.codex"
    # Whatever download_codex_state() kept, verbatim. It already filtered.
    if ! cp -r "${codex_dir}/." "${stage}/.codex/" 2>/dev/null \
       || [[ -z "$(ls -A "${stage}/.codex" 2>/dev/null)" ]]; then
        rm -rf "$stage"
        return 0
    fi
    echo "Restoring Codex session state..." >&2
    # Merges, so this cannot delete the auth.json upload_config() just placed
    # (gotcha 20).
    run openshell sandbox upload "$sandbox_name" "${GW_FLAG[@]}" \
        "${stage}/.codex" /sandbox
    rm -rf "$stage"
}

upload_claude_state() {
    local sandbox_name="$1" sandbox_dir="$2"
    local claude_dir="${sandbox_dir}/claude"
    local has_state=false
    local stage
    stage="$(mktemp -d)"
    mkdir -p "${stage}/.claude"
    if [[ -d "${claude_dir}/projects" ]]; then
        cp -r "${claude_dir}/projects" "${stage}/.claude/projects"
        has_state=true
    fi
    if [[ -f "${claude_dir}/.credentials.json" ]]; then
        cp "${claude_dir}/.credentials.json" "${stage}/.claude/.credentials.json"
        has_state=true
        echo "Restoring OAuth credentials..." >&2
    fi
    # Stage .claude.json inside .claude/ dir, move after upload
    local restore_claude_json=false
    if [[ -f "${claude_dir}/.claude.json" ]]; then
        cp "${claude_dir}/.claude.json" "${stage}/.claude/.claude.json"
        has_state=true
        restore_claude_json=true
        echo "Restoring .claude.json..." >&2
    fi
    if [[ "$has_state" == true ]]; then
        echo "Restoring Claude session state..." >&2
        run openshell sandbox upload "$sandbox_name" "${GW_FLAG[@]}" \
            "${stage}/.claude" /sandbox
        if [[ "$restore_claude_json" == true ]]; then
            run openshell sandbox exec --name "$sandbox_name" "${GW_FLAG[@]}" \
                -- mv /sandbox/.claude/.claude.json /sandbox/.claude.json
        fi
    fi
    rm -rf "$stage"
}

upload_config() {
    local sandbox_target="$1"
    local sandbox_dir="$2"

    echo "Uploading Claude config..." >&2
    if [[ -d "${HOME}/.claude" ]]; then
        CLAUDE_TMP="$(mktemp -d)"
        rsync -rL \
            --exclude=projects \
            --exclude=agentpulse \
            --exclude=venvs \
            --exclude=file-history \
            --exclude=backups \
            --exclude=paste-cache \
            --exclude=debug \
            --exclude=my-claude-stuff-data \
            --exclude=claude-dashboard \
            --exclude=.git \
            --exclude=.venv \
            --exclude=.credentials.json \
            "${HOME}/.claude/" "${CLAUDE_TMP}/.claude/"

        # Strip settings.json: host paths, allow permissions, pinned models,
        # work-only env on personal, every hook but the OTEL dummies. In a
        # script, not inline: it is real logic with quoting hazards, and
        # tests/test-strip-settings.sh can only reach it as a file.
        if [[ -f "${CLAUDE_TMP}/.claude/settings.json" ]]; then
            python3 "${SCRIPT_DIR}/strip-settings.py" \
                "${CLAUDE_TMP}/.claude/settings.json" "${HOME}" "${SANDBOX_PROFILE}"
        fi

        # Rewrite host HOME paths to /sandbox in all plugin config files
        if [[ -d "${CLAUDE_TMP}/.claude/plugins" ]]; then
            find "${CLAUDE_TMP}/.claude/plugins" -name "*.json" -exec \
                sed -i "s|${HOME}|/sandbox|g" {} +
        fi

        # Stage .bashrc and .env into temp dir
        cp "${REPO_ROOT}/config/bashrc" "${CLAUDE_TMP}/.bashrc"
        echo "$ENV_CONTENT" > "${CLAUDE_TMP}/.env"

        # Upload config to /sandbox
        run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
            "${CLAUDE_TMP}/.claude" /sandbox
        run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
            "${CLAUDE_TMP}/.bashrc" /sandbox
        run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
            "${CLAUDE_TMP}/.env" /sandbox
        rm -rf "$CLAUDE_TMP"
    fi

    # Upload the gitconfig — user, aliases, url rewrites. NOT the signing key.
    #
    # This used to `cp "$(git config --global user.signingkey)"` into
    # /sandbox/.ssh/. On this host that value is the PRIVATE key path, not the
    # .pub, so every sandbox on every profile received an unencrypted signing
    # key it had no use for: nothing commits in a sandbox, and the image has no
    # ssh-keygen to sign with even if something tried.
    #
    # The gitconfig still ships with commit.gpgsign=true and a signingkey path
    # that now resolves to nothing, so a commit fails instead of silently
    # landing unsigned. That is the intent. If you are here because a commit in
    # a sandbox errors on the missing key: it is meant to. Do not restore the
    # upload, and do not add openssh-client to the Containerfile.
    if [[ -f "${HOME}/.gitconfig" ]]; then
        GIT_TMP="$(mktemp -d)"
        sed "s|${HOME}|/sandbox|g" "${HOME}/.gitconfig" > "${GIT_TMP}/.gitconfig"
        run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
            "${GIT_TMP}/.gitconfig" /sandbox
        rm -rf "$GIT_TMP"
    fi

    # Upload the host's global excludes. Git reads $XDG_CONFIG_HOME/git/ignore
    # with no config key, so copying the file is the whole mechanism — nothing
    # to add to the gitconfig above. Without it the sandbox disagrees with the
    # host about what is ignored: repo upload and download both run
    # --no-git-ignore, so globally-ignored files are present here, and every
    # in-sandbox `git status`, bare `rg`, and skill that enumerates through
    # `git ls-files` sees files the host treats as invisible.
    #
    # ponytail: assumes the host uses the XDG default. A host that sets
    # core.excludesFile to some other path gets that path sed-rewritten to
    # /sandbox/... in the gitconfig above, and this copy lands where git will
    # not look. Read the key and mirror its rewritten destination if that ever
    # becomes true.
    GLOBAL_IGNORE="${XDG_CONFIG_HOME:-${HOME}/.config}/git/ignore"
    if [[ -f "$GLOBAL_IGNORE" ]]; then
        IGN_TMP="$(mktemp -d)"
        mkdir -p "${IGN_TMP}/.config/git"
        cp "$GLOBAL_IGNORE" "${IGN_TMP}/.config/git/ignore"
        run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
            "${IGN_TMP}/.config" /sandbox
        rm -rf "$IGN_TMP"
    fi

    # Upload gws (Google Workspace CLI) readonly credentials (work profile only)
    if ! personal_profile "$SANDBOX_PROFILE"; then
        GWS_SANDBOX_DIR="${HOME}/.config/gws-sandbox"
        if [[ -d "$GWS_SANDBOX_DIR" ]]; then
            GWS_TMP="$(mktemp -d)"
            mkdir -p "${GWS_TMP}/.config"
            cp -r "$GWS_SANDBOX_DIR" "${GWS_TMP}/.config/gws"
            rm -rf "${GWS_TMP}/.config/gws/cache"
            run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
                "${GWS_TMP}/.config" /sandbox
            rm -rf "$GWS_TMP"
        fi
    fi

    # Codex config, work profile only (gotcha 20). Three named files plus a
    # generated config.toml, never a mirror of ~/.codex/: sessions/,
    # history.jsonl and the state sqlites are transcripts of every Codex
    # conversation on the host across all projects, and shipping those into a
    # work sandbox pushes personal content in exactly the direction the
    # profile split exists to stop.
    #
    # A directory upload is safe: `openshell sandbox upload` streams a tar and
    # runs `tar xf - -C <dest>` (OpenShell crates/openshell-cli/src/ssh.rs),
    # which overwrites the entries in the archive and touches nothing else.
    # The pre-delete belongs to upload_repo(), not to this path. So the
    # sandbox's own state_*.sqlite, sessions/ and rollouts survive a --refresh.
    #
    # hooks.json + observe-hook.py are read from the host rather than vendored
    # here: they are source-controlled in claude-otel-stack and the user already
    # copies them to ~/.codex/, so reading them keeps one source of truth. A
    # host without them ships no hooks and the sandbox reports no Codex state.
    if ! personal_profile "$SANDBOX_PROFILE"; then
        CODEX_TMP="$(mktemp -d)"
        mkdir -p "${CODEX_TMP}/.codex"
        codex_shipped=0
        # auth.json holds OPENAI_API_KEY. It ships on work for the same reason
        # the gws credentials above do — signing in by hand in every sandbox is
        # friction, and work sandboxes already carry work credentials. The codex
        # profile is deliberately excluded and still signs in inside; see
        # gotcha 19.
        for f in auth.json hooks.json observe-hook.py; do
            if [[ -f "${HOME}/.codex/${f}" ]]; then
                cp "${HOME}/.codex/${f}" "${CODEX_TMP}/.codex/${f}"
                codex_shipped=1
            fi
        done

        # config.toml: rendered, never the host's file. See gotcha 21 and
        # render_codex_config() above.
        render_codex_config "${HOME}/.codex/config.toml" "$OTEL_URL" \
            > "${CODEX_TMP}/.codex/config.toml"
        codex_shipped=1

        if (( codex_shipped )); then
            run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
                "${CODEX_TMP}/.codex" /sandbox
        fi
        rm -rf "$CODEX_TMP"
    fi

    # Re-upload bin/
    run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
        "${REPO_ROOT}/bin" /sandbox

    upload_static "$sandbox_target" "$sandbox_dir"
}

# ---------------------------------------------------------------------------
# Resolve policy file from bare name or path
# ---------------------------------------------------------------------------

fetch_service_teardown() {
    # Stop the service first, then decide the policy: with the service down the
    # grant points at nothing, so there is no rush and no unsafe interval.
    "${REPO_ROOT}/fetchsvc/fetchsvc.sh" down

    # Revert to the sandbox's own profile policy, not a fixed name: home and
    # personal differ, and handing a home sandbox back the personal policy
    # takes away the Prometheus and Loki reads it was built with.
    local revert
    revert="$(jq -r '.profile // "personal"' \
        "${SANDBOXES_DIR}/$(infer_sandbox_name || true)/manifest.json" 2>/dev/null)" \
        || revert="personal"
    [[ -n "$revert" ]] || revert="personal"
    if [[ -t 0 ]]; then
        echo "" >&2
        echo "Revert policy (empty = leave fetch-service applied):" >&2
        read -erp "> " -i "$revert" revert
    else
        echo "Not a terminal — reverting policy to ${revert}" >&2
    fi

    if [[ -z "$revert" ]]; then
        echo "Policy left as fetch-service — the sandbox keeps a grant to a service that is no longer running" >&2
        return 0
    fi
    "$0" --policy "$revert" ${GATEWAY:+--gateway "$GATEWAY"}
}

render_policy() {
    # Substitute site.env values into a policy template and echo the path to
    # the rendered file. Renders to a temp path, NOT into the sandbox dir:
    # ~/sandboxes/<name>/openshell-policy.yaml is the record of what the
    # enforcer accepted, so only install_policy() may write it. That one rule
    # is why nothing else has to track the applied policy.
    # ponytail: sed over a fixed placeholder list; switch to a real templating
    # pass if this outgrows simple name substitution.
    local src="$1" dest
    dest="$(mktemp)"
    local expr=() v
    for v in OTEL_HOST OTEL_PORT PROMETHEUS_HOST PROMETHEUS_PORT LOKI_HOST LOKI_PORT; do
        expr+=(-e "s|\${${v}}|${!v}|g")
    done
    sed "${expr[@]}" "$src" > "$dest"
    if grep -q '\${' "$dest"; then
        echo "Error: unresolved placeholder in ${src} after rendering:" >&2
        grep -n '\${' "$dest" >&2
        rm -f "$dest"
        return 1
    fi
    echo "$dest"
}

install_policy() {
    # Promote a rendered policy to the sandbox's effective one. Call ONLY after
    # the enforcer has accepted it — on any failure the old file stays, so the
    # artifact still describes what is actually in force and upload_static is
    # safe to run either way.
    local rendered="$1" sandbox_dir="$2"
    mkdir -p "$sandbox_dir"
    mv "$rendered" "${sandbox_dir}/openshell-policy.yaml"
}

upload_static() {
    # Everything in /sandbox/source that is host-owned and not a repo: the
    # system prompt, manifest.json (sandbox name, repo list), and
    # openshell-policy.yaml (what this sandbox may reach). All three go in one
    # staged-directory upload (#12) — they are inert once written, so
    # re-sending an unchanged one costs nothing and there is no reason to
    # decide per file. The only path that uploads any of them, and it runs
    # exactly where one of the three can have changed: create and refresh
    # (through upload_config), --add-repo once the repo list is rewritten, and
    # --policy once the enforcer has accepted. Deliberately NOT on --upload,
    # which moves repos and nothing else.
    #
    # None is ever downloaded: download_sandbox() pulls only the repo
    # directories named in the manifest, so the host copies stay authoritative.
    local sandbox_target="$1" sandbox_dir="$2"
    local tmp profile="$SANDBOX_PROFILE"
    tmp="$(mktemp -d)"
    mkdir -p "${tmp}/source"

    # Profile from the manifest when the caller has not resolved it — the
    # policy hot-swap path runs before --profile is read.
    if [[ -z "$profile" && -f "${sandbox_dir}/manifest.json" ]]; then
        profile=$(jq -r '.profile // empty' "${sandbox_dir}/manifest.json" 2>/dev/null || true)
    fi

    # copy: system prompt — the base, plus this profile's additions appended
    # from config/sandbox-claude.d/<profile>.md. Additive, not subtractive: the
    # sed this replaced deleted from "## Jira" to the next "## " heading, so
    # the base file's section order silently decided what a personal sandbox
    # saw. Observability needs nothing here either way — the prompt names no
    # endpoints, it points at openshell-policy.yaml, which already omits
    # whatever the profile cannot reach.
    cp "${REPO_ROOT}/config/sandbox-claude.md" "${tmp}/source/CLAUDE.md"
    local profile_prompt="${REPO_ROOT}/config/sandbox-claude.d/${profile}.md"
    if [[ -n "$profile" && -f "$profile_prompt" ]]; then
        printf '\n' >> "${tmp}/source/CLAUDE.md"
        cat "$profile_prompt" >> "${tmp}/source/CLAUDE.md"
    fi

    # copy: manifest — init_manifest() writes the skeleton before create, so
    # this is present from the first upload. harness-wrapper.sh reads .profile
    # out of the sandbox copy to decide the model, and it only ever gets what
    # this function ships.
    if [[ -f "${sandbox_dir}/manifest.json" ]]; then
        cp "${sandbox_dir}/manifest.json" "${tmp}/source/manifest.json"
    fi

    # copy: openshell policy — same conditional as the manifest above. Absent
    # means no policy was ever applied through this script (a sandbox predating
    # the artifact, or a wiped local dir), and what the enforcer holds is
    # unknown. Leaving the sandbox's existing copy alone is the honest move:
    # a rendered profile default would be a guess, and the whole point of the
    # artifact is that it is not one. `--policy NAME` applies and installs.
    if [[ -f "${sandbox_dir}/openshell-policy.yaml" ]]; then
        cp "${sandbox_dir}/openshell-policy.yaml" "${tmp}/source/openshell-policy.yaml"
    else
        echo "Warning: no policy artifact in ${sandbox_dir} — leaving the sandbox's copy as-is. Run --policy NAME to set and record one." >&2
    fi

    # do: upload
    transfer_quiet "Upload complete — sandbox config (prompt, manifest, policy)" \
        run openshell sandbox upload "$sandbox_target" "${GW_FLAG[@]}" \
            "${tmp}/source" /sandbox
    rm -rf "$tmp"
}

resolve_policy() {
    local input="$1"
    if [[ -f "$input" ]]; then
        echo "$input"
    elif [[ -f "${REPO_ROOT}/policies/${input}.yaml" ]]; then
        echo "${REPO_ROOT}/policies/${input}.yaml"
    elif [[ -f "${REPO_ROOT}/policies/${input}" ]]; then
        echo "${REPO_ROOT}/policies/${input}"
    else
        echo "Error: policy not found: ${input} (tried ${REPO_ROOT}/policies/${input}.yaml)" >&2
        return 1
    fi
}

# ---------------------------------------------------------------------------
# Parse args
# ---------------------------------------------------------------------------

# Pre-scan, because --refresh/--recreate resolve their NAME as they are parsed
# and would infer-or-die before a later --all is ever seen.
[[ " $* " == *" --all "* ]] && ALL_MODE=true

while [[ $# -gt 0 ]]; do
    case "$1" in
        --help|-h)
            usage 0
            ;;
        --create)
            [[ $# -ge 2 ]] || { echo "Error: --create requires NAME" >&2; exit 1; }
            CREATE_MODE=true
            SANDBOX_NAME="$2"
            shift 2
            ;;
        --policy)
            [[ $# -ge 2 ]] || { echo "Error: --policy requires NAME" >&2; exit 1; }
            POLICY_FILE="$(resolve_policy "$2")" || exit 1
            shift 2
            ;;
        --refresh)
            REFRESH_MODE=true
            if [[ $# -ge 2 && "$2" != -* ]]; then
                SANDBOX_NAME="$2"; shift 2
            elif [[ "$ALL_MODE" == true ]]; then
                shift
            else
                SANDBOX_NAME="$(infer_sandbox_name)" || { echo "Error: --refresh requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --recreate)
            RECREATE_MODE=true
            if [[ $# -ge 2 && "$2" != -* ]]; then
                SANDBOX_NAME="$2"; shift 2
            elif [[ "$ALL_MODE" == true ]]; then
                shift
            else
                SANDBOX_NAME="$(infer_sandbox_name)" || { echo "Error: --recreate requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --all)
            shift
            ;;
        --source-dir)
            [[ $# -ge 2 ]] || { echo "Error: --source-dir requires PATH" >&2; exit 1; }
            SOURCE_DIR="$2"
            shift 2
            ;;
        --repo)
            [[ $# -ge 2 ]] || { echo "Error: --repo requires URL" >&2; exit 1; }
            REPOS+=("$2")
            REFS+=("")
            shift 2
            ;;
        --ref)
            [[ $# -ge 2 ]] || { echo "Error: --ref requires REF" >&2; exit 1; }
            if [[ ${#REFS[@]} -gt 0 ]]; then
                REFS[${#REFS[@]}-1]="$2"
            else
                echo "Error: --ref must follow --repo or --add-repo" >&2
                exit 1
            fi
            shift 2
            ;;
        --ensure)
            ENSURE_MODE=true
            if [[ $# -ge 2 && "$2" != -* ]]; then
                SANDBOX_NAME="$2"; shift 2
            else
                SANDBOX_NAME="$(infer_sandbox_name)" || { echo "Error: --ensure requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --add-repo)
            ADD_REPO_MODE=true
            if [[ $# -ge 2 && "$2" != -* ]]; then
                SANDBOX_NAME="$2"; shift 2
            else
                SANDBOX_NAME="$(infer_sandbox_name)" || { echo "Error: --add-repo requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --download)
            DOWNLOAD_MODE=true
            if [[ $# -ge 2 && "$2" != -* ]]; then
                SANDBOX_NAME="$2"; shift 2
            else
                SANDBOX_NAME="$(infer_sandbox_name)" || { echo "Error: --download requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --upload)
            UPLOAD_MODE=true
            if [[ $# -ge 2 && "$2" != -* ]]; then
                SANDBOX_NAME="$2"; shift 2
            else
                SANDBOX_NAME="$(infer_sandbox_name)" || { echo "Error: --upload requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        -f|--force)
            FORCE_MODE=true
            shift
            ;;
        --harness)
            [[ $# -ge 2 ]] || { echo "Error: --harness requires claude or codex" >&2; exit 1; }
            valid_harness "$2" || { echo "Error: unknown harness '$2' (valid: claude, codex)" >&2; exit 1; }
            HARNESS="$2"; shift 2
            ;;
        --connect)
            if [[ $# -ge 2 && "$2" != -* ]]; then
                CONNECT_NAME="$2"; shift 2
            else
                CONNECT_NAME="$(infer_sandbox_name)" || { echo "Error: --connect requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --delete)
            if [[ $# -ge 2 && "$2" != -* ]]; then
                DELETE_NAME="$2"; shift 2
            else
                DELETE_NAME="$(infer_sandbox_name)" || { echo "Error: --delete requires NAME (not in a sandbox directory)" >&2; exit 1; }
                shift
            fi
            ;;
        --dryrun|--dry-run)
            DRYRUN=true
            shift
            ;;
        --debug)
            DEBUG=true
            shift
            ;;
        --list)
            LIST_MODE=true
            shift
            ;;
        --fetch-service)
            FETCH_SERVICE_MODE=true
            shift
            ;;
        --profile)
            [[ $# -ge 2 ]] || { echo "Error: --profile requires NAME" >&2; exit 1; }
            SANDBOX_PROFILE="$2"
            PROFILE_FROM_CLI=true
            shift 2
            ;;
        --no-clone)
            NO_CLONE=true
            shift
            ;;
        --no-connect)
            NO_CONNECT=true
            shift
            ;;
        --gateway|-g)
            [[ $# -ge 2 ]] || { echo "Error: --gateway requires NAME" >&2; exit 1; }
            GATEWAY="$2"
            shift 2
            ;;
        --*)
            echo "Error: unknown option: $1" >&2
            usage 1
            ;;
        *)
            echo "Error: unexpected argument: $1" >&2
            usage 1
            ;;
    esac
done

# A path that clones a repo always behaves as --force: the repo is new to the
# sandbox, so there is no last_upload to skip on, and its pr/Jira/open-PR
# context has never been generated. Leaving these on the default would create
# sandboxes with no context at all.
if [[ "$CREATE_MODE" == true || "$ADD_REPO_MODE" == true ]]; then
    FORCE_MODE=true
fi

# ---------------------------------------------------------------------------
# --all: re-invoke this script once per local sandbox
# ---------------------------------------------------------------------------

# ~/sandboxes/*/manifest.json is the list. Not `openshell sandbox list`: both
# modes read and write host-side state under ~/sandboxes/<name>/, and a remote
# container with no local directory has neither a name to resolve back to nor
# repos to re-upload.
if [[ "$ALL_MODE" == true ]]; then
    if [[ "$REFRESH_MODE" != true && "$RECREATE_MODE" != true ]]; then
        echo "Error: --all is only valid with --refresh or --recreate" >&2
        exit 1
    fi
    if [[ -n "$SANDBOX_NAME" ]]; then
        echo "Error: --all and a sandbox NAME are mutually exclusive" >&2
        exit 1
    fi

    ALL_MODE_FLAG=--refresh
    [[ "$RECREATE_MODE" == true ]] && ALL_MODE_FLAG=--recreate

    ALL_COMMON=()
    [[ -n "$GATEWAY" ]] && ALL_COMMON+=(--gateway "$GATEWAY")
    [[ "$DRYRUN" == true ]] && ALL_COMMON+=(--dryrun)
    [[ "$DEBUG" == true ]] && ALL_COMMON+=(--debug)

    ALL_FAILED=()
    ALL_FOUND=false
    for manifest in "${SANDBOXES_DIR}"/*/manifest.json; do
        [[ -f "$manifest" ]] || continue
        ALL_FOUND=true
        name="$(basename "$(dirname "$manifest")")"
        one=("$ALL_MODE_FLAG" "$name" "${ALL_COMMON[@]}")
        if [[ "$RECREATE_MODE" == true ]]; then
            # --recreate rejects a missing --profile before the manifest
            # fallback runs, and ends by exec'ing --connect. Neither is
            # workable unattended, so read the profile here and suppress the
            # connect. A sandbox with no .profile predates the field; guessing
            # one would rebuild it on the wrong credentials (see gotcha 5).
            profile="$(jq -r '.profile // empty' "$manifest" 2>/dev/null || true)"
            if [[ -z "$profile" ]]; then
                echo "Skipped ${name}: no profile in manifest — recreate it by name with --profile" >&2
                ALL_FAILED+=("$name")
                continue
            fi
            one+=(--profile "$profile" --no-connect)
        fi
        echo "=== ${ALL_MODE_FLAG#--} ${name} ===" >&2
        "$0" "${one[@]}" || { echo "Failed: ${name}" >&2; ALL_FAILED+=("$name"); }
    done

    if [[ "$ALL_FOUND" != true ]]; then
        echo "Error: no sandboxes found in ${SANDBOXES_DIR}" >&2
        exit 1
    fi
    if [[ ${#ALL_FAILED[@]} -gt 0 ]]; then
        echo "Failed sandboxes: ${ALL_FAILED[*]}" >&2
        exit 1
    fi
    echo "Done." >&2
    exit 0
fi

# ---------------------------------------------------------------------------
# --profile is only applied on a path that creates a sandbox
# ---------------------------------------------------------------------------

# Profile decides four things at once: which env vars land in /sandbox/.env,
# which credentials upload, which policy renders, and whether the system prompt
# keeps its Jira section. Only the create path writes all four. Every other mode
# either ignores --profile outright or — worse, --refresh — applies the new
# .env and leaves the policy, system prompt, and manifest on the old profile.
# Half-applied reads as applied, so refuse instead.
if [[ "$PROFILE_FROM_CLI" == true \
      && "$CREATE_MODE" != true \
      && "$RECREATE_MODE" != true \
      && "$ENSURE_MODE" != true ]]; then
    echo "Error: --profile is only valid with --create, --recreate, or --ensure." >&2
    echo "    profile is applied when a sandbox is built, not afterwards" >&2
    echo "    to switch an existing sandbox: $(basename "$0") --recreate NAME --profile ${SANDBOX_PROFILE}" >&2
    exit 1
fi

# The two paths that build a sandbox name the profile or do not run. There is
# no machine default to fall back on: the profile decides which credentials
# leave the host, and inheriting that from a config file means the command
# that uploads a work token looks identical to the one that does not.
if [[ ( "$CREATE_MODE" == true || "$RECREATE_MODE" == true ) && -z "$SANDBOX_PROFILE" ]]; then
    echo "Error: --profile is required with --create and --recreate (work, personal, home, codex)." >&2
    exit 1
fi

if [[ -n "$SANDBOX_PROFILE" ]] && ! valid_profile "$SANDBOX_PROFILE"; then
    echo "Error: unknown profile '${SANDBOX_PROFILE}' (valid: work, personal, home, codex)." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------

if [[ "$DEBUG" == true ]]; then
    set -x
fi

GW_FLAG=()
if [[ -n "$GATEWAY" ]]; then
    GW_FLAG=(--gateway "$GATEWAY")
fi

# --- Fetch service: run in the foreground, tear down on exit ---
if [[ "$FETCH_SERVICE_MODE" == true ]]; then
    FETCHSVC="${REPO_ROOT}/fetchsvc/fetchsvc.sh"
    [[ -x "$FETCHSVC" ]] || { echo "Error: ${FETCHSVC} not executable" >&2; exit 1; }

    if "$FETCHSVC" running; then
        echo "Fetch service already running — will stop it on exit" >&2
    else
        "$FETCHSVC" up || exit 1
    fi

    # Foreground on purpose: the service widens what a sandbox can read, so it
    # lives exactly as long as this terminal does. The policy grant is applied
    # and reverted alongside it, so the sandbox cannot reach a service that is
    # not running and cannot keep the grant after it stops.
    trap 'trap - INT TERM EXIT; fetch_service_teardown' INT TERM EXIT
    "$0" --policy fetch-service ${GATEWAY:+--gateway "$GATEWAY"} || exit 1

    echo "Following log — Ctrl-C stops the service" >&2
    "$FETCHSVC" logs
    exit 0
fi

if [[ "$LIST_MODE" == true ]]; then
    openshell sandbox list "${GW_FLAG[@]}" | while IFS= read -r line; do
        os_name=$(echo "$line" | awk '{print $1}')
        full=$(resolve_full_name "$os_name")
        if [[ "$full" != "$os_name" ]]; then
            echo "$line  ($full)"
        else
            echo "$line"
        fi
    done
    exit $?
elif [[ -n "$DELETE_NAME" ]]; then
    OS_NAME=$(resolve_openshell_name "$DELETE_NAME")
    run openshell sandbox delete "$OS_NAME" "${GW_FLAG[@]}" || true
    if [[ -d "${SANDBOXES_DIR}/${DELETE_NAME}" ]]; then
        # ${...:?} so an empty name aborts instead of deleting ~/sandboxes
        rm -rf "${SANDBOXES_DIR:?}/${DELETE_NAME:?}"
        echo "Removed local state: ${SANDBOXES_DIR}/${DELETE_NAME}" >&2
    fi
    exit 0
elif [[ -n "$CONNECT_NAME" ]]; then
    OS_NAME=$(resolve_openshell_name "$CONNECT_NAME")
    SANDBOX_DIR="${SANDBOXES_DIR}/${CONNECT_NAME}"
    WORKDIR="/sandbox"
    if [[ -f "${SANDBOX_DIR}/manifest.json" ]]; then
        WORKDIR="/sandbox/source/"
    fi
    start_error_sandbox "$OS_NAME" || exit 1
    # An explicit --harness is what changes the memory; the prompt does not.
    if [[ -n "$HARNESS" ]]; then
        init_manifest "$SANDBOX_DIR" "$CONNECT_NAME" "" "$HARNESS"
    fi
    connect_sandbox "$OS_NAME" "$WORKDIR" "$HARNESS" "$SANDBOX_DIR"
    exit $?
fi

# --- Add repo to existing sandbox ---
if [[ "$ADD_REPO_MODE" == true ]]; then
    if [[ ${#REPOS[@]} -eq 0 && -n "$SOURCE_DIR" && -d "$SOURCE_DIR/.git" ]]; then
        REPOS+=("$(git -C "$SOURCE_DIR" remote get-url origin)")
        REFS+=("")
    fi
    if [[ ${#REPOS[@]} -eq 0 ]]; then
        echo "Error: --add-repo requires --repo URL or --source-dir PATH" >&2
        exit 1
    fi
    OS_NAME=$(resolve_openshell_name "$SANDBOX_NAME")
    SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
    mkdir -p "$SANDBOX_DIR"

    # Read profile from manifest for repo visibility check
    if [[ -z "$SANDBOX_PROFILE" && -f "${SANDBOX_DIR}/manifest.json" ]]; then
        SANDBOX_PROFILE=$(jq -r '.profile // empty' "${SANDBOX_DIR}/manifest.json" 2>/dev/null || true)
    fi

    for i in "${!REPOS[@]}"; do
        repo="${REPOS[$i]}"
        ref="${REFS[$i]:-}"
        repo_name=$(basename "$repo" .git)

        echo "Adding ${repo_name} to sandbox ${SANDBOX_NAME}..." >&2
        clone_repo_host "$repo" "$ref" "$SANDBOX_DIR"

        sha=$(git -C "${SANDBOX_DIR}/${repo_name}" rev-parse HEAD)
        write_manifest "$SANDBOX_DIR" "$SANDBOX_NAME" "$repo_name" "$repo" "$ref" "$sha"

        upload_repo "$OS_NAME" "$SANDBOX_DIR" "$repo_name"
    done

    # Re-upload so the sandbox has the updated repo list
    upload_static "$OS_NAME" "$SANDBOX_DIR"

    echo "Done." >&2
    exit 0
fi

# --- Download from sandbox ---
if [[ "$DOWNLOAD_MODE" == true ]]; then
    OS_NAME=$(resolve_openshell_name "$SANDBOX_NAME")
    SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"

    # Repos, and nothing else. Claude session state used to come down here too,
    # which made every routine `--download` pull the OAuth token and the whole
    # transcript directory for the benefit of one caller. --recreate does that
    # itself now; see step 1 there.
    echo "Downloading from sandbox ${SANDBOX_NAME}..." >&2
    download_sandbox "$OS_NAME" "$SANDBOX_DIR"
    echo "Done. Files in ${SANDBOX_DIR}/" >&2
    exit 0
fi

# --- Upload to sandbox ---
if [[ "$UPLOAD_MODE" == true ]]; then
    OS_NAME=$(resolve_openshell_name "$SANDBOX_NAME")
    SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
    target_repo=""
    if [[ ${#REPOS[@]} -gt 0 ]]; then
        target_repo=$(basename "${REPOS[0]}" .git)
    fi

    # Repos, and nothing else. upload_static() used to run here as well, so the
    # system prompt, manifest and policy went up on every --upload including the
    # ones where every repo was skipped. Every path that can change one of those
    # three ships them itself: --create and --refresh through upload_config(),
    # --add-repo after it rewrites the repo list, --policy after the enforcer
    # accepts. Nothing --upload does can change any of them.
    echo "Uploading to sandbox ${SANDBOX_NAME}..." >&2
    upload_sandbox "$OS_NAME" "$SANDBOX_DIR" "$target_repo"
    echo "Done." >&2
    # Last line, so it survives a long upload log. The change check reads
    # mtimes and skips `.git/index`, which is the only thing an unstage
    # touches — see repo_changed_since_upload().
    if [[ "$FORCE_MODE" != true ]]; then
        echo "Note: repos with no detected change are skipped, and unstaging" >&2
        echo "  (git reset) alone is not detected. Re-run with --force to" >&2
        echo "  send every repo." >&2
    fi
    exit 0
fi

# --- Recreate: download, delete remote, ensure (creates + uploads + connects) ---
if [[ "$RECREATE_MODE" == true ]]; then
    COMMON_ARGS=()
    [[ -n "$GATEWAY" ]] && COMMON_ARGS+=(--gateway "$GATEWAY")
    [[ "$DRYRUN" == true ]] && COMMON_ARGS+=(--dryrun)

    echo "Recreating sandbox ${SANDBOX_NAME}..." >&2

    # Pre-flight: check all repos before touching anything
    SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
    if [[ -f "${SANDBOX_DIR}/manifest.json" ]]; then
        for repo_name in $(jq -r '.repos | keys[]' "${SANDBOX_DIR}/manifest.json"); do
            if [[ -d "${SANDBOX_DIR}/${repo_name}/.git" ]]; then
                origin_url=$(git -C "${SANDBOX_DIR}/${repo_name}" remote get-url origin 2>/dev/null || true)
                if [[ -n "$origin_url" ]]; then
                    guard_private_repo "$origin_url"
                fi
            fi
        done
    fi

    # 1. Download repos, then claude state. --force on the repo transfers: the
    # sandbox is deleted in step 2, so a wrongly skipped download is
    # unrecoverable, and step 4 uploads into a container that holds no repos at
    # all — the change checks compare against stamps from the sandbox that no
    # longer exists.
    #
    # download_claude_state() is called here rather than inherited from
    # --download, which moves repos and nothing else. Recreate is its only
    # consumer: the OAuth token and .claude.json it preserves are read back by
    # upload_claude_state() during the create in step 3, and step 2 deletes the
    # only other copy. A direct call, not a flag on --download — there is one
    # caller, and a flag would be a second way to say "recreate".
    #
    # A stopped container has to come up first or both transfers fail against
    # it, and a failed start is fatal: step 2 destroys the only copy of
    # everything this step was supposed to save. Recreating from stale local
    # state silently discards whatever the session did. Stop instead — the
    # container is still there to retry against. Deliberately rebuilding from
    # local state is `--delete NAME` then `--create`.
    OS_NAME=$(resolve_openshell_name "$SANDBOX_NAME")
    start_error_sandbox "$OS_NAME" || exit 1
    "$0" --download "$SANDBOX_NAME" --force "${COMMON_ARGS[@]}"
    download_claude_state "$OS_NAME" "$SANDBOX_DIR"
    download_codex_state "$OS_NAME" "$SANDBOX_DIR"

    # 2. Delete remote sandbox only (preserve local dir)
    run openshell sandbox delete "$OS_NAME" "${GW_FLAG[@]}" || true

    # 3. Create fresh sandbox without connecting
    "$0" --create "$SANDBOX_NAME" --no-clone --no-connect ${POLICY_FILE:+--policy "$POLICY_FILE"} ${SANDBOX_PROFILE:+--profile "$SANDBOX_PROFILE"} "${COMMON_ARGS[@]}"

    # 4. Upload local repos
    "$0" --upload "$SANDBOX_NAME" --force "${COMMON_ARGS[@]}"

    # 5. Connect
    if [[ "$NO_CONNECT" == true ]]; then
        echo "Recreated ${SANDBOX_NAME}. Connect with: $(basename "$0") --connect ${SANDBOX_NAME}" >&2
        exit 0
    fi
    exec "$0" --connect "$SANDBOX_NAME" ${HARNESS:+--harness "$HARNESS"} "${COMMON_ARGS[@]}"
fi

# --- Ensure (create-or-connect) ---
if [[ "$ENSURE_MODE" == true ]]; then
    OS_NAME=$(resolve_openshell_name "$SANDBOX_NAME")
    if openshell sandbox list "${GW_FLAG[@]}" 2>/dev/null | grep -q "^${OS_NAME}[[:space:]]"; then
        SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
        WORKDIR="/sandbox"
        if [[ -f "${SANDBOX_DIR}/manifest.json" ]]; then
            WORKDIR="/sandbox/source/"
        fi
        # This branch connects, it does not build — so --profile is dropped.
        # Dropping it silently when it disagrees with what the sandbox was
        # built as hands the caller a sandbox on the other profile's
        # credentials and policy while the command line says otherwise.
        # scode passes --profile on every --ensure (scode:137,165,189,207,243),
        # so a match must stay silent; only a mismatch is an error.
        if [[ "$PROFILE_FROM_CLI" == true ]]; then
            manifest_profile=$(jq -r '.profile // empty' "${SANDBOX_DIR}/manifest.json" 2>/dev/null || true)
            if [[ "$SANDBOX_PROFILE" != "$manifest_profile" ]]; then
                echo "Error: sandbox '${SANDBOX_NAME}' exists with profile '${manifest_profile:-<none>}', cannot connect as '${SANDBOX_PROFILE}'." >&2
                echo "    --ensure connects an existing sandbox; profile is only applied at create" >&2
                echo "    to switch it: $(basename "$0") --recreate ${SANDBOX_NAME} --profile ${SANDBOX_PROFILE}" >&2
                exit 1
            fi
        fi
        start_error_sandbox "$OS_NAME" || exit 1
        echo "Sandbox '${SANDBOX_NAME}' exists, connecting..." >&2
        connect_sandbox "$OS_NAME" "$WORKDIR"
    else
        ENSURE_ARGS=(--create "$SANDBOX_NAME")
        for i in "${!REPOS[@]}"; do
            ENSURE_ARGS+=(--repo "${REPOS[$i]}")
            if [[ -n "${REFS[$i]:-}" ]]; then
                ENSURE_ARGS+=(--ref "${REFS[$i]}")
            fi
        done
        [[ -n "$GATEWAY" ]] && ENSURE_ARGS+=(--gateway "$GATEWAY")
        [[ -n "$POLICY_FILE" ]] && ENSURE_ARGS+=(--policy "$POLICY_FILE")
        [[ -n "$SANDBOX_PROFILE" ]] && ENSURE_ARGS+=(--profile "$SANDBOX_PROFILE")
        [[ -n "$SOURCE_DIR" ]] && ENSURE_ARGS+=(--source-dir "$SOURCE_DIR")
        [[ "$DRYRUN" == true ]] && ENSURE_ARGS+=(--dryrun)
        exec "$0" "${ENSURE_ARGS[@]}"
    fi
fi

# --- Policy hot-swap on existing sandbox ---
if [[ -n "$POLICY_FILE" && -z "$SANDBOX_NAME" && -z "$CONNECT_NAME" && "$ENSURE_MODE" != true ]]; then
    POLICY_TARGET="$(infer_sandbox_name)" || { echo "Error: --policy requires sandbox NAME or CWD under ~/sandboxes/<name>/" >&2; exit 1; }
    OS_NAME=$(resolve_openshell_name "$POLICY_TARGET")
    POLICY_DIR="${SANDBOXES_DIR}/${POLICY_TARGET}"
    POLICY_FILE="$(render_policy "$POLICY_FILE")" || exit 1
    echo "Setting policy on ${POLICY_TARGET}..." >&2
    if [[ "$DRYRUN" == true ]]; then
        run openshell policy set "${GW_FLAG[@]}" --policy "$POLICY_FILE" "$OS_NAME"
        exit 0
    fi
    set_output=$(openshell policy set "${GW_FLAG[@]}" --policy "$POLICY_FILE" "$OS_NAME" 2>&1)
    echo "$set_output" >&2
    if ! echo "$set_output" | grep -qi "unchanged"; then
        elapsed=0
    while true; do
        # Highest VERSION wins, not the last row. `openshell policy list` prints
        # newest-first under a header, so `tail -1` read the OLDEST row — always
        # Superseded — and the poll timed out on every real change.
        latest_status=$(openshell policy list "${GW_FLAG[@]}" "$OS_NAME" 2>/dev/null \
            | awk 'NR>1 && $1 ~ /^[0-9]+$/ {print $1, $3}' | sort -rn | head -1 | awk '{print $2}')
        if [[ "$latest_status" == "Failed" ]]; then
            echo "Error: policy validation failed" >&2
            openshell policy list "${GW_FLAG[@]}" "$OS_NAME" >&2
            exit 1
        fi
        if [[ "$latest_status" == "Loaded" || "$latest_status" == "Effective" ]]; then
            break
        fi
        sleep 1
        elapsed=$((elapsed + 1))
        if [[ $elapsed -ge 30 ]]; then
            echo "Error: policy update not applied within 30s" >&2
            openshell policy list "${GW_FLAG[@]}" "$OS_NAME" >&2
            echo "Artifact left on the previous policy — re-run once it settles" >&2
            exit 1
        fi
    done
    fi
    # Accepted: this is now the effective policy, so it becomes the artifact.
    install_policy "$POLICY_FILE" "$POLICY_DIR"
    upload_static "$OS_NAME" "$POLICY_DIR"
    echo "Done." >&2
    exit 0
fi

# ---------------------------------------------------------------------------
# Validate --create required when --repo specified
# ---------------------------------------------------------------------------

if [[ -z "$SANDBOX_NAME" && "$NO_CLONE" != true && ${#REPOS[@]} -gt 0 ]]; then
    echo "Error: --create required when --repo is specified" >&2
    exit 1
fi

# Everything past this point creates a sandbox. Reaching it without a name
# means no mode flag matched. Without this guard the create path runs with an
# empty name — short_name "" hashes to sb-d41d8cd98f00 — and installs the
# policy into ~/sandboxes//, a directory no sandbox will ever look for.
if [[ -z "$SANDBOX_NAME" ]]; then
    echo "Error: no sandbox name — nothing to do. See --help for modes." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Resolve profile from manifest (for --refresh when --profile not on CLI)
# ---------------------------------------------------------------------------

if [[ -z "$SANDBOX_PROFILE" && -n "$SANDBOX_NAME" && -f "${SANDBOXES_DIR}/${SANDBOX_NAME}/manifest.json" ]]; then
    SANDBOX_PROFILE=$(jq -r '.profile // empty' "${SANDBOXES_DIR}/${SANDBOX_NAME}/manifest.json" 2>/dev/null || true)
    if [[ -n "$SANDBOX_PROFILE" ]]; then
        echo "Using profile '${SANDBOX_PROFILE}' from manifest" >&2
    fi
fi

# ---------------------------------------------------------------------------
# Resolve policy
# ---------------------------------------------------------------------------

# --refresh re-uploads config; it never calls `openshell policy set`. Letting
# it take a --policy would render and ship an artifact for a policy the
# enforcer never received. Standalone --policy is the path that changes one.
if [[ -n "$POLICY_FILE" && "$REFRESH_MODE" == true ]]; then
    echo "Error: --policy is not valid with --refresh — it would upload a policy artifact without applying it to the enforcer" >&2
    echo "    to change the policy: cd ~/sandboxes/${SANDBOX_NAME} && $(basename "$0") --policy NAME" >&2
    exit 1
fi

# Profile name and policy name are the same word — work, personal, home, codex. The
# `:-work` covers a sandbox whose manifest predates .profile: --create demands
# a profile, and every other path that reaches here renders a temp policy it
# never installs, so the fallback picks a file and changes nothing.
if [[ -z "$POLICY_FILE" ]]; then
    POLICY_FILE="$(resolve_policy "${SANDBOX_PROFILE:-work}")" || exit 1
fi

# Render to a temp file. It is handed to `openshell sandbox create` below and
# only becomes the sandbox's openshell-policy.yaml once that create succeeds.
# --refresh reaches here too and renders a temp it never installs, which costs
# one sed and changes nothing on disk.
POLICY_FILE="$(render_policy "$POLICY_FILE")" || exit 1

# ---------------------------------------------------------------------------
# Generate /sandbox/.env content (runtime env vars)
# ---------------------------------------------------------------------------

# Build active var list based on profile
ACTIVE_VARS=()
if personal_profile "$SANDBOX_PROFILE"; then
    ACTIVE_VARS+=("${ANTHROPIC_VARS[@]}" "${CLAUDE_VARS[@]}")
else
    ACTIVE_VARS+=("${ALL_VARS[@]}")
fi

ENV_CONTENT=""
captured=0
for var in "${ACTIVE_VARS[@]}"; do
    if [[ -n "${!var+x}" ]]; then
        ENV_CONTENT+="$(printf '%s=%q' "$var" "${!var}")"$'\n'
        captured=$((captured + 1))
    fi
done

if ! personal_profile "$SANDBOX_PROFILE"; then
    # JIRA env var aliases — tools use inconsistent names
    if [[ -n "${JIRA_USERNAME+x}" && -z "${JIRA_EMAIL+x}" ]]; then
        ENV_CONTENT+="$(printf 'JIRA_EMAIL=%q' "${JIRA_USERNAME}")"$'\n'
    fi
    if [[ -n "${JIRA_EMAIL+x}" && -z "${JIRA_USERNAME+x}" ]]; then
        ENV_CONTENT+="$(printf 'JIRA_USERNAME=%q' "${JIRA_EMAIL}")"$'\n'
    fi
    if [[ -n "${JIRA_TOKEN+x}" && -z "${JIRA_API_TOKEN+x}" ]]; then
        ENV_CONTENT+="$(printf 'JIRA_API_TOKEN=%q' "${JIRA_TOKEN}")"$'\n'
    fi
    if [[ -n "${JIRA_API_TOKEN+x}" && -z "${JIRA_TOKEN+x}" ]]; then
        ENV_CONTENT+="$(printf 'JIRA_TOKEN=%q' "${JIRA_API_TOKEN}")"$'\n'
    fi

    # Sandbox-scoped JIRA credentials override (read-only scoped token via gateway)
    if [[ -n "${SANDBOX_JIRA_TOKEN+x}" ]]; then
        ENV_CONTENT+="$(printf 'JIRA_TOKEN=%q' "${SANDBOX_JIRA_TOKEN}")"$'\n'
        ENV_CONTENT+="$(printf 'JIRA_API_TOKEN=%q' "${SANDBOX_JIRA_TOKEN}")"$'\n'
        if [[ -n "${SANDBOX_JIRA_EMAIL+x}" ]]; then
            ENV_CONTENT+="$(printf 'JIRA_EMAIL=%q' "${SANDBOX_JIRA_EMAIL}")"$'\n'
            ENV_CONTENT+="$(printf 'JIRA_USERNAME=%q' "${SANDBOX_JIRA_EMAIL}")"$'\n'
        fi
        if [[ -n "${SANDBOX_JIRA_URL+x}" ]]; then
            ENV_CONTENT+="$(printf 'JIRA_URL=%q' "${SANDBOX_JIRA_URL}")"$'\n'
        fi
        if [[ -n "${SANDBOX_JIRA_CLOUD_ID+x}" ]]; then
            ENV_CONTENT+="$(printf 'JIRA_CLOUD_ID=%q' "${SANDBOX_JIRA_CLOUD_ID}")"$'\n'
        fi
    fi

    # Remap credential file paths for sandbox
    if [[ -n "${GOOGLE_APPLICATION_CREDENTIALS+x}" ]]; then
        ENV_CONTENT+=$'\n'"GOOGLE_APPLICATION_CREDENTIALS=/sandbox/.config/gcloud/application_default_credentials.json"
    fi
fi

# Dashboard hooks: relay to host dashboard via container gateway
ENV_CONTENT+="CLAUDE_DASHBOARD_HOST=host.containers.internal"$'\n'

# Telemetry egress. Always written from site.env, overriding anything captured
# from the host env: the host reaches its collector on a host-local address
# and over gRPC, neither of which works from inside a sandbox (gotcha 13).
ENV_CONTENT+="$(printf 'OTEL_EXPORTER_OTLP_ENDPOINT=%q' "$OTEL_URL")"$'\n'
ENV_CONTENT+="OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf"$'\n'

# Telemetry query endpoints — consumed only by validate-profile.sh.
ENV_CONTENT+="$(printf 'SANDBOX_PROMETHEUS_URL=%q' "$PROMETHEUS_URL")"$'\n'
ENV_CONTENT+="$(printf 'SANDBOX_LOKI_URL=%q' "$LOKI_URL")"$'\n'

# Sandbox source directory name for OTEL enrichment
ENV_CONTENT+="$(printf 'SANDBOX_SOURCE_NAME=%q' "${SANDBOX_NAME}")"$'\n'

# The creating host's hostname, for OTEL host.name. Inside the container
# `hostname` returns sandbox-sb-<hash>, which identifies the sandbox, not the
# machine — and sandbox.source already carries the sandbox identity. With
# several machines shipping to one collector, host.name has to be the machine.
# Must be the same `hostname` invocation the host's own claude.env uses, or the
# same laptop splits into two series (short name vs FQDN).
HOST_NAME_VALUE="$(hostname)"
ENV_CONTENT+="$(printf 'SANDBOX_HOST_NAME=%q' "$HOST_NAME_VALUE")"$'\n'

# This sandbox's directory on the host, for OTEL project. A sandbox session's
# $(pwd) is /sandbox/source/ for every sandbox on every machine, because
# connect_sandbox() cds there before launch — so project collapses them all
# into one value. The full host path is deliberate: the dashboards' existing
# ^/home/<user> -> ~ rewrite turns it into ~/sandboxes/<name>, which is what
# they already synthesise for the sandbox case.
HOST_DIR_VALUE="${SANDBOXES_DIR}/${SANDBOX_NAME}"
ENV_CONTENT+="$(printf 'SANDBOX_HOST_DIR=%q' "$HOST_DIR_VALUE")"$'\n'

# The openshell name (sb-<hash>). The only handle tying a session to its
# container, `openshell sandbox list`, and the openshell.ai/sandbox-name podman
# label. In manifest.json too, but exporting it saves every consumer a jq call.
OPENSHELL_NAME_VALUE="$(resolve_openshell_name "$SANDBOX_NAME")"
ENV_CONTENT+="$(printf 'SANDBOX_OPENSHELL_NAME=%q' "$OPENSHELL_NAME_VALUE")"$'\n'

# The profile, by name, for every profile — not just the credential-less ones.
# validate-profile.sh and harness-wrapper.sh both read it out of /sandbox/.env,
# and `home` and `personal` differ only in what they may reach, so a tag that
# lumps them together tells neither of them anything. Also lands in
# OTEL_RESOURCE_ATTRIBUTES as sandbox.profile below. Empty only on a
# pre-.profile manifest, where a blank tag would be worse than none.
if [[ -n "$SANDBOX_PROFILE" ]]; then
    ENV_CONTENT+="$(printf 'SANDBOX_PROFILE=%q' "$SANDBOX_PROFILE")"$'\n'
fi

# The OTEL identity, assembled from the values just written. Every attribute is
# host knowledge and none of it is observable from inside the container:
# `hostname` there is sandbox-sb-<hash>, and $(pwd) is /sandbox/source for every
# sandbox on every machine.
#
# Assembled here rather than at launch (an earlier version built it in a file
# the wrapper sourced) because
# every input is fixed the moment this file is written, and a launch-time
# assembly only reaches processes that source that file. A nested `claude -p` —
# every review-orchestrator sub-agent — does not, so it reported with no
# identity at all. In .env it travels with the endpoint, through every consumer
# that already reads .env.
#
# No user.name: single-user hosts, and the container-side ${USER} this replaces
# was the constant `sandbox` on every sandbox on every machine. Add it here if
# that stops being true.
#
# Consumers append their own attributes to this (the review orchestrator stamps
# review.run_id/stage/agent per sub-agent), so nothing downstream may assign
# over it.
OTEL_ATTRS="project=${HOST_DIR_VALUE}"
OTEL_ATTRS+=",host.name=${HOST_NAME_VALUE}"
OTEL_ATTRS+=",sandbox.source=${SANDBOX_NAME}"
OTEL_ATTRS+=",sandbox.openshell_name=${OPENSHELL_NAME_VALUE}"
if [[ -n "$SANDBOX_PROFILE" ]]; then
    OTEL_ATTRS+=",sandbox.profile=${SANDBOX_PROFILE}"
fi
# Single-quoted, not %q: %q escapes the separating commas as \, and the
# consumers disagree about what that means. `source` unescapes them, but
# anything reading .env as text does not — the review orchestrator's parser
# (jewzaam-reviews backend.py) would ingest literal backslashes and ship
# malformed attributes. Both consumers strip surrounding single quotes.
ENV_CONTENT+="OTEL_RESOURCE_ATTRIBUTES='${OTEL_ATTRS}'"$'\n'

if [[ $captured -eq 0 ]]; then
    echo "Warning: no env vars captured, sandbox will have no credentials" >&2
else
    echo "Captured $captured env vars" >&2
fi

if [[ "$DRYRUN" == true ]]; then
    echo "" >&2
    echo "--- .env content (redacted tokens) ---" >&2
    echo "$ENV_CONTENT" | sed 's/\(TOKEN\|KEY\|SECRET\|CREDENTIALS\)=.*/\1=REDACTED/' >&2
    echo "--------------------------------------" >&2
fi

# --- Refresh config on existing sandbox ---
if [[ "$REFRESH_MODE" == true ]]; then
    if ! personal_profile "$SANDBOX_PROFILE"; then
        ensure_gws_creds
    fi
    OS_NAME=$(resolve_openshell_name "$SANDBOX_NAME")
    start_error_sandbox "$OS_NAME" || exit 1
    echo "Refreshing config on ${SANDBOX_NAME}..." >&2
    SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
    upload_config "$OS_NAME" "$SANDBOX_DIR"
    # Regenerate and upload context files for PR repos. Unconditional: --force
    # is about the upload and download change checks, and --refresh has no
    # repos to check. Refreshing a sandbox whose PR moved on and leaving it
    # with the old pr-context.md is the failure this exists to prevent.
    if [[ -f "${SANDBOX_DIR}/manifest.json" ]]; then
        for repo_name in $(jq -r '.repos | keys[]' "${SANDBOX_DIR}/manifest.json"); do
            generate_repo_context "$SANDBOX_DIR" "$repo_name" "${SANDBOX_PROFILE:-}"
            for ctx_file in pr-context.md jira-context.md open-prs.json; do
                if [[ -f "${SANDBOX_DIR}/${repo_name}/${ctx_file}" ]]; then
                    echo "Uploading ${ctx_file} for ${repo_name}..." >&2
                    # Trailing slash is load-bearing: `sandbox upload` treats a
                    # dest without one as the file's new *name*, so this would
                    # try to write a regular file over the repo directory and
                    # the remote tar fails. --no-git-ignore so the context
                    # files upload whether or not the host gitignores them.
                    run openshell sandbox upload "$OS_NAME" "${GW_FLAG[@]}" \
                        --no-git-ignore \
                        "${SANDBOX_DIR}/${repo_name}/${ctx_file}" "/sandbox/source/${repo_name}/"
                fi
            done
        done
    fi
    # Upload top-level jira-context.md (Jira-seeded sandboxes, no repos)
    if [[ -f "${SANDBOX_DIR}/jira-context.md" ]]; then
        echo "Uploading jira-context.md..." >&2
        JIRA_TMP="$(mktemp -d)"
        mkdir -p "${JIRA_TMP}/source"
        cp "${SANDBOX_DIR}/jira-context.md" "${JIRA_TMP}/source/jira-context.md"
        run openshell sandbox upload "$OS_NAME" "${GW_FLAG[@]}" \
            "${JIRA_TMP}/source" /sandbox
        rm -rf "$JIRA_TMP"
    fi
    echo "Done. Reconnect to apply (sandbox.sh --connect)" >&2
    exit 0
fi

# ---------------------------------------------------------------------------
# Create sandbox
# ---------------------------------------------------------------------------

# Host-side state dir + manifest first: the manifest is how the host learns the
# profile, and everything below is slow — an OAuth prompt from
# ensure_gws_creds, then the 120s create. The repo loop fills in .repos later.
init_manifest "${SANDBOXES_DIR}/${SANDBOX_NAME}" "$SANDBOX_NAME" "$SANDBOX_PROFILE" "$HARNESS"

if ! personal_profile "$SANDBOX_PROFILE"; then
    ensure_gws_creds
fi

OPENSHELL_NAME=$(short_name "$SANDBOX_NAME")

CREATE_CMD=(openshell sandbox create "${GW_FLAG[@]}" --no-auto-providers --keep)

if [[ -n "$OPENSHELL_NAME" ]]; then
    CREATE_CMD+=(--name "$OPENSHELL_NAME")
fi

CREATE_CMD+=(--policy "$POLICY_FILE")
CREATE_CMD+=(--from "openshell-sandbox:latest")
CREATE_CMD+=(--label "source.directory=${SANDBOX_NAME}")

SANDBOX_TARGET="${OPENSHELL_NAME:-}"

echo "Creating sandbox '${SANDBOX_NAME}' (openshell: ${OPENSHELL_NAME})..." >&2
echo "    policy: ${POLICY_FILE}" >&2
echo "" >&2

# sandbox create hangs on SSH connect (podman driver issue).
# Run in background, poll for sandbox, then use sandbox exec.
if [[ "$DRYRUN" == true ]]; then
    run "${CREATE_CMD[@]}"
    run echo "(poll openshell sandbox list until Ready)"
else
    CREATE_LOG="$(mktemp)"
    "${CREATE_CMD[@]}" &>"$CREATE_LOG" &
    CREATE_PID=$!

    elapsed=0
    while true; do
        if ! kill -0 "$CREATE_PID" 2>/dev/null; then
            if ! wait "$CREATE_PID" 2>/dev/null; then
                echo "Error: sandbox create failed:" >&2
                cat "$CREATE_LOG" >&2
                rm -f "$CREATE_LOG"
                exit 1
            fi
        fi
        if openshell sandbox list "${GW_FLAG[@]}" 2>/dev/null | grep -q "^${SANDBOX_TARGET}[[:space:]].*Ready"; then
            break
        fi
        sleep 1
        elapsed=$((elapsed + 1))
        if [[ $elapsed -ge 120 ]]; then
            kill "$CREATE_PID" 2>/dev/null || true
            echo "Error: sandbox did not reach Ready within 120s" >&2
            cat "$CREATE_LOG" >&2
            rm -f "$CREATE_LOG"
            exit 1
        fi
    done

    kill "$CREATE_PID" 2>/dev/null || true
    wait "$CREATE_PID" 2>/dev/null || true
    rm -f "$CREATE_LOG"
fi

# The sandbox exists on the policy rendered above, so that render is now the
# effective one. upload_config -> upload_static ships it below.
install_policy "$POLICY_FILE" "${SANDBOXES_DIR}/${SANDBOX_NAME}"

# ---------------------------------------------------------------------------
# Upload credentials
# ---------------------------------------------------------------------------

echo "Uploading credentials..." >&2

if ! personal_profile "$SANDBOX_PROFILE" && [[ -d "${HOME}/.config/gcloud" ]]; then
    run openshell sandbox upload "${SANDBOX_TARGET}" "${GW_FLAG[@]}" \
        "${HOME}/.config/gcloud" /sandbox/.config
fi

upload_config "${SANDBOX_TARGET}" "${SANDBOXES_DIR}/${SANDBOX_NAME}"

# Restore prior claude session state if available
upload_claude_state "$SANDBOX_TARGET" "${SANDBOXES_DIR}/${SANDBOX_NAME}"
upload_codex_state "$SANDBOX_TARGET" "${SANDBOXES_DIR}/${SANDBOX_NAME}"

# ---------------------------------------------------------------------------
# Clone repos on host and upload to sandbox
# ---------------------------------------------------------------------------

if [[ "$NO_CLONE" != true && ${#REPOS[@]} -eq 0 ]]; then
    current_remote=$(git remote get-url origin 2>/dev/null || true)
    if [[ -n "$current_remote" ]]; then
        REPOS+=("$current_remote")
        REFS+=("")
    fi
fi

WORKDIR="/sandbox"
if [[ "$NO_CLONE" != true && ${#REPOS[@]} -gt 0 ]]; then
    SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
    mkdir -p "$SANDBOX_DIR"

    echo "Cloning repos on host..." >&2
    for i in "${!REPOS[@]}"; do
        repo="${REPOS[$i]}"
        ref="${REFS[$i]:-}"
        repo_name=$(basename "$repo" .git)

        echo "    ${repo_name}${ref:+ (${ref})}" >&2
        clone_repo_host "$repo" "$ref" "$SANDBOX_DIR"

        sha=$(git -C "${SANDBOX_DIR}/${repo_name}" rev-parse HEAD)
        write_manifest "$SANDBOX_DIR" "$SANDBOX_NAME" "$repo_name" "$repo" "$ref" "$sha"
    done

    echo "Uploading repos to sandbox..." >&2
    for i in "${!REPOS[@]}"; do
        repo="${REPOS[$i]}"
        repo_name=$(basename "$repo" .git)
        upload_repo "$SANDBOX_TARGET" "$SANDBOX_DIR" "$repo_name"
    done

    # The manifest uploaded before create lists no repos yet. Ship it again now
    # that the loop has filled it in — the sandbox reads its repo list here.
    upload_static "$SANDBOX_TARGET" "$SANDBOX_DIR"

    WORKDIR="/sandbox/source/"
fi

# Upload jira-context.md if present (generated by scode for Jira-seeded sandboxes)
SANDBOX_DIR="${SANDBOXES_DIR}/${SANDBOX_NAME}"
if [[ -f "${SANDBOX_DIR}/jira-context.md" ]]; then
    echo "Uploading jira-context.md..." >&2
    JIRA_TMP="$(mktemp -d)"
    mkdir -p "${JIRA_TMP}/source"
    cp "${SANDBOX_DIR}/jira-context.md" "${JIRA_TMP}/source/jira-context.md"
    run openshell sandbox upload "$SANDBOX_TARGET" "${GW_FLAG[@]}" \
        "${JIRA_TMP}/source" /sandbox
    rm -rf "$JIRA_TMP"
    WORKDIR="/sandbox/source/"
fi

# ---------------------------------------------------------------------------
# Start Claude Code
# ---------------------------------------------------------------------------

if [[ "$NO_CONNECT" == true ]]; then
    echo "Sandbox ready. Connect with: sandbox.sh --connect ${SANDBOX_NAME}" >&2
    exit 0
fi

echo "Starting Claude in ${WORKDIR}..." >&2
connect_sandbox "$SANDBOX_TARGET" "$WORKDIR"
exit $?
