#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 5)
#
# Strip a copy of the host's ~/.claude/settings.json down to what a sandbox
# should run with, in place. Called by sandbox.sh on the staged copy, never on
# the host's own file.
#
# Usage: strip-settings.py <settings.json> <host-home> [profile]

import json
import re
import sys

# Host paths mean nothing in the sandbox, where $HOME is /sandbox.
SANDBOX_HOME = "/sandbox"

# The host pins models for its own reasons (cost, a rollout, a bug). A sandbox
# has no business inheriting that: the wrapper decides the model there
# (personal and home pin --model), and a stale default here silently overrides
# it with no trace in the command line. Stripped for every profile.
MODEL_KEYS = (
    "ANTHROPIC_DEFAULT_HAIKU_MODEL",
    "ANTHROPIC_DEFAULT_OPUS_MODEL",
    "ANTHROPIC_DEFAULT_SONNET_MODEL",
)

# Profiles that carry no work credentials. home is personal plus Prometheus
# and Loki reads, and codex is home with OpenAI in place of Anthropic — both
# are network policy differences, nothing to do with settings.
PERSONAL_PROFILES = ("personal", "home", "codex")

# Personal sandboxes get no work credentials or work-only integrations.
PERSONAL_STRIP_RE = re.compile(
    r"^(CLAUDE_CODE_USE_VERTEX|ANTHROPIC_VERTEX|GOOGLE|CLOUDSDK|CLOUD_ML|JIRA|ATLASSIAN)",
    re.I,
)

# A hook carrying a truthy `_keep` survives stripping. The hook declares its own
# retention instead of this file naming it, so a new hook that must reach a
# sandbox is a change where the hook is defined and no change here.
#
# Claude Code ignores unrecognised keys inside a hook object: verified with
# `claude doctor`, whose output is byte-identical with and without `_keep`,
# while a genuinely invalid settings file yields per-path "Invalid settings"
# diagnostics. The leading underscore follows the same convention as the
# `_source` annotation already in the host's settings.json and keeps the key
# clear of any real setting.
#
# The value should say *why*, not just `true` — it is the only explanation a
# reader of a stripped sandbox settings.json will find.
#
# This is the only rule. Nothing here names a hook, matches a command, or knows
# what any of them do — including the OTEL no-ops, which now carry their own
# marker. Adding a name or pattern back is what this replaced.
KEEP_MARKER = "_keep"


def strip_permissions(settings):
    if isinstance(settings.get("permissions"), dict):
        settings["permissions"].pop("allow", None)


def strip_env(settings, profile):
    env = settings.get("env")
    if not isinstance(env, dict):
        return
    for key in MODEL_KEYS:
        env.pop(key, None)
    if profile in PERSONAL_PROFILES:
        settings["env"] = {k: v for k, v in env.items() if not PERSONAL_STRIP_RE.match(k)}


def keep_hook(hook):
    """Whether one hook object survives stripping."""
    return isinstance(hook, dict) and bool(hook.get(KEEP_MARKER))


def strip_hooks(settings):
    hooks = settings.get("hooks")
    if not isinstance(hooks, dict):
        settings.pop("hooks", None)
        return
    for event in list(hooks.keys()):
        rules = hooks[event]
        if not isinstance(rules, list):
            continue
        # Filtered per hook, not per rule entry. Keeping the whole entry
        # because one hook in it qualified is how an unmarked hook used to
        # reach a sandbox by sharing an entry with a marked one — silent, and
        # it made "give it its own entry" a rule every hook author had to know.
        kept = []
        for rule in rules:
            if not isinstance(rule, dict):
                continue
            inner = [h for h in rule.get("hooks", []) if keep_hook(h)]
            if inner:
                kept.append(dict(rule, hooks=inner))
        if kept:
            hooks[event] = kept
        else:
            del hooks[event]
    if not hooks:
        del settings["hooks"]


def main():
    if len(sys.argv) < 3:
        print("Usage: strip-settings.py <settings.json> <host-home> [profile]", file=sys.stderr)
        sys.exit(1)

    path, host_home = sys.argv[1], sys.argv[2]
    profile = sys.argv[3] if len(sys.argv) > 3 else ""

    with open(path, "r") as f:
        raw = f.read()
    settings = json.loads(raw.replace(host_home, SANDBOX_HOME))

    strip_permissions(settings)
    strip_env(settings, profile)
    strip_hooks(settings)

    with open(path, "w") as f:
        json.dump(settings, f, indent=2)


if __name__ == "__main__":
    main()
