#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 5)
#
# Strip a copy of the host's ~/.claude/settings.json down to what a sandbox
# should run with, in place. Called by sandbox.sh on the staged copy, never on
# the host's own file.
#
# Usage: strip-settings.py <settings.json> <host-home> [profile]

import json
import re
import sys

# Host paths mean nothing in the sandbox, where $HOME is /sandbox.
SANDBOX_HOME = "/sandbox"

# The host pins models for its own reasons (cost, a rollout, a bug). A sandbox
# has no business inheriting that: the wrapper decides the model there
# (personal and home pin --model), and a stale default here silently overrides
# it with no trace in the command line. Stripped for every profile.
MODEL_KEYS = (
    "ANTHROPIC_DEFAULT_HAIKU_MODEL",
    "ANTHROPIC_DEFAULT_OPUS_MODEL",
    "ANTHROPIC_DEFAULT_SONNET_MODEL",
)

# Profiles that carry no work credentials. home is personal plus Prometheus
# and Loki reads, and codex is home with OpenAI in place of Anthropic — both
# are network policy differences, nothing to do with settings.
PERSONAL_PROFILES = ("personal", "home", "codex")

# Personal sandboxes get no work credentials or work-only integrations.
PERSONAL_STRIP_RE = re.compile(
    r"^(CLAUDE_CODE_USE_VERTEX|ANTHROPIC_VERTEX|GOOGLE|CLOUDSDK|CLOUD_ML|JIRA|ATLASSIAN)",
    re.I,
)

# The dummy OTEL hooks must survive: Claude Code emits no telemetry for a hook
# type with no registered hook, so these entries exist solely to trigger it.
OTEL_DUMMY_COMMANDS = ('python3 -c ""', 'python -c ""')


def strip_permissions(settings):
    if isinstance(settings.get("permissions"), dict):
        settings["permissions"].pop("allow", None)


def strip_env(settings, profile):
    env = settings.get("env")
    if not isinstance(env, dict):
        return
    for key in MODEL_KEYS:
        env.pop(key, None)
    if profile in PERSONAL_PROFILES:
        settings["env"] = {k: v for k, v in env.items() if not PERSONAL_STRIP_RE.match(k)}


def strip_hooks(settings):
    hooks = settings.get("hooks")
    if not isinstance(hooks, dict):
        settings.pop("hooks", None)
        return
    for event in list(hooks.keys()):
        rules = hooks[event]
        if not isinstance(rules, list):
            continue
        kept = [
            r
            for r in rules
            if isinstance(r, dict)
            and any(
                isinstance(h, dict) and h.get("command", "").strip() in OTEL_DUMMY_COMMANDS
                for h in r.get("hooks", [])
            )
        ]
        if kept:
            hooks[event] = kept
        else:
            del hooks[event]
    if not hooks:
        del settings["hooks"]


def main():
    if len(sys.argv) < 3:
        print("Usage: strip-settings.py <settings.json> <host-home> [profile]", file=sys.stderr)
        sys.exit(1)

    path, host_home = sys.argv[1], sys.argv[2]
    profile = sys.argv[3] if len(sys.argv) > 3 else ""

    with open(path, "r") as f:
        raw = f.read()
    settings = json.loads(raw.replace(host_home, SANDBOX_HOME))

    strip_permissions(settings)
    strip_env(settings, profile)
    strip_hooks(settings)

    with open(path, "w") as f:
        json.dump(settings, f, indent=2)


if __name__ == "__main__":
    main()
