#!/usr/bin/env python3
# Generated By: Claude Code (Claude Opus 5)
#
# Strip a copy of the host's ~/.claude/settings.json down to what a sandbox
# should run with, in place. Called by sandbox.sh on the staged copy, never on
# the host's own file.
#
# Usage: strip-settings.py <settings.json> <host-home> [profile]

import json
import re
import sys

# Host paths mean nothing in the sandbox, where $HOME is /sandbox.
SANDBOX_HOME = "/sandbox"

# The host pins models for its own reasons (cost, a rollout, a bug). A sandbox
# has no business inheriting that: the wrapper decides the model there
# (personal and home pin --model), and a stale default here silently overrides
# it with no trace in the command line. Stripped for every profile.
MODEL_KEYS = (
    "ANTHROPIC_DEFAULT_HAIKU_MODEL",
    "ANTHROPIC_DEFAULT_OPUS_MODEL",
    "ANTHROPIC_DEFAULT_SONNET_MODEL",
)

# Profiles that carry no work credentials. home is personal plus Prometheus
# and Loki reads — a network policy difference, nothing to do with settings.
# Mirrors personal_profile() in scripts/lib.sh; keep the two in step.
PERSONAL_PROFILES = ("personal", "home")

# Personal sandboxes get no work credentials or work-only integrations.
PERSONAL_STRIP_RE = re.compile(
    r"^(CLAUDE_CODE_USE_VERTEX|ANTHROPIC_VERTEX|GOOGLE|CLOUDSDK|CLOUD_ML|JIRA|ATLASSIAN)",
    re.I,
)

# A hook whose command carries a `# KEEP:` comment survives stripping. The hook
# declares its own retention instead of this file naming it, so a new hook that
# must reach a sandbox is a change where the hook is defined and no change here.
#
# It is a shell comment, and it has to be. The obvious place for this was a
# `_keep` key on the hook object, and that silently does not work: Claude Code
# rewrites settings.json (adding `skipDangerousModePermissionPrompt`, persisting
# a plugin toggle) and drops unrecognised keys nested inside hook objects and
# rule entries. Unknown keys at the TOP level survive, which is why `_source`
# does and a nested marker does not. Measured, not assumed: seeded 19 marked
# hooks, ran `claude plugin disable`, 0 markers left. `claude doctor` does not
# show this -- it only reads, so it proves tolerance, never persistence.
#
# The command string does survive that rewrite, and hook commands are run
# through a shell, so the comment never reaches the program: a probe hook with a
# trailing `# KEEP:` reported argc=0. A dummy argument would survive equally
# well but would land in argv of a real hook like Codex's observe-hook.py.
#
# Matching is deliberately lenient -- `# KEEP` with no reason still retains the
# hook. A stricter rule would silently strip a hook someone meant to keep, and
# silence is the failure being designed out. Tests in the config repos are what
# require the reason.
KEEP_MARKER_RE = re.compile(r"#\s*KEEP\b")


def strip_permissions(settings):
    if isinstance(settings.get("permissions"), dict):
        settings["permissions"].pop("allow", None)


def strip_env(settings, profile):
    env = settings.get("env")
    if not isinstance(env, dict):
        return
    for key in MODEL_KEYS:
        env.pop(key, None)
    if profile in PERSONAL_PROFILES:
        settings["env"] = {k: v for k, v in env.items() if not PERSONAL_STRIP_RE.match(k)}


def keep_hook(hook):
    """Whether one hook object survives stripping."""
    return isinstance(hook, dict) and bool(KEEP_MARKER_RE.search(hook.get("command", "")))


def strip_hooks(settings):
    hooks = settings.get("hooks")
    if not isinstance(hooks, dict):
        settings.pop("hooks", None)
        return
    for event in list(hooks.keys()):
        rules = hooks[event]
        if not isinstance(rules, list):
            continue
        # Filtered per hook, not per rule entry. Keeping the whole entry
        # because one hook in it qualified is how an unmarked hook used to
        # reach a sandbox by sharing an entry with a marked one — silent, and
        # it made "give it its own entry" a rule every hook author had to know.
        kept = []
        for rule in rules:
            if not isinstance(rule, dict):
                continue
            inner = [h for h in rule.get("hooks", []) if keep_hook(h)]
            if inner:
                kept.append(dict(rule, hooks=inner))
        if kept:
            hooks[event] = kept
        else:
            del hooks[event]
    if not hooks:
        del settings["hooks"]


def main():
    if len(sys.argv) < 3:
        print("Usage: strip-settings.py <settings.json> <host-home> [profile]", file=sys.stderr)
        sys.exit(1)

    path, host_home = sys.argv[1], sys.argv[2]
    profile = sys.argv[3] if len(sys.argv) > 3 else ""

    with open(path, "r") as f:
        raw = f.read()
    settings = json.loads(raw.replace(host_home, SANDBOX_HOME))

    strip_permissions(settings)
    strip_env(settings, profile)
    strip_hooks(settings)

    with open(path, "w") as f:
        json.dump(settings, f, indent=2)


if __name__ == "__main__":
    main()
