#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# One rule under test: manifest.json exists, with .profile set, before anything
# slow runs. The host prompt and claude-wrapper.sh both key off the profile, so
# a manifest that only appears after create + clone + upload reads as "no
# profile" for minutes.
#
# Covers init_manifest() directly, scode (manifest written before `code` opens
# the folder), and sandbox.sh --create (manifest written before the create
# call). Runs against a scratch HOME with --dryrun, so no openshell calls.
#
# Run: scripts/test-manifest-timing.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

WORK="${TMP}/work"
mkdir -p "$WORK"
cp -r "${REPO_ROOT}/scripts" "${REPO_ROOT}/config" "${REPO_ROOT}/policies" "$WORK/"
# site.env is gitignored and absent on a fresh clone; sandbox.sh refuses to run
# without one. Values are never dialled — every run below is --dryrun.
if [[ ! -f "${WORK}/config/site.env" ]]; then
    printf 'OTEL_URL=http://x:4318\nPROMETHEUS_URL=http://x:9090\nLOKI_URL=http://x:3100\n' \
        > "${WORK}/config/site.env"
fi

FAKE_HOME="${TMP}/home"
mkdir -p "${FAKE_HOME}/sandboxes"

fail=0
profile_of() { jq -r '.profile // empty' "$1" 2>/dev/null; }

# --- init_manifest(): skeleton, name hash, idempotency ---
source "${WORK}/scripts/lib.sh"

D="${TMP}/direct"
init_manifest "$D" "probe" "personal"
M="${D}/manifest.json"

[[ -f "$M" ]] || { echo "FAIL: init_manifest wrote no manifest" >&2; fail=1; }
[[ "$(jq -r '.name' "$M")" == "probe" ]] \
    || { echo "FAIL: .name not written" >&2; fail=1; }
[[ "$(jq -r '.openshell_name' "$M")" == "$(short_name probe)" ]] \
    || { echo "FAIL: .openshell_name does not match short_name" >&2; fail=1; }
[[ "$(profile_of "$M")" == "personal" ]] \
    || { echo "FAIL: .profile not written" >&2; fail=1; }
[[ "$(jq -r '.repos | length' "$M")" == "0" ]] \
    || { echo "FAIL: .repos should start empty" >&2; fail=1; }

# A second call must not wipe what the repo loop filled in, and must refresh
# the profile — that is the --recreate-on-another-profile path.
jq '.repos.myrepo = {url: "u", ref: "r", sha: "s", cloned_at: "t"}' "$M" > "${M}.tmp" && mv "${M}.tmp" "$M"
init_manifest "$D" "probe" "code"
[[ "$(jq -r '.repos.myrepo.url' "$M")" == "u" ]] \
    || { echo "FAIL: init_manifest dropped an existing repo entry" >&2; fail=1; }
[[ "$(profile_of "$M")" == "code" ]] \
    || { echo "FAIL: init_manifest did not refresh .profile" >&2; fail=1; }

# --- scode: the manifest is there before VS Code opens the folder ---
# The `code` stub is the whole point: it records what a shell starting with the
# folder would see, at the moment it would see it.
STUB="${TMP}/stub"
mkdir -p "$STUB"
cat > "${STUB}/code" << 'STUBEOF'
#!/bin/bash
jq -r '.profile // "<none>"' "$1/manifest.json" 2>/dev/null > "${SEEN_FILE}" || echo "<no-manifest>" > "${SEEN_FILE}"
STUBEOF
chmod +x "${STUB}/code"

# $SANDBOX_SH deliberately points at a DIFFERENT checkout, with a library that
# has none of the functions scode needs. scode must source its own lib.sh; the
# fixed absolute default of SANDBOX_SH is not a hint about where scode lives.
DECOY="${TMP}/decoy/scripts"
mkdir -p "$DECOY"
echo '# stale checkout: no init_manifest, no site_default_profile' > "${DECOY}/lib.sh"

SEEN="${TMP}/seen"

# scode's own exit status matters as much as the manifest: sourcing the wrong
# library kills it with "init_manifest: command not found", and a scode that
# never ran also never wrote the wrong file.
run_scode() {
    rm -f "$SEEN"
    local out
    out="$(HOME="$FAKE_HOME" PATH="${STUB}:${PATH}" SEEN_FILE="$SEEN" \
        SANDBOX_SH="${DECOY}/sandbox.sh" \
        bash "${WORK}/scripts/scode" "$@" 2>&1)" && return 0
    echo "FAIL: scode $* exited nonzero:" >&2
    echo "  ${out}" >&2
    fail=1
}

run_scode --profile personal --name probe-scode
[[ "$(cat "$SEEN" 2>/dev/null)" == "personal" ]] \
    || { echo "FAIL: scode opened VS Code before writing the profile (saw: $(cat "$SEEN" 2>/dev/null))" >&2; fail=1; }

# An existing sandbox keeps the profile it was built with. scode must not
# rewrite it from the command line — sandbox.sh --ensure is what refuses the
# mismatch, and it can only do that if the manifest still says the truth.
EXIST="${FAKE_HOME}/sandboxes/probe-existing"
mkdir -p "$EXIST"
printf '{"name":"probe-existing","openshell_name":"sb-x","profile":"code","repos":{}}' \
    > "${EXIST}/manifest.json"
run_scode --profile personal "$EXIST"
[[ "$(profile_of "${EXIST}/manifest.json")" == "code" ]] \
    || { echo "FAIL: scode overwrote an existing sandbox's profile" >&2; fail=1; }

# With no $SANDBOX_SH at all, the VS Code task must point at the sandbox.sh
# sitting next to this scode — not at a fixed path under $HOME. Same rule as
# the lib.sh source above: one checkout drives one sandbox.
HOME="$FAKE_HOME" PATH="${STUB}:${PATH}" SEEN_FILE="$SEEN" \
    bash "${WORK}/scripts/scode" --profile personal --name probe-default >/dev/null 2>&1
TASKS="${FAKE_HOME}/sandboxes/probe-default/.vscode/tasks.json"
grep -qF "${WORK}/scripts/sandbox.sh" "$TASKS" 2>/dev/null \
    || { echo "FAIL: scode's default SANDBOX_SH is not its own checkout" >&2; fail=1; }

# --- sandbox.sh --create: manifest written on the create path, no repos needed ---
HOME="$FAKE_HOME" bash "${WORK}/scripts/sandbox.sh" \
    --create probe-create --profile personal --no-clone --no-connect --dryrun >/dev/null 2>&1 || true
CM="${FAKE_HOME}/sandboxes/probe-create/manifest.json"
[[ -f "$CM" ]] || { echo "FAIL: --create wrote no manifest" >&2; fail=1; }
[[ "$(profile_of "$CM")" == "personal" ]] \
    || { echo "FAIL: --create left .profile unset (saw: $(profile_of "$CM"))" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all manifest-timing checks passed"
exit $fail
