#!/bin/bash
# Generated By: Claude Code (Claude Opus 5)
#
# Self-check for scode's second-positional REF-vs-LABEL split and for
# site_default_profile(). Builds a throwaway git repo in a temp dir, sources
# the real functions out of scode/lib.sh, and asserts the resulting names.
#
# Run: scripts/test-scode-naming.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# The function under test, lifted verbatim from scode. Kept in sync by the
# assertion below, which fails if scode's copy stops matching this one.
is_ref() {
    [[ "$2" =~ ^(pr/[0-9]+|tag/.+)$ ]] && return 0
    git -C "$1" rev-parse --verify --quiet "$2" >/dev/null 2>&1
}

if ! grep -qF 'git -C "$1" rev-parse --verify --quiet "$2" >/dev/null 2>&1' "${SCRIPT_DIR}/scode"; then
    echo "FAIL: scode's is_ref no longer matches the copy under test" >&2
    exit 1
fi

# --- fixture: a repo with a default branch, a feature branch, and a tag ---
REPO="${TMP}/my-great-project"
mkdir -p "$REPO"
git -C "$REPO" init -q -b main
git -C "$REPO" config user.email test@example.com
git -C "$REPO" config user.name test
echo x > "${REPO}/f"
git -C "$REPO" add f
git -C "$REPO" commit -qm init
git -C "$REPO" branch existing-branch
git -C "$REPO" tag v1.0.0
SHA="$(git -C "$REPO" rev-parse HEAD)"

# origin/HEAD, which scode reads to find the default branch
git -C "$REPO" remote add origin "${REPO}"
git -C "$REPO" fetch -q origin
git -C "$REPO" symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main

# name(): the naming logic from scode's repo mode, same order, same fallbacks
name() {
    local label="" ref=""
    if [[ $# -ge 1 ]] && is_ref "$REPO" "$1"; then
        ref="$1"
    else
        [[ $# -ge 1 ]] && label="${1//\//-}"
        ref="$(git -C "$REPO" symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's|refs/remotes/origin/||')"
    fi
    echo "$(basename "$REPO")-${label:-${ref//\//-}} ref=${ref}"
}

fail=0
check() {
    local got want="$2"
    got="$(name ${1:+"$1"})"
    if [[ "$got" != "$want" ]]; then
        echo "FAIL: name(${1:-<none>})" >&2
        echo "  want: ${want}" >&2
        echo "  got:  ${got}" >&2
        fail=1
    fi
}

# no second positional -> default branch, name from ref
check ""                     "my-great-project-main ref=main"

# a real local branch -> REF, checked out
check "existing-branch"      "my-great-project-existing-branch ref=existing-branch"

# a tag and a raw SHA are refs rev-parse resolves
check "v1.0.0"               "my-great-project-v1.0.0 ref=v1.0.0"
check "$SHA"                 "my-great-project-${SHA} ref=${SHA}"

# pr/N and tag/X resolve remotely in sandbox.sh, so they are refs by pattern
# even though rev-parse cannot see them here
check "pr/1176"              "my-great-project-pr-1176 ref=pr/1176"
check "tag/v9.9.9"           "my-great-project-tag-v9.9.9 ref=tag/v9.9.9"

# the new case: not a ref -> LABEL, name from label, default branch checked out
check "the-best-new-feature" "my-great-project-the-best-new-feature ref=main"

# a label with a slash is flattened for the name but never becomes the ref
check "some/feature"         "my-great-project-some-feature ref=main"

# --- site_default_profile(): unset, set, and missing-file ---
source "${SCRIPT_DIR}/lib.sh"

FAKE_ROOT="${TMP}/fake"
mkdir -p "${FAKE_ROOT}/scripts" "${FAKE_ROOT}/config"
cp "${SCRIPT_DIR}/lib.sh" "${FAKE_ROOT}/scripts/lib.sh"

probe() { ( source "${FAKE_ROOT}/scripts/lib.sh"; site_default_profile ); }

printf 'OTEL_URL=http://x:4318\nDEFAULT_PROFILE=personal\n' > "${FAKE_ROOT}/config/site.env"
[[ "$(probe)" == "personal" ]] || { echo "FAIL: DEFAULT_PROFILE=personal not read" >&2; fail=1; }

printf 'OTEL_URL=http://x:4318\nDEFAULT_PROFILE=\n' > "${FAKE_ROOT}/config/site.env"
[[ -z "$(probe)" ]] || { echo "FAIL: empty DEFAULT_PROFILE should read empty" >&2; fail=1; }

printf 'OTEL_URL=http://x:4318\n' > "${FAKE_ROOT}/config/site.env"
[[ -z "$(probe)" ]] || { echo "FAIL: absent DEFAULT_PROFILE should read empty" >&2; fail=1; }

# site.env is gitignored and may not exist at all — must not error under set -e
rm -f "${FAKE_ROOT}/config/site.env"
[[ -z "$(probe)" ]] || { echo "FAIL: missing site.env should read empty" >&2; fail=1; }

# the subshell must not leak site.env into the caller
printf 'OTEL_URL=http://leaked:4318\nDEFAULT_PROFILE=personal\n' > "${FAKE_ROOT}/config/site.env"
probe >/dev/null
[[ "${OTEL_URL:-}" != "http://leaked:4318" ]] || { echo "FAIL: site.env leaked into caller" >&2; fail=1; }

[[ $fail -eq 0 ]] && echo "all naming + default-profile checks passed"
exit $fail
