#!/bin/bash
# Generated By: Claude Code (Claude Opus 4.6)
#
# Test Jira API auth combinations to find what works.
# Requires: JIRA_USERNAME, JIRA_TOKEN (unscoped), JIRA_CLOUD_ID
# Scoped token read from: secret-tool lookup atlassian openshell-sandbox-jira

set -euo pipefail

ISSUE="ANSTRAT-1740"
CLOUD_ID="${JIRA_CLOUD_ID:?JIRA_CLOUD_ID not set}"
USERNAME="${JIRA_USERNAME:?JIRA_USERNAME not set}"
UNSCOPED="${JIRA_TOKEN:?JIRA_TOKEN not set}"
SCOPED="$(secret-tool lookup atlassian openshell-sandbox-jira)"

run_test() {
    local label="$1" url="$2" auth_header="$3"
    local http_code body
    http_code=$(curl -s -o /tmp/jira-test-body -w '%{http_code}' -H "$auth_header" "$url")
    body=$(cat /tmp/jira-test-body)

    if [[ "$http_code" == "200" ]]; then
        printf "  %-60s %s\n" "$label" "OK (200)"
    else
        # extract error message if JSON
        local msg
        msg=$(echo "$body" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('errorMessages',[''])[0] or d.get('message',''))" 2>/dev/null || echo "$body" | head -c 80)
        printf "  %-60s %s: %s\n" "$label" "$http_code" "$msg"
    fi
}

basic_auth() {
    local user="$1" token="$2"
    echo "Authorization: Basic $(printf '%s:%s' "$user" "$token" | base64 -w0)"
}

bearer_auth() {
    local token="$1"
    echo "Authorization: Bearer $token"
}

echo "=== Jira Auth Test ==="
echo "Issue:    $ISSUE"
echo "Cloud ID: $CLOUD_ID"
echo "Username: $USERNAME"
echo ""

echo "--- Unscoped token ---"
run_test "basic @ tenant /api/3" \
    "https://redhat.atlassian.net/rest/api/3/issue/${ISSUE}" \
    "$(basic_auth "$USERNAME" "$UNSCOPED")"

run_test "basic @ tenant /api/2" \
    "https://redhat.atlassian.net/rest/api/2/issue/${ISSUE}" \
    "$(basic_auth "$USERNAME" "$UNSCOPED")"

run_test "basic @ gateway /api/3" \
    "https://api.atlassian.com/ex/jira/${CLOUD_ID}/rest/api/3/issue/${ISSUE}" \
    "$(basic_auth "$USERNAME" "$UNSCOPED")"

run_test "basic @ gateway /api/2" \
    "https://api.atlassian.com/ex/jira/${CLOUD_ID}/rest/api/2/issue/${ISSUE}" \
    "$(basic_auth "$USERNAME" "$UNSCOPED")"

echo ""
echo "--- Scoped token ---"
run_test "basic @ tenant /api/3" \
    "https://redhat.atlassian.net/rest/api/3/issue/${ISSUE}" \
    "$(basic_auth "$USERNAME" "$SCOPED")"

run_test "basic @ tenant /api/2" \
    "https://redhat.atlassian.net/rest/api/2/issue/${ISSUE}" \
    "$(basic_auth "$USERNAME" "$SCOPED")"

run_test "basic @ gateway /api/3" \
    "https://api.atlassian.com/ex/jira/${CLOUD_ID}/rest/api/3/issue/${ISSUE}" \
    "$(basic_auth "$USERNAME" "$SCOPED")"

run_test "basic @ gateway /api/2" \
    "https://api.atlassian.com/ex/jira/${CLOUD_ID}/rest/api/2/issue/${ISSUE}" \
    "$(basic_auth "$USERNAME" "$SCOPED")"

run_test "bearer @ gateway /api/3" \
    "https://api.atlassian.com/ex/jira/${CLOUD_ID}/rest/api/3/issue/${ISSUE}" \
    "$(bearer_auth "$SCOPED")"

run_test "bearer @ gateway /api/2" \
    "https://api.atlassian.com/ex/jira/${CLOUD_ID}/rest/api/2/issue/${ISSUE}" \
    "$(bearer_auth "$SCOPED")"

rm -f /tmp/jira-test-body
echo ""
echo "done."
